create or replace view DISC_PROD.DATAFLEXSYNCDATA.DFCONTRACTSAUTH(
	DBNAME,
	CONTRACTCODE,
	CONTRACTNAME,
	PAYMENTMETHOD,
	BILLPERSONCODE,
	RATE1,
	RATE2,
	RATEEFFECTIVEDATE1,
	RATEEFFECTIVEDATE2,
	BILLABLE,
	ISMEDWAIVER,
	OVERHEADRATE1,
	OVERHEADRATE2,
	ISSKILLED,
	BILLEDBYQUARTERHOURS,
	USEBILLCODE,
	PAYROLLCODE,
	BILLBYHALFHOURS,
	LISTRATE1,
	LISTRATE2,
	DEFAULTBILLCODE,
	ISMILEAGE,
	ALLOWQUARTERHOURS,
	PAYTRAVELS,
	PAYORCODE,
	PAYABLE,
	CREATEDDATE,
	UPDATEBATCH,
	UPDATEDTIME,
	PAYINUNITS,
	PAYINDOLLARS,
	PAYINDOLLARPAYCODE,
	PAYINDOLLARRATE,
	ISEVV,
	REVENUECATEGORY,
	RATE3,
	RATE4,
	RATEEFFECTIVEDATE3,
	RATEEFFECTIVEDATE4,
	LISTRATE3,
	LISTRATE4,
	PAYTRAVELSCODE,
	REVENUESUBCATEGORY,
	SYS_CHANGE_VERSION,
	SYS_CHANGE_OPERATION,
	ETL_TASK_KEY,
	ETL_INSERTED_TASK_KEY,
	ETL_INSERTED_DATE,
	ETL_INSERTED_BY,
	ETL_LAST_UPDATED_DATE,
	ETL_LAST_UPDATED_BY,
	ETL_DELETED_FLAG,
	CPTHPCSCODE,
	AUTHTYPE
) as 
--************************************************************************************************************************
--This view is created after receiving multiple weekly auth type contract in jira ticket  ---IDDOX-554
-- 2023-11-30			KDHOKAI				Changed Database DISC_DEV to DISC_PROD
--************************************************************************************************************************
SELECT *, 'Weekly' AS AUTHTYPE FROM DISC_PROD.DATAFLEXSYNCDATA.DFCONTRACTS  
WHERE (CONTRACTCODE ILIKE  ANY
('OE','OR','OS','V','OG','OF','ON','OT','OP') AND DBNAME IN ('MO')OR
CONTRACTCODE ILIKE  ANY
('SV','B3','P8','VF','VE','VI','3D','P6','P7','B2','O4','O1','AQ','A3','A1','P5','B1','VC','3R','3'
,'O3','VM','VT','K','VD','O2','V1','AR','3A','A2','2','VA','VS','71','3B') AND DBNAME IN ('IL'))
UNION ALL
SELECT *, 'Monthly' AS AUTHTYPE FROM DISC_PROD.DATAFLEXSYNCDATA.DFCONTRACTS  
WHERE NOT(CONTRACTCODE ILIKE  ANY
('OE','OR','OS','V','OG','OF','ON','OT','OP') AND DBNAME IN ('MO')OR
CONTRACTCODE ILIKE  ANY
('SV','B3','P8','VF','VE','VI','3D','P6','P7','B2','O4','O1','AQ','A3','A1','P5','B1','VC','3R','3'
,'O3','VM','VT','K','VD','O2','V1','AR','3A','A2','2','VA','VS','71','3B') AND DBNAME IN ('IL'));