create or replace view DISC_PROD.DEVERO.VIEW_DEVERO_PATIENT(
	PATIENT_CODE,
	PATIENT_FIRST_NAME,
	PATIENT_LAST_NAME,
	PATIENT_MI,
	DATE_MODIFIED,
	ETL_TASK_KEY,
	ETL_INSERTED_TASK_KEY,
	ETL_INSERTED_DATE,
	ETL_INSERTED_BY,
	ETL_LAST_UPDATED_DATE,
	ETL_LAST_UPDATED_BY,
	ETL_DELETED_FLAG
) as (
WITH RESULT_DATA AS
(
SELECT DISTINCT
		  P.PATIENT_CODE
		, XMLGET(PARSE_XML(P.PATIENT_XML), 'PATIENT_FIRST_NAME'):"$"::STRING AS PATIENT_FIRST_NAME
	 	, XMLGET(PARSE_XML(P.PATIENT_XML), 'PATIENT_LAST_NAME'):"$"::STRING AS PATIENT_LAST_NAME
		, XMLGET(PARSE_XML(P.PATIENT_XML), 'PATIENT_MI'):"$"::STRING AS PATIENT_MI
		, XMLGET(PARSE_XML(P.PATIENT_XML), 'DATE_MODIFIED'):"$"::STRING AS DATE_MODIFIED
 		, P.ETL_TASK_KEY
		, P.ETL_INSERTED_TASK_KEY
		, P.ETL_INSERTED_DATE
		, P.ETL_INSERTED_BY
		, P.ETL_LAST_UPDATED_DATE
		, P.ETL_LAST_UPDATED_BY
		, P.ETL_DELETED_FLAG
		, ROW_NUMBER() OVER(PARTITION BY P.PATIENT_CODE ORDER BY DATE_MODIFIED DESC) AS LATEST_MODIFIED
FROM DISC_PROD.DEVERO.HIST_DEVERO_PATIENT P
--WHERE DATE(P.ETL_LAST_UPDATED_DATE) = COALESCE((
--SELECT MAX(DATE(ETL_LAST_UPDATED_DATE)) FROM DISC_PROD.DEVERO.HIST_DEVERO_PATIENT),DATE(GETDATE()))
)
SELECT  PATIENT_CODE
		, PATIENT_FIRST_NAME
	 	, PATIENT_LAST_NAME
		, PATIENT_MI
		, DATE_MODIFIED
		, ETL_TASK_KEY
		, ETL_INSERTED_TASK_KEY
		, ETL_INSERTED_DATE
		, ETL_INSERTED_BY
		, ETL_LAST_UPDATED_DATE
		, ETL_LAST_UPDATED_BY
		, ETL_DELETED_FLAG
FROM RESULT_DATA 
WHERE LATEST_MODIFIED = 1
);