create or replace view DISC_PROD.ADP.QB_SSN_MAPPING(
	COMPANY,
	NAME,
	SSN,
	CLASS,
	RANK,
	ETL_TASK_KEY,
	ETL_INSERTED_TASK_KEY,
	ETL_INSERTED_DATE,
	ETL_INSERTED_BY,
	ETL_LAST_UPDATED_DATE,
	ETL_LAST_UPDATED_BY,
	ETL_DELETED_FLAG
) as 
SELECT DISTINCT 
	COMPANY,
	TRIM(UPPER(REPLACE(NAME, ','))) AS NAME, 
	TRIM(REPLACE(SSN, '-')) AS SSN, 
	CLASS,
	ROW_NUMBER() OVER (PARTITION BY TRIM(UPPER(REPLACE(NAME, ','))), COMPANY ORDER BY SSN DESC NULLS LAST, CLASS DESC NULLS LAST) AS RANK,
	-1 AS ETL_TASK_KEY,
	-1 AS ETL_INSERTED_TASK_KEY,
	convert_timezone('UTC', CURRENT_TIMESTAMP)::timestamp_ntz AS ETL_INSERTED_DATE,
	CURRENT_USER AS ETL_INSERTED_BY,
	convert_timezone('UTC', CURRENT_TIMESTAMP)::timestamp_ntz AS ETL_LAST_UPDATED_DATE,
	CURRENT_USER AS ETL_LAST_UPDATED_BY,
	FALSE AS ETL_DELETED_FLAG
FROM (
	SELECT DISTINCT COMPANY, NAME, SSN, NULL AS CLASS FROM DISC_PROD.ADP.QB_PAYROLL
	UNION
	SELECT DISTINCT COMPANY, NAME, SSN, NULL AS CLASS FROM DISC_PROD.ADP.QB_PAYROLL_DATES
	UNION
	SELECT DISTINCT COMPANY, NAME, SSN, NULL AS CLASS FROM DISC_PROD.ADP.QB_PAYROLL_HOURS
	UNION 
	SELECT DISTINCT COMPANY, NAME, SSN, NULL AS CLASS FROM DISC_PROD.ADP.QB_PAYROLL_RATE
	UNION 
	SELECT DISTINCT COMPANY, NAME, NULL AS SSN, NULL AS CLASS FROM DISC_PROD.ADP.QB_PAYROLL_MIDWAY_20_GROSS
	UNION 
	SELECT DISTINCT COMPANY, NAME, NULL AS SSN, NULL AS CLASS FROM DISC_PROD.ADP.QB_PAYROLL_MIDWAY_20_HOURS
	UNION 
	SELECT DISTINCT COMPANY, EMPLOYEE, SS_NO, CLASS FROM DISC_PROD.ADP.QB_EMPLOYEES WHERE FIRST_NAME IS NOT NULL
)
QUALIFY RANK = 1
ORDER BY 1, 2 DESC NULLS LAST;