create or replace view DISC_PROD.FILEPRO.VW_CALLS_FIELD(
	DATE_TIME,
	LOG_IN_OUT,
	EMP_ID,
	CALLER_ID,
	MINS_WORKED,
	IS_SHARED,
	CLIENT_NAME,
	CLIENT_ID,
	OFFICE,
	DESK,
	SERVICE_TYPE,
	PROCESSED_MODULE
) as
SELECT CAST (T.$1 AS DATETIME) AS "DATE_TIME",
CAST (T.$2 AS INTEGER) AS "LOG_IN_OUT",
CAST (T.$3 AS INTEGER) AS "EMP_ID",
CAST (T.$4 AS INTEGER) AS "CALLER_ID",
CAST (T.$5 AS INTEGER) AS "MINS_WORKED",
CAST (T.$6 AS VARCHAR) AS "IS_SHARED",
CAST (T.$7 AS VARCHAR) AS "CLIENT_NAME",
CAST (T.$8 AS INTEGER) AS "CLIENT_ID",
CAST (T.$9 AS VARCHAR) AS "OFFICE",
CAST (T.$10 AS INTEGER) AS "DESK",
CAST (T.$11 AS VARCHAR)AS "SERVICE_TYPE",
CAST (T.$12 AS VARCHAR) AS "PROCESSED_MODULE"
FROM @DISC_PROD.STAGE.AZSTAGEPROD/FilePro/CallsField (file_format => DISC_PROD.PUBLIC.CSV_FORMAT ) AS T;