create or replace view DISC_PROD.DEVERO.VIEW_DEVERO_REFERRER(
	REFERRER_ID,
	FIRST_NAME,
	LAST_NAME,
	COMPANY_NAME,
	TITLE,
	ADDRESS_1,
	ADDRESS_2,
	CITY,
	STATE,
	ZIP_CODE,
	PHONE,
	FAX,
	EMAIL,
	REFERRER_CODE,
	EXTERNAL_ID,
	PROTOCOL,
	AGENCY_ID,
	ACTIVE,
	DATE_MODIFIED,
	ETL_TASK_KEY,
	ETL_INSERTED_TASK_KEY,
	ETL_INSERTED_DATE,
	ETL_INSERTED_BY,
	ETL_LAST_UPDATED_DATE,
	ETL_LAST_UPDATED_BY,
	ETL_DELETED_FLAG
) as (
WITH RESULT_DATA AS
(
SELECT 	DISTINCT
          R.REFERRER_ID
		, XMLGET(PARSE_XML(R.REFERRER_XML), 'FIRST_NAME'):"$"::STRING AS FIRST_NAME
		, XMLGET(PARSE_XML(R.REFERRER_XML), 'LAST_NAME'):"$"::STRING AS LAST_NAME
		, XMLGET(PARSE_XML(R.REFERRER_XML), 'COMPANY_NAME'):"$"::STRING AS COMPANY_NAME
		, XMLGET(PARSE_XML(R.REFERRER_XML), 'TITLE'):"$"::STRING AS TITLE
		, XMLGET(PARSE_XML(R.REFERRER_XML), 'ADDRESS_1'):"$"::STRING AS ADDRESS_1
		, XMLGET(PARSE_XML(R.REFERRER_XML), 'ADDRESS_2'):"$"::STRING AS ADDRESS_2
		, XMLGET(PARSE_XML(R.REFERRER_XML), 'CITY'):"$"::STRING AS CITY
		, XMLGET(PARSE_XML(R.REFERRER_XML), 'STATE'):"$"::STRING AS STATE
		, XMLGET(PARSE_XML(R.REFERRER_XML), 'ZIP_CODE'):"$"::STRING AS ZIP_CODE
		, XMLGET(PARSE_XML(R.REFERRER_XML), 'PHONE'):"$"::STRING AS PHONE
		, XMLGET(PARSE_XML(R.REFERRER_XML), 'FAX'):"$"::STRING AS FAX
		, XMLGET(PARSE_XML(R.REFERRER_XML), 'EMAIL'):"$"::STRING AS EMAIL
		, XMLGET(PARSE_XML(R.REFERRER_XML), 'REFERRER_CODE'):"$"::STRING AS REFERRER_CODE
		, XMLGET(PARSE_XML(R.REFERRER_XML), 'EXTERNAL_ID'):"$"::STRING AS EXTERNAL_ID
		, XMLGET(PARSE_XML(R.REFERRER_XML), 'PROTOCOL'):"$"::STRING AS PROTOCOL
		, NULL AS AGENCY_ID  --REFERRER.VALUE:"$" :: STRING AGENCY_ID
		, XMLGET(PARSE_XML(R.REFERRER_XML), 'ACTIVE'):"$"::STRING AS ACTIVE
		, XMLGET(PARSE_XML(R.REFERRER_XML), 'DATE_MODIFIED'):"$"::STRING AS DATE_MODIFIED
		, R.ETL_TASK_KEY
		, R.ETL_INSERTED_TASK_KEY
		, R.ETL_INSERTED_DATE
		, R.ETL_INSERTED_BY
		, R.ETL_LAST_UPDATED_DATE
		, R.ETL_LAST_UPDATED_BY
		, R.ETL_DELETED_FLAG
		, ROW_NUMBER() OVER(PARTITION BY R.REFERRER_ID ORDER BY DATE_MODIFIED DESC) AS LATEST_MODIFIED
  FROM DISC_PROD.DEVERO.HIST_DEVERO_REFERRER  R
--, LATERAL FLATTEN(XMLGET(PARSE_XML(R.REFERRER_XML), 'AGENCY_IDS'):"$":: ARRAY) REFERRER
--WHERE DATE(R.ETL_LAST_UPDATED_DATE) = COALESCE((
--SELECT MAX(DATE(ETL_LAST_UPDATED_DATE)) FROM DISC_PROD.DEVERO.HIST_DEVERO_REFERRER),DATE(GETDATE()))
)
SELECT 	
          REFERRER_ID
		, FIRST_NAME
		, LAST_NAME
		, COMPANY_NAME
		, TITLE
		, ADDRESS_1
		, ADDRESS_2
		, CITY
		, STATE
		, ZIP_CODE
		, PHONE
		, FAX
		, EMAIL
		, REFERRER_CODE
		, EXTERNAL_ID
		, PROTOCOL
		, AGENCY_ID  
		, ACTIVE
		, DATE_MODIFIED
		, ETL_TASK_KEY
		, ETL_INSERTED_TASK_KEY
		, ETL_INSERTED_DATE
		, ETL_INSERTED_BY
		, ETL_LAST_UPDATED_DATE
		, ETL_LAST_UPDATED_BY
		, ETL_DELETED_FLAG
FROM 
RESULT_DATA
WHERE LATEST_MODIFIED = 1
);