create or replace view DISC_PROD.DATA_CLEANSING.CLIENT_STANDARDIZED_ADDRESSES_INCNSTNT(
	ADDRESS,
	CITY,
	STATE,
	ZIP,
	CNT
) as (
SELECT X.ADDRESS ,X.CITY,X.STATE,X.ZIP ,count(*) FROM  
	(SELECT DISTINCT 
	ADDRESS,
	CITY,
	STATE,
	ZIP,
	POINTS,
	LATITUDE,
	LONGITUDE,
	LABEL,
	ADDRESS_NUMBER,
	STREET,
	MUNICIPALITY,
	REGION,
	SUB_REGION,
	COUNTRY_CODE,
	ZIPCODE,
	PLUS_FOUR_CODE,
	RELEVANCE
	FROM DISC_PROD.DATA_CLEANSING.CLIENT_STANDARDIZED_ADDRESSES 
	WHERE zip = ZIPCODE )X 
	GROUP BY 1,2,3,4 HAVING count(*) > 1);