create or replace view DISC_PROD.DEVERO.VIEW_DEVERO_PATIENT_CHART(
	PATIENT_CODE,
	CHART_NUMBER,
	CHART_ID,
	DATE_MODIFIED,
	CHART_STATUS,
	START_OF_CARE,
	REFERRAL_DATE,
	DISCHARGE_DATE,
	MR_NUMBER,
	AGENCY_ID,
	AGENCY_NAME,
	PHYSICIAN_CODE_1,
	PHYSICIAN_NAME_1,
	PHYSICIAN_CODE_2,
	PHYSICIAN_NAME_2,
	PHYSICIAN_CODE_3,
	PHYSICIAN_NAME_3,
	INSURANCE_CODE_1,
	INSURANCE_NAME_1,
	INSURANCE_CODE_2,
	INSURANCE_NAME_2,
	INSURANCE_CODE_3,
	INSURANCE_NAME_3,
	INSURANCE_CODE_4,
	INSURANCE_NAME_4,
	INSURANCE_CODE_5,
	INSURANCE_NAME_5,
	REFERRER_CODE_1,
	REFERRER_NAME_1,
	REFERRER_CODE_2,
	REFERRER_NAME_2,
	REFERRER_CODE_3,
	REFERRER_NAME_3,
	FACILITY_CODE_1,
	FACILITY_NAME_1,
	ADMISSION_SOURCE_NAME,
	ADMISSION_SOURCE_CODE,
	CHART_REMOVED,
	ETL_TASK_KEY,
	ETL_INSERTED_TASK_KEY,
	ETL_INSERTED_DATE,
	ETL_INSERTED_BY,
	ETL_LAST_UPDATED_DATE,
	ETL_LAST_UPDATED_BY,
	ETL_DELETED_FLAG
) as (
WITH RESULT_DATA AS
(
SELECT DISTINCT
		  P.PATIENT_CODE
		, XMLGET(CHART.VALUE, 'CHART_NUMBER'):"$"::STRING AS CHART_NUMBER
	    , XMLGET(CHART.VALUE, 'CHART_ID'):"$"::STRING AS CHART_ID
		, XMLGET(CHART.VALUE,'DATE_MODIFIED'):"$"::STRING AS DATE_MODIFIED
		, XMLGET(CHART.VALUE,'CHART_STATUS'):"$"::STRING AS CHART_STATUS
		, XMLGET(CHART.VALUE,'START_OF_CARE'):"$"::STRING AS START_OF_CARE
		, XMLGET(CHART.VALUE,'REFERRAL_DATE'):"$"::STRING AS REFERRAL_DATE
		, XMLGET(CHART.VALUE,'DISCHARGE_DATE'):"$"::STRING AS DISCHARGE_DATE
		, XMLGET(CHART.VALUE,'MR_NUMBER'):"$"::STRING AS MR_NUMBER
		, XMLGET(CHART.VALUE,'AGENCY_ID'):"$"::STRING AS AGENCY_ID
		, XMLGET(CHART.VALUE,'AGENCY_NAME'):"$"::STRING AS AGENCY_NAME
		, XMLGET(CHART.VALUE,'PHYSICIAN_CODE_1'):"$"::STRING AS PHYSICIAN_CODE_1
		, XMLGET(CHART.VALUE,'PHYSICIAN_NAME_1'):"$"::STRING AS PHYSICIAN_NAME_1
		, XMLGET(CHART.VALUE,'PHYSICIAN_CODE_2'):"$"::STRING AS PHYSICIAN_CODE_2
		, XMLGET(CHART.VALUE,'PHYSICIAN_NAME_2'):"$"::STRING AS PHYSICIAN_NAME_2
		, XMLGET(CHART.VALUE,'PHYSICIAN_CODE_3'):"$"::STRING AS PHYSICIAN_CODE_3
		, XMLGET(CHART.VALUE,'PHYSICIAN_NAME_3'):"$"::STRING AS PHYSICIAN_NAME_3
		, XMLGET(CHART.VALUE,'INSURANCE_CODE_1'):"$"::STRING AS INSURANCE_CODE_1
		, XMLGET(CHART.VALUE,'INSURANCE_NAME_1'):"$"::STRING AS INSURANCE_NAME_1
		, XMLGET(CHART.VALUE,'INSURANCE_CODE_2'):"$"::STRING AS INSURANCE_CODE_2
		, XMLGET(CHART.VALUE,'INSURANCE_NAME_2'):"$"::STRING AS INSURANCE_NAME_2
		, XMLGET(CHART.VALUE,'INSURANCE_CODE_3'):"$"::STRING AS INSURANCE_CODE_3
		, XMLGET(CHART.VALUE,'INSURANCE_NAME_3'):"$"::STRING AS INSURANCE_NAME_3
		, XMLGET(CHART.VALUE,'INSURANCE_CODE_4'):"$"::STRING AS INSURANCE_CODE_4
		, XMLGET(CHART.VALUE,'INSURANCE_NAME_4'):"$"::STRING AS INSURANCE_NAME_4
		, XMLGET(CHART.VALUE,'INSURANCE_CODE_5'):"$"::STRING AS INSURANCE_CODE_5
		, XMLGET(CHART.VALUE,'INSURANCE_NAME_5'):"$"::STRING AS INSURANCE_NAME_5
		, XMLGET(CHART.VALUE,'REFERRER_CODE_1'):"$"::STRING AS REFERRER_CODE_1
		, XMLGET(CHART.VALUE,'REFERRER_NAME_1'):"$"::STRING AS REFERRER_NAME_1
		, XMLGET(CHART.VALUE,'REFERRER_CODE_2'):"$"::STRING AS REFERRER_CODE_2
		, XMLGET(CHART.VALUE,'REFERRER_NAME_2'):"$"::STRING AS REFERRER_NAME_2
		, XMLGET(CHART.VALUE,'REFERRER_CODE_3'):"$"::STRING AS REFERRER_CODE_3
		, XMLGET(CHART.VALUE,'REFERRER_NAME_3'):"$"::STRING AS REFERRER_NAME_3
		, XMLGET(CHART.VALUE,'FACILITY_CODE_1'):"$"::STRING AS FACILITY_CODE_1
		, XMLGET(CHART.VALUE,'FACILITY_NAME_1'):"$"::STRING AS FACILITY_NAME_1
		, XMLGET(CHART.VALUE,'ADMISSION_SOURCE_NAME'):"$"::STRING AS ADMISSION_SOURCE_NAME
		, XMLGET(CHART.VALUE,'ADMISSION_SOURCE_CODE'):"$"::STRING AS ADMISSION_SOURCE_CODE
		, XMLGET(CHART.VALUE,'REMOVED'):"$"::STRING AS CHART_REMOVED
 		, P.ETL_TASK_KEY
		, P.ETL_INSERTED_TASK_KEY
		, P.ETL_INSERTED_DATE
		, P.ETL_INSERTED_BY
		, P.ETL_LAST_UPDATED_DATE
		, P.ETL_LAST_UPDATED_BY
		, P.ETL_DELETED_FLAG
		, ROW_NUMBER() OVER(PARTITION BY P.PATIENT_CODE,CHART_NUMBER,CHART_ID ORDER BY DATE_MODIFIED DESC) AS LATEST_MODIFIED
FROM DISC_PROD.DEVERO.HIST_DEVERO_PATIENT P
, LATERAL FLATTEN (XMLGET(PARSE_XML(P.PATIENT_XML) ,'CHARTS'):"$" :: ARRAY) CHART
--WHERE DATE(P.ETL_LAST_UPDATED_DATE) = COALESCE((
--SELECT MAX(DATE(ETL_LAST_UPDATED_DATE)) FROM DISC_PROD.DEVERO.HIST_DEVERO_PATIENT),DATE(GETDATE()))
)
SELECT 
 PATIENT_CODE
		, CHART_NUMBER
	    , CHART_ID
		, DATE_MODIFIED
		, CHART_STATUS
		, START_OF_CARE
		, REFERRAL_DATE
		, DISCHARGE_DATE
		, MR_NUMBER
		, AGENCY_ID
		, AGENCY_NAME
		, PHYSICIAN_CODE_1
		, PHYSICIAN_NAME_1
		, PHYSICIAN_CODE_2
		, PHYSICIAN_NAME_2
		, PHYSICIAN_CODE_3
		, PHYSICIAN_NAME_3
		, INSURANCE_CODE_1
		, INSURANCE_NAME_1
		, INSURANCE_CODE_2
		, INSURANCE_NAME_2
		, INSURANCE_CODE_3
		, INSURANCE_NAME_3
		, INSURANCE_CODE_4
		, INSURANCE_NAME_4
		, INSURANCE_CODE_5
		, INSURANCE_NAME_5
		, REFERRER_CODE_1
		, REFERRER_NAME_1
		, REFERRER_CODE_2
		, REFERRER_NAME_2
		, REFERRER_CODE_3
		, REFERRER_NAME_3
		, FACILITY_CODE_1
		, FACILITY_NAME_1
		, ADMISSION_SOURCE_NAME
		, ADMISSION_SOURCE_CODE
		, CHART_REMOVED
		, ETL_TASK_KEY
		, ETL_INSERTED_TASK_KEY
		, ETL_INSERTED_DATE
		, ETL_INSERTED_BY
		, ETL_LAST_UPDATED_DATE
		, ETL_LAST_UPDATED_BY
		, ETL_DELETED_FLAG
FROM RESULT_DATA
WHERE LATEST_MODIFIED = 1
);