create or replace view DISC_PROD."1UP_BISON".VW_FHIR_R4_PRACTITIONER(
	ID,
	FIRST_NAME,
	MIDDLE_NAME,
	LAST_NAME,
	FULL_NAME,
	ACTIVE_STATUS,
	IDENTIFIER_PERIOD_END_DATE,
	IDENTIFIER_PERIOD_START_DATE,
	IDENTIFIER_SYSTEM,
	IDENTIFIER_TYPE_CODING_CODE1,
	IDENTIFIER_TYPE_CODING_DISPLAY1,
	IDENTIFIER_TYPE_CODING_SYSTEM1,
	IDENTIFIER_VALUE,
	META_EXTENSION_URL1,
	META_EXTENSION_VALUEDATETIME1,
	META_EXTENSION_URL2,
	META_EXTENSION_CODE2,
	META_EXTENSION_URL3,
	META_EXTENSION_CODE3,
	META_EXTENSION_SYSTEM3,
	META_EXTENSION_URL4,
	META_EXTENSION_VALUEDATETIME4,
	META_EXTENSION_URL5,
	META_EXTENSION_VALUESTRING5,
	META_EXTENSION_URL6,
	META_EXTENSION_VALUESTRING6,
	META_EXTENSION_URL7,
	META_EXTENSION_VALUESTRING7,
	META_LASTUPDATED,
	META_PROFILE,
	META_TAG_CODE,
	META_TAG_SYSTEM,
	META_TAG_VERSION,
	META_VERSIONID,
	RESOURCETYPE,
	LANDING_INSERTED_DATE,
	LANDING_INSERTED_BY,
	FILENAME,
	ETL_INSERTED_BY,
	ETL_TASK_KEY,
	ETL_INSERTED_DATE
) as (
select 
parse_json(source_data):id::string as id,
parse_json(source_data):name[0]:given[0]::string as First_name,
parse_json(source_data):name[0]:given[1]::string as Middle_name,
parse_json(source_data):name[0]:family::string as Last_name,
parse_json(source_data):name[0]:text::string as Full_name,
parse_json(source_data):active::string as active_status,
parse_json(source_data):identifier[0]:period:end::TIMESTAMP_NTZ as identifier_period_end_date,
parse_json(source_data):identifier[0]:period:start::TIMESTAMP_NTZ as identifier_period_start_date,
parse_json(source_data):identifier[0]:system::string as identifier_system,
parse_json(source_data):identifier[0]:type:coding[0]:code::string as identifier_type_coding_code1,
parse_json(source_data):identifier[0]:type:coding[0]:display::string as identifier_type_coding_display1,
parse_json(source_data):identifier[0]:type:coding[0]:system::string as identifier_type_coding_system1,
parse_json(source_data):identifier[0]:value::string as identifier_value,
parse_json(source_data):meta:extension[0]:url::string as meta_extension_url1,
parse_json(source_data):meta:extension[0]:valueDateTime::TIMESTAMP_NTZ as meta_extension_valueDateTime1,
parse_json(source_data):meta:extension[1]:url::string as meta_extension_url2,
parse_json(source_data):meta:extension[1]:valueCodeableConcept:coding[0]:code::string as meta_extension_code2,
parse_json(source_data):meta:extension[2]:url::string as meta_extension_url3,
parse_json(source_data):meta:extension[2]:valueCodeableConcept:coding[0]:code::string as meta_extension_code3,
parse_json(source_data):meta:extension[2]:valueCodeableConcept:coding[0]:system::string as meta_extension_system3,
parse_json(source_data):meta:extension[3]:url::string as meta_extension_url4,
parse_json(source_data):meta:extension[3]:valueDateTime::TIMESTAMP_NTZ as meta_extension_valueDateTime4,
parse_json(source_data):meta:extension[4]:url::string as meta_extension_url5,
parse_json(source_data):meta:extension[4]:valueString::string as meta_extension_valueString5,
parse_json(source_data):meta:extension[5]:url::string as meta_extension_url6,
parse_json(source_data):meta:extension[5]:valueString::string as meta_extension_valueString6,
parse_json(source_data):meta:extension[6]:url::string as meta_extension_url7,
parse_json(source_data):meta:extension[6]:valueString::string as meta_extension_valueString7,
parse_json(source_data):meta:lastUpdated::TIMESTAMP_NTZ as meta_lastUpdated,
parse_json(source_data):meta:profile::string as meta_profile,
parse_json(source_data):meta:tag[0]:code::string as meta_tag_code,
parse_json(source_data):meta:tag[0]:system::string as meta_tag_system,
parse_json(source_data):meta:tag[0]:version::string as meta_tag_version,
parse_json(source_data):meta:versionId::string as meta_versionId,
parse_json(source_data):resourceType::string as resourceType,
LANDING_INSERTED_DATE,
LANDING_INSERTED_BY,
FILENAME,
ETL_INSERTED_BY,
ETL_TASK_KEY,
ETL_INSERTED_DATE
FROM DISC_PROD."1UP_BISON".HIST_FHIR_R4_PRACTITIONER
);