create or replace view DISC_PROD.DEVERO.VIEW_DEVERO_USER(
	USER_ID,
	CAREGIVER_CODE,
	FIRST_NAME,
	LAST_NAME,
	USERNAME,
	ACTIVE,
	PRIMARY_USER_TYPE,
	PAY_TYPE,
	TITLE,
	USER_NUMBER,
	ADDRESS,
	ADDRESS2,
	CITY,
	STATE,
	ZIP_CODE,
	PHONE_NUM,
	CELL_PHONE,
	FAX_NUM,
	EMAIL,
	IS_ON_CALL,
	DATE_MODIFIED,
	USER_AGENCY,
	ETL_TASK_KEY,
	ETL_INSERTED_TASK_KEY,
	ETL_INSERTED_DATE,
	ETL_INSERTED_BY,
	ETL_LAST_UPDATED_DATE,
	ETL_LAST_UPDATED_BY,
	ETL_DELETED_FLAG
) as (
WITH RESULT_DATA AS 
(
SELECT 	DISTINCT
          U.USER_ID
		, XMLGET(PARSE_XML(U.USER_XML), 'CAREGIVER_CODE'):"$" :: STRING AS CAREGIVER_CODE
		, XMLGET(PARSE_XML(U.USER_XML), 'FIRST_NAME'):"$" :: STRING AS FIRST_NAME
		, XMLGET(PARSE_XML(U.USER_XML), 'LAST_NAME'):"$" :: STRING AS LAST_NAME
		, XMLGET(PARSE_XML(U.USER_XML), 'USERNAME'):"$" :: STRING AS USERNAME
		, XMLGET(PARSE_XML(U.USER_XML), 'ACTIVE'):"$" :: STRING AS ACTIVE
		, XMLGET(PARSE_XML(U.USER_XML), 'PRIMARY_USER_TYPE'):"$" :: STRING AS PRIMARY_USER_TYPE
		, XMLGET(PARSE_XML(U.USER_XML), 'PAY_TYPE'):"$" :: STRING AS PAY_TYPE
		, XMLGET(PARSE_XML(U.USER_XML), 'TITLE'):"$" :: STRING AS TITLE
		, XMLGET(PARSE_XML(U.USER_XML), 'USER_NUMBER'):"$" :: STRING AS USER_NUMBER
		, XMLGET(PARSE_XML(U.USER_XML), 'ADDRESS'):"$" :: STRING AS ADDRESS
		, XMLGET(PARSE_XML(U.USER_XML), 'ADDRESS2'):"$" :: STRING AS ADDRESS2
		, XMLGET(PARSE_XML(U.USER_XML), 'CITY'):"$" :: STRING AS CITY
		, XMLGET(PARSE_XML(U.USER_XML), 'STATE'):"$" :: STRING AS STATE
		, XMLGET(PARSE_XML(U.USER_XML), 'ZIP_CODE'):"$" :: STRING AS ZIP_CODE
		, XMLGET(PARSE_XML(U.USER_XML), 'PHONE_NUM'):"$" :: STRING AS PHONE_NUM
		, XMLGET(PARSE_XML(U.USER_XML), 'CELL_PHONE'):"$" :: STRING AS CELL_PHONE
		, XMLGET(PARSE_XML(U.USER_XML), 'FAX_NUM'):"$" :: STRING AS FAX_NUM
		, XMLGET(PARSE_XML(U.USER_XML), 'EMAIL'):"$" :: STRING AS EMAIL
		, XMLGET(PARSE_XML(U.USER_XML), 'IS_ON_CALL'):"$" :: STRING AS IS_ON_CALL
		, XMLGET(PARSE_XML(U.USER_XML), 'DATE_MODIFIED'):"$" :: STRING AS DATE_MODIFIED
		, NULL AS USER_AGENCY   --USERS.VALUE:"$" :: STRING USER_AGENCY
		, U.ETL_TASK_KEY
		, U.ETL_INSERTED_TASK_KEY
		, U.ETL_INSERTED_DATE
		, U.ETL_INSERTED_BY
		, U.ETL_LAST_UPDATED_DATE
		, U.ETL_LAST_UPDATED_BY
		, U.ETL_DELETED_FLAG
		, ROW_NUMBER() OVER(PARTITION BY U.USER_ID ORDER BY DATE_MODIFIED DESC) AS LATEST_MODIFIED
  FROM DISC_PROD.DEVERO.HIST_DEVERO_USER  U
--, LATERAL FLATTEN(XMLGET(PARSE_XML(U.USER_XML), 'USER_AGENCIES'):"$":: ARRAY) USERS
--WHERE DATE(U.ETL_LAST_UPDATED_DATE) = COALESCE((
--SELECT MAX(DATE(ETL_LAST_UPDATED_DATE)) FROM DISC_PROD.DEVERO.HIST_DEVERO_USER),DATE(GETDATE()))
)
SELECT USER_ID,
	CAREGIVER_CODE,
	FIRST_NAME,
	LAST_NAME,
	USERNAME,
	ACTIVE,
	PRIMARY_USER_TYPE,
	PAY_TYPE,
	TITLE,
	USER_NUMBER,
	ADDRESS,
	ADDRESS2,
	CITY,
	STATE,
	ZIP_CODE,
	PHONE_NUM,
	CELL_PHONE,
	FAX_NUM,
	EMAIL,
	IS_ON_CALL,
	DATE_MODIFIED,
	USER_AGENCY,
	ETL_TASK_KEY,
	ETL_INSERTED_TASK_KEY,
	ETL_INSERTED_DATE,
	ETL_INSERTED_BY,
	ETL_LAST_UPDATED_DATE,
	ETL_LAST_UPDATED_BY,
	ETL_DELETED_FLAG
FROM RESULT_DATA
WHERE LATEST_MODIFIED = 1
);