create or replace view DISC_PROD.MATRIXCARE.VW_T_CLIENT_GENDER(
	CLI_SEX,
	GENDER_TEXT
) as
WITH DEFINITIONS AS (
	SELECT CODES.CLI_SEX, DEFINITIONS.GENDER AS GENDER_TEXT, 
		ROW_NUMBER() OVER (PARTITION BY CODES.CLI_SEX ORDER BY COUNT(*) DESC) AS ROW_NUMBER
	FROM MATRIXCARE.STVHC_T_CLIENT AS CODES
	JOIN ADAPTIVENURSINGEXPORT.T_CLIENT AS DEFINITIONS
		ON DEFINITIONS.CLI_ID = CODES.CLI_ID  
	WHERE CODES.CLI_SEX IS NOT NULL AND DEFINITIONS.GENDER IS NOT NULL
	GROUP BY CODES.CLI_SEX, DEFINITIONS.GENDER 
)
	SELECT CLI_SEX, GENDER_TEXT
	FROM DEFINITIONS
	WHERE ROW_NUMBER = 1;