create or replace view DISC_PROD.ALAYACARE.VW_CONFIRM_VISIT_CHECK(
	BRANCH_ID,
	LATEST_VISIT
) as 
SELECT BRANCH_ID, MAX(VISITS.START_AT::dATE) AS LATEST_VISIT
FROM DISC_PROD.ALAYACARE.VISIT AS VISITS
WHERE CASE WHEN VISITS.PROPERTIES_TBL_SCHEDULER_ITEM_cancelled_code_id IS NOT NULL THEN '10'
WHEN VISITS.PROPERTIES_TBL_SCHEDULER_ITEM_cancelled_code_id IS NULL
AND VISITS.VISIT_COMPLETED = 1
AND VISITS.PROPERTIES_TBL_SCHEDULER_ITEM_approval_status = '1' -- 0-Not Approved, 1-Approved, 2-Rejected, 3-In-violation
THEN '02'
ELSE '01' END IN ('02','03','04','05')
AND
IFF(VISITS.VISIT_COMPUTED_RATE_UNITS = 'hours',
COALESCE(
IFF(
VISITS.PROPERTIES_TBL_SCHEDULER_ITEM_hours_pay IS NULL,
IFF(TRIM(VISITS.PROPERTIES_TBL_SCHEDULER_ITEM_approval_status) = '1', TRY_CAST(VISITS.PROPERTIES_TBL_SCHEDULER_ITEM_hours_approved::STRING AS DECIMAL(8, 3)), NULL),
TRY_CAST(VISITS.PROPERTIES_TBL_SCHEDULER_ITEM_hours_pay::STRING AS DECIMAL(8, 3))
), IFF(CASE
WHEN VISITS.PROPERTIES_TBL_SCHEDULER_ITEM_cancelled_code_id IS NOT NULL THEN '10'
WHEN VISITS.PROPERTIES_TBL_SCHEDULER_ITEM_cancelled_code_id IS NULL
AND VISITS.VISIT_COMPLETED = 1
AND VISITS.PROPERTIES_TBL_SCHEDULER_ITEM_approval_status = '1' -- 0-Not Approved, 1-Approved, 2-Rejected, 3-In-violation
THEN '02'
ELSE '01' END NOT IN ('02', '03', '04', '05'), VISITS.VISIT_SCHEDULED_DURATION, NULL)),
NULL) > 0
group by 1;