CREATE OR REPLACE FILE FORMAT DW_PROD.PUBLIC.CSV_FORMAT_ONE_HEAD_ROW
	ESCAPE = '\\'
	TRIM_SPACE = TRUE
	FIELD_OPTIONALLY_ENCLOSED_BY = '\"'
	COMPRESSION = NONE
	VALIDATE_UTF8 = FALSE
COMMENT='CSV Format with one header row - Abhishek'
;