CREATE OR REPLACE FILE FORMAT DW_PROD.PUBLIC.CSV_FORMAT_ISO_8859_15_AB
	SKIP_HEADER = 1
	ESCAPE = '\\'
	TRIM_SPACE = TRUE
	FIELD_OPTIONALLY_ENCLOSED_BY = '\"'
	COMPRESSION = NONE
	VALIDATE_UTF8 = FALSE
	ENCODING = 'ISO-8859-15'
;