resource "snowflake_view" "DW_INTEGRATION_VW_DIM_EMPLOYEE_GA_FIRST" {
	database = "DW_${var.SF_ENVIRONMENT}"
	schema = "INTEGRATION"
	name = "VW_DIM_EMPLOYEE_GA_FIRST"
	statement = <<-SQL
	 
with q1 as (select DISTINCT EMPLOYEE_KEY AS ID,SYSTEM_CODE,SOURCE_SYSTEM_ID,EMPLOYEE_ID,EMPLOYEE_PID,EMPLOYEE_DOB,EMPLOYEE_FIRST_NAME,EMPLOYEE_LAST_NAME,EMPLOYEE_ADDRESS1,EMPLOYEE_CITY,COALESCE(EMPLOYEE_HOME_PHONE,EMPLOYEE_CELL_PHONE) AS EMPLOYEE_HOME_PHONE,EMPLOYEE_PERSONAL_EMAIL from DW_${var.SF_ENVIRONMENT}.HAH.DIM_EMPLOYEE WHERE (SOURCE_SYSTEM_ID =3 AND SYSTEM_CODE ='GA') OR(SOURCE_SYSTEM_ID IN (1,2)) OR (SOURCE_SYSTEM_ID =9 AND SYSTEM_CODE ='GEORGIA (1002)')) select * from q1 where (EMPLOYEE_PID is not null or EMPLOYEE_DOB is not null);
SQL
	or_replace = true 
	is_secure = false 
}

