resource "snowflake_procedure" "DW_HAH_DIM_CONTRACT_POSTPROCESSING" {
	name ="DIM_CONTRACT_POSTPROCESSING"
	database = "DW_${var.SF_ENVIRONMENT}"
	schema = "HAH"
	language  = "SQL"

	arguments {
		name = "STR_ETL_TASK_KEY"
		type = "VARCHAR(16777216)"
}	

	arguments {
		name = "STR_CDC_START"
		type = "VARCHAR(16777216)"
}	

	arguments {
		name = "STR_CDC_END"
		type = "VARCHAR(16777216)"
}	
	return_type = "VARCHAR(16777216)"
	execute_as = "OWNER"
	statement = <<-EOT

BEGIN
    UPDATE DW_${var.SF_ENVIRONMENT}.HAH.DIM_CONTRACT AS TGT 
SET TGT.PARTNER_KEY = STG.PARTNER_KEY,
    TGT.PARENT_PARTNER_KEY = STG.PARENT_PARTNER_KEY,
	TGT.ETL_TASK_KEY = :STR_ETL_TASK_KEY,
	TGT.ETL_LAST_UPDATED_DATE = convert_timezone(''UTC'', CURRENT_TIMESTAMP)::timestamp_ntz,
	TGT.ETL_LAST_UPDATED_BY = CURRENT_USER
FROM (
   SELECT DISTINCT
MD5(PCM.SYSTEM_CODE||''-''||PCM.PAYOR_ID||''-''||PCM.SOURCE_SYSTEM_ID) AS PARTNER_KEY
,MD5(PCM.SYSTEM_CODE||''-''||DPP.PARENT_PAYOR_ID||''-''||PCM.SOURCE_SYSTEM_ID) AS PARENT_PARTNER_KEY	
,PCM.SOURCE_SYSTEM_ID AS SOURCE_SYSTEM_ID 
	,PCM.SYSTEM_CODE AS SYSTEM_CODE
	,PCM.ORIGINAL_SOURCE_SYSTEM_ID AS ORIGINAL_SOURCE_SYSTEM_ID 
	,PCM.ORIGINAL_SYSTEM_CODE  AS ORIGINAL_SYSTEM_CODE
	,PCM.CONTRACT_CODE 
	,PCM.CONTRACT_NAME
	FROM DISC_${var.SF_ENVIRONMENT}.PAYOR_CONTRACT_UI.PAYOR_CONTRACT_MAPPING PCM
    JOIN DISC_${var.SF_ENVIRONMENT}.PAYOR_CONTRACT_UI.PAYOR DPP
    ON PCM.PAYOR_ID = DPP.PAYOR_ID
	) AS STG 
WHERE STG.ORIGINAL_SYSTEM_CODE = TGT.SYSTEM_CODE 
     AND STG.CONTRACT_CODE = TGT.CONTRACT_CODE 
     AND STG.CONTRACT_NAME = TGT.CONTRACT_NAME 
;
RETURN ''SUCCESS'';
    END;
    
 EOT
}

