resource "snowflake_procedure" "DW_HAH_FACT_BRANCH_MAPPING_POST_PROCESSING" {
	name ="FACT_BRANCH_MAPPING_POST_PROCESSING"
	database = "DW_${var.SF_ENVIRONMENT}"
	schema = "HAH"
	language  = "SQL"
	return_type = "VARCHAR(16777216)"
	execute_as = "OWNER"
	statement = <<-EOT

DECLARE
    return_result VARCHAR;
BEGIN

INSERT OVERWRITE INTO DW_${var.SF_ENVIRONMENT}.HAH.FACT_BRANCH_MAPPING 
WITH MERGE_1 AS (
	WITH DATAFLEX_OFFICES AS (
		SELECT BRANCH_KEY, OFFICE_STATE_CODE, OFFICE_NUMBER
		FROM HAH.DIM_BRANCH 
		WHERE SOURCE_SYSTEM_ID = 3
	), COASTAL_OFFICES AS (
		SELECT BRANCH_KEY, OFFICE_STATE_CODE, OFFICE_NUMBER 
		FROM HAH.DIM_BRANCH 
		WHERE SOURCE_SYSTEM_ID IN (1, 2)
	), EXCEL_OFFICES AS (
		SELECT BRANCH_KEY, OFFICE_STATE_CODE, OFFICE_NUMBER 
		FROM HAH.DIM_BRANCH 
		WHERE SOURCE_SYSTEM_ID = 4
	), MATRIXCARE_OFFICES AS (
		SELECT BRANCH_KEY, OFFICE_CODE, OFFICE_NUMBER, DETAILED_OFFICE_NAME, OFFICE_STATE_CODE 
		FROM HAH.DIM_BRANCH 
		WHERE SOURCE_SYSTEM_ID = 7
	), CCSI_OFFICES AS 
	(
		SELECT BRANCH_KEY, OFFICE_STATE_CODE, OFFICE_NUMBER
		FROM HAH.DIM_BRANCH 
		WHERE SOURCE_SYSTEM_ID = 8
	),
	MERGED_OFFICES AS (
		-- Coastal offices
		SELECT DATAFLEX.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY, COASTAL.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY
		FROM DATAFLEX_OFFICES AS DATAFLEX
		JOIN COASTAL_OFFICES AS COASTAL
			ON COASTAL.OFFICE_STATE_CODE = DATAFLEX.OFFICE_STATE_CODE AND COASTAL.OFFICE_NUMBER = DATAFLEX.OFFICE_NUMBER
		-- Excel offices
		UNION
		SELECT DATAFLEX.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY, EXCEL.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY
		FROM DATAFLEX_OFFICES AS DATAFLEX
		JOIN EXCEL_OFFICES AS EXCEL
			ON EXCEL.OFFICE_STATE_CODE = DATAFLEX.OFFICE_STATE_CODE AND EXCEL.OFFICE_NUMBER = DATAFLEX.OFFICE_NUMBER
		-- MatrixCare offices
		UNION
		SELECT DATAFLEX.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY, MATRIXCARE.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY
		FROM DATAFLEX_OFFICES AS DATAFLEX
		JOIN MATRIXCARE_OFFICES AS MATRIXCARE
			ON MATRIXCARE.OFFICE_STATE_CODE = DATAFLEX.OFFICE_STATE_CODE AND MATRIXCARE.OFFICE_NUMBER = DATAFLEX.OFFICE_NUMBER
		UNION 
		SELECT C.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY, C.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY
		FROM CCSI_OFFICES C
	), 
	ALAYACARE_OFFICES AS 
	(
		-- Some AlayaCare offices were merged from legacy into a single AlayaCare office
		SELECT BRANCH.BRANCH_KEY, BRANCH.OFFICE_STATE_CODE, BRANCH.OFFICE_NUMBER, BRANCH.OFFICE_NAME,
			COUNT(*) OVER (PARTITION BY BRANCH.OFFICE_STATE_CODE, BRANCH.OFFICE_NUMBER) AS OFFICE_NUMBER_COUNT
		FROM HAH.DIM_BRANCH AS BRANCH
		WHERE BRANCH.SOURCE_SYSTEM_ID = 9
	), PRE_ALAYACARE_OFFICES AS (
		SELECT BRANCH.BRANCH_KEY as ORIGINAL_BRANCH_KEY,
			BRANCH.SOURCE_SYSTEM_ID AS ORIGINAL_SOURCE_SYSTEM_ID,
			BRANCH.SYSTEM_CODE AS ORIGINAL_SYSTEM_CODE,
			BRANCH.OFFICE_CODE AS ORIGINAL_OFFICE_CODE,
			NEW_BRANCH.BRANCH_KEY,
			NEW_BRANCH.SOURCE_SYSTEM_ID,
			NEW_BRANCH.SYSTEM_CODE,
			NEW_BRANCH.OFFICE_CODE
		FROM HAH.DIM_BRANCH AS BRANCH
		LEFT JOIN MERGED_OFFICES AS MERGED_OFFICES
			ON MERGED_OFFICES.OLD_SYSTEM_BRANCH_KEY = BRANCH.BRANCH_KEY 
		LEFT JOIN HAH.DIM_BRANCH AS NEW_BRANCH
			ON NEW_BRANCH.BRANCH_KEY = COALESCE(MERGED_OFFICES.NEW_SYSTEM_BRANCH_KEY, BRANCH.BRANCH_KEY)
	)
		SELECT OFFICES.ORIGINAL_BRANCH_KEY,
			OFFICES.ORIGINAL_SOURCE_SYSTEM_ID,
			OFFICES.ORIGINAL_SYSTEM_CODE,
			OFFICES.ORIGINAL_OFFICE_CODE,
			B.*,
			TRIM(
			-- Remove Prepended State from Parent_Branch_Name
			REGEXP_REPLACE(
				SUBSTRING(
					B.PARENT_BRANCH_NAME,
					1, LEN(B.PARENT_BRANCH_NAME) - CHARINDEX(''('', REVERSE(B.PARENT_BRANCH_NAME)) - 1 -- Remove appended office_code/office_number from Parent_Branch_Name
				)
			, ''[A-Z]{2,} -'', '''', 1, 1)) AS PARENT_BRANCH_NAME_SHORTENED,
			''1900-01-01'' AS CONSOLIDATE_DATE,
			FALSE AS IS_HISTORY
		FROM PRE_ALAYACARE_OFFICES AS OFFICES
		LEFT JOIN LOAD_ALAYACARE_${var.SF_ENVIRONMENT}.CONFIGURATION.REALIGNED_BRANCHES AS ALAYACARE_MERGED_BRANCH_MAPPING
			ON ALAYACARE_MERGED_BRANCH_MAPPING.BRANCH_KEY = OFFICES.BRANCH_KEY
		LEFT JOIN HAH.DIM_BRANCH AS ALAYACARE_MERGED_BRANCHES
			ON ALAYACARE_MERGED_BRANCHES.BRANCH_KEY = COALESCE(ALAYACARE_MERGED_BRANCH_MAPPING.NEW_BRANCH_KEY, OFFICES.BRANCH_KEY)
		LEFT JOIN ALAYACARE_OFFICES AS ALAYACARE_OFFICES
			ON ALAYACARE_OFFICES.OFFICE_STATE_CODE = ALAYACARE_MERGED_BRANCHES.OFFICE_STATE_CODE
				AND ALAYACARE_OFFICES.OFFICE_NUMBER = ALAYACARE_MERGED_BRANCHES.OFFICE_NUMBER
				AND (ALAYACARE_OFFICES.OFFICE_NUMBER_COUNT = 1 OR (ALAYACARE_OFFICES.OFFICE_NUMBER_COUNT <> 1 AND ALAYACARE_OFFICES.OFFICE_NAME = ALAYACARE_MERGED_BRANCHES.OFFICE_NAME))
		LEFT JOIN HAH.DIM_BRANCH AS B
			ON B.BRANCH_KEY = COALESCE(ALAYACARE_OFFICES.BRANCH_KEY, OFFICES.BRANCH_KEY)
		LEFT JOIN HAH.DIM_SOURCE_SYSTEM AS SOURCE_SYSTEM ON OFFICES.SOURCE_SYSTEM_ID = SOURCE_SYSTEM.SOURCE_SYSTEM_ID 		-- Added LEFT JOIN WITH DIM_SOURCE_SYSTEM TO revert back payroll TO AMS branch consolidations  -- by Shikhar
		WHERE SOURCE_SYSTEM.SOURCE_SYSTEM_TYPE NOT ILIKE ''%Payroll%''
		AND OFFICES.ORIGINAL_BRANCH_KEY <> B.BRANCH_KEY 
) , 
MERGE_2 AS (
	--JOLIET_OFFICE 
	SELECT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY ,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2021-09-24'' AS CONSOLIDATE_DATE,FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME IN (''JOLIET'')	AND B.SOURCE_SYSTEM_ID =''3'' AND B.SYSTEM_CODE =''IL''
	WHERE A.BRANCH_NAME =''JOLIET OFFICE''
	AND A.SYSTEM_CODE =''CCSI''
	AND A.SOURCE_SYSTEM_ID =''8''
	UNION
	--PITTSFIED_OFFICE 
	SELECT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY ,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2021-11-01'' AS CONSOLIDATE_DATE,FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''PITTSFIELD''
	AND B.SYSTEM_CODE =''IL'' AND B.SOURCE_SYSTEM_ID =''3''
	WHERE A.BRANCH_NAME =''PITTSFIELD OFFICE''
	AND A.SYSTEM_CODE =''CCSI''
	AND A.SOURCE_SYSTEM_ID =''8''
	UNION
	--PEKIN_OFFICE 
	SELECT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY ,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2021-11-11'' AS CONSOLIDATE_DATE,FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''PEKIN'' AND B.SOURCE_SYSTEM_ID =''3''
	AND B.SYSTEM_CODE =''IL''
	WHERE A.BRANCH_NAME =''PEKIN OFFICE''
	AND A.SYSTEM_CODE =''CCSI''
	AND A.SOURCE_SYSTEM_ID =''8''
	--UNION 							-- Commented to revert back payroll to AMS branch consolidations  -- by Shikhar
	--TERRE_HAUTE_OFFICE 
	--SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY ,
	--B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	--''2021-11-01'' AS CONSOLIDATE_DATE,FALSE AS IS_HISTORY
	--FROM HAH.DIM_BRANCH A
	--JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''H_TERRE HAUTE''
	--WHERE A.PARENT_BRANCH_NAME =''IN - A_TERRE HAUTE (25)''
	UNION
	--SOUTH_BEND_OFFICE 
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY ,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2021-12-01'' AS CONSOLIDATE_DATE,FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''H_SOUTH BEND'' AND B.SOURCE_SYSTEM_ID = ''7'' AND B.SYSTEM_CODE = ''MATRIXCARE''
	WHERE A.BRANCH_NAME =''A_SOUTH BEND'' AND A.SOURCE_SYSTEM_ID = ''7'' AND A.SYSTEM_CODE = ''MATRIXCARE''
	UNION
	--LAFAYETTE_OFFICE 
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY ,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2021-12-01'' AS CONSOLIDATE_DATE,FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''H_LAFAYETTE'' AND B.SOURCE_SYSTEM_ID = ''7'' AND B.SYSTEM_CODE = ''MATRIXCARE''
	WHERE A.BRANCH_NAME =''A_LAFAYETTE'' AND A.SOURCE_SYSTEM_ID = ''7'' AND A.SYSTEM_CODE = ''MATRIXCARE''
	UNION
	--BLOMMINGTON_OFFICE 
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY ,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2021-11-01'' AS CONSOLIDATE_DATE,FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''H_BLOOMINGTON'' AND B.SOURCE_SYSTEM_ID = ''7'' AND B.SYSTEM_CODE = ''MATRIXCARE''
	WHERE A.BRANCH_NAME =''A_BLOOMINGTON'' AND A.SOURCE_SYSTEM_ID = ''7'' AND A.SYSTEM_CODE = ''MATRIXCARE''
	UNION
	--HILLSBORRO_OFFICE 
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY ,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2021-10-01'' AS CONSOLIDATE_DATE,FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''UNION'' AND B.SOURCE_SYSTEM_ID=''3'' AND B.SYSTEM_CODE= ''MO''
	WHERE A.PARENT_BRANCH_NAME =''MO - HILLSBORO (54)'' AND A.SOURCE_SYSTEM_ID=''3'' AND A.SYSTEM_CODE= ''MO''
	--UNION 							-- Commented to revert back payroll to AMS branch consolidations  -- by Shikhar
	--INDY_NORTH_OFFICE 
	--SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY ,
	--B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	--''2022-03-31'' AS CONSOLIDATE_DATE,FALSE AS IS_HISTORY
	--FROM HAH.DIM_BRANCH A
	--JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''H_INDIANAPOLIS EAST''
	--WHERE A.PARENT_BRANCH_NAME =''IN - A_INDY NORTH (12)''
	--UNION 							-- Commented to revert back payroll to AMS branch consolidations  -- by Shikhar
	--MUNCIE_OFFICE 
	--SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY ,
	--B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	--''2022-03-31'' AS CONSOLIDATE_DATE,FALSE AS IS_HISTORY
	--FROM HAH.DIM_BRANCH A
	--JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''H_MUNCIE''
	--WHERE A.PARENT_BRANCH_NAME =''IN - A_MUNCIE (15)''
	UNION
	--CROWPOINT_OFFICE 
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY ,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2022-03-31'' AS CONSOLIDATE_DATE,FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''H_SCHERERVILLE''AND B.SOURCE_SYSTEM_ID = ''7'' AND B.SYSTEM_CODE = ''MATRIXCARE''
	WHERE A.PARENT_BRANCH_NAME =''IN - A_CROWN POINT (27)'' AND A.SOURCE_SYSTEM_ID = ''7'' AND A.SYSTEM_CODE = ''MATRIXCARE''
	--UNION  							-- Commented to revert back payroll to AMS branch consolidations  -- by Shikhar
	--SEYMOUR_OFFCE 
	--SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY ,
	--B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	--''2022-03-31'' AS CONSOLIDATE_DATE,FALSE AS IS_HISTORY
	--FROM HAH.DIM_BRANCH A
	--JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''H_SEYMOUR''
	--WHERE A.PARENT_BRANCH_NAME =''IN - A_SEYMOUR (22)''
	--UNION 							-- Commented to revert back payroll to AMS branch consolidations  -- by Shikhar
	--JEFFORSONVILLE_OFFICE 
	--SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY ,
	--B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	--''2022-03-31'' AS CONSOLIDATE_DATE,FALSE AS IS_HISTORY
	--FROM HAH.DIM_BRANCH A
	--JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''H_NEW ALBANY''
	--WHERE A.PARENT_BRANCH_NAME =''IN - A_JEFFERSONVILLE (3)''
	--UNION 							-- Commented to revert back payroll to AMS branch consolidations  -- by Shikhar
	--EVANSVILLE_OFFICE 
	--SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY ,
	--B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	--''2022-03-31'' AS CONSOLIDATE_DATE,FALSE AS IS_HISTORY
	--FROM HAH.DIM_BRANCH A
	--JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''H_EVANSVILLE''
	--WHERE A.PARENT_BRANCH_NAME =''IN - A_EVANSVILLE (16)''
	--UNION 							-- Commented to revert back payroll to AMS branch consolidations  -- by Shikhar
	--FORTWAYNE_OFFICE AS 
	--SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY ,
	--B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	--''2022-03-31'' AS CONSOLIDATE_DATE,FALSE AS IS_HISTORY
	--FROM HAH.DIM_BRANCH A
	--JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''H_FORT WAYNE''
	--WHERE A.PARENT_BRANCH_NAME =''IN - A_FT. WAYNE (17)''
	UNION
	--METROPOLIS_OFFICE 
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY ,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2022-02-25'' AS CONSOLIDATE_DATE,FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''CARBONDALE'' AND B.SOURCE_SYSTEM_ID = ''3'' AND B.SYSTEM_CODE = ''IL''
	WHERE A.BRANCH_NAME =''METROPOLIS'' AND A.SOURCE_SYSTEM_ID= ''3'' AND A.SYSTEM_CODE = ''IL''
	UNION
	--SWANSEA_OFFICE 
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY ,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2022-02-28'' AS CONSOLIDATE_DATE,FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''ALTON'' AND B.SOURCE_SYSTEM_ID = ''3'' AND B.SYSTEM_CODE = ''IL''
	WHERE A.BRANCH_NAME =''SWANSEA OFFICE'' AND A.SOURCE_SYSTEM_ID = ''8'' AND A.SYSTEM_CODE = ''CCSI''
	UNION 
	--ANN_ARBOR_OFFCE 
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY ,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''1900-01-01'' AS CONSOLIDATE_DATE,FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.PARENT_BRANCH_NAME =''MI - MI_ANN ARBOR (55)'' AND B.SOURCE_SYSTEM_ID = ''7'' AND B.SYSTEM_CODE = ''MATRIXCARE''
	WHERE A.PARENT_BRANCH_NAME = ''MI - ANN ARBOR (76)'' AND A.SOURCE_SYSTEM_ID = ''3'' AND A.SYSTEM_CODE = ''MI''
	UNION
	--AUBURNHILLS_OFFICE 
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY ,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''1900-01-01'' AS CONSOLIDATE_DATE,FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.PARENT_BRANCH_NAME =''MI - MI_AUBURN HILLS (56)'' AND B.SOURCE_SYSTEM_ID = ''7'' AND B.SYSTEM_CODE = ''MATRIXCARE''
	WHERE A.PARENT_BRANCH_NAME = ''MI - AUBURN HILLS (72)'' AND A.SOURCE_SYSTEM_ID = ''3'' AND A.SYSTEM_CODE = ''MI''
	UNION
	--DEARBORN_OFFICE 
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY ,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''1900-01-01'' AS CONSOLIDATE_DATE,FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.PARENT_BRANCH_NAME =''MI - MI_DEARBORN (53)'' AND B.SOURCE_SYSTEM_ID = ''7'' AND B.SYSTEM_CODE = ''MATRIXCARE''
	WHERE A.PARENT_BRANCH_NAME = ''MI - DEARBORN (74)'' AND A.SOURCE_SYSTEM_ID = ''3'' AND A.SYSTEM_CODE = ''MI''
	UNION
	--LANSING_OFFICE 
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY ,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''1900-01-01'' AS CONSOLIDATE_DATE,FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.PARENT_BRANCH_NAME =''MI - MI_LANSING (60)'' AND B.SOURCE_SYSTEM_ID = ''7'' AND B.SYSTEM_CODE = ''MATRIXCARE''
	WHERE A.PARENT_BRANCH_NAME = ''MI - LANSING (78)'' AND A.SOURCE_SYSTEM_ID = ''3'' AND A.SYSTEM_CODE = ''MI''
	UNION
	--FLINT_OFFICE 
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY ,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''1900-01-01'' AS CONSOLIDATE_DATE,FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.PARENT_BRANCH_NAME =''MI - MI_FLINT (59)'' AND B.SOURCE_SYSTEM_ID = ''7'' AND B.SYSTEM_CODE = ''MATRIXCARE''
	WHERE A.PARENT_BRANCH_NAME = ''MI - FLINT (79)'' AND A.SOURCE_SYSTEM_ID = ''3'' AND A.SYSTEM_CODE = ''MI''
	UNION
	--WARREN_OFFCE 
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY ,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''1900-01-01'' AS CONSOLIDATE_DATE,FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.PARENT_BRANCH_NAME =''MI - MI_WARREN (54)'' AND B.SOURCE_SYSTEM_ID = ''7'' AND B.SYSTEM_CODE = ''MATRIXCARE''
	WHERE A.PARENT_BRANCH_NAME = ''MI - WARREN (75)'' AND A.SOURCE_SYSTEM_ID = ''3'' AND A.SYSTEM_CODE = ''MI''
	UNION
	--VILLA_GROOVE_OFFCE 
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY ,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2021-07-01'' AS CONSOLIDATE_DATE,FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.PARENT_BRANCH_NAME =''IL - VILLA GROVE (752)'' AND B.SOURCE_SYSTEM_ID = ''3'' AND B.SYSTEM_CODE = ''IL''
	WHERE A.PARENT_BRANCH_NAME = ''IL - VILLA GROVE OFFICE (854)'' AND A.SOURCE_SYSTEM_ID = ''8'' AND A.SYSTEM_CODE = ''CCSI''
	UNION
	--QUINCY_OFFICE 
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY ,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2021-07-01'' AS CONSOLIDATE_DATE,FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.PARENT_BRANCH_NAME =''IL - QUINCY (753)'' AND B.SOURCE_SYSTEM_ID = ''3'' AND B.SYSTEM_CODE = ''IL''
	WHERE A.PARENT_BRANCH_NAME = ''IL - QUINCY OFFICE (789)'' AND A.SOURCE_SYSTEM_ID = ''8'' AND A.SYSTEM_CODE = ''CCSI''
	UNION
	--HOMEWOOD_OFFICE 
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY ,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2021-07-01'' AS CONSOLIDATE_DATE,FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.PARENT_BRANCH_NAME =''IL - HOMEWOOD (756)'' AND B.SOURCE_SYSTEM_ID = ''3'' AND B.SYSTEM_CODE = ''IL''
	WHERE A.PARENT_BRANCH_NAME = ''IL - HOMEWOOD OFFICE (427)'' AND A.SOURCE_SYSTEM_ID = ''8'' AND A.SYSTEM_CODE = ''CCSI''
	UNION
	--HILLSIDE_OFFICE 
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY ,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2021-07-01'' AS CONSOLIDATE_DATE,FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.PARENT_BRANCH_NAME =''IL - HILLSIDE (755)'' AND B.SOURCE_SYSTEM_ID = ''3'' AND B.SYSTEM_CODE = ''IL''
	WHERE A.PARENT_BRANCH_NAME = ''IL - HILLSIDE OFFICE (625)'' AND A.SOURCE_SYSTEM_ID = ''8'' AND A.SYSTEM_CODE = ''CCSI''
	UNION 
	--SPRINGFIELD_OFFICE 
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY ,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2021-09-27'' AS CONSOLIDATE_DATE,FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''SPRINGFIELD'' AND B.OFFICE_ADDRESS1 =''1873 East Sangamon Ave.'' AND B.SOURCE_SYSTEM_ID = ''3'' AND B.SYSTEM_CODE = ''IL''
	WHERE A.BRANCH_NAME = ''SPRINGFIELD OFFICE''
	AND A.SOURCE_SYSTEM_ID = ''8'' AND A.SYSTEM_CODE =''CCSI''
	AND A.OFFICE_ADDRESS1 =''1320 South 2nd Street''
	UNION 
	-- CHICAGO OFFICE
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY ,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2021-10-11'' AS CONSOLIDATE_DATE,FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''CHICAGO'' AND B.PARENT_BRANCH_NAME =''IL - CHICAGO (1)'' AND B.SOURCE_SYSTEM_ID =''3'' AND B.SYSTEM_CODE = ''IL''
	WHERE A.BRANCH_NAME = ''CHICAGO OFFICE''
	AND A.SYSTEM_CODE =''CCSI''
	AND A.SOURCE_SYSTEM_ID =''8''
	UNION 
	-- ROCKFORD OFFICE
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY ,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2021-11-11'' AS CONSOLIDATE_DATE,FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''ROCKFORD'' AND B.PARENT_BRANCH_NAME =''IL - ROCKFORD (13)'' AND B.SOURCE_SYSTEM_ID =''3'' AND B.SYSTEM_CODE = ''IL''
	WHERE A.BRANCH_NAME = ''ROCKFORD OFFICE''
	AND A.SYSTEM_CODE =''CCSI''
	AND A.SOURCE_SYSTEM_ID =''8''
	UNION 
	-- SALEM OFFICE
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY ,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2022-02-18'' AS CONSOLIDATE_DATE,FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''MT. VERNON'' AND B.PARENT_BRANCH_NAME =''IL - MT. VERNON (14)'' AND B.SOURCE_SYSTEM_ID =''3'' AND B.SYSTEM_CODE = ''IL''
	WHERE A.BRANCH_NAME = ''SALEM''
	AND A.SYSTEM_CODE =''IL''
	AND A.SOURCE_SYSTEM_ID =''3''
	UNION 
	-- HAH FAIRFIELD
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY ,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2021-10-18'' AS CONSOLIDATE_DATE,FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''FAIRFIELD OFFICE'' AND B.SYSTEM_CODE =''CCSI'' AND B.SOURCE_SYSTEM_ID =''8''
	WHERE A.BRANCH_NAME IN (''FAIRFIELD'')
	AND A.SYSTEM_CODE =''IL''
	AND A.SOURCE_SYSTEM_ID =''3''
	UNION 
	--CARMEL OFFICE
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY ,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2022-02-28'' AS CONSOLIDATE_DATE,FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''FAIRFIELD OFFICE'' AND B.SYSTEM_CODE =''CCSI'' AND B.SOURCE_SYSTEM_ID =''8''
	WHERE A.BRANCH_NAME IN (''MT CARMEL'')
	AND A.SYSTEM_CODE =''IL''
	AND A.SOURCE_SYSTEM_ID =''3''
	UNION
	--BRADLEY OFFICE
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY ,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2022-03-21'' AS CONSOLIDATE_DATE,FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''JOLIET'' AND B.SYSTEM_CODE =''IL'' AND B.SOURCE_SYSTEM_ID =''3''
	WHERE A.BRANCH_NAME IN (''BRADLEY'')
	AND A.SYSTEM_CODE =''IL''
	AND A.SOURCE_SYSTEM_ID =''3''
	UNION
	--FREEPORT OFFICE
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY ,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2022-03-21'' AS CONSOLIDATE_DATE,FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''ROCKFORD'' AND B.SYSTEM_CODE =''IL'' AND B.SOURCE_SYSTEM_ID =''3''
	WHERE A.BRANCH_NAME IN (''FREEPORT'')
	AND A.SYSTEM_CODE =''IL''
	AND A.SOURCE_SYSTEM_ID =''3''
	UNION
	--GALESBURG OFFICE
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY ,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2022-03-21'' AS CONSOLIDATE_DATE,FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''MOLINE'' AND B.SYSTEM_CODE =''IL'' AND B.SOURCE_SYSTEM_ID =''3''
	WHERE A.BRANCH_NAME IN (''GALESBURG'')
	AND A.SYSTEM_CODE =''IL''
	AND A.SOURCE_SYSTEM_ID =''3''
	UNION
	--OTTAWA OFFICE
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY ,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2022-03-21'' AS CONSOLIDATE_DATE,FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''JOLIET'' AND B.SYSTEM_CODE =''IL'' AND B.SOURCE_SYSTEM_ID =''3''
	WHERE A.BRANCH_NAME IN (''OTTAWA'')
	AND A.SYSTEM_CODE =''IL''
	AND A.SOURCE_SYSTEM_ID =''3''
	UNION
	--MACOMB OFFICE
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY ,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2022-03-21'' AS CONSOLIDATE_DATE,FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''CANTON'' AND B.SYSTEM_CODE =''IL'' AND B.SOURCE_SYSTEM_ID =''3''
	WHERE A.BRANCH_NAME IN (''MACOMB'')
	AND A.SYSTEM_CODE =''IL''
	AND A.SOURCE_SYSTEM_ID =''3''
	UNION
	--WOODRIDGE OFFICE
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY ,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2022-03-21'' AS CONSOLIDATE_DATE,FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''WHEATON'' AND B.SYSTEM_CODE =''IL'' AND B.SOURCE_SYSTEM_ID =''3''
	WHERE A.BRANCH_NAME IN (''WOODRIDGE'')
	AND A.SYSTEM_CODE =''IL''
	AND A.SOURCE_SYSTEM_ID =''3''
	UNION
	--COLUMBIA OFFICE
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY ,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2021-10-11'' AS CONSOLIDATE_DATE,FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''JEFFERSON CITY'' AND B.SYSTEM_CODE =''MO'' AND B.SOURCE_SYSTEM_ID =''3''
	WHERE A.BRANCH_NAME IN (''COLUMBIA'')
	AND A.SYSTEM_CODE =''MO''
	AND A.SOURCE_SYSTEM_ID =''3''
	UNION
	--ST LOUIS OFFICE
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY ,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2021-10-11'' AS CONSOLIDATE_DATE,TRUE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''UNION'' AND B.SYSTEM_CODE =''MO'' AND B.SOURCE_SYSTEM_ID =''3''
	WHERE A.BRANCH_NAME IN (''ST. LOUIS'')
	AND A.SYSTEM_CODE =''MO''
	AND A.SOURCE_SYSTEM_ID =''3''
	UNION 
	--KENNETT TO CAPE GIRARDEAU
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY ,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2021-10-11'' AS CONSOLIDATE_DATE,FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''CAPE GIRARDEAU'' AND B.SYSTEM_CODE =''MO'' AND B.SOURCE_SYSTEM_ID =''3''
	WHERE A.BRANCH_NAME IN (''KENNETT'')
	AND A.SYSTEM_CODE =''MO''
	AND A.SOURCE_SYSTEM_ID =''3''
	UNION
	-- A_RICHMOND TO H_RICHMOND
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY ,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2021-12-31'' AS CONSOLIDATE_DATE,FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''H_RICHMOND'' AND B.SOURCE_SYSTEM_ID =''7'' AND B.SYSTEM_CODE = ''MATRIXCARE''
	WHERE A.BRANCH_NAME IN (''A_RICHMOND'')
	AND A.SOURCE_SYSTEM_ID =''7'' AND A.SYSTEM_CODE = ''MATRIXCARE''
	UNION
	-- A_GREENWOOD TO H_GREENWOOD
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY ,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2021-03-31'' AS CONSOLIDATE_DATE,FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''H_GREENWOOD'' AND B.SOURCE_SYSTEM_ID =''7'' AND B.SYSTEM_CODE = ''MATRIXCARE''
	WHERE A.BRANCH_NAME IN (''A_GREENWOOD'')
	AND A.SOURCE_SYSTEM_ID =''7'' AND A.SYSTEM_CODE = ''MATRIXCARE''
	UNION
	-- MT VERNON ADS TO MT. VERNON							
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY ,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''1900-01-01'' AS CONSOLIDATE_DATE,FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''MT. VERNON'' AND B.SOURCE_SYSTEM_ID =''3'' AND B.OFFICE_CODE =''14'' AND B.SYSTEM_CODE = ''IL''
	WHERE A.BRANCH_NAME IN (''MT VERNON ADS'')
	AND A.SOURCE_SYSTEM_ID =''3'' AND A.SYSTEM_CODE = ''IL''
	AND A.OFFICE_CODE =''743''
	UNION  
	-- EVANSTON TO SKOKIE
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY ,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2022-06-01'' AS CONSOLIDATE_DATE,FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''SKOKIE'' AND B.SYSTEM_CODE =''IL'' AND B.SOURCE_SYSTEM_ID =''3''
	WHERE A.BRANCH_NAME = ''EVANSTON''
	AND A.SYSTEM_CODE =''IL''
	AND A.SOURCE_SYSTEM_ID =''3''
	UNION
	-- BETHLEHEM TO ALLENTOWN
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''1900-01-01'' AS CONSOLIDATE_DATE, FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''ALLENTOWN'' AND B.SYSTEM_CODE=''OSHAH - PA'' AND B.SOURCE_SYSTEM_ID = ''17''
	WHERE A.BRANCH_NAME IN (''BETHLEHEM'')
	AND A.SYSTEM_CODE = ''OPENSYSTEMS - PA''
	AND A.SOURCE_SYSTEM_ID = ''17''
	--AND A.SYSTEM_CODE IN (''ADP-OPAL'',''OPENSYSTEMS - PA'')		-- Commented to revert back payroll to AMS branch consolidations  -- by Shikhar
	--AND A.SOURCE_SYSTEM_ID IN (''18'',''17'')
	UNION
	-- PITTSBURGH NORTH, ERIE-ODP, Erie, Pittsburgh North TO ERIE
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''1900-01-01'' AS CONSOLIDATE_DATE, FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''ERIE'' AND B.SYSTEM_CODE=''OSHAH - PA'' AND B.SOURCE_SYSTEM_ID = ''17''
	WHERE A.BRANCH_NAME IN (''Erie'',''ERIE-ODP'',''PITTSBURGH NORTH'',''ERIE'',''Pittsburgh North'')
	AND A.SYSTEM_CODE = ''OPENSYSTEMS - PA''
	AND A.SOURCE_SYSTEM_ID = ''17''
	--AND A.SYSTEM_CODE IN (''ADP-OPAL'',''OPENSYSTEMS - PA'')
	--AND A.SOURCE_SYSTEM_ID IN (''18'',''17'')
	--UNION											-- Commented to revert back payroll to AMS branch consolidations  -- by Shikhar
	-- Pittsburgh South TO ERIE
	--SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY,
	--B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	--''1900-01-01'' AS CONSOLIDATE_DATE, FALSE AS IS_HISTORY
	--FROM HAH.DIM_BRANCH A
	--JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''ERIE'' AND B.SYSTEM_CODE=''OSHAH - PA'' AND B.SOURCE_SYSTEM_ID = ''17''
	--WHERE A.BRANCH_NAME IN (''Pittsburgh South'')
	--AND A.SYSTEM_CODE = ''ADP-OPAL''
	--AND A.SOURCE_SYSTEM_ID = ''18''
	UNION
	-- PROSTAT - Harrisburg, Harrisburg, PS HARRISBURG, PS LEBANON, PROSTAT - Lebanon, YORK, YORK-ODP TO HARRISBURG
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''1900-01-01'' AS CONSOLIDATE_DATE, FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''HARRISBURG'' AND B.SYSTEM_CODE=''OSHAH - PA'' AND B.SOURCE_SYSTEM_ID = ''17''
	WHERE A.BRANCH_NAME IN (''PROSTAT - Harrisburg'',''Harrisburg'',''PS HARRISBURG'',''HARRISBURG'',''PS LEBANON'',''PROSTAT - Lebanon'',''YORK'',''YORK-ODP'')
	AND A.SYSTEM_CODE = ''OPENSYSTEMS - PA''
	AND A.SOURCE_SYSTEM_ID = ''17''
	--AND A.SYSTEM_CODE IN (''ADP-OPAL'',''OPENSYSTEMS - PA'')		-- Commented to revert back payroll to AMS branch consolidations  -- by Shikhar
	--AND A.SOURCE_SYSTEM_ID IN (''18'',''17'')
	UNION
	-- Bala Cynwyd, BALA BEHAVIORAL HEALTH, BALA BH BSS TO HORSHAM
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''1900-01-01'' AS CONSOLIDATE_DATE, FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''HORSHAM'' AND B.SYSTEM_CODE=''OSHAH - PA'' AND B.SOURCE_SYSTEM_ID = ''17''
	WHERE A.BRANCH_NAME IN (''Bala Cynwyd'',''BALA BEHAVIORAL HEALTH'',''BALA BH BSS'')
	AND A.SYSTEM_CODE = ''OPENSYSTEMS - PA''
	AND A.SOURCE_SYSTEM_ID = ''17''
	--AND A.SYSTEM_CODE IN (''ADP-OPAL'',''OPENSYSTEMS - PA'') 		
	--AND A.SOURCE_SYSTEM_ID IN (''18'',''17'')
	UNION
	-- PROSTAT - Lancaster, York, PS LANCASTER TO LANCASTER
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''1900-01-01'' AS CONSOLIDATE_DATE, FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''LANCASTER'' AND B.SYSTEM_CODE=''OSHAH - PA'' AND B.SOURCE_SYSTEM_ID = ''17''
	WHERE A.BRANCH_NAME IN (''PROSTAT - Lancaster'',''York'',''PS LANCASTER'')
	AND A.SYSTEM_CODE = ''OPENSYSTEMS - PA''
	AND A.SOURCE_SYSTEM_ID = ''17''
	--AND A.SYSTEM_CODE IN (''ADP-OPAL'',''OPENSYSTEMS - PA'')
	--AND A.SOURCE_SYSTEM_ID IN (''18'',''17'')
	UNION
	-- BH Bala, NE PHILADELPHIA, BALA CYNWYD, NE Philly TO PHILADELPHIA
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''1900-01-01'' AS CONSOLIDATE_DATE, FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''PHILADELPHIA'' AND B.SYSTEM_CODE=''OSHAH - PA'' AND B.SOURCE_SYSTEM_ID = ''17''
	WHERE A.BRANCH_NAME IN (''BH Bala'',''NE PHILADELPHIA'',''BALA CYNWYD'',''NE Philly'')
	AND A.SYSTEM_CODE = ''OPENSYSTEMS - PA''
	AND A.SOURCE_SYSTEM_ID = ''17''
	--AND A.SYSTEM_CODE IN (''ADP-OPAL'',''OPENSYSTEMS - PA'')
	--AND A.SOURCE_SYSTEM_ID IN (''18'',''17'')
	UNION
	-- PITTSBURGH BEHAVIORAL, PITTSBURGH SOUTH-ODP, PITTSBURGH SOUTH TO PITTSBURGH
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''1900-01-01'' AS CONSOLIDATE_DATE, FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''PITTSBURGH'' AND B.SYSTEM_CODE=''OSHAH - PA'' AND B.SOURCE_SYSTEM_ID = ''17''
	WHERE A.BRANCH_NAME IN (''PITTSBURGH BEHAVIORAL'',''PITTSBURGH SOUTH-ODP'',''PITTSBURGH SOUTH'')
	AND A.SYSTEM_CODE = ''OPENSYSTEMS - PA''
	AND A.SOURCE_SYSTEM_ID = ''17''
	UNION
	-- PROSTAT - Pottsville, PROSTAT - Reading, Reading, READING, PS POTTSVILLE, PS READING TO READING
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''1900-01-01'' AS CONSOLIDATE_DATE, FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''READING'' AND B.SYSTEM_CODE=''OSHAH - PA'' AND B.SOURCE_SYSTEM_ID = ''17''
	WHERE A.BRANCH_NAME IN (''PROSTAT - Pottsville'',''PROSTAT - Reading'',''Reading'',''READING'',''PS POTTSVILLE'',''PS READING'')
	AND A.SYSTEM_CODE = ''OPENSYSTEMS - PA''
	AND A.SOURCE_SYSTEM_ID = ''17''
	--AND A.SYSTEM_CODE IN (''ADP-OPAL'',''OPENSYSTEMS - PA'')
	--AND A.SOURCE_SYSTEM_ID IN (''18'',''17'')
	UNION
	-- SCRANTON-ODP, SCRANTON, Scranton TO SCRANTON
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''1900-01-01'' AS CONSOLIDATE_DATE, FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''SCRANTON'' AND B.SYSTEM_CODE=''OSHAH - PA'' AND B.SOURCE_SYSTEM_ID = ''17''
	WHERE A.BRANCH_NAME IN (''SCRANTON-ODP'',''SCRANTON'',''Scranton'')
	AND A.SYSTEM_CODE = ''OPENSYSTEMS - PA''
	AND A.SOURCE_SYSTEM_ID = ''17''
	--AND A.SYSTEM_CODE IN (''ADP-OPAL'',''OPENSYSTEMS - PA'') 	-- Commented to revert back payroll to AMS branch consolidations  -- by Shikhar
	--AND A.SOURCE_SYSTEM_ID IN (''18'',''17'')
	UNION
	-- PROSTAT - Bellefonte, PROSTAT - Williamsport, PS BELLEFONTE, PS WILLIAMSPORT TO WILLIAMSPORT
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''1900-01-01'' AS CONSOLIDATE_DATE, FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''WILLIAMSPORT'' AND B.SYSTEM_CODE=''OSHAH - PA'' AND B.SOURCE_SYSTEM_ID = ''17''
	WHERE A.BRANCH_NAME IN (''PROSTAT - Bellefonte'',''PROSTAT - Williamsport'',''PS BELLEFONTE'',''PS WILLIAMSPORT'')
	AND A.SYSTEM_CODE = ''OPENSYSTEMS - PA''
	AND A.SOURCE_SYSTEM_ID = ''17''
	--AND A.SYSTEM_CODE IN (''ADP-OPAL'',''OPENSYSTEMS - PA'') 		-- Commented to revert back payroll to AMS branch consolidations  -- by Shikhar
	--AND A.SOURCE_SYSTEM_ID IN (''18'',''17'')
	UNION
	-- WILMINGTON TO WILMINGTON
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''1900-01-01'' AS CONSOLIDATE_DATE, FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''WILMINGTON'' AND B.SYSTEM_CODE=''OSHAH - DE'' AND B.SOURCE_SYSTEM_ID = ''17''
	WHERE A.BRANCH_NAME IN (''WILMINGTON'')
	AND A.SYSTEM_CODE = ''OPENSYSTEMS - DE''
	AND A.SOURCE_SYSTEM_ID = ''17''
	--WHERE A.BRANCH_NAME IN (''WILMINGTON'',''Wilmington'',''HAHDELAWARE - WILMINGTON'') 	-- Commented to revert back payroll to AMS branch consolidations  -- by Shikhar
	--AND A.SYSTEM_CODE IN (''ADP-OPAL'',''OPENSYSTEMS - DE'',''HAHDELAWARE'')
	--AND A.SOURCE_SYSTEM_ID IN (''18'',''17'',''6'')
	UNION
	-- A_KOKOMO TO H_LOGANSPORT
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2022-11-25'' AS CONSOLIDATE_DATE, FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''H_LOGANSPORT'' AND B.SYSTEM_CODE=''MATRIXCARE'' AND B.SOURCE_SYSTEM_ID = ''7''
	WHERE A.BRANCH_NAME IN (''A_KOKOMO'')
	AND A.SYSTEM_CODE = ''MATRIXCARE''
	AND A.SOURCE_SYSTEM_ID=''7''
	UNION
	-- Sandata to OSHAH migration
	SELECT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''1900-01-01'' AS CONSOLIDATE_DATE,
	FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B
	ON B.BRANCH_NAME = A.BRANCH_NAME
	AND B.SYSTEM_CODE = ''OSHAH - PA''
	AND B.SOURCE_SYSTEM_ID = ''17''
	WHERE A.SOURCE_SYSTEM_ID = ''4''
	AND A.SYSTEM_CODE = ''8485''
	AND A.OFFICE_STATE_CODE = ''PA''
	UNION
	-- CHINATOWN PA TO PHILADELPHIA
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''1900-01-01'' AS CONSOLIDATE_DATE, FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''PHILADELPHIA'' AND B.SYSTEM_CODE=''OSHAH - PA'' AND B.SOURCE_SYSTEM_ID = ''17''
	WHERE A.BRANCH_NAME IN (''CHINATOWN PA'')
	AND A.SYSTEM_CODE = ''8485''
	AND A.SOURCE_SYSTEM_ID=''4''
	UNION
	-- CORPORATE TO HORSHAM
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''1900-01-01'' AS CONSOLIDATE_DATE, FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''HORSHAM'' AND B.SYSTEM_CODE=''OSHAH - PA'' AND B.SOURCE_SYSTEM_ID = ''17''
	WHERE A.BRANCH_NAME IN (''CORPORATE'')
	AND A.SYSTEM_CODE = ''8485''
	AND A.SOURCE_SYSTEM_ID=''4''
	UNION
	-- FAIRVIEW HEIGHTS TO ALTON
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2021-10-01'' AS CONSOLIDATE_DATE, FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''ALTON'' AND B.SYSTEM_CODE=''IL'' AND B.SOURCE_SYSTEM_ID = ''3''
	WHERE A.BRANCH_NAME IN (''FAIRVIEW HEIGHTS'')
	AND A.SYSTEM_CODE = ''IL''
	AND A.SOURCE_SYSTEM_ID=''3''
	UNION
	-- SALEM TO MT VERNON
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2022-03-01'' AS CONSOLIDATE_DATE, FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''MT VERNON'' AND B.SYSTEM_CODE=''IL'' AND B.SOURCE_SYSTEM_ID = ''3''
	WHERE A.BRANCH_NAME IN (''SALEM'')
	AND A.SYSTEM_CODE = ''IL''
	AND A.SOURCE_SYSTEM_ID=''3''
	UNION
	-- EVANSVILLE, A_EVANSVILLE TO H_EVANSVILLE
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2022-03-31'' AS CONSOLIDATE_DATE, FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''H_EVANSVILLE'' AND B.SYSTEM_CODE=''MATRIXCARE'' AND B.SOURCE_SYSTEM_ID = ''7'' AND B.SOURCE_SYSTEM_TYPE = ''AMS''
	WHERE A.BRANCH_NAME IN (''EVANSVILLE'',''A_EVANSVILLE'')
	AND A.SYSTEM_CODE IN (''IN'',''MATRIXCARE'')
	AND A.SOURCE_SYSTEM_ID IN (''3'',''7'')
	AND A.SOURCE_SYSTEM_TYPE = ''AMS''
	UNION
	-- FORT WAYNE, A_FT. WAYNE TO H_FORT WAYNE
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2022-03-31'' AS CONSOLIDATE_DATE, FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''H_FORT WAYNE'' AND B.SYSTEM_CODE=''MATRIXCARE'' AND B.SOURCE_SYSTEM_ID = ''7'' AND B.SOURCE_SYSTEM_TYPE = ''AMS''
	WHERE A.BRANCH_NAME IN (''FORT WAYNE'',''A_FT. WAYNE'')
	AND A.SYSTEM_CODE IN (''IN'',''MATRIXCARE'')
	AND A.SOURCE_SYSTEM_ID IN (''3'',''7'')
	AND A.SOURCE_SYSTEM_TYPE = ''AMS''
	UNION
	-- A_INDY NORTH, INDIANAPOLIS EAST TO H_INDIANAPOLIS EAST
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2022-03-31'' AS CONSOLIDATE_DATE, FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''H_INDIANAPOLIS EAST'' AND B.SYSTEM_CODE=''MATRIXCARE'' AND B.SOURCE_SYSTEM_ID = ''7'' AND B.SOURCE_SYSTEM_TYPE = ''AMS''
	WHERE A.BRANCH_NAME IN (''A_INDY NORTH'',''INDIANAPOLIS EAST'')
	AND A.SYSTEM_CODE IN (''IN'',''MATRIXCARE'')
	AND A.SOURCE_SYSTEM_ID IN (''3'',''7'')
	AND A.SOURCE_SYSTEM_TYPE = ''AMS''
	UNION
	-- A_JEFFERSONVILLE, NEW ALBANY TO H_NEW ALBANY
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2022-03-31'' AS CONSOLIDATE_DATE, FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''H_NEW ALBANY'' AND B.SYSTEM_CODE=''MATRIXCARE'' AND B.SOURCE_SYSTEM_ID = ''7'' AND B.SOURCE_SYSTEM_TYPE = ''AMS''
	WHERE A.BRANCH_NAME IN (''A_JEFFERSONVILLE'',''NEW ALBANY'')
	AND A.SYSTEM_CODE IN (''IN'',''MATRIXCARE'')
	AND A.SOURCE_SYSTEM_ID IN (''3'',''7'')
	AND A.SOURCE_SYSTEM_TYPE = ''AMS''
	UNION
	-- MUNCIE, A_MUNCIE TO H_MUNCIE
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2022-03-31'' AS CONSOLIDATE_DATE, FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''H_MUNCIE'' AND B.SYSTEM_CODE=''MATRIXCARE'' AND B.SOURCE_SYSTEM_ID = ''7'' AND B.SOURCE_SYSTEM_TYPE = ''AMS''
	WHERE A.BRANCH_NAME IN (''MUNCIE'',''A_MUNCIE'')
	AND A.SYSTEM_CODE IN (''IN'',''MATRIXCARE'')
	AND A.SOURCE_SYSTEM_ID IN (''3'',''7'')
	AND A.SOURCE_SYSTEM_TYPE = ''AMS''
	UNION
	-- SEYMOUR, A_SEYMOUR TO H_SEYMOUR
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2022-03-31'' AS CONSOLIDATE_DATE, FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''H_SEYMOUR'' AND B.SYSTEM_CODE=''MATRIXCARE'' AND B.SOURCE_SYSTEM_ID = ''7'' AND B.SOURCE_SYSTEM_TYPE = ''AMS''
	WHERE A.BRANCH_NAME IN (''SEYMOUR'',''A_SEYMOUR'')
	AND A.SYSTEM_CODE IN (''IN'',''MATRIXCARE'')
	AND A.SOURCE_SYSTEM_ID IN (''3'',''7'')
	AND A.SOURCE_SYSTEM_TYPE = ''AMS''
	UNION
	-- TERRE HAUTE, A_TERRE HAUTE TO H_TERRE HAUTE
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2021-11-01'' AS CONSOLIDATE_DATE, FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''H_TERRE HAUTE'' AND B.SYSTEM_CODE=''MATRIXCARE'' AND B.SOURCE_SYSTEM_ID = ''7'' AND B.SOURCE_SYSTEM_TYPE = ''AMS''
	WHERE A.BRANCH_NAME IN (''TERRE HAUTE'',''A_TERRE HAUTE'')
	AND A.SYSTEM_CODE IN (''IN'',''MATRIXCARE'')
	AND A.SOURCE_SYSTEM_ID IN (''3'',''7'')
	AND A.SOURCE_SYSTEM_TYPE = ''AMS''
	UNION
	-- MI_ST. JOSEPH TO MI_ALLEGAN
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2023-06-01'' AS CONSOLIDATE_DATE, FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''MI_ALLEGAN'' AND B.SYSTEM_CODE=''MATRIXCARE'' AND B.SOURCE_SYSTEM_ID = ''7'' AND B.SOURCE_SYSTEM_TYPE = ''AMS''
	WHERE A.BRANCH_NAME IN (''MI_ST. JOSEPH'')
	AND A.SYSTEM_CODE = ''MATRIXCARE''
	AND A.SOURCE_SYSTEM_ID = ''7''
	AND A.SOURCE_SYSTEM_TYPE = ''AMS''
	UNION
	-- MI_NILES TO MI_ALLEGAN
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2023-01-01'' AS CONSOLIDATE_DATE, FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''MI_ALLEGAN'' AND B.SYSTEM_CODE=''MATRIXCARE'' AND B.SOURCE_SYSTEM_ID = ''7'' AND B.SOURCE_SYSTEM_TYPE = ''AMS''
	WHERE A.BRANCH_NAME IN (''MI_NILES'')
	AND A.SYSTEM_CODE = ''MATRIXCARE''
	AND A.SOURCE_SYSTEM_ID = ''7''
	AND A.SOURCE_SYSTEM_TYPE = ''AMS''
	UNION
	-- MI_MUSKEGON TO MI_GRANDVILLE
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2023-09-01'' AS CONSOLIDATE_DATE, FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''MI_GRANDVILLE'' AND B.SYSTEM_CODE=''MATRIXCARE'' AND B.SOURCE_SYSTEM_ID = ''7'' AND B.SOURCE_SYSTEM_TYPE = ''AMS''
	WHERE A.BRANCH_NAME IN (''MI_MUSKEGON'')
	AND A.SYSTEM_CODE = ''MATRIXCARE''
	AND A.SOURCE_SYSTEM_ID = ''7''
	AND A.SOURCE_SYSTEM_TYPE = ''AMS''
	UNION
	-- MUNDELEIN TO WHEELING
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2023-09-01'' AS CONSOLIDATE_DATE, FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''WHEELING'' AND B.SYSTEM_CODE=''IL'' AND B.SOURCE_SYSTEM_ID = ''3'' AND B.SOURCE_SYSTEM_TYPE = ''AMS''
	WHERE A.BRANCH_NAME IN (''MUNDELEIN'')
	AND A.SYSTEM_CODE = ''IL''
	AND A.SOURCE_SYSTEM_ID = ''3''
	AND A.SOURCE_SYSTEM_TYPE = ''AMS''
	UNION
	-- MS(DATAFLEX) TO OSHAH - MS MIGRATION
	SELECT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''1900-01-01'' AS CONSOLIDATE_DATE,
	FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B
	ON B.BRANCH_NAME = A.BRANCH_NAME
	AND B.SYSTEM_CODE = ''OSHAH - MS''
	AND B.SOURCE_SYSTEM_ID = ''17''
	AND B.OFFICE_STATE_CODE = ''MS''
	AND B.SOURCE_SYSTEM_TYPE = ''AMS''
	WHERE A.SOURCE_SYSTEM_ID = ''3''
	AND A.SYSTEM_CODE = ''MS''
	AND A.OFFICE_STATE_CODE = ''MS''
	AND A.SOURCE_SYSTEM_TYPE = ''AMS''
	UNION
	-- CANTON TO HAH CANTON
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''1900-01-01'' AS CONSOLIDATE_DATE, FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''HAH CANTON'' AND B.SYSTEM_CODE=''PRIME'' AND B.SOURCE_SYSTEM_ID = ''14'' AND B.SOURCE_SYSTEM_TYPE = ''AMS''
	WHERE A.BRANCH_NAME IN (''CANTON'')
	AND A.SYSTEM_CODE = ''CLEARCARE''
	AND A.SOURCE_SYSTEM_ID = ''16''
	AND A.SOURCE_SYSTEM_TYPE = ''AMS''
	UNION
	-- CLEVELAND TO HAH CLEVELAND
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''1900-01-01'' AS CONSOLIDATE_DATE, FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''HAH CLEVELAND'' AND B.SYSTEM_CODE=''PRIME'' AND B.SOURCE_SYSTEM_ID = ''14'' AND B.SOURCE_SYSTEM_TYPE = ''AMS''
	WHERE A.BRANCH_NAME IN (''CLEVELAND'')
	AND A.SYSTEM_CODE = ''CLEARCARE''
	AND A.SOURCE_SYSTEM_ID = ''16''
	AND A.SOURCE_SYSTEM_TYPE = ''AMS''
	UNION
	-- TOLEDO TO HAH TOLEDO
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''1900-01-01'' AS CONSOLIDATE_DATE, FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''HAH TOLEDO'' AND B.SYSTEM_CODE=''PRIME'' AND B.SOURCE_SYSTEM_ID = ''14'' AND B.SOURCE_SYSTEM_TYPE = ''AMS''
	WHERE A.BRANCH_NAME IN (''TOLEDO'')
	AND A.SYSTEM_CODE = ''CLEARCARE''
	AND A.SOURCE_SYSTEM_ID = ''16''
	AND A.SOURCE_SYSTEM_TYPE = ''AMS''
	UNION
	-- YOUNGSTOWN (GIRARD) TO HAH YOUNGSTOWN
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''1900-01-01'' AS CONSOLIDATE_DATE, FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''HAH YOUNGSTOWN'' AND B.SYSTEM_CODE=''PRIME'' AND B.SOURCE_SYSTEM_ID = ''14'' AND B.SOURCE_SYSTEM_TYPE = ''AMS''
	WHERE A.BRANCH_NAME IN (''YOUNGSTOWN (GIRARD)'')
	AND A.SYSTEM_CODE = ''CLEARCARE''
	AND A.SOURCE_SYSTEM_ID = ''16''
	AND A.SOURCE_SYSTEM_TYPE = ''AMS''
	UNION
	-- Below 6 consolidations are internal AXXESS consolidations, branch having BRANCH_SERVICE_LINE = HH are consolidated into branch having BRANCH_SERVICE_LINE = HC 		  -- by Shikhar
	-- PRIME COLUMBUS(HH) TO PRIME COLUMBUS(HC)
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''1900-01-01'' AS CONSOLIDATE_DATE, FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME = ''PRIME COLUMBUS'' AND B.SYSTEM_CODE = ''PRIME'' AND B.BRANCH_SERVICE_LINE = ''HC'' AND B.SOURCE_SYSTEM_ID = ''14'' AND B.SOURCE_SYSTEM_TYPE = ''AMS''
	WHERE A.BRANCH_NAME IN (''PRIME COLUMBUS'')
	AND A.SYSTEM_CODE = ''PRIME''
	AND A.BRANCH_SERVICE_LINE = ''HH''
	AND A.SOURCE_SYSTEM_ID = ''14''
	AND A.SOURCE_SYSTEM_TYPE = ''AMS''
	UNION
	-- PRIME CINCINNATI(HH) TO PRIME CINCINNATI(HC)
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''1900-01-01'' AS CONSOLIDATE_DATE, FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME = ''PRIME CINCINNATI'' AND B.SYSTEM_CODE = ''PRIME'' AND B.BRANCH_SERVICE_LINE = ''HC'' AND B.SOURCE_SYSTEM_ID = ''14'' AND B.SOURCE_SYSTEM_TYPE = ''AMS''
	WHERE A.BRANCH_NAME IN (''PRIME CINCINNATI'')
	AND A.SYSTEM_CODE = ''PRIME''
	AND A.BRANCH_SERVICE_LINE = ''HH''
	AND A.SOURCE_SYSTEM_ID = ''14''
	AND A.SOURCE_SYSTEM_TYPE = ''AMS''
	UNION
	-- PRIME CIRCLEVILLE(HH) TO PRIME CIRCLEVILLE(HC)
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''1900-01-01'' AS CONSOLIDATE_DATE, FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME = ''PRIME CIRCLEVILLE'' AND B.SYSTEM_CODE = ''PRIME'' AND B.BRANCH_SERVICE_LINE = ''HC'' AND B.SOURCE_SYSTEM_ID = ''14'' AND B.SOURCE_SYSTEM_TYPE = ''AMS''
	WHERE A.BRANCH_NAME IN (''PRIME CIRCLEVILLE'')
	AND A.SYSTEM_CODE = ''PRIME''
	AND A.BRANCH_SERVICE_LINE = ''HH''
	AND A.SOURCE_SYSTEM_ID = ''14''
	AND A.SOURCE_SYSTEM_TYPE = ''AMS''
	UNION
	-- PRIME DAYTON(HH) TO PRIME DAYTON(HC)
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''1900-01-01'' AS CONSOLIDATE_DATE, FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME = ''PRIME DAYTON'' AND B.SYSTEM_CODE = ''PRIME'' AND B.BRANCH_SERVICE_LINE = ''HC'' AND B.SOURCE_SYSTEM_ID = ''14'' AND B.SOURCE_SYSTEM_TYPE = ''AMS''
	WHERE A.BRANCH_NAME IN (''PRIME DAYTON'')
	AND A.SYSTEM_CODE = ''PRIME''
	AND A.BRANCH_SERVICE_LINE = ''HH''
	AND A.SOURCE_SYSTEM_ID = ''14''
	AND A.SOURCE_SYSTEM_TYPE = ''AMS''
	UNION
	-- PRIME TOLEDO(HH) TO PRIME TOLEDO(HC)
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''1900-01-01'' AS CONSOLIDATE_DATE, FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME = ''PRIME TOLEDO'' AND B.SYSTEM_CODE = ''PRIME'' AND B.BRANCH_SERVICE_LINE = ''HC'' AND B.SOURCE_SYSTEM_ID = ''14'' AND B.SOURCE_SYSTEM_TYPE = ''AMS''
	WHERE A.BRANCH_NAME IN (''PRIME TOLEDO'')
	AND A.SYSTEM_CODE = ''PRIME''
	AND A.BRANCH_SERVICE_LINE = ''HH''
	AND A.SOURCE_SYSTEM_ID = ''14''
	AND A.SOURCE_SYSTEM_TYPE = ''AMS''
	UNION
	-- PRIME WASHINGTON COURT HOUSE(HH) TO PRIME WASHINGTON COURT HOUSE(HC)
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''1900-01-01'' AS CONSOLIDATE_DATE, FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME = ''PRIME WASHINGTON COURT HOUSE'' AND B.SYSTEM_CODE = ''PRIME'' AND B.BRANCH_SERVICE_LINE = ''HC'' AND B.SOURCE_SYSTEM_ID = ''14'' AND B.SOURCE_SYSTEM_TYPE = ''AMS''
	WHERE A.BRANCH_NAME IN (''PRIME WASHINGTON COURT HOUSE'')
	AND A.SYSTEM_CODE = ''PRIME''
	AND A.BRANCH_SERVICE_LINE = ''HH''
	AND A.SOURCE_SYSTEM_ID = ''14''
	AND A.SOURCE_SYSTEM_TYPE = ''AMS''
	UNION
	-- Below 6 consolidations are ASR(13) to AXXESS(14) Migration (AXXESS branches having BRANCH_SERVICE_LINE = HC) 			  -- by Shikhar
	-- CINCINNATI TO PRIME CINCINNATI(HC)
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''1900-01-01'' AS CONSOLIDATE_DATE, FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME = ''PRIME CINCINNATI'' AND B.SYSTEM_CODE = ''PRIME'' AND B.BRANCH_SERVICE_LINE = ''HC'' AND B.SOURCE_SYSTEM_ID = ''14'' AND B.SOURCE_SYSTEM_TYPE = ''AMS''
	WHERE A.BRANCH_NAME IN (''CINCINNATI'')
	AND A.SYSTEM_CODE = ''PRIME''
	AND A.SOURCE_SYSTEM_ID = ''13''
	AND A.SOURCE_SYSTEM_TYPE = ''AMS''
	UNION
	-- CIRCLEVILLE TO PRIME CIRCLEVILLE(HC)
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''1900-01-01'' AS CONSOLIDATE_DATE, FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME = ''PRIME CIRCLEVILLE'' AND B.SYSTEM_CODE = ''PRIME'' AND B.BRANCH_SERVICE_LINE = ''HC'' AND B.SOURCE_SYSTEM_ID = ''14'' AND B.SOURCE_SYSTEM_TYPE = ''AMS''
	WHERE A.BRANCH_NAME IN (''CIRCLEVILLE'')
	AND A.SYSTEM_CODE = ''PRIME''
	AND A.SOURCE_SYSTEM_ID = ''13''
	AND A.SOURCE_SYSTEM_TYPE = ''AMS''
	UNION
	-- COLUMBUS TO PRIME COLUMBUS(HC)
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''1900-01-01'' AS CONSOLIDATE_DATE, FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME = ''PRIME COLUMBUS'' AND B.SYSTEM_CODE = ''PRIME'' AND B.BRANCH_SERVICE_LINE = ''HC'' AND B.SOURCE_SYSTEM_ID = ''14'' AND B.SOURCE_SYSTEM_TYPE = ''AMS''
	WHERE A.BRANCH_NAME IN (''COLUMBUS'')
	AND A.SYSTEM_CODE = ''PRIME''
	AND A.SOURCE_SYSTEM_ID = ''13''
	AND A.SOURCE_SYSTEM_TYPE = ''AMS''
	UNION
	-- DAYTON TO PRIME DAYTON(HC)
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''1900-01-01'' AS CONSOLIDATE_DATE, FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME = ''PRIME DAYTON'' AND B.SYSTEM_CODE = ''PRIME''AND B.BRANCH_SERVICE_LINE = ''HC'' AND B.SOURCE_SYSTEM_ID = ''14'' AND B.SOURCE_SYSTEM_TYPE = ''AMS''
	WHERE A.BRANCH_NAME IN (''DAYTON'')
	AND A.SYSTEM_CODE = ''PRIME''
	AND A.SOURCE_SYSTEM_ID = ''13''
	AND A.SOURCE_SYSTEM_TYPE = ''AMS''
	UNION
	-- TOLEDO TO PRIME TOLEDO(HC)
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''1900-01-01'' AS CONSOLIDATE_DATE, FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME = ''PRIME TOLEDO'' AND B.SYSTEM_CODE = ''PRIME'' AND B.BRANCH_SERVICE_LINE = ''HC'' AND B.SOURCE_SYSTEM_ID = ''14'' AND B.SOURCE_SYSTEM_TYPE = ''AMS''
	WHERE A.BRANCH_NAME IN (''TOLEDO'')
	AND A.SYSTEM_CODE = ''PRIME''
	AND A.SOURCE_SYSTEM_ID = ''13''
	AND A.SOURCE_SYSTEM_TYPE = ''AMS''
	UNION
	-- WASHINGTON CH TO PRIME WASHINGTON COURT HOUSE(HC)
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''1900-01-01'' AS CONSOLIDATE_DATE, FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME = ''PRIME WASHINGTON COURT HOUSE'' AND B.SYSTEM_CODE = ''PRIME'' AND B.BRANCH_SERVICE_LINE = ''HC'' AND B.SOURCE_SYSTEM_ID = ''14'' AND B.SOURCE_SYSTEM_TYPE = ''AMS''
	WHERE A.BRANCH_NAME IN (''WASHINGTON CH'')
	AND A.SYSTEM_CODE = ''PRIME''
	AND A.SOURCE_SYSTEM_ID = ''13''
	AND A.SOURCE_SYSTEM_TYPE = ''AMS''
	UNION
	-- HILLSIDE TO OAKPARK
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2024-02-01'' AS CONSOLIDATE_DATE, FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''OAKPARK'' AND B.SYSTEM_CODE=''IL'' AND B.SOURCE_SYSTEM_ID = ''3'' AND B.SOURCE_SYSTEM_TYPE = ''AMS''
	WHERE A.BRANCH_NAME IN (''HILLSIDE'')
	AND A.SYSTEM_CODE = ''IL''
	AND A.SOURCE_SYSTEM_ID = ''3''
	AND A.SOURCE_SYSTEM_TYPE = ''AMS''
	UNION
	-- PRIME CIRCLEVILLE(HC) TO PRIME WASHINGTON COURT HOUSE(HC)
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2024-01-03'' AS CONSOLIDATE_DATE, FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME = ''PRIME WASHINGTON COURT HOUSE'' AND B.SYSTEM_CODE = ''PRIME'' AND B.BRANCH_SERVICE_LINE = ''HC'' AND B.SOURCE_SYSTEM_ID = ''14'' AND B.SOURCE_SYSTEM_TYPE = ''AMS''
	WHERE A.BRANCH_NAME IN (''PRIME CIRCLEVILLE'')
	AND A.SYSTEM_CODE = ''PRIME''
	AND A.BRANCH_SERVICE_LINE = ''HC''
	AND A.SOURCE_SYSTEM_ID = ''14''
	AND A.SOURCE_SYSTEM_TYPE = ''AMS''
), MERGE_3 AS (
	-- QUINCY TO PITTSFIELD
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY ,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2022-06-13'' AS CONSOLIDATE_DATE,FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''PITTSFIELD'' AND B.SYSTEM_CODE =''IL'' AND B.SOURCE_SYSTEM_ID =''3''
	WHERE A.BRANCH_NAME = ''QUINCY''
	AND A.SYSTEM_CODE =''IL''
	AND A.SOURCE_SYSTEM_ID =''3''
	UNION 
	-- LITCHFIELD TO SPRINGFIELD
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY ,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2022-06-13'' AS CONSOLIDATE_DATE,FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''SPRINGFIELD'' AND B.SYSTEM_CODE =''IL'' AND B.SOURCE_SYSTEM_ID =''3''
	WHERE A.BRANCH_NAME = ''LITCHFIELD''
	AND A.SYSTEM_CODE =''IL''
	AND A.SOURCE_SYSTEM_ID =''3''
	UNION 
	-- SCHAUMBURG TO WHEATON
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY ,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2022-06-13'' AS CONSOLIDATE_DATE,FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''WHEATON'' AND B.SYSTEM_CODE =''IL'' AND B.SOURCE_SYSTEM_ID =''3''
	WHERE A.BRANCH_NAME = ''SCHAUMBURG''
	AND A.SYSTEM_CODE =''IL''
	AND A.SOURCE_SYSTEM_ID =''3''
	UNION 
	-- MATTESON TO HOMEWOOD
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY ,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2022-06-13'' AS CONSOLIDATE_DATE,FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''HOMEWOOD'' AND B.SYSTEM_CODE =''IL'' AND B.SOURCE_SYSTEM_ID =''3''
	WHERE A.BRANCH_NAME = ''MATTESON''
	AND A.SYSTEM_CODE =''IL''
	AND A.SOURCE_SYSTEM_ID =''3''
	UNION
	-- HANNIBAL TO JEFFERSON
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY ,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2022-08-01'' AS CONSOLIDATE_DATE,FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''JEFFERSON CITY'' AND B.SYSTEM_CODE =''MO'' AND B.SOURCE_SYSTEM_ID =''3''
	WHERE A.BRANCH_NAME = ''HANNIBAL''
	AND A.SYSTEM_CODE =''MO''
	AND A.SOURCE_SYSTEM_ID =''3''
	UNION
	-- ST JOSEPH TO KANSAS CITY
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY ,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2022-08-01'' AS CONSOLIDATE_DATE,FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''KANSAS CITY'' AND B.SYSTEM_CODE =''MO'' AND B.SOURCE_SYSTEM_ID =''3''
	WHERE A.BRANCH_NAME = ''SAINT JOSEPH''
	AND A.SYSTEM_CODE =''MO''
	AND A.SOURCE_SYSTEM_ID =''3''
	UNION
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY ,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2022-08-01'' AS CONSOLIDATE_DATE,FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''ST LOUIS'' AND B.SYSTEM_CODE =''MO'' AND B.SOURCE_SYSTEM_ID =''3''
	WHERE A.BRANCH_NAME IN (''UNION'')
	AND A.SYSTEM_CODE =''MO''
	AND A.SOURCE_SYSTEM_ID =''3''
	UNION
    SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2022-09-24'' AS CONSOLIDATE_DATE, FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''A_JASPER'' AND B.SYSTEM_CODE=''MATRIXCARE'' AND B.SOURCE_SYSTEM_ID = ''7''
	WHERE A.BRANCH_NAME IN (''H_WASHINGTON'')
	AND A.SYSTEM_CODE = ''MATRIXCARE''
	AND A.SOURCE_SYSTEM_ID=''7''
	UNION
	-- WEST COLUMBUS TO COLUMBUS
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2022-05-20'' AS CONSOLIDATE_DATE, FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''COLUMBUS'' AND B.SYSTEM_CODE=''PRIME'' AND B.SOURCE_SYSTEM_ID = ''12''
	WHERE A.BRANCH_NAME IN (''WEST COLUMBUS'')
	AND A.SYSTEM_CODE = ''PRIME''
	AND A.SOURCE_SYSTEM_ID=''13''
    UNION
	-- DUBLIN TO MACON
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2022-12-05'' AS CONSOLIDATE_DATE, FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''MACON'' AND B.SYSTEM_CODE=''GEORGIA (1002)'' AND B.SOURCE_SYSTEM_ID = ''9''
	WHERE A.BRANCH_NAME IN (''DUBLIN'')
	AND A.SYSTEM_CODE = ''GEORGIA (1002)''
	AND A.SOURCE_SYSTEM_ID=''9''
	UNION
	-- STATESBORO TO SAVANNA – SAV
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2022-12-05'' AS CONSOLIDATE_DATE, FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''SAVANNAH - SAV'' AND B.SYSTEM_CODE=''GEORGIA (1002)'' AND B.SOURCE_SYSTEM_ID = ''9''
	WHERE A.BRANCH_NAME IN (''STATESBORO'')
	AND A.SYSTEM_CODE = ''GEORGIA (1002)''
	AND A.SOURCE_SYSTEM_ID=''9''
	UNION
	-- BARNESVILLE TO NEWNAN
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2022-12-05'' AS CONSOLIDATE_DATE, FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''NEWNAN'' AND B.SYSTEM_CODE=''GEORGIA (1002)'' AND B.SOURCE_SYSTEM_ID = ''9''
	WHERE A.BRANCH_NAME IN (''BARNESVILLE'')
	AND A.SYSTEM_CODE = ''GEORGIA (1002)''
	AND A.SOURCE_SYSTEM_ID=''9''
	UNION
	-- HINESVILLE TO BRUNSWICK
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2022-12-05'' AS CONSOLIDATE_DATE, FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''BRUNSWICK'' AND B.SYSTEM_CODE=''GEORGIA (1002)'' AND B.SOURCE_SYSTEM_ID = ''9''
	WHERE A.BRANCH_NAME IN (''HINESVILLE'')
	AND A.SYSTEM_CODE = ''GEORGIA (1002)''
	AND A.SOURCE_SYSTEM_ID=''9''
	UNION
	-- BAXLEY TO VALDOSTA
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2023-01-01'' AS CONSOLIDATE_DATE, FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''VALDOSTA'' AND B.SYSTEM_CODE=''GEORGIA (1002)'' AND B.SOURCE_SYSTEM_ID = ''9''
	WHERE A.BRANCH_NAME IN (''BAXLEY'')
	AND A.SYSTEM_CODE = ''GEORGIA (1002)''
	AND A.SOURCE_SYSTEM_ID=''9''
	UNION
	-- CAPE GIRARDEAU TO ST LOUIS
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2023-01-01'' AS CONSOLIDATE_DATE, FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''ST LOUIS'' AND B.SYSTEM_CODE=''MO'' AND B.SOURCE_SYSTEM_ID = ''3''
	WHERE A.BRANCH_NAME IN (''CAPE GIRARDEAU'')
	AND A.SYSTEM_CODE = ''MO''
	AND A.SOURCE_SYSTEM_ID=''3''
	UNION
	-- RAINSVILLE TO ATHENS/HUNTSVILLE
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2022-03-16'' AS CONSOLIDATE_DATE, FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''ATHENS/HUNTSVILLE'' AND B.SYSTEM_CODE=''ALABAMA (3554)'' AND B.SOURCE_SYSTEM_ID = ''9''
	WHERE A.BRANCH_NAME IN (''RAINSVILLE'')
	AND A.SYSTEM_CODE = ''ALABAMA (3554)''
	AND A.SOURCE_SYSTEM_ID=''9''
	UNION
	-- MUSCLE SHOALS TO CULLMAN
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2022-07-23'' AS CONSOLIDATE_DATE, FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''CULLMAN'' AND B.SYSTEM_CODE=''ALABAMA (3554)'' AND B.SOURCE_SYSTEM_ID = ''9''
	WHERE A.BRANCH_NAME IN (''MUSCLE SHOALS'')
	AND A.SYSTEM_CODE = ''ALABAMA (3554)''
	AND A.SOURCE_SYSTEM_ID=''9''
	UNION
	-- AMERICUS TO MACON
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2023-01-01'' AS CONSOLIDATE_DATE, FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''MACON'' AND B.SYSTEM_CODE=''GEORGIA (1002)'' AND B.SOURCE_SYSTEM_ID = ''9''
	WHERE A.BRANCH_NAME IN (''AMERICUS'')
	AND A.SYSTEM_CODE = ''GEORGIA (1002)''
	AND A.SOURCE_SYSTEM_ID=''9''
	UNION
	-- OPELIKA TO MONTGOMERY
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2022-07-15'' AS CONSOLIDATE_DATE, FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''MONTGOMERY'' AND B.SYSTEM_CODE=''ALABAMA (3554)'' AND B.SOURCE_SYSTEM_ID = ''9''
	WHERE A.BRANCH_NAME IN (''OPELIKA'')
	AND A.SYSTEM_CODE = ''ALABAMA (3554)''
	AND A.SOURCE_SYSTEM_ID=''9''	  
	UNION
	-- ATHENS/HUNTSVILLE TO BIRMINGHAM
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2023-02-01'' AS CONSOLIDATE_DATE, FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''BIRMINGHAM'' AND B.SYSTEM_CODE=''ALABAMA (3554)'' AND B.SOURCE_SYSTEM_ID = ''9''
	WHERE A.BRANCH_NAME IN (''ATHENS/HUNTSVILLE'')
	AND A.SYSTEM_CODE = ''ALABAMA (3554)''
	AND A.SOURCE_SYSTEM_ID=''9''
	UNION
	-- CULLMAN TO BIRMINGHAM
	SELECT DISTINCT A.BRANCH_KEY AS OLD_SYSTEM_BRANCH_KEY,
	B.BRANCH_KEY AS NEW_SYSTEM_BRANCH_KEY,
	''2023-02-01'' AS CONSOLIDATE_DATE, FALSE AS IS_HISTORY
	FROM HAH.DIM_BRANCH A
	JOIN HAH.DIM_BRANCH B ON B.BRANCH_NAME =''BIRMINGHAM'' AND B.SYSTEM_CODE=''ALABAMA (3554)'' AND B.SOURCE_SYSTEM_ID = ''9''
	WHERE A.BRANCH_NAME IN (''CULLMAN'')
	AND A.SYSTEM_CODE = ''ALABAMA (3554)''
	AND A.SOURCE_SYSTEM_ID=''9''  
),
MERGE_DATA AS (
	SELECT MERGE_1.ORIGINAL_BRANCH_KEY AS OLD_SYSTEM_BRANCH_key, 
	MERGE_1.branch_key AS new_system_branch_key,
	1 AS layer,
	MERGE_1.CONSOLIDATE_DATE,MERGE_1.IS_HISTORY
	FROM MERGE_1 
	UNION ALL 
	SELECT MERGE_2.OLD_SYSTEM_BRANCH_key, 
	MERGE_2.new_system_branch_key,
	2 AS layer,
	MERGE_2.CONSOLIDATE_DATE,MERGE_2.IS_HISTORY
	FROM MERGE_2 
	UNION ALL 
	SELECT MERGE_3.OLD_SYSTEM_BRANCH_key, 
	MERGE_3.new_system_branch_key,
	3 AS layer,
	MERGE_3.CONSOLIDATE_DATE,MERGE_3.IS_HISTORY
	FROM MERGE_3
)
SELECT 
A.OLD_SYSTEM_BRANCH_KEY,
B.BRANCH_NAME AS OLD_BRANCH_NAME ,
B.SYSTEM_CODE AS OLD_SYSTEM_CODE,
B.SOURCE_SYSTEM_ID  AS OLD_SOURCE_SYSTEM_ID,
A.NEW_SYSTEM_BRANCH_KEY,
C.BRANCH_NAME AS NEW_BRANCH_NAME ,
C.SYSTEM_CODE AS NEW_SYSTEM_CODE,
C.SOURCE_SYSTEM_ID  AS NEW_SOURCE_SYSTEM_ID,
A.LAYER,
CAST(A.CONSOLIDATE_DATE AS date) AS CONSOLIDATE_DATE,
A.IS_HISTORY
FROM MERGE_DATA A 
LEFT JOIN HAH.DIM_BRANCH B ON A.OLD_SYSTEM_BRANCH_KEY = B.BRANCH_KEY 
LEFT JOIN HAH.DIM_BRANCH C ON A.NEW_SYSTEM_BRANCH_KEY = C.BRANCH_KEY;

SELECT CONCAT(''Message : '',"number of rows inserted",'' Rows Inserted.'') into :return_result FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

return return_result;
END;


 EOT
}

