resource "snowflake_procedure" "DW_HAH_DELETE_STAGE_ADPANSWERCARE_DIM_PAYCODE_MAPPING" {
	name ="DELETE_STAGE_ADPANSWERCARE_DIM_PAYCODE_MAPPING"
	database = "DW_${var.SF_ENVIRONMENT}"
	schema = "HAH"
	language  = "SQL"
	return_type = "VARCHAR(16777216)"
	execute_as = "OWNER"
	statement = <<-EOT

DECLARE
  RETURN_RESULT VARCHAR;
BEGIN
		DELETE FROM HAH.DIM_PAYCODE_MAPPING WHERE SOURCE_SYSTEM_ID = 18 AND SYSTEM_CODE = ''ADP-ANSWERCARE'' AND PAYCODE_MAPPING_KEY NOT IN 
	(SELECT PAYCODE_MAPPING_KEY FROM STAGE.ADPANSWERCARE_DIM_PAYCODE_MAPPING);
	SELECT CONCAT(''Message : '',"number of rows deleted", '' Rows Deleted.'') into :return_result FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));
	RETURN RETURN_RESULT;
END;

 EOT
}

