resource "snowflake_procedure" "DW_HAH_FACT_CLIENT_ACQUIRED_POSTPROCESSING_2_0" {
	name ="FACT_CLIENT_ACQUIRED_POSTPROCESSING_2_0"
	database = "DW_${var.SF_ENVIRONMENT}"
	schema = "HAH"
	language  = "JAVASCRIPT"
	return_type = "VARCHAR(16777216)"
	execute_as = "OWNER"
	statement = <<-EOT


var sql = `
INSERT OVERWRITE INTO DW_${var.SF_ENVIRONMENT}.HAH.FACT_CLIENT_ACQUIRED_2_0
--WITH DW2_0 AS (WITH FINAL AS(
WITH ALAYACARE_CLIENT AS (
SELECT 
MD5(NVL(TRIM(B.PROPERTIES_TBL_GT_ACCOUNT_DESCRIPTION), ''Unknown'') || '' ('' || NVL(C.BRANCH_ID,-1) || '')'' || ''-'' || NVL(C.CLIENT_ID::STRING,'''') || ''-'' || ''ALAYACARE'') 
CLIENT_KEY,
  NVL(TRIM(B.PROPERTIES_TBL_GT_ACCOUNT_DESCRIPTION), ''Unknown'') || '' ('' || NVL(C.BRANCH_ID,-1) || '')'' as SYSTEMCODE,
PROFILE_ACQUIRED_BUSINESS_  AS ACQUISITION_NAME
 FROM DISC_${var.SF_ENVIRONMENT}.Alayacare.client c
LEFT OUTER JOIN DISC_${var.SF_ENVIRONMENT}.ALAYACARE.BRANCH B 
	ON c.BRANCH_ID = B.BRANCH_ID
    where PROFILE_ACQUIRED_BUSINESS_  IS NOT NULL
),Preferred_client as 
(
	SELECT distinct
	CLIENT_KEY , 
	SOURCE_SYSTEM_ID ,
	SYSTEM_CODE 
	FROM HAH.DIM_CLIENT a
	WHERE a.SOURCE_SYSTEM_ID =17
	AND a.SYSTEM_CODE = ''PREFERRED''
),EDISON_CLIENT AS(
SELECT DISTINCT
E.CLIENT_KEY,
E.SOURCE_SYSTEM_ID,
E.SYSTEM_CODE,
NVL(ACQ_NAME, ''EDISON'') AS Acquisition
FROM HAH.DIM_CLIENT E
LEFT JOIN (
SELECT MASTER_ID,PATIENTID,MD5((AGENCYID||''-''||MASTER_ID||''-''||''EDISON'' )) AS CLIENT_KEY,
CASE WHEN Acquisition = ''Recco'' THEN UPPER(Acquisition) END AS ACQ_NAME
FROM
	(
		SELECT A.AGENCYID, A.PATIENTID, A.MASTER_ID, TRIM(B.DROPDOWNTEXT1) AS Acquisition
		FROM DISC_DEDUPE_${var.SF_ENVIRONMENT}.HHAEXCHANGEEDISON.CLIENT_MASTER_LIST A
		JOIN DISC_${var.SF_ENVIRONMENT}.HHAEXCHANGEEDISON.PATIENTCUSTOMFIELDS B ON A.PATIENTID = B.PATIENTID
	)
UNION
SELECT MASTER_ID,PATIENTID,MD5((AGENCYID||''-''||MASTER_ID||''-''||''EDISON'' )) AS CLIENT_KEY,
CASE WHEN Acquisition = ''Recco'' THEN UPPER(Acquisition) END AS ACQ_NAME
FROM
	(
		SELECT DISTINCT A.AGENCYID, A.PATIENTID, A.MASTER_ID, TRIM(B.DROPDOWNTEXT1) AS Acquisition
		FROM DISC_DEDUPE_${var.SF_ENVIRONMENT}.HHAEXCHANGEEDISON.CLIENT_MATCH_LIST A
		JOIN DISC_${var.SF_ENVIRONMENT}.HHAEXCHANGEEDISON.PATIENTCUSTOMFIELDS  B ON A.PATIENTID = B.PATIENTID
		AND A.PATIENTID NOT IN (SELECT CC.PATIENTID FROM DISC_DEDUPE_${var.SF_ENVIRONMENT}.HHAEXCHANGEEDISON.CLIENT_MASTER_LIST CC)
	)
) DE ON DE.CLIENT_KEY = E.CLIENT_KEY
WHERE E.SYSTEM_CODE = ''EDISON''
),
 Praetorian_client as
  (
    SELECT md5(DBNAME || ''-'' || NUMBER || ''-'' || ''DATAFLEXSYNCDATA'' ) AS CLIENT_KEY ,DBNAME AS SYSTEM_CODE
FROM DISC_${var.SF_ENVIRONMENT}.DATAFLEXSYNCDATA.DFCLIENTS WHERE AGENCY = ''Praetorian''
  )
  , Longevity_client as
  (
    SELECT md5(DBNAME || ''-'' || NUMBER || ''-'' || ''DATAFLEXSYNCDATA'' ) AS CLIENT_KEY ,DBNAME AS SYSTEM_CODE
FROM DISC_${var.SF_ENVIRONMENT}.DATAFLEXSYNCDATA.DFCLIENTS WHERE AGENCY = ''Acquisition-Longevity''
  ),
Meridius_client as 
(
	select md5(C.AGENCYID || ''-'' || C.CLIENTID || ''-''  ||  ''SANDATAIMPORT'' ) AS CLIENT_KEY,
C.AGENCYID AS SYSTEM_CODE , 
CASE WHEN r.LASTNAME = ''Meridius Homecare'' THEN ''Meridius''
WHEN r.LASTNAME =''All Generations Home Health'' THEN ''All Generations'' END AS ACQUISITION
from DISC_${var.SF_ENVIRONMENT}.SANDATAIMPORT.SANDATA_CLIENTADMISSIONS c 
INNER JOIN  DISC_${var.SF_ENVIRONMENT}.SANDATAIMPORT.SANDATA_REFERRALSOURCES R ON C.REFERRALSOURCEID = R.REFERRALID 
WHERE R.LASTNAME IN (''Meridius Homecare'',''All Generations Home Health'') and c.agencyid = ''8485'' 
),ASR_CLIENT AS (
SELECT DISTINCT 
	CLIENT_KEY  , 
	SOURCE_SYSTEM_ID ,
	SYSTEM_CODE 
	FROM HAH.DIM_CLIENT  a
	WHERE a.SOURCE_SYSTEM_ID =13
),CLEARCARE_CLIENT AS (
SELECT DISTINCT 
	CLIENT_KEY  , 
	SOURCE_SYSTEM_ID ,
	SYSTEM_CODE 
	FROM HAH.DIM_CLIENT  a
	WHERE a.SOURCE_SYSTEM_ID =16
),DEVERO_CLIENT as 
(
	SELECT distinct
	CLIENT_KEY , 
	SOURCE_SYSTEM_ID ,
	SYSTEM_CODE 
	FROM HAH.DIM_CLIENT a
	WHERE a.SOURCE_SYSTEM_ID =15
), AXXESS_CLIENT AS (
SELECT DISTINCT 
	CLIENT_KEY  , 
	SOURCE_SYSTEM_ID ,
	SYSTEM_CODE 
	FROM HAH.DIM_CLIENT  a
	WHERE a.SOURCE_SYSTEM_ID =14
	AND a.SYSTEM_CODE = ''PRIME''
), ALLIANCE_CLIENT AS (
SELECT DISTINCT 
	CLIENT_KEY  , 
	SOURCE_SYSTEM_ID ,
	SYSTEM_CODE 
	FROM HAH.DIM_CLIENT  a
	WHERE a.SOURCE_SYSTEM_ID =19
	AND a.SYSTEM_CODE = ''ALLIANCE''
), OPENSYSTEMS_CLIENT AS (
SELECT DISTINCT 
	CLIENT_KEY  , 
	SOURCE_SYSTEM_ID ,
	SYSTEM_CODE 
	FROM HAH.DIM_CLIENT  a
	WHERE a.SOURCE_SYSTEM_ID =17
	AND a.SYSTEM_CODE in( ''OPENSYSTEMS - PA'',''OPENSYSTEMS - DE'')
), OSHAH_CLIENT AS (
SELECT  E.CLIENT_KEY,
ACQ_NAME AS Acquisition,
try_to_date(ACQ_DATE) as ACQ_DATE
FROM HAH.DIM_CLIENT E 
LEFT JOIN(
SELECT MASTER_ID,PATIENTID,MD5(''OSHAH''|| ''-'' || MASTER_ID::NUMBER || ''-'' || ''HHAEXCHANGE'' ) AS CLIENT_KEY, ACQ_DATE,
CASE WHEN Acquisition = ''Open Systems HealthCare'' THEN ''OPENSYSTEMS''
WHEN Acquisition = ''All Gen'' THEN ''All Generations''
WHEN Acquisition = ''Meridus'' THEN ''Meridius'' END AS ACQ_NAME
FROM
	(
		SELECT A.PATIENTID, A.MASTER_ID,  B.TEXT8 AS ACQ_DATE, trim(B.DROPDOWNTEXT2) AS Acquisition
		FROM DISC_DEDUPE_${var.SF_ENVIRONMENT}.HHAEXCHANGEOSHAH.CLIENT_MASTER_LIST A
		JOIN DISC_${var.SF_ENVIRONMENT}.HHAEXCHANGEOSHAH.PATIENTCUSTOMFIELDS  B ON A.PATIENTID = B.PATIENTID
		WHERE  trim(B.DROPDOWNTEXT2) IN (''Open Systems HealthCare'',''All Gen'',''Meridus'')
	)
UNION
SELECT MASTER_ID,PATIENTID,MD5(''OSHAH''|| ''-'' || MASTER_ID::NUMBER || ''-'' || ''HHAEXCHANGE'' ) AS CLIENT_KEY, ACQ_DATE,
CASE WHEN Acquisition = ''Open Systems HealthCare'' THEN ''OPENSYSTEMS''
WHEN Acquisition = ''All Gen'' THEN ''All Generations''
WHEN Acquisition = ''Meridus'' THEN ''Meridius'' END AS ACQ_NAME	
FROM
	(
		SELECT DISTINCT A.PATIENTID, A.MASTER_ID, B.TEXT8 AS ACQ_DATE , trim(B.DROPDOWNTEXT2) AS Acquisition
		FROM DISC_DEDUPE_${var.SF_ENVIRONMENT}.HHAEXCHANGEOSHAH.CLIENT_MATCH_LIST A
		JOIN DISC_${var.SF_ENVIRONMENT}.HHAEXCHANGEOSHAH.PATIENTCUSTOMFIELDS  B ON A.PATIENTID = B.PATIENTID
		WHERE  trim(B.DROPDOWNTEXT2)IN (''Open Systems HealthCare'',''All Gen'',''Meridus'')
		AND A.PATIENTID NOT IN (SELECT CC.PATIENTID FROM DISC_DEDUPE_${var.SF_ENVIRONMENT}.HHAEXCHANGEOSHAH.CLIENT_MASTER_LIST CC) 
	)
) DE ON DE.CLIENT_KEY = E.CLIENT_KEY
WHERE E.SYSTEM_CODE IN ( ''OSHAH - PA'',''OSHAH - DE'')
), ALLIANCE_MYCARE_MATRIXCARE AS (
WITH dat AS (
SELECT CLIV_RECORDID ,a.CLIV_FIELDID , b.CLIF_NAME ,a.CLIV_FIELDVALUE  , a.INSERTDATE , a.UPDATEDATE , c.CLIDD_TEXT 
, CASE WHEN a.CLIV_FIELDVALUE IS NULL THEN 0 ELSE 1 END  AS aa ,
ROW_NUMBER() OVER (PARTITION BY A.CLIV_RECORDID, trim(b.CLIF_NAME)  ORDER BY A.UPDATEDATE DESC ) AS RNUM,
first_value(trim( c.CLIDD_TEXT )) OVER (PARTITION BY CLIV_RECORDID ORDER BY trim(CLIF_NAME), A.UPDATEDATE DESC ) AS acq_name,
first_value(a.CLIV_FIELDVALUE) OVER (PARTITION BY CLIV_RECORDID ORDER BY trim(CLIF_NAME) DESC, A.UPDATEDATE DESC ) AS acq_date
FROM DISC_${var.SF_ENVIRONMENT}.MATRIXCARE.STVHC_T_CLIENTVALUES a 
INNER JOIN DISC_${var.SF_ENVIRONMENT}.MATRIXCARE.STVHC_T_CLIENTFIELDS  b ON a.CLIV_FIELDID = b.CLIF_ID 
LEFT JOIN  DISC_${var.SF_ENVIRONMENT}.MATRIXCARE.STVHC_T_CLIENTFIELDLISTITEMS c ON a.CLIV_FIELDVALUE = c.CLIDD_VALUE ::STRING AND a.CLIV_FIELDID =c.CLIDD_FIELDID 
WHERE trim(CLIF_NAME)IN (''Acquisition'',''Acquisition Date'')
)
SELECT DISTINCT  CLIV_RECORDID, ACQ_NAME, TRY_TO_DATE(ACQ_DATE,''YYYY.MM.DD'') AS ACQ_DATE
,MASTER_ID,MD5(''MATRIXCARE'' || ''-'' || CL.MASTER_ID::STRING || ''-'' || ''MATRIXCARE'') AS CLIENT_KEY
FROM dat A 
JOIN DISC_DEDUPE_${var.SF_ENVIRONMENT}.MATRIXCARE.CLIENT_MASTER_LIST CL ON A.CLIV_RECORDID = CL.CLI_ID
WHERE A.ACQ_NAME in (''Alliance'',''MYCARE'')
UNION 
SELECT DISTINCT  CLIV_RECORDID, ACQ_NAME, TRY_TO_DATE(ACQ_DATE,''YYYY.MM.DD'') AS ACQ_DATE
,MASTER_ID,MD5(''MATRIXCARE'' || ''-'' || CL.MASTER_ID::STRING || ''-'' || ''MATRIXCARE'') AS CLIENT_KEY
FROM dat A 
JOIN DISC_DEDUPE_${var.SF_ENVIRONMENT}.MATRIXCARE.CLIENT_MATCH_LIST CL ON A.CLIV_RECORDID = CL.CLI_ID
WHERE A.ACQ_NAME in (''Alliance'',''MYCARE'')
AND CL.CLI_ID NOT IN (SELECT L.CLI_ID FROM DISC_DEDUPE_${var.SF_ENVIRONMENT}.MATRIXCARE.CLIENT_MASTER_LIST L)
),
mycare_clients AS (
WITH dat AS (
SELECT CLIV_RECORDID ,a.CLIV_FIELDID , b.CLIF_NAME ,a.CLIV_FIELDVALUE  , a.INSERTDATE , a.UPDATEDATE , c.CLIDD_TEXT 
, CASE WHEN a.CLIV_FIELDVALUE IS NULL THEN 0 ELSE 1 END  AS aa ,
ROW_NUMBER() OVER (PARTITION BY A.CLIV_RECORDID, trim(b.CLIF_NAME)  ORDER BY A.UPDATEDATE DESC ) AS RNUM,
first_value(trim( c.CLIDD_TEXT )) OVER (PARTITION BY CLIV_RECORDID ORDER BY trim(CLIF_NAME), A.UPDATEDATE DESC ) AS acq_name,
first_value(a.CLIV_FIELDVALUE) OVER (PARTITION BY CLIV_RECORDID ORDER BY trim(CLIF_NAME) DESC, A.UPDATEDATE DESC ) AS acq_date
FROM DISC_${var.SF_ENVIRONMENT}.MATRIXCARE.STVHC_T_CLIENTVALUES a 
INNER JOIN DISC_${var.SF_ENVIRONMENT}.MATRIXCARE.STVHC_T_CLIENTFIELDS  b ON a.CLIV_FIELDID = b.CLIF_ID 
LEFT JOIN  DISC_${var.SF_ENVIRONMENT}.MATRIXCARE.STVHC_T_CLIENTFIELDLISTITEMS c ON a.CLIV_FIELDVALUE = c.CLIDD_VALUE ::STRING AND a.CLIV_FIELDID =c.CLIDD_FIELDID 
WHERE trim(CLIF_NAME)IN (''Acquisition'',''Acquisition Date'')
)
SELECT DISTINCT MD5(''MATRIXCARE'' || ''-'' || CL.MASTER_ID::STRING || ''-'' || ''MATRIXCARE'') AS CLIENT_KEY
FROM dat A 
JOIN DISC_DEDUPE_prod.MATRIXCARE.CLIENT_MASTER_LIST CL ON A.CLIV_RECORDID = CL.CLI_ID
WHERE A.ACQ_NAME in (''MYCARE'')
UNION 
SELECT DISTINCT MD5(''MATRIXCARE'' || ''-'' || CL.MASTER_ID::STRING || ''-'' || ''MATRIXCARE'') AS CLIENT_KEY
FROM dat A 
JOIN DISC_DEDUPE_prod.MATRIXCARE.CLIENT_MATCH_LIST CL ON A.CLIV_RECORDID = CL.CLI_ID
WHERE A.ACQ_NAME in (''MYCARE'')
AND CL.CLI_ID NOT IN (SELECT L.CLI_ID FROM DISC_DEDUPE_prod.MATRIXCARE.CLIENT_MASTER_LIST L)
)
--MATRIXCARE
SELECT DISTINCT 
	MD5(CLIENT_MERGED.CLIENT_KEY || VISIT.PARTNER_CONTRACT_SERVICE_KEY || BRANCH_MERGED.BRANCH_KEY || DATE_TRUNC(''MONTH'', REPORT_DATE)) AS CLIENT_ACQUIRED_KEY,
	CLIENT_MERGED.ORIGINAL_CLIENT_KEY,
	CLIENT_MERGED.CLIENT_KEY, CLIENT_MERGED.CLIENT_NUMBER, VISIT.SOURCE_SYSTEM_ID, VISIT.SYSTEM_CODE,BRANCH_MERGED.ORIGINAL_BRANCH_KEY, BRANCH_MERGED.BRANCH_KEY, PARTNER_CONTRACT_SERVICE_KEY , DATE_TRUNC(''MONTH'', REPORT_DATE) AS SERVICE_MONTH, ''ADAPTIVE'' AS AQUISITION_NAME,
	-1 AS ETL_TASK_KEY, -1 AS ETL_INSERTED_TASK_KEY, /*VISIT.ETL_INSERTED_DATE, VISIT.ETL_INSERTED_BY,*/ CONVERT_TIMEZONE(''UTC'', CONVERT_TIMEZONE(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ)::TIMESTAMP_NTZ AS ETL_LAST_UPDATED_DATE, CURRENT_USER AS ETL_LAST_UPDATED_BY, FALSE AS ETL_DELETED_FLAG
FROM DW_${var.SF_ENVIRONMENT}.HAH.FACT_VISIT VISIT
INNER JOIN DW_${var.SF_ENVIRONMENT}.HAH.DIM_BRANCH BRANCH
	ON VISIT.BRANCH_KEY = BRANCH.BRANCH_KEY
INNER JOIN DW_${var.SF_ENVIRONMENT}.INTEGRATION.DIM_BRANCH_MERGED BRANCH_MERGED ON BRANCH_MERGED.ORIGINAL_BRANCH_KEY = BRANCH.BRANCH_KEY 
INNER JOIN DW_${var.SF_ENVIRONMENT}.INTEGRATION.DIM_CLIENT_MERGED CLIENT_MERGED ON CLIENT_MERGED.ORIGINAL_CLIENT_KEY =VISIT.CLIENT_KEY 
WHERE VISIT.SOURCE_SYSTEM_ID = 7
	AND BRANCH.BRANCH_NAME LIKE ''A_%''
	AND REPORT_DATE >= ''2021-01-01''
	AND CLIENT_MERGED.client_key NOT IN (SELECT client_key FROM mycare_clients)
UNION
--ADAPTIVE
SELECT DISTINCT 
	MD5(CLIENT_MERGED.CLIENT_KEY || VISIT.PARTNER_CONTRACT_SERVICE_KEY || BRANCH_MERGED.BRANCH_KEY || DATE_TRUNC(''MONTH'', REPORT_DATE)) AS CLIENT_ACQUIRED_KEY,
	CLIENT_MERGED.ORIGINAL_CLIENT_KEY,
	CLIENT_MERGED.CLIENT_KEY, CLIENT_MERGED.CLIENT_NUMBER, VISIT.SOURCE_SYSTEM_ID, VISIT.SYSTEM_CODE,BRANCH_MERGED.ORIGINAL_BRANCH_KEY, BRANCH_MERGED.BRANCH_KEY, PARTNER_CONTRACT_SERVICE_KEY , DATE_TRUNC(''MONTH'', REPORT_DATE) AS SERVICE_MONTH, ''ADAPTIVE'' AS AQUISITION_NAME,
	-1 AS ETL_TASK_KEY, -1 AS ETL_INSERTED_TASK_KEY, /*VISIT.ETL_INSERTED_DATE, VISIT.ETL_INSERTED_BY,*/ CONVERT_TIMEZONE(''UTC'', CONVERT_TIMEZONE(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ)::TIMESTAMP_NTZ AS ETL_LAST_UPDATED_DATE, CURRENT_USER AS ETL_LAST_UPDATED_BY, FALSE AS ETL_DELETED_FLAG
FROM DW_${var.SF_ENVIRONMENT}.HAH.FACT_VISIT VISIT
INNER JOIN DW_${var.SF_ENVIRONMENT}.HAH.DIM_BRANCH BRANCH
	ON VISIT.BRANCH_KEY = BRANCH.BRANCH_KEY
INNER JOIN DW_${var.SF_ENVIRONMENT}.INTEGRATION.DIM_BRANCH_MERGED BRANCH_MERGED ON BRANCH_MERGED.ORIGINAL_BRANCH_KEY = BRANCH.BRANCH_KEY 
INNER JOIN DW_${var.SF_ENVIRONMENT}.INTEGRATION.DIM_CLIENT_MERGED CLIENT_MERGED ON CLIENT_MERGED.ORIGINAL_CLIENT_KEY =VISIT.CLIENT_KEY 
WHERE VISIT.SOURCE_SYSTEM_ID = 7
	AND REPORT_DATE < ''2021-01-01''
	AND CLIENT_MERGED.client_key NOT IN (SELECT client_key FROM mycare_clients)
UNION 
--CCSI 
SELECT DISTINCT 
	MD5(CLIENT_MERGED.CLIENT_KEY || VISIT.PARTNER_CONTRACT_SERVICE_KEY || BRANCH_MERGED.BRANCH_KEY || DATE_TRUNC(''MONTH'', REPORT_DATE)) AS CLIENT_ACQUIRED_KEY,
	CLIENT_MERGED.ORIGINAL_CLIENT_KEY,
	CLIENT_MERGED.CLIENT_KEY, CLIENT_MERGED.CLIENT_NUMBER, VISIT.SOURCE_SYSTEM_ID, VISIT.SYSTEM_CODE,
BRANCH_MERGED.ORIGINAL_BRANCH_KEY ,BRANCH_MERGED.BRANCH_KEY, PARTNER_CONTRACT_SERVICE_KEY, DATE_TRUNC(''MONTH'', REPORT_DATE) AS SERVICE_MONTH, ''CCSI'' AS AQUISITION_NAME,
	-1 AS ETL_TASK_KEY, -1 AS ETL_INSERTED_TASK_KEY, /*VISIT.ETL_INSERTED_DATE, VISIT.ETL_INSERTED_BY,*/ CONVERT_TIMEZONE(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ AS ETL_LAST_UPDATED_DATE, CURRENT_USER AS ETL_LAST_UPDATED_BY, FALSE AS ETL_DELETED_FLAG
FROM DW_${var.SF_ENVIRONMENT}.HAH.FACT_VISIT VISIT
INNER JOIN DW_${var.SF_ENVIRONMENT}.HAH.DIM_BRANCH BRANCH
	ON VISIT.BRANCH_KEY = BRANCH.BRANCH_KEY
INNER JOIN DW_${var.SF_ENVIRONMENT}.INTEGRATION.DIM_BRANCH_MERGED BRANCH_MERGED ON BRANCH_MERGED.ORIGINAL_BRANCH_KEY = BRANCH.BRANCH_KEY 
INNER JOIN DW_${var.SF_ENVIRONMENT}.INTEGRATION.DIM_CLIENT_MERGED CLIENT_MERGED ON CLIENT_MERGED.ORIGINAL_CLIENT_KEY =VISIT.CLIENT_KEY 
WHERE BRANCH.SOURCE_SYSTEM_ID = 8
UNION 
-- ALAYACARE 
SELECT DISTINCT 
MD5(CLIENT_MERGED.CLIENT_KEY || VISIT.PARTNER_CONTRACT_SERVICE_KEY || BRANCH_MERGED.BRANCH_KEY || DATE_TRUNC(''MONTH'', VISIT.REPORT_DATE)) AS CLIENT_ACQUIRED_KEY,
CLIENT_MERGED.ORIGINAL_CLIENT_KEY,
CLIENT_MERGED.CLIENT_KEY,
CLIENT_MERGED.CLIENT_NUMBER,
VISIT.SOURCE_SYSTEM_ID,
VISIT.SYSTEM_CODE,
BRANCH_MERGED.ORIGINAL_BRANCH_KEY,
BRANCH_MERGED.BRANCH_KEY,
VISIT.PARTNER_CONTRACT_SERVICE_KEY,
DATE_TRUNC(''MONTH'', VISIT.REPORT_DATE) AS SERVICE_MONTH,
 ACQUISITION_NAME,
-1 AS ETL_TASK_KEY,
-1 AS ETL_INSERTED_TASK_KEY,
CONVERT_TIMEZONE(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ AS ETL_LAST_UPDATED_DATE,
CURRENT_USER AS ETL_LAST_UPDATED_BY,
FALSE AS ETL_DELETED_FLAG
FROM ALAYACARE_CLIENT a 
INNER JOIN DW_${var.SF_ENVIRONMENT}.HAH.FACT_VISIT VISIT ON VISIT.CLIENT_KEY = a.client_key
INNER JOIN DW_${var.SF_ENVIRONMENT}.INTEGRATION.DIM_BRANCH_MERGED BRANCH_MERGED ON BRANCH_MERGED.ORIGINAL_BRANCH_KEY = VISIT.BRANCH_KEY 
INNER JOIN DW_${var.SF_ENVIRONMENT}.INTEGRATION.DIM_CLIENT_MERGED CLIENT_MERGED ON CLIENT_MERGED.ORIGINAL_CLIENT_KEY = VISIT.CLIENT_KEY 
UNION 
--PRAETORIAN 
SELECT DISTINCT 
MD5(CLIENT_MERGED.CLIENT_KEY || VISIT.PARTNER_CONTRACT_SERVICE_KEY || BRANCH_MERGED.BRANCH_KEY || DATE_TRUNC(''MONTH'', VISIT.REPORT_DATE)) AS CLIENT_ACQUIRED_KEY,
CLIENT_MERGED.ORIGINAL_CLIENT_KEY,
CLIENT_MERGED.CLIENT_KEY,
CLIENT_MERGED.CLIENT_NUMBER,
VISIT.SOURCE_SYSTEM_ID,
VISIT.SYSTEM_CODE,
BRANCH_MERGED.ORIGINAL_BRANCH_KEY,
BRANCH_MERGED.BRANCH_KEY,
VISIT.PARTNER_CONTRACT_SERVICE_KEY,
DATE_TRUNC(''MONTH'', VISIT.REPORT_DATE) AS SERVICE_MONTH,
''Praetorian'' AS AQUISITION_NAME,
-1 AS ETL_TASK_KEY,
-1 AS ETL_INSERTED_TASK_KEY,
CONVERT_TIMEZONE(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ AS ETL_LAST_UPDATED_DATE,
CURRENT_USER AS ETL_LAST_UPDATED_BY,
FALSE AS ETL_DELETED_FLAG
FROM Praetorian_client a 
INNER JOIN DW_${var.SF_ENVIRONMENT}.HAH.FACT_VISIT VISIT ON VISIT.CLIENT_KEY = a.CLIENT_KEY
INNER JOIN DW_${var.SF_ENVIRONMENT}.INTEGRATION.DIM_BRANCH_MERGED BRANCH_MERGED ON BRANCH_MERGED.ORIGINAL_BRANCH_KEY = VISIT.BRANCH_KEY 
INNER JOIN DW_${var.SF_ENVIRONMENT}.INTEGRATION.DIM_CLIENT_MERGED CLIENT_MERGED ON CLIENT_MERGED.ORIGINAL_CLIENT_KEY = VISIT.CLIENT_KEY 
UNION
--LONGEVITY 
SELECT DISTINCT 
MD5(CLIENT_MERGED.CLIENT_KEY || VISIT.PARTNER_CONTRACT_SERVICE_KEY || BRANCH_MERGED.BRANCH_KEY || DATE_TRUNC(''MONTH'', VISIT.REPORT_DATE)) AS CLIENT_ACQUIRED_KEY,
CLIENT_MERGED.ORIGINAL_CLIENT_KEY,
CLIENT_MERGED.CLIENT_KEY,
CLIENT_MERGED.CLIENT_NUMBER,
VISIT.SOURCE_SYSTEM_ID,
VISIT.SYSTEM_CODE,
BRANCH_MERGED.ORIGINAL_BRANCH_KEY,
BRANCH_MERGED.BRANCH_KEY,
VISIT.PARTNER_CONTRACT_SERVICE_KEY,
DATE_TRUNC(''MONTH'', VISIT.REPORT_DATE) AS SERVICE_MONTH,
''Longevity'' AS AQUISITION_NAME,
-1 AS ETL_TASK_KEY,
-1 AS ETL_INSERTED_TASK_KEY,
CONVERT_TIMEZONE(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ AS ETL_LAST_UPDATED_DATE,
CURRENT_USER AS ETL_LAST_UPDATED_BY,
FALSE AS ETL_DELETED_FLAG
FROM Longevity_client a 
INNER JOIN DW_${var.SF_ENVIRONMENT}.HAH.FACT_VISIT VISIT ON VISIT.CLIENT_KEY = a.CLIENT_KEY
INNER JOIN DW_${var.SF_ENVIRONMENT}.INTEGRATION.DIM_BRANCH_MERGED BRANCH_MERGED ON BRANCH_MERGED.ORIGINAL_BRANCH_KEY = VISIT.BRANCH_KEY 
INNER JOIN DW_${var.SF_ENVIRONMENT}.INTEGRATION.DIM_CLIENT_MERGED CLIENT_MERGED ON CLIENT_MERGED.ORIGINAL_CLIENT_KEY = VISIT.CLIENT_KEY 
UNION
--MERIDIUS 
SELECT DISTINCT 
MD5(CLIENT_MERGED.CLIENT_KEY || VISIT.PARTNER_CONTRACT_SERVICE_KEY || BRANCH_MERGED.BRANCH_KEY || DATE_TRUNC(''MONTH'', VISIT.REPORT_DATE)) AS CLIENT_ACQUIRED_KEY,
CLIENT_MERGED.ORIGINAL_CLIENT_KEY,
CLIENT_MERGED.CLIENT_KEY,
CLIENT_MERGED.CLIENT_NUMBER,
VISIT.SOURCE_SYSTEM_ID,
VISIT.SYSTEM_CODE,
BRANCH_MERGED.ORIGINAL_BRANCH_KEY,
BRANCH_MERGED.BRANCH_KEY,
VISIT.PARTNER_CONTRACT_SERVICE_KEY,
DATE_TRUNC(''MONTH'', VISIT.REPORT_DATE) AS SERVICE_MONTH,
a.ACQUISITION AS AQUISITION_NAME,
-1 AS ETL_TASK_KEY,
-1 AS ETL_INSERTED_TASK_KEY,
CONVERT_TIMEZONE(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ AS ETL_LAST_UPDATED_DATE,
CURRENT_USER AS ETL_LAST_UPDATED_BY,
FALSE AS ETL_DELETED_FLAG
FROM Meridius_client a 
INNER JOIN DW_${var.SF_ENVIRONMENT}.HAH.FACT_VISIT VISIT ON VISIT.CLIENT_KEY = a.CLIENT_KEY
INNER JOIN DW_${var.SF_ENVIRONMENT}.INTEGRATION.DIM_BRANCH_MERGED BRANCH_MERGED ON BRANCH_MERGED.ORIGINAL_BRANCH_KEY = VISIT.BRANCH_KEY 
INNER JOIN DW_${var.SF_ENVIRONMENT}.INTEGRATION.DIM_CLIENT_MERGED CLIENT_MERGED ON CLIENT_MERGED.ORIGINAL_CLIENT_KEY = VISIT.CLIENT_KEY 
UNION
--PREFERRED
SELECT DISTINCT 
MD5(CLIENT_MERGED.CLIENT_KEY || VISIT.PARTNER_CONTRACT_SERVICE_KEY || BRANCH_MERGED.BRANCH_KEY || DATE_TRUNC(''MONTH'', VISIT.REPORT_DATE)) AS CLIENT_ACQUIRED_KEY,
CLIENT_MERGED.ORIGINAL_CLIENT_KEY,
CLIENT_MERGED.CLIENT_KEY,
CLIENT_MERGED.CLIENT_NUMBER,
VISIT.SOURCE_SYSTEM_ID,
VISIT.SYSTEM_CODE,
BRANCH_MERGED.ORIGINAL_BRANCH_KEY,
BRANCH_MERGED.BRANCH_KEY,
VISIT.PARTNER_CONTRACT_SERVICE_KEY,
DATE_TRUNC(''MONTH'', VISIT.REPORT_DATE) AS SERVICE_MONTH,
''PREFERRED'' AS AQUISITION_NAME,
-1 AS ETL_TASK_KEY,
-1 AS ETL_INSERTED_TASK_KEY,
CONVERT_TIMEZONE(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ AS ETL_LAST_UPDATED_DATE,
CURRENT_USER AS ETL_LAST_UPDATED_BY,
FALSE AS ETL_DELETED_FLAG
FROM Preferred_client a 
INNER JOIN DW_${var.SF_ENVIRONMENT}.HAH.FACT_VISIT VISIT ON VISIT.CLIENT_KEY = a.CLIENT_KEY
INNER JOIN DW_${var.SF_ENVIRONMENT}.INTEGRATION.DIM_BRANCH_MERGED BRANCH_MERGED ON BRANCH_MERGED.ORIGINAL_BRANCH_KEY = VISIT.BRANCH_KEY 
INNER JOIN DW_${var.SF_ENVIRONMENT}.INTEGRATION.DIM_CLIENT_MERGED CLIENT_MERGED ON CLIENT_MERGED.ORIGINAL_CLIENT_KEY = VISIT.CLIENT_KEY
UNION
--EDISON
SELECT DISTINCT 
MD5(CLIENT_MERGED.CLIENT_KEY || VISIT.PARTNER_CONTRACT_SERVICE_KEY || BRANCH_MERGED.BRANCH_KEY || DATE_TRUNC(''MONTH'', VISIT.REPORT_DATE)) AS CLIENT_ACQUIRED_KEY,
CLIENT_MERGED.ORIGINAL_CLIENT_KEY,
CLIENT_MERGED.CLIENT_KEY,
CLIENT_MERGED.CLIENT_NUMBER,
VISIT.SOURCE_SYSTEM_ID,
VISIT.SYSTEM_CODE,
BRANCH_MERGED.ORIGINAL_BRANCH_KEY,
BRANCH_MERGED.BRANCH_KEY,
VISIT.PARTNER_CONTRACT_SERVICE_KEY,
DATE_TRUNC(''MONTH'', VISIT.REPORT_DATE) AS SERVICE_MONTH,
A.Acquisition AS AQUISITION_NAME,
-1 AS ETL_TASK_KEY,
-1 AS ETL_INSERTED_TASK_KEY,
CONVERT_TIMEZONE(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ AS ETL_LAST_UPDATED_DATE,
CURRENT_USER AS ETL_LAST_UPDATED_BY,
FALSE AS ETL_DELETED_FLAG
FROM EDISON_CLIENT a 
INNER JOIN DW_${var.SF_ENVIRONMENT}.HAH.FACT_VISIT VISIT ON VISIT.CLIENT_KEY = a.CLIENT_KEY
INNER JOIN DW_${var.SF_ENVIRONMENT}.INTEGRATION.DIM_BRANCH_MERGED BRANCH_MERGED ON BRANCH_MERGED.ORIGINAL_BRANCH_KEY = VISIT.BRANCH_KEY 
INNER JOIN DW_${var.SF_ENVIRONMENT}.INTEGRATION.DIM_CLIENT_MERGED CLIENT_MERGED ON CLIENT_MERGED.ORIGINAL_CLIENT_KEY = VISIT.CLIENT_KEY
UNION
--ASR
SELECT DISTINCT 
MD5(CLIENT_MERGED.CLIENT_KEY || VISIT.PARTNER_CONTRACT_SERVICE_KEY || BRANCH_MERGED.BRANCH_KEY || DATE_TRUNC(''MONTH'', VISIT.REPORT_DATE)) AS CLIENT_ACQUIRED_KEY,
CLIENT_MERGED.ORIGINAL_CLIENT_KEY,
CLIENT_MERGED.CLIENT_KEY,
CLIENT_MERGED.CLIENT_NUMBER,
VISIT.SOURCE_SYSTEM_ID,
VISIT.SYSTEM_CODE,
BRANCH_MERGED.ORIGINAL_BRANCH_KEY,
BRANCH_MERGED.BRANCH_KEY,
VISIT.PARTNER_CONTRACT_SERVICE_KEY,
DATE_TRUNC(''MONTH'', VISIT.REPORT_DATE) AS SERVICE_MONTH,
''ASR'' AS AQUISITION_NAME,
-1 AS ETL_TASK_KEY,
-1 AS ETL_INSERTED_TASK_KEY,
CONVERT_TIMEZONE(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ AS ETL_LAST_UPDATED_DATE,
CURRENT_USER AS ETL_LAST_UPDATED_BY,
FALSE AS ETL_DELETED_FLAG
FROM ASR_CLIENT a 
INNER JOIN DW_${var.SF_ENVIRONMENT}.HAH.FACT_VISIT VISIT ON VISIT.CLIENT_KEY = a.CLIENT_KEY
INNER JOIN DW_${var.SF_ENVIRONMENT}.INTEGRATION.DIM_BRANCH_MERGED BRANCH_MERGED ON BRANCH_MERGED.ORIGINAL_BRANCH_KEY = VISIT.BRANCH_KEY 
INNER JOIN DW_${var.SF_ENVIRONMENT}.INTEGRATION.DIM_CLIENT_MERGED CLIENT_MERGED ON CLIENT_MERGED.ORIGINAL_CLIENT_KEY = VISIT.CLIENT_KEY
UNION
--CLEARCARE
SELECT DISTINCT 
MD5(CLIENT_MERGED.CLIENT_KEY || VISIT.PARTNER_CONTRACT_SERVICE_KEY || BRANCH_MERGED.BRANCH_KEY || DATE_TRUNC(''MONTH'', VISIT.REPORT_DATE)) AS CLIENT_ACQUIRED_KEY,
CLIENT_MERGED.ORIGINAL_CLIENT_KEY,
CLIENT_MERGED.CLIENT_KEY,
CLIENT_MERGED.CLIENT_NUMBER,
VISIT.SOURCE_SYSTEM_ID,
VISIT.SYSTEM_CODE,
BRANCH_MERGED.ORIGINAL_BRANCH_KEY,
BRANCH_MERGED.BRANCH_KEY,
VISIT.PARTNER_CONTRACT_SERVICE_KEY,
DATE_TRUNC(''MONTH'', VISIT.REPORT_DATE) AS SERVICE_MONTH,
''CLEARCARE'' AS AQUISITION_NAME,
-1 AS ETL_TASK_KEY,
-1 AS ETL_INSERTED_TASK_KEY,
CONVERT_TIMEZONE(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ AS ETL_LAST_UPDATED_DATE,
CURRENT_USER AS ETL_LAST_UPDATED_BY,
FALSE AS ETL_DELETED_FLAG
FROM CLEARCARE_CLIENT a 
INNER JOIN DW_${var.SF_ENVIRONMENT}.HAH.FACT_VISIT VISIT ON VISIT.CLIENT_KEY = a.CLIENT_KEY
INNER JOIN DW_${var.SF_ENVIRONMENT}.INTEGRATION.DIM_BRANCH_MERGED BRANCH_MERGED ON BRANCH_MERGED.ORIGINAL_BRANCH_KEY = VISIT.BRANCH_KEY 
INNER JOIN DW_${var.SF_ENVIRONMENT}.INTEGRATION.DIM_CLIENT_MERGED CLIENT_MERGED ON CLIENT_MERGED.ORIGINAL_CLIENT_KEY = VISIT.CLIENT_KEY
UNION
--DEVERO
SELECT DISTINCT 
MD5(CLIENT_MERGED.CLIENT_KEY || VISIT.PARTNER_CONTRACT_SERVICE_KEY || BRANCH_MERGED.BRANCH_KEY || DATE_TRUNC(''MONTH'', VISIT.REPORT_DATE)) AS CLIENT_ACQUIRED_KEY,
CLIENT_MERGED.ORIGINAL_CLIENT_KEY,
CLIENT_MERGED.CLIENT_KEY,
CLIENT_MERGED.CLIENT_NUMBER,
VISIT.SOURCE_SYSTEM_ID,
VISIT.SYSTEM_CODE,
BRANCH_MERGED.ORIGINAL_BRANCH_KEY,
BRANCH_MERGED.BRANCH_KEY,
VISIT.PARTNER_CONTRACT_SERVICE_KEY,
DATE_TRUNC(''MONTH'', VISIT.REPORT_DATE) AS SERVICE_MONTH,
''DEVERO'' AS AQUISITION_NAME,
-1 AS ETL_TASK_KEY,
-1 AS ETL_INSERTED_TASK_KEY,
CONVERT_TIMEZONE(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ AS ETL_LAST_UPDATED_DATE,
CURRENT_USER AS ETL_LAST_UPDATED_BY,
FALSE AS ETL_DELETED_FLAG
FROM DEVERO_CLIENT a 
INNER JOIN DW_${var.SF_ENVIRONMENT}.HAH.FACT_VISIT VISIT ON VISIT.CLIENT_KEY = a.CLIENT_KEY
INNER JOIN DW_${var.SF_ENVIRONMENT}.INTEGRATION.DIM_BRANCH_MERGED BRANCH_MERGED ON BRANCH_MERGED.ORIGINAL_BRANCH_KEY = VISIT.BRANCH_KEY 
INNER JOIN DW_${var.SF_ENVIRONMENT}.INTEGRATION.DIM_CLIENT_MERGED CLIENT_MERGED ON CLIENT_MERGED.ORIGINAL_CLIENT_KEY = VISIT.CLIENT_KEY
UNION
--AXXESS
SELECT DISTINCT 
MD5(CLIENT_MERGED.CLIENT_KEY || VISIT.PARTNER_CONTRACT_SERVICE_KEY || BRANCH_MERGED.BRANCH_KEY || DATE_TRUNC(''MONTH'', VISIT.REPORT_DATE)) AS CLIENT_ACQUIRED_KEY,
CLIENT_MERGED.ORIGINAL_CLIENT_KEY,
CLIENT_MERGED.CLIENT_KEY,
CLIENT_MERGED.CLIENT_NUMBER,
VISIT.SOURCE_SYSTEM_ID,
VISIT.SYSTEM_CODE,
BRANCH_MERGED.ORIGINAL_BRANCH_KEY,
BRANCH_MERGED.BRANCH_KEY,
VISIT.PARTNER_CONTRACT_SERVICE_KEY,
DATE_TRUNC(''MONTH'', VISIT.REPORT_DATE) AS SERVICE_MONTH,
''AXXESS'' AS AQUISITION_NAME,
-1 AS ETL_TASK_KEY,
-1 AS ETL_INSERTED_TASK_KEY,
CONVERT_TIMEZONE(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ AS ETL_LAST_UPDATED_DATE,
CURRENT_USER AS ETL_LAST_UPDATED_BY,
FALSE AS ETL_DELETED_FLAG
FROM AXXESS_CLIENT a 
INNER JOIN DW_${var.SF_ENVIRONMENT}.HAH.FACT_VISIT VISIT ON VISIT.CLIENT_KEY = a.CLIENT_KEY
INNER JOIN DW_${var.SF_ENVIRONMENT}.INTEGRATION.DIM_BRANCH_MERGED BRANCH_MERGED ON BRANCH_MERGED.ORIGINAL_BRANCH_KEY = VISIT.BRANCH_KEY 
INNER JOIN DW_${var.SF_ENVIRONMENT}.INTEGRATION.DIM_CLIENT_MERGED CLIENT_MERGED ON CLIENT_MERGED.ORIGINAL_CLIENT_KEY = VISIT.CLIENT_KEY
UNION
--ALLIANCE
SELECT DISTINCT 
MD5(CLIENT_MERGED.CLIENT_KEY || VISIT.PARTNER_CONTRACT_SERVICE_KEY || BRANCH_MERGED.BRANCH_KEY || DATE_TRUNC(''MONTH'', VISIT.REPORT_DATE)) AS CLIENT_ACQUIRED_KEY,
CLIENT_MERGED.ORIGINAL_CLIENT_KEY,
CLIENT_MERGED.CLIENT_KEY,
CLIENT_MERGED.CLIENT_NUMBER,
VISIT.SOURCE_SYSTEM_ID,
VISIT.SYSTEM_CODE,
BRANCH_MERGED.ORIGINAL_BRANCH_KEY,
BRANCH_MERGED.BRANCH_KEY,
VISIT.PARTNER_CONTRACT_SERVICE_KEY,
DATE_TRUNC(''MONTH'', VISIT.REPORT_DATE) AS SERVICE_MONTH,
''ALLIANCE'' AS AQUISITION_NAME,
-1 AS ETL_TASK_KEY,
-1 AS ETL_INSERTED_TASK_KEY,
CONVERT_TIMEZONE(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ AS ETL_LAST_UPDATED_DATE,
CURRENT_USER AS ETL_LAST_UPDATED_BY,
FALSE AS ETL_DELETED_FLAG
FROM ALLIANCE_CLIENT a 
INNER JOIN DW_${var.SF_ENVIRONMENT}.HAH.FACT_VISIT VISIT ON VISIT.CLIENT_KEY = a.CLIENT_KEY
INNER JOIN DW_${var.SF_ENVIRONMENT}.INTEGRATION.DIM_BRANCH_MERGED BRANCH_MERGED ON BRANCH_MERGED.ORIGINAL_BRANCH_KEY = VISIT.BRANCH_KEY 
INNER JOIN DW_${var.SF_ENVIRONMENT}.INTEGRATION.DIM_CLIENT_MERGED CLIENT_MERGED ON CLIENT_MERGED.ORIGINAL_CLIENT_KEY = VISIT.CLIENT_KEY
UNION
--OPENSYSTEMS 
SELECT DISTINCT 
MD5(CLIENT_MERGED.CLIENT_KEY || VISIT.PARTNER_CONTRACT_SERVICE_KEY || BRANCH_MERGED.BRANCH_KEY || DATE_TRUNC(''MONTH'', VISIT.REPORT_DATE)) AS CLIENT_ACQUIRED_KEY,
CLIENT_MERGED.ORIGINAL_CLIENT_KEY,
CLIENT_MERGED.CLIENT_KEY,
CLIENT_MERGED.CLIENT_NUMBER,
VISIT.SOURCE_SYSTEM_ID,
VISIT.SYSTEM_CODE,
BRANCH_MERGED.ORIGINAL_BRANCH_KEY,
BRANCH_MERGED.BRANCH_KEY,
VISIT.PARTNER_CONTRACT_SERVICE_KEY,
DATE_TRUNC(''MONTH'', VISIT.REPORT_DATE) AS SERVICE_MONTH,
''OPENSYSTEMS'' AS AQUISITION_NAME,
-1 AS ETL_TASK_KEY,
-1 AS ETL_INSERTED_TASK_KEY,
CONVERT_TIMEZONE(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ AS ETL_LAST_UPDATED_DATE,
CURRENT_USER AS ETL_LAST_UPDATED_BY,
FALSE AS ETL_DELETED_FLAG
FROM OPENSYSTEMS_CLIENT a 
INNER JOIN DW_${var.SF_ENVIRONMENT}.HAH.FACT_VISIT VISIT ON VISIT.CLIENT_KEY = a.CLIENT_KEY
INNER JOIN DW_${var.SF_ENVIRONMENT}.INTEGRATION.DIM_BRANCH_MERGED BRANCH_MERGED ON BRANCH_MERGED.ORIGINAL_BRANCH_KEY = VISIT.BRANCH_KEY 
INNER JOIN DW_${var.SF_ENVIRONMENT}.INTEGRATION.DIM_CLIENT_MERGED CLIENT_MERGED ON CLIENT_MERGED.ORIGINAL_CLIENT_KEY = VISIT.CLIENT_KEY
UNION
--OSHAH - PA
SELECT DISTINCT 
MD5(CLIENT_MERGED.CLIENT_KEY || VISIT.PARTNER_CONTRACT_SERVICE_KEY || BRANCH_MERGED.BRANCH_KEY || DATE_TRUNC(''MONTH'', VISIT.REPORT_DATE)) AS CLIENT_ACQUIRED_KEY,
CLIENT_MERGED.ORIGINAL_CLIENT_KEY,
CLIENT_MERGED.CLIENT_KEY,
CLIENT_MERGED.CLIENT_NUMBER,
VISIT.SOURCE_SYSTEM_ID,
VISIT.SYSTEM_CODE,
BRANCH_MERGED.ORIGINAL_BRANCH_KEY,
BRANCH_MERGED.BRANCH_KEY,
VISIT.PARTNER_CONTRACT_SERVICE_KEY,
DATE_TRUNC(''MONTH'', VISIT.REPORT_DATE) AS SERVICE_MONTH,
A.Acquisition AS AQUISITION_NAME,
-1 AS ETL_TASK_KEY,
-1 AS ETL_INSERTED_TASK_KEY,
CONVERT_TIMEZONE(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ AS ETL_LAST_UPDATED_DATE,
CURRENT_USER AS ETL_LAST_UPDATED_BY,
FALSE AS ETL_DELETED_FLAG
FROM OSHAH_CLIENT a 
INNER JOIN DW_${var.SF_ENVIRONMENT}.HAH.FACT_VISIT VISIT ON VISIT.CLIENT_KEY = a.CLIENT_KEY
INNER JOIN DW_${var.SF_ENVIRONMENT}.INTEGRATION.DIM_BRANCH_MERGED BRANCH_MERGED ON BRANCH_MERGED.ORIGINAL_BRANCH_KEY = VISIT.BRANCH_KEY 
INNER JOIN DW_${var.SF_ENVIRONMENT}.INTEGRATION.DIM_CLIENT_MERGED CLIENT_MERGED ON CLIENT_MERGED.ORIGINAL_CLIENT_KEY = VISIT.CLIENT_KEY
UNION
--ALLIANCE MYCARE MATRIXCARE
SELECT DISTINCT 
MD5(CLIENT_MERGED.CLIENT_KEY || VISIT.PARTNER_CONTRACT_SERVICE_KEY || BRANCH_MERGED.BRANCH_KEY || DATE_TRUNC(''MONTH'', VISIT.REPORT_DATE)) AS CLIENT_ACQUIRED_KEY,
CLIENT_MERGED.ORIGINAL_CLIENT_KEY,
CLIENT_MERGED.CLIENT_KEY,
CLIENT_MERGED.CLIENT_NUMBER,
VISIT.SOURCE_SYSTEM_ID,
VISIT.SYSTEM_CODE,
BRANCH_MERGED.ORIGINAL_BRANCH_KEY,
BRANCH_MERGED.BRANCH_KEY,
VISIT.PARTNER_CONTRACT_SERVICE_KEY,
DATE_TRUNC(''MONTH'', VISIT.REPORT_DATE) AS SERVICE_MONTH,
CASE WHEN ACQ_NAME= ''MYCARE'' AND VISIT.REPORT_DATE < date ''2023-07-24'' 
         THEN ''ADAPTIVE''
         WHEN ACQ_NAME= ''MYCARE'' AND VISIT.REPORT_DATE >= date ''2023-07-24''
         THEN UPPER(ACQ_NAME) 
         WHEN ACQ_NAME <> ''MYCARE''
         THEN UPPER(ACQ_NAME) 
     END AS AQUISITION_NAME,
-1 AS ETL_TASK_KEY,
-1 AS ETL_INSERTED_TASK_KEY,
CONVERT_TIMEZONE(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ AS ETL_LAST_UPDATED_DATE,
CURRENT_USER AS ETL_LAST_UPDATED_BY,
FALSE AS ETL_DELETED_FLAG
FROM ALLIANCE_MYCARE_MATRIXCARE a 
INNER JOIN DW_${var.SF_ENVIRONMENT}.HAH.FACT_VISIT VISIT ON VISIT.CLIENT_KEY = a.CLIENT_KEY
INNER JOIN DW_${var.SF_ENVIRONMENT}.INTEGRATION.DIM_BRANCH_MERGED BRANCH_MERGED ON BRANCH_MERGED.ORIGINAL_BRANCH_KEY = VISIT.BRANCH_KEY 
INNER JOIN DW_${var.SF_ENVIRONMENT}.INTEGRATION.DIM_CLIENT_MERGED CLIENT_MERGED ON CLIENT_MERGED.ORIGINAL_CLIENT_KEY = VISIT.CLIENT_KEY;
`;
		try {
			snowflake.execute (
			{sqlText: sql}
			);
			return "Succeeded."; // Return a success/error indicator.
		}
		catch (err) {
			return "Failed: " + err; // Return a success/error indicator.
		}

 EOT
}

