resource "snowflake_procedure" "DW_HAH_DELETE_STAGE_PAYLOCITY_FACT_PAYROLL_DETAILS" {
	name ="DELETE_STAGE_PAYLOCITY_FACT_PAYROLL_DETAILS"
	database = "DW_${var.SF_ENVIRONMENT}"
	schema = "HAH"
	language  = "SQL"
	return_type = "VARCHAR(16777216)"
	execute_as = "OWNER"
	statement = <<-EOT

DECLARE
  RETURN_RESULT VARCHAR;
BEGIN
		DELETE FROM HAH.FACT_PAYROLL_DETAILS WHERE SOURCE_SYSTEM_ID =10 AND PAYROLL_DETAIL_KEY
  NOT IN (SELECT PAYROLL_DETAIL_KEY FROM STAGE.PAYLOCITY_FACT_PAYROLL_DETAILS);
	SELECT CONCAT(''Message : '',"number of rows deleted", '' Rows Deleted.'') into :return_result FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));
	RETURN RETURN_RESULT;
END;

 EOT
}

