resource "snowflake_procedure" "DW_HAH_GET_STAGE_DATAFLEXSYNCDATA_DIM_INVOICE_STATUS_MAPPING" {
	name ="GET_STAGE_DATAFLEXSYNCDATA_DIM_INVOICE_STATUS_MAPPING"
	database = "DW_${var.SF_ENVIRONMENT}"
	schema = "HAH"
	language  = "SQL"

	arguments {
		name = "STR_ETL_TASK_KEY"
		type = "VARCHAR(16777216)"
}	

	arguments {
		name = "STR_CDC_START"
		type = "VARCHAR(16777216)"
}	

	arguments {
		name = "STR_CDC_END"
		type = "VARCHAR(16777216)"
}	
	return_type = "VARCHAR(16777216)"
	execute_as = "OWNER"
	statement = <<-EOT

BEGIN
--*****************************************************************************************************************************
-- DEVELOPMENT LOG:
-- DATE        AUTHOR                NOTES:
-- --------    -------------------   -----------------------------------------------------------------------------------------------
-- 21/04/23    Pinkal Panchal        Initial Development
--*****************************************************************************************************************************

INSERT OVERWRITE INTO STAGE.DATAFLEXSYNCDATA_DIM_INVOICE_STATUS_MAPPING
WITH INVOICE_STATUS AS
(
SELECT	
	INV.INVOICENO::STRING AS INVOICENO,
    3 AS SOURCE_SYSTEM_ID ,
	inv.DBNAME AS SYSTEM_CODE ,
	inv.OFFICE,inv.PERIOD,inv.CONTRACTCODE,
    CASE WHEN inv.OUTSANDINGAMOUNT <= 0 THEN ''PAID''
        WHEN inv.OUTSANDINGAMOUNT > 0 AND max(inv.PAYMENTRECEIVED) > 0 THEN ''PARTIAL PAY''
        ELSE ''BILLED'' END AS DERIVED_INVOICE_STATUS,
	MD5(SOURCE_SYSTEM_ID || ''-'' || DERIVED_INVOICE_STATUS || ''-'' || SYSTEM_CODE) AS INVOICE_STATUS_KEY    
FROM DISC_${var.SF_ENVIRONMENT}.DATAFLEXSYNCDATA.DFINVOICES inv
GROUP by inv.DBNAME,INV.INVOICENO,inv.OUTSANDINGAMOUNT,
inv.OFFICE,inv.PERIOD,inv.CONTRACTCODE
UNION 
SELECT 
	ARINV.INVOICENUMBER AS INVOICENO,
	3 AS SOURCE_SYSTEM_ID,
	ARINV.DBNAME AS SYSTEM_CODE,
	ARINV.OFFICE, ARINV.PERIOD,ARINV.CONTRACTCODE,
	CASE WHEN ARINV.OUTSTANDING <= 0 THEN ''PAID''
		WHEN ARINV.OUTSTANDING > 0 AND ARINV.GROSSPAID > 0 THEN ''PARTIAL PAY''
		ELSE ''BILLED'' END AS DERIVED_INVOICE_STATUS,
	MD5(SOURCE_SYSTEM_ID || ''-'' || DERIVED_INVOICE_STATUS || ''-'' || SYSTEM_CODE) AS INVOICE_STATUS_KEY 
FROM DISC_${var.SF_ENVIRONMENT}.DATAFLEXSYNCDATA.DFARINVOICES ARINV
GROUP BY ARINV.DBNAME,ARINV.INVOICENUMBER,ARINV.OUTSTANDING,ARINV.GROSSPAID,
ARINV.OFFICE, ARINV.PERIOD,ARINV.CONTRACTCODE
)
SELECT DISTINCT 
SOURCE_SYSTEM_ID,SYSTEM_CODE,DERIVED_INVOICE_STATUS,INVOICE_STATUS_KEY
	-- ETL Fields
    ,:STR_ETL_TASK_KEY AS ETL_TASK_KEY
    ,:STR_ETL_TASK_KEY AS ETL_INSERTED_TASK_KEY                    
	,convert_timezone(''UTC'', CURRENT_TIMESTAMP)::timestamp_ntz as ETL_INSERTED_DATE
	,CURRENT_USER as ETL_INSERTED_BY
	,convert_timezone(''UTC'', CURRENT_TIMESTAMP)::timestamp_ntz as ETL_LAST_UPDATED_DATE
	,CURRENT_USER as ETL_LAST_UPDATED_BY
FROM INVOICE_STATUS;
RETURN ''SUCCESS'';
END;

 EOT
}

