resource "snowflake_procedure" "DW_HAH_DELETE_STAGE_OSHAH_DIM_BRANCH" {
	name ="DELETE_STAGE_OSHAH_DIM_BRANCH"
	database = "DW_${var.SF_ENVIRONMENT}"
	schema = "HAH"
	language  = "SQL"
	return_type = "VARCHAR(16777216)"
	execute_as = "OWNER"
	statement = <<-EOT

BEGIN
 
DELETE FROM DW_${var.SF_ENVIRONMENT}.HAH.DIM_BRANCH WHERE SOURCE_SYSTEM_ID =17 AND SYSTEM_CODE  ILIKE ''%OSHAH%''
  AND BRANCH_KEY  NOT IN (SELECT BRANCH_KEY FROM DW_${var.SF_ENVIRONMENT}.STAGE.OSHAH_DIM_BRANCH);
RETURN ''SUCCESS'';
END;

 EOT
}

