resource "snowflake_procedure" "DW_HAH_GET_STAGE_ALAYACARE_DIM_SERVICES" {
	name ="GET_STAGE_ALAYACARE_DIM_SERVICES"
	database = "DW_${var.SF_ENVIRONMENT}"
	schema = "HAH"
	language  = "SQL"

	arguments {
		name = "STR_ETL_TASK_KEY"
		type = "VARCHAR(16777216)"
}	

	arguments {
		name = "STR_CDC_START"
		type = "VARCHAR(16777216)"
}	

	arguments {
		name = "STR_CDC_END"
		type = "VARCHAR(16777216)"
}	
	return_type = "VARCHAR(16777216)"
	execute_as = "OWNER"
	statement = <<-EOT

BEGIN
--*****************************************************************************************************************************
-- NAME:  ALAYACARE_DIM_SERVICE
--
-- PURPOSE: Creates one row per SERVICE_CODE, RATE_TYPE AND SERVICE_LINE combination according to ALAYACARE
--
-- DEVELOPMENT LOG:
-- DATE        AUTHOR                	NOTES:
-- --------    -------------------   	-----------------------------------------------------------------------------------------------
-- 12/28/22     Shraddha Sejpal         Initial development		
--06/26/23      Nutan Jagnade	 	     Modified changes in REVENUE_CATEGORY,REVENUE_SUBCATEGORY_NAME,REVENUE_SUBCATEGORY_CODE 
--*****************************************************************************************************************************
--
INSERT OVERWRITE INTO STAGE.ALAYACARE_DIM_SERVICES
SELECT DISTINCT 
MD5(NVL(TRIM(COMPANY.PROPERTIES_TBL_GT_ACCOUNT_DESCRIPTION), ''Unknown'') || '' ('' || NVL(BC.BRANCH_ID,-1) || '')'' || ''-'' || 
NVL(TRIM(S.SERVICE_CODE_ID::STRING), ''Unknown'') || ''-'' || NVL(VISITS.VISIT_COMPUTED_RATE_UNITS, ''Unknown'') || ''-'' || 
NVL(CASE WHEN CHARINDEX(''HOMECARE'', REPLACE(UPPER(BC.GL_REVENUE_ACC_ACCOUNT_NAME), '' '', '''')) > 0
		THEN ''HC''
	WHEN CHARINDEX(''HOMEHEALTH'', REPLACE(UPPER(BC.GL_REVENUE_ACC_ACCOUNT_NAME), '' '', '''')) > 0
		THEN ''HH''
	ELSE ''NA'' END, ''NA'') || ''-'' || ''ALAYACARE'') AS SERVICE_KEY        --per service we have multiple visit type and revenue_subcategory so added VISIT_COMPUTED_RATE_UNITS,GL_REVENUE_ACC_ACCOUNT_NAME      
,9 AS SOURCE_SYSTEM_ID  
,UPPER(NVL(TRIM(COMPANY.PROPERTIES_TBL_GT_ACCOUNT_DESCRIPTION), ''Unknown'') || '' ('' || NVL(BC.BRANCH_ID,-1) || '')'') AS SYSTEM_CODE          
,S.SERVICE_CODE_ID AS SERVICE_CODE               
,S.PROPERTIES_NAME AS SERVICE_DESCRIPTION   
,NULL AS SERVICE_TYPE
,CASE WHEN VISITS.VISIT_COMPUTED_RATE_UNITS=''hours'' THEN ''Hourly'' 
	  WHEN VISITS.VISIT_COMPUTED_RATE_UNITS= ''visits'' THEN ''Visit'' 
	  ELSE VISITS.VISIT_COMPUTED_RATE_UNITS END AS SERVICE_RATE_TYPE
,CASE WHEN CHARINDEX(''HOMECARE'', REPLACE(UPPER(BC.GL_REVENUE_ACC_ACCOUNT_NAME), '' '', '''')) > 0
		THEN ''HC''
	WHEN CHARINDEX(''HOMEHEALTH'', REPLACE(UPPER(BC.GL_REVENUE_ACC_ACCOUNT_NAME), '' '', '''')) > 0
		THEN ''HH''
	ELSE ''NA'' END AS REVENUE_CATEGORY,  
	CASE REVENUE_CATEGORY
			WHEN ''HC'' THEN ''HC''
			WHEN ''HH'' THEN ''HHA''
		  ELSE ''NA'' END AS REVENUE_SUBCATEGORY_CODE
,CASE WHEN  REVENUE_CATEGORY = ''HC'' THEN ''HOME CARE''
	WHEN REVENUE_CATEGORY = ''HH'' THEN ''HOME HEALTH''
	ELSE ''NA'' END AS REVENUE_SUBCATEGORY_NAME          
,CASE WHEN S.PROPERTIES_IS_DISABLED=0 THEN TRUE ELSE FALSE END AS ACTIVE_FLAG    -- Need to confirm          
 -- ETL Field
       , :STR_ETL_TASK_KEY AS ETL_TASK_KEY
       , :STR_ETL_TASK_KEY AS ETL_INSERTED_TASK_KEY              
        , CONVERT_TIMEZONE(''UTC'',CURRENT_TIMESTAMP)::TIMESTAMP_NTZ AS ETL_INSERTED_DATE
        , CURRENT_USER AS ETL_INSERTED_BY
        , CONVERT_TIMEZONE(''UTC'',CURRENT_TIMESTAMP)::TIMESTAMP_NTZ AS ETL_LAST_UPDATED_DATE
        , CURRENT_USER AS ETL_LAST_UPDATED_BY
        , 0 AS ETL_DELETED_FLAG        
 FROM DISC_${var.SF_ENVIRONMENT}.ALAYACARE.SERVICE_CODE AS S
LEFT JOIN DISC_${var.SF_ENVIRONMENT}.ALAYACARE.SERVICE_CODE_BILL_CODE SBC ON S.SERVICE_CODE_ID = SBC.SERVICE_CODE_ID
LEFT JOIN DISC_${var.SF_ENVIRONMENT}.ALAYACARE.BILL_CODE AS BC ON BC.BILL_CODE_ID = SBC.BILL_CODE_ID 
LEFT JOIN DISC_${var.SF_ENVIRONMENT}.ALAYACARE.BRANCH AS COMPANY ON COMPANY.BRANCH_ID = BC.BRANCH_ID
--LEFT JOIN (SELECT DISTINCT SERVICE_CODE_ID,VISIT_COMPUTED_RATE_UNITS,BRANCH_ID FROM DISC_${var.SF_ENVIRONMENT}.ALAYACARE.VISIT ) VISITS 
--ON VISITS.SERVICE_CODE_ID = S.SERVICE_CODE_ID AND VISITS.BRANCH_ID = NVL(BC.BRANCH_ID,-1)
LEFT JOIN (SELECT DISTINCT SERVICE_CODE_ID,VISIT_COMPUTED_RATE_UNITS,BRANCH_ID FROM DISC_${var.SF_ENVIRONMENT}.ALAYACARE.VISIT) VISITS
--QUALIFY ROW_NUMBER()OVER(PARTITION BY SERVICE_CODE_ID,BRANCH_ID ORDER BY VISIT_COMPUTED_RATE_UNITS)=1) VISITS 
ON VISITS.SERVICE_CODE_ID = S.SERVICE_CODE_ID AND VISITS.BRANCH_ID = NVL(BC.BRANCH_ID,-1)
INNER JOIN DISC_${var.SF_ENVIRONMENT}.ALAYACARE.CONFIGURATION CONFIG 
	ON CONFIG.SYSTEM_CODE= SYSTEM_CODE
	AND CONFIG.CONFIGURATION_ACTIVE= TRUE
	AND CONFIG.SYSTEM_CODE IS NOT NULL
UNION 
--to get the combinations of service and VISIT_COMPUTED_RATE_UNITS coming from visit table
SELECT 
MD5(NVL(TRIM(B.PROPERTIES_TBL_GT_ACCOUNT_DESCRIPTION), ''Unknown'') || '' ('' || NVL(VISITS.BRANCH_ID,-1) || '')'' || ''-'' || 
NVL(TRIM(VISITS.SERVICE_CODE_ID::STRING), ''Unknown'') || ''-'' || NVL(VISITS.VISIT_COMPUTED_RATE_UNITS, ''Unknown'') || ''-'' || 
NVL(CASE WHEN CHARINDEX(''HOMECARE'', REPLACE(UPPER(BC.GL_REVENUE_ACC_ACCOUNT_NAME), '' '', '''')) > 0
		THEN ''HC''
	WHEN CHARINDEX(''HOMEHEALTH'', REPLACE(UPPER(BC.GL_REVENUE_ACC_ACCOUNT_NAME), '' '', '''')) > 0
		THEN ''HH''
	ELSE ''NA'' END, ''NA'') || ''-'' || ''ALAYACARE'') AS SERVICE_KEY  --per service we have multiple visit type and revenue_subcategory so added VISIT_COMPUTED_RATE_UNITS,GL_REVENUE_ACC_ACCOUNT_NAME
	,9 AS SOURCE_SYSTEM_ID  
	,UPPER(NVL(TRIM(B.PROPERTIES_TBL_GT_ACCOUNT_DESCRIPTION), ''Unknown'') || '' ('' || NVL(VISITS.BRANCH_ID,-1) || '')'') AS SYSTEM_CODE          
,S.SERVICE_CODE_ID AS SERVICE_CODE               
,S.PROPERTIES_NAME AS SERVICE_DESCRIPTION   
,NULL AS SERVICE_TYPE
,CASE WHEN VISITS.VISIT_COMPUTED_RATE_UNITS=''hours'' THEN ''Hourly'' 
	  WHEN VISITS.VISIT_COMPUTED_RATE_UNITS= ''visits'' THEN ''Visit'' 
	  ELSE VISITS.VISIT_COMPUTED_RATE_UNITS END AS SERVICE_RATE_TYPE
,CASE WHEN CHARINDEX(''HOMECARE'', REPLACE(UPPER(BC.GL_REVENUE_ACC_ACCOUNT_NAME), '' '', '''')) > 0
		THEN ''HC''
	WHEN CHARINDEX(''HOMEHEALTH'', REPLACE(UPPER(BC.GL_REVENUE_ACC_ACCOUNT_NAME), '' '', '''')) > 0
		THEN ''HH''
	ELSE ''NA'' END AS REVENUE_CATEGORY,  
	CASE REVENUE_CATEGORY
			WHEN ''HC'' THEN ''HC''
			WHEN ''HH'' THEN ''HHA''
		  ELSE ''NA'' END AS REVENUE_SUBCATEGORY_CODE
,CASE WHEN  REVENUE_CATEGORY = ''HC'' THEN ''HOME CARE''
	WHEN REVENUE_CATEGORY = ''HH'' THEN ''HOME HEALTH''
	ELSE ''NA'' END AS REVENUE_SUBCATEGORY_NAME          
,CASE WHEN S.PROPERTIES_IS_DISABLED=0 THEN TRUE ELSE FALSE END AS ACTIVE_FLAG 
    , :STR_ETL_TASK_KEY AS ETL_TASK_KEY
    , :STR_ETL_TASK_KEY AS ETL_INSERTED_TASK_KEY
    , CONVERT_TIMEZONE(''UTC'',CURRENT_TIMESTAMP)::TIMESTAMP_NTZ AS ETL_INSERTED_DATE
        , CURRENT_USER AS ETL_INSERTED_BY
        , CONVERT_TIMEZONE(''UTC'',CURRENT_TIMESTAMP)::TIMESTAMP_NTZ AS ETL_LAST_UPDATED_DATE
        , CURRENT_USER AS ETL_LAST_UPDATED_BY
        , 0 AS ETL_DELETED_FLAG 
FROM  DISC_${var.SF_ENVIRONMENT}.ALAYACARE.visit as VISITS 
LEFT JOIN DISC_${var.SF_ENVIRONMENT}.ALAYACARE.SERVICE SERVICES ON SERVICES.SERVICE_ID =VISITS.SERVICE_ID
LEFT JOIN DISC_${var.SF_ENVIRONMENT}.ALAYACARE.BRANCH B ON
VISITS.BRANCH_ID = B.BRANCH_ID
LEFT JOIN DISC_${var.SF_ENVIRONMENT}.ALAYACARE.FUNDER F ON f.FUNDER_ID =SERVICES.SERVICE_FUNDER_ID 
LEFT JOIN DISC_${var.SF_ENVIRONMENT}.ALAYACARE.BILL_CODE AS BC ON BC.BILL_CODE_ID = VISITS.VISIT_COMPUTED_RATE_BILLITEM_ID
LEFT JOIN DISC_${var.SF_ENVIRONMENT}.ALAYACARE.SERVICE_CODE S ON S.SERVICE_CODE_ID =VISITS.SERVICE_CODE_ID;
  RETURN ''SUCCESS'';
    END;
    
 EOT
}

