resource "snowflake_procedure" "DW_HAH_DELETE_STAGE_ALLIANCE_DIM_SUPERVISOR" {
	name ="DELETE_STAGE_ALLIANCE_DIM_SUPERVISOR"
	database = "DW_${var.SF_ENVIRONMENT}"
	schema = "HAH"
	language  = "SQL"
	return_type = "VARCHAR(16777216)"
	execute_as = "OWNER"
	statement = <<-EOT

	BEGIN 
DELETE FROM DW_${var.SF_ENVIRONMENT}.HAH.DIM_SUPERVISOR WHERE SOURCE_SYSTEM_ID=19
	AND SYSTEM_CODE=''ALLIANCE'' AND SUPERVISOR_KEY
	NOT IN (SELECT SUPERVISOR_KEY FROM DW_${var.SF_ENVIRONMENT}.STAGE.ALLIANCE_DIM_SUPERVISOR);
	RETURN ''SUCCESS'';
END;

 EOT
}

