resource "snowflake_procedure" "DW_HAH_FACT_CLIENT_ACQUIRED_MERGED_POSTPROCESSING" {
	name ="FACT_CLIENT_ACQUIRED_MERGED_POSTPROCESSING"
	database = "DW_${var.SF_ENVIRONMENT}"
	schema = "HAH"
	language  = "JAVASCRIPT"

	arguments {
		name = "STR_ETL_TASK_KEY"
		type = "VARCHAR(16777216)"
}	

	arguments {
		name = "STR_CDC_START"
		type = "VARCHAR(16777216)"
}	

	arguments {
		name = "STR_CDC_END"
		type = "VARCHAR(16777216)"
}	
	return_type = "VARCHAR(16777216)"
	execute_as = "OWNER"
	statement = <<-EOT

        var sql = `
	INSERT OVERWRITE INTO HAH.FACT_CLIENT_ACQUIRED_MERGED
    WITH ccsi_client AS(
SELECT DISTINCT cm.CLIENT_KEY FROM HAH.FACT_VISIT visit
JOIN HAH.DIM_BRANCH branch ON visit.BRANCH_KEY = branch.BRANCH_KEY
JOIN INTEGRATION.DIM_CLIENT_MERGED cm ON visit.CLIENT_KEY = cm.ORIGINAL_CLIENT_KEY
WHERE visit.SERVICE_DATE >= ''2021-07-01'' AND branch.SOURCE_SYSTEM_ID = 8
),
dataflex_client AS(
SELECT DISTINCT cm.CLIENT_KEY FROM HAH.FACT_VISIT visit
JOIN HAH.DIM_BRANCH branch ON visit.BRANCH_KEY = branch.BRANCH_KEY
JOIN INTEGRATION.DIM_CLIENT_MERGED cm ON visit.CLIENT_KEY = cm.ORIGINAL_CLIENT_KEY
WHERE visit.SERVICE_DATE >= ''2021-07-01'' AND branch.SOURCE_SYSTEM_ID = 3
),
inter AS (
SELECT client_key FROM ccsi_client
INTERSECT
SELECT client_key FROM dataflex_client
),
Altamaha_client as
(
  SELECT 
MD5(NVL(TRIM(B.PROPERTIES_TBL_GT_ACCOUNT_DESCRIPTION), ''Unknown'') || '' ('' || NVL(C.BRANCH_ID,-1) || '')'' || ''-'' || NVL(C.CLIENT_ID::STRING,'''') || ''-'' || ''ALAYACARE'') 
CLIENT_KEY,
  NVL(TRIM(B.PROPERTIES_TBL_GT_ACCOUNT_DESCRIPTION), ''Unknown'') || '' ('' || NVL(C.BRANCH_ID,-1) || '')'' as SYSTEMCODE 
 FROM DISC_${var.SF_ENVIRONMENT}.Alayacare.client c
LEFT OUTER JOIN DISC_${var.SF_ENVIRONMENT}.ALAYACARE.BRANCH B 
	ON c.BRANCH_ID = B.BRANCH_ID
    where PROFILE_ACQUIRED_BUSINESS_  = ''Altamaha''
),
  Praetorian_client as
  (
    SELECT md5(DBNAME || ''-'' || NUMBER || ''-'' || ''DATAFLEXSYNCDATA'' ) AS CLIENT_KEY ,DBNAME AS SYSTEM_CODE
FROM DISC_${var.SF_ENVIRONMENT}.DATAFLEXSYNCDATA.DFCLIENTS WHERE AGENCY = ''Praetorian''
  ),
Preferred_client as 
(
	SELECT distinct
	CLIENT_KEY , 
	SOURCE_SYSTEM_ID ,
	SYSTEM_CODE 
	FROM HAH.DIM_CLIENT a
	WHERE a.SOURCE_SYSTEM_ID =17
	AND a.SYSTEM_CODE = ''PREFERRED''
),
edison_client AS 
(
	SELECT distinct 
	CLIENT_KEY , 
	SOURCE_SYSTEM_ID ,
	SYSTEM_CODE 
	FROM HAH.DIM_CLIENT a
	WHERE a.SOURCE_SYSTEM_ID =17
	AND a.SYSTEM_CODE = ''EDISON''
),
CLEARCARE_client AS 
(
	SELECT distinct 
	CLIENT_KEY , 
	SOURCE_SYSTEM_ID ,
	SYSTEM_CODE 
	FROM HAH.DIM_CLIENT a
	WHERE a.SOURCE_SYSTEM_ID =16
	AND a.SYSTEM_CODE = ''CLEARCARE''
),
ASR_client AS 
(
	SELECT distinct 
	CLIENT_KEY , 
	SOURCE_SYSTEM_ID ,
	SYSTEM_CODE 
	FROM HAH.DIM_CLIENT a
	WHERE a.SOURCE_SYSTEM_ID =13
	AND a.SYSTEM_CODE = ''ASR''
)
SELECT DISTINCT int.CLIENT_KEY,clm.original_client_key, 
clm.ORIGINAL_SOURCE_SYSTEM_ID,clm.SOURCE_SYSTEM_ID,original_system_code,system_code,
TRUE as Acquired_Flag, ''CCSI Acquired'' as NOtes,
CONVERT_TIMEZONE(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ AS ETL_INSERTED_DATE,
CURRENT_USER AS ETL_INSERTED_BY,
CONVERT_TIMEZONE(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ AS ETL_LAST_UPDATED_DATE,
CURRENT_USER AS ETL_LAST_UPDATED_BY
FROM inter int
inner join integration.dim_client_merged clm
on clm.client_key = int.client_key
and ORIGINAL_SOURCE_SYSTEM_ID = 8 
WHERE int.CLIENT_KEY IN (SELECT Client_key FROM inter)
UNION all
SELECT CLIENT_KEY,CLIENT_KEY,9,9,SYSTEMCODE,SYSTEMCODE,TRUE,''Altamaha'',
CONVERT_TIMEZONE(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ AS ETL_INSERTED_DATE,
CURRENT_USER AS ETL_INSERTED_BY,
CONVERT_TIMEZONE(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ AS ETL_LAST_UPDATED_DATE,
CURRENT_USER AS ETL_LAST_UPDATED_BY from Altamaha_client
 UNION all
SELECT CLIENT_KEY,CLIENT_KEY,3,3,SYSTEM_CODE,SYSTEM_CODE,TRUE,''Praetorian'',
CONVERT_TIMEZONE(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ AS ETL_INSERTED_DATE,
CURRENT_USER AS ETL_INSERTED_BY,
CONVERT_TIMEZONE(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ AS ETL_LAST_UPDATED_DATE,
CURRENT_USER AS ETL_LAST_UPDATED_BY from Praetorian_client
UNION ALL 
SELECT  CLIENT_KEY,CLIENT_KEY,SOURCE_SYSTEM_ID,SOURCE_SYSTEM_ID,SYSTEM_CODE,SYSTEM_CODE,TRUE,''Preferred'',
CONVERT_TIMEZONE(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ AS ETL_INSERTED_DATE,
CURRENT_USER AS ETL_INSERTED_BY,
CONVERT_TIMEZONE(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ AS ETL_LAST_UPDATED_DATE,
CURRENT_USER AS ETL_LAST_UPDATED_BY from Preferred_client
UNION ALL 
SELECT  CLIENT_KEY,CLIENT_KEY,SOURCE_SYSTEM_ID,SOURCE_SYSTEM_ID,SYSTEM_CODE,SYSTEM_CODE,TRUE,''Edison'',
CONVERT_TIMEZONE(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ AS ETL_INSERTED_DATE,
CURRENT_USER AS ETL_INSERTED_BY,
CONVERT_TIMEZONE(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ AS ETL_LAST_UPDATED_DATE,
CURRENT_USER AS ETL_LAST_UPDATED_BY from edison_client
UNION ALL 
SELECT  CLIENT_KEY,CLIENT_KEY,SOURCE_SYSTEM_ID,SOURCE_SYSTEM_ID,SYSTEM_CODE,SYSTEM_CODE,TRUE,''CLEARCARE'',
CONVERT_TIMEZONE(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ AS ETL_INSERTED_DATE,
CURRENT_USER AS ETL_INSERTED_BY,
CONVERT_TIMEZONE(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ AS ETL_LAST_UPDATED_DATE,
CURRENT_USER AS ETL_LAST_UPDATED_BY from CLEARCARE_client
UNION ALL 
SELECT  CLIENT_KEY,CLIENT_KEY,SOURCE_SYSTEM_ID,SOURCE_SYSTEM_ID,SYSTEM_CODE,SYSTEM_CODE,TRUE,''ASR'',
CONVERT_TIMEZONE(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ AS ETL_INSERTED_DATE,
CURRENT_USER AS ETL_INSERTED_BY,
CONVERT_TIMEZONE(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ AS ETL_LAST_UPDATED_DATE,
CURRENT_USER AS ETL_LAST_UPDATED_BY from ASR_client
;`;
//          try {
                snowflake.execute (
                    {sqlText: sql}
                    );
                return "Succeeded.";   // Return a success/error indicator.
//                }
//            catch (err)  {
//                return "Failed: " + err;   // Return a success/error indicator.
//                }  

 EOT
}

