resource "snowflake_procedure" "DW_HAH_DELETE_STAGE_OPENSYSTEMS_FACT_BRANCH_PAYROLL_PERIODS" {
	name ="DELETE_STAGE_OPENSYSTEMS_FACT_BRANCH_PAYROLL_PERIODS"
	database = "DW_${var.SF_ENVIRONMENT}"
	schema = "HAH"
	language  = "SQL"
	return_type = "VARCHAR(16777216)"
	execute_as = "OWNER"
	statement = <<-EOT

DECLARE
    return_result VARCHAR;
BEGIN 
DELETE FROM DW_${var.SF_ENVIRONMENT}.HAH.FACT_BRANCH_PAYROLL_PERIODS 
	WHERE BRANCH_KEY IN (SELECT BRANCH_KEY FROM DW_${var.SF_ENVIRONMENT}."STAGE".OPENSYSTEMS_DIM_BRANCH)
	AND BRANCH_PAYROLL_PERIODS_KEY NOT IN (select BRANCH_PAYROLL_PERIODS_KEY from DW_${var.SF_ENVIRONMENT}."STAGE".OPENSYSTEMS_FACT_BRANCH_PAYROLL_PERIODS);
SELECT CONCAT(''Message : '',"number of rows deleted", '' Rows Deleted.  '') into :return_result FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));
return return_result;
END;

 EOT
}

