resource "snowflake_procedure" "DW_HAH_MERGE_STAGE_PREFERRED_FACT_INTAKE" {
	name ="MERGE_STAGE_PREFERRED_FACT_INTAKE"
	database = "DW_${var.SF_ENVIRONMENT}"
	schema = "HAH"
	language  = "SQL"
	return_type = "VARCHAR(16777216)"
	execute_as = "OWNER"
	statement = <<-EOT

DECLARE
    return_result VARCHAR;
BEGIN
    MERGE INTO HAH.FACT_INTAKE TGT USING STAGE.PREFERRED_FACT_INTAKE STAGE 
ON TGT.INTAKE_KEY = STAGE.INTAKE_KEY
WHEN MATCHED THEN 
UPDATE SET 
    TGT.REPORT_DATE= STAGE.REPORT_DATE
   ,TGT.BRANCH_KEY= STAGE.BRANCH_KEY
   ,TGT.CLIENT_KEY= STAGE.CLIENT_KEY
   ,TGT.CONTRACT_KEY= STAGE.CONTRACT_KEY
   ,TGT.SOURCE_SYSTEM_ID= STAGE.SOURCE_SYSTEM_ID
   ,TGT.REAUTHORIZED_DATE= STAGE.REAUTHORIZED_DATE
	
   ,TGT.PRE_AUTH_NUMBER = STAGE.PRE_AUTH_NUMBER
   ,TGT.BEGIN_SERVICE_DATE = STAGE.BEGIN_SERVICE_DATE
   ,TGT.END_SERVICE_DATE = STAGE.END_SERVICE_DATE
   ,TGT.LATEST_AUTH_BEGIN_DATE = STAGE.LATEST_AUTH_BEGIN_DATE
   ,TGT.LATEST_AUTH_END_DATE = STAGE.LATEST_AUTH_END_DATE
   ,TGT.BRANCH_NAME= STAGE.BRANCH_NAME
   ,TGT.CLIENT_NUMBER= STAGE.CLIENT_NUMBER
   ,TGT.CONTRACT_CODE= STAGE.CONTRACT_CODE
   ,TGT.BILL_RATE= STAGE.BILL_RATE
   ,TGT.SYSTEM_CODE= STAGE.SYSTEM_CODE
   ,TGT.CASE_MANAGER= STAGE.CASE_MANAGER
   ,TGT.HOURS_AUTHORIZED= STAGE.HOURS_AUTHORIZED
   ,TGT.HOURS_AUTHORIZED_NON_ADJUSTED= STAGE.HOURS_AUTHORIZED_NON_ADJUSTED
   ,TGT.ETL_TASK_KEY= STAGE.ETL_TASK_KEY
   ,TGT.ETL_LAST_UPDATED_DATE= STAGE.ETL_LAST_UPDATED_DATE
   ,TGT.ETL_LAST_UPDATED_BY= STAGE.ETL_LAST_UPDATED_BY
   ,TGT.ETL_DELETED_FLAG= STAGE.ETL_DELETED_FLAG
WHEN NOT MATCHED THEN 
INSERT ( 
    INTAKE_KEY
   ,REPORT_DATE
   ,BRANCH_KEY
   ,CLIENT_KEY
   ,CONTRACT_KEY
   ,SOURCE_SYSTEM_ID
   ,REAUTHORIZED_DATE
   ,PRE_AUTH_NUMBER
   ,BEGIN_SERVICE_DATE
   ,END_SERVICE_DATE
   ,LATEST_AUTH_BEGIN_DATE
   ,LATEST_AUTH_END_DATE
   ,BRANCH_NAME
   ,CLIENT_NUMBER
   ,CONTRACT_CODE
   ,BILL_RATE
   ,SYSTEM_CODE
   ,CASE_MANAGER
   ,HOURS_AUTHORIZED
   ,HOURS_AUTHORIZED_NON_ADJUSTED
   ,ETL_TASK_KEY
   ,ETL_INSERTED_TASK_KEY
   ,ETL_INSERTED_DATE
   ,ETL_INSERTED_BY
   ,ETL_LAST_UPDATED_DATE
   ,ETL_LAST_UPDATED_BY
   ,ETL_DELETED_FLAG
) 
VALUES (
    STAGE.INTAKE_KEY
   ,STAGE.REPORT_DATE
   ,STAGE.BRANCH_KEY
   ,STAGE.CLIENT_KEY
   ,STAGE.CONTRACT_KEY
   ,STAGE.SOURCE_SYSTEM_ID
   ,STAGE.REAUTHORIZED_DATE
   ,STAGE.PRE_AUTH_NUMBER
   ,STAGE.BEGIN_SERVICE_DATE
   ,STAGE.END_SERVICE_DATE
   ,STAGE.LATEST_AUTH_BEGIN_DATE
   ,STAGE.LATEST_AUTH_END_DATE
   ,STAGE.BRANCH_NAME
   ,STAGE.CLIENT_NUMBER
   ,STAGE.CONTRACT_CODE
   ,STAGE.BILL_RATE
   ,STAGE.SYSTEM_CODE
   ,STAGE.CASE_MANAGER
   ,STAGE.HOURS_AUTHORIZED
   ,STAGE.HOURS_AUTHORIZED_NON_ADJUSTED
   ,STAGE.ETL_TASK_KEY
   ,STAGE.ETL_INSERTED_TASK_KEY
   ,STAGE.ETL_INSERTED_DATE
   ,STAGE.ETL_INSERTED_BY
   ,STAGE.ETL_LAST_UPDATED_DATE
   ,STAGE.ETL_LAST_UPDATED_BY
   ,STAGE.ETL_DELETED_FLAG
);
SELECT CONCAT(''Message : '',"number of rows inserted", '' Rows Insrted & '' ,"number of rows updated",'' Rows Updated.'') into :return_result FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));
return return_result;
END;
    
 EOT
}

