resource "snowflake_view" "DW_HAH_VW_DIM_EMPLOYEE_MERGED_BACKUP_20210813" {
	database = "DW_${var.SF_ENVIRONMENT}"
	schema = "HAH"
	name = "VW_DIM_EMPLOYEE_MERGED_BACKUP_20210813"
	statement = <<-SQL
	 WITH DATAFLEX_EMPLOYEES AS (
	SELECT EMPLOYEE.EMPLOYEE_KEY, LIST.SYSTEM_CODE, EMPLOYEE.EMPLOYEE_PID
	FROM (
		SELECT SOURCE_SYSTEM_ID, IFF(SYSTEM_CODE IN ('GA', 'SC'), 'GA', SYSTEM_CODE) AS SYSTEM_CODE, EMPLOYEE_PID 
		FROM HAH.DIM_EMPLOYEE
		WHERE SOURCE_SYSTEM_ID = 3
		GROUP BY SOURCE_SYSTEM_ID, IFF(SYSTEM_CODE IN ('GA', 'SC'), 'GA', SYSTEM_CODE), EMPLOYEE_PID
		HAVING COUNT(*) = 1
	) LIST
	JOIN HAH.DIM_EMPLOYEE AS EMPLOYEE
		ON EMPLOYEE.SOURCE_SYSTEM_ID = LIST.SOURCE_SYSTEM_ID AND IFF(EMPLOYEE.SYSTEM_CODE IN ('GA', 'SC'), 'GA', EMPLOYEE.SYSTEM_CODE) = LIST.SYSTEM_CODE AND EMPLOYEE.EMPLOYEE_PID = LIST.EMPLOYEE_PID
), COASTAL_EMPLOYEES AS (
	SELECT EMPLOYEE.EMPLOYEE_KEY, EMPLOYEE.EMPLOYEE_PID
	FROM (
		SELECT EMPLOYEE_PID
		FROM HAH.DIM_EMPLOYEE
		WHERE SOURCE_SYSTEM_ID IN (1, 2)
		GROUP BY EMPLOYEE_PID
		HAVING COUNT(*) = 1
	) LIST
	JOIN HAH.DIM_EMPLOYEE AS EMPLOYEE
		ON EMPLOYEE.SOURCE_SYSTEM_ID IN (1, 2) AND EMPLOYEE.EMPLOYEE_PID = LIST.EMPLOYEE_PID
), EXCEL_EMPLOYEES AS (
	SELECT EMPLOYEE.EMPLOYEE_KEY, EMPLOYEE.EMPLOYEE_PID
	FROM (
		SELECT SOURCE_SYSTEM_ID, EMPLOYEE_PID
		FROM HAH.DIM_EMPLOYEE
		WHERE SOURCE_SYSTEM_ID = 4
		GROUP BY SOURCE_SYSTEM_ID, EMPLOYEE_PID
		HAVING COUNT(*) = 1
	) LIST
	JOIN HAH.DIM_EMPLOYEE AS EMPLOYEE
		ON EMPLOYEE.SOURCE_SYSTEM_ID = LIST.SOURCE_SYSTEM_ID AND EMPLOYEE.EMPLOYEE_PID = LIST.EMPLOYEE_PID
), MERGED_EMPLOYEES AS (
	-- Coastal
	SELECT DATAFLEX.EMPLOYEE_KEY AS OLD_SYSTEM_EMPLOYEE_KEY, COASTAL.EMPLOYEE_KEY AS NEW_SYSTEM_EMPLOYEE_KEY
	FROM DATAFLEX_EMPLOYEES AS DATAFLEX
	JOIN COASTAL_EMPLOYEES AS COASTAL
		ON COASTAL.EMPLOYEE_PID = DATAFLEX.EMPLOYEE_PID
	WHERE DATAFLEX.SYSTEM_CODE = 'GA'
	-- Excel
	UNION ALL
	SELECT DATAFLEX.EMPLOYEE_KEY AS OLD_SYSTEM_EMPLOYEE_KEY, EXCEL.EMPLOYEE_KEY AS NEW_SYSTEM_EMPLOYEE_KEY
	FROM DATAFLEX_EMPLOYEES AS DATAFLEX
	JOIN EXCEL_EMPLOYEES AS EXCEL
		ON EXCEL.EMPLOYEE_PID = DATAFLEX.EMPLOYEE_PID
	WHERE DATAFLEX.SYSTEM_CODE = 'PA'
)
	SELECT EMPLOYEE.EMPLOYEE_KEY AS ORIGINAL_EMPLOYEE_KEY,
		EMPLOYEE.SOURCE_SYSTEM_ID AS ORIGINAL_SOURCE_SYSTEM_ID,
		EMPLOYEE.SYSTEM_CODE AS ORIGINAL_SYSTEM_CODE,
		EMPLOYEE.EMPLOYEE_NUMBER AS ORIGINAL_EMPLOYEE_NUMBER,
		NEW_EMPLOYEE.*
	FROM HAH.DIM_EMPLOYEE AS EMPLOYEE
	LEFT JOIN MERGED_EMPLOYEES AS MERGED_EMPLOYEES
		ON MERGED_EMPLOYEES.OLD_SYSTEM_EMPLOYEE_KEY = EMPLOYEE.EMPLOYEE_KEY
	JOIN HAH.DIM_EMPLOYEE AS NEW_EMPLOYEE
		ON NEW_EMPLOYEE.EMPLOYEE_KEY = COALESCE(MERGED_EMPLOYEES.NEW_SYSTEM_EMPLOYEE_KEY, EMPLOYEE.EMPLOYEE_KEY);
SQL
	or_replace = true 
	is_secure = false 
}

