CREATE OR REPLACE FUNCTION DW_PROD.PUBLIC.REPLACE_NON_UTF8_CHARS("STR" VARCHAR(16777216))
RETURNS VARCHAR(16777216)
LANGUAGE JAVASCRIPT
STRICT
IMMUTABLE
AS '  
  return STR.replace(/[^ -~]+/g, '''')    
';