resource "snowflake_procedure" "DISC_ALAYACARE_GET_PAYROLL_ITEM" {
	name ="GET_PAYROLL_ITEM"
	database = "DISC_${var.SF_ENVIRONMENT}"
	schema = "ALAYACARE"
	language  = "SQL"
	return_type = "VARCHAR(16777216)"
	execute_as = "OWNER"
	statement = <<-EOT

DECLARE
--*****************************************************************************************************************************
-- NAME:  GET_PAYROLL_ITEM 
--
-- PURPOSE: USING THIS SP FOR DISCOVERY TABLE LOAD
--
-- DEVELOPMENT LOG:
-- DATE        		AUTHOR                	NOTES:
-- ----------  		-------------------   	-----------------------------------------------------------------------------------------------
-- 2021-11-11		UNKNOWN					INITIAL DEVELOPMENT
-- 2023-09-05  		RAVI SUTHAR            	MIGRATED JavaScript to SQL
--*****************************************************************************************************************************
    return_result varchar(1000);
BEGIN
	
    INSERT OVERWRITE INTO ALAYACARE.PAYROLL_ITEM (
        EMPAY_ID, VISIT_ID, EMPLOYEE_ID, PAYROLL_PERIOD_ID, PAYROLL_RUN_ID, QUANTITY_REG, QUANTITY_REG_UNITS, QUANTITY_OT, QUANTITY_OT_UNITS, QUANTITY_HOLIDAY, QUANTITY_HOLIDAY_UNITS, REG, OT1, RATE, PAYCODE_ID, IDPAYCODE_HOLIDAY, IDPAYCODE_OVERTIME, EMPAY_TYPE_MAIN, COMPUTED_REGULAR_TOTAL, COMPUTED_OT_TOTAL, COMPUTED_HOLIDAY_TOTAL, RUN_TOTAL_COST, RUN_TOTAL_HOURS, RUN_TOTAL_OT_HOURS, RUN_TOTAL_PREMIUMS, RUN_TOTAL_REG_HOURS, RUN_TOTAL_SHIFTS, RUN_IS_DELETED, RUN_TOTAL_UNAVAILABILITIES, RUN_CREATE_TIME, RUN_UPDATE_TIME, RUN_DELETE_TIME, PERIOD_START_TIME, PERIOD_END_TIME,
		PROPERTIES_PAY_RUN_OP, PROPERTIES_PAY_RUN_CREATE_TIME, PROPERTIES_PAY_RUN_CREATE_USER_ID, PROPERTIES_PAY_RUN_GUID, PROPERTIES_PAY_RUN_ID, PROPERTIES_PAY_RUN_ID_PAYROLL_PERIOD, PROPERTIES_PAY_RUN_IDMASTERACCOUNT, PROPERTIES_PAY_RUN_TOTAL_COST, PROPERTIES_PAY_RUN_TOTAL_HOURS, PROPERTIES_PAY_RUN_TOTAL_OT_HOURS, PROPERTIES_PAY_RUN_TOTAL_PREMIUMS, PROPERTIES_PAY_RUN_TOTAL_REG_HOURS, PROPERTIES_PAY_RUN_TOTAL_SHIFTS, PROPERTIES_PAY_RUN_TOTAL_UNAVAILABILITIES, PROPERTIES_PAY_RUN_UPDATE_TIME, PROPERTIES_PAY_RUN_UPDATE_USER_ID, 
		PROPERTIES_PAY_ITEM_OP, PROPERTIES_PAY_ITEM_GUID_TO, PROPERTIES_PAY_ITEM_ID, PROPERTIES_PAY_ITEM_IDEMPLOYEE, PROPERTIES_PAY_ITEM_IDPAYCODE_HOLIDAY, PROPERTIES_PAY_ITEM_IDPAYCODE_OVERTIME, PROPERTIES_PAY_ITEM_IDPAYITEM, PROPERTIES_PAY_ITEM_IDPAYROLLRUN, PROPERTIES_PAY_ITEM_IS_HOLIDAY, PROPERTIES_PAY_ITEM_MEMO, PROPERTIES_PAY_ITEM_OT1, PROPERTIES_PAY_ITEM_OT2, PROPERTIES_PAY_ITEM_PAYROLL_PERIOD_ID, PROPERTIES_PAY_ITEM_QUANTITY_HOLIDAY, PROPERTIES_PAY_ITEM_QUANTITY_HOLIDAY_UNITS, PROPERTIES_PAY_ITEM_QUANTITY_OT, PROPERTIES_PAY_ITEM_QUANTITY_OT_UNITS, PROPERTIES_PAY_ITEM_QUANTITY_REG, PROPERTIES_PAY_ITEM_QUANTITY_REG_UNITS, PROPERTIES_PAY_ITEM_RATE, PROPERTIES_PAY_ITEM_RATE_HOLIDAY, PROPERTIES_PAY_ITEM_RATE_OT, PROPERTIES_PAY_ITEM_REG, PROPERTIES_PAY_ITEM_TYPE)
        SELECT EMPAY_ID AS EMPAY_ID, VISIT_ID AS VISIT_ID, EMPLOYEE_ID AS EMPLOYEE_ID, PAYROLL_PERIOD_ID AS PAYROLL_PERIOD_ID, PAYROLL_RUN_ID AS PAYROLL_RUN_ID, QUANTITY_REG AS QUANTITY_REG, QUANTITY_REG_UNITS AS QUANTITY_REG_UNITS, QUANTITY_OT AS QUANTITY_OT, QUANTITY_OT_UNITS AS QUANTITY_OT_UNITS, QUANTITY_HOLIDAY AS QUANTITY_HOLIDAY, QUANTITY_HOLIDAY_UNITS AS QUANTITY_HOLIDAY_UNITS, REG AS REG, OT1 AS OT1, RATE AS RATE, PAYCODE_ID AS PAYCODE_ID, IDPAYCODE_HOLIDAY AS IDPAYCODE_HOLIDAY, IDPAYCODE_OVERTIME AS IDPAYCODE_OVERTIME, EMPAY_TYPE_MAIN AS EMPAY_TYPE_MAIN, COMPUTED_REGULAR_TOTAL AS COMPUTED_REGULAR_TOTAL, COMPUTED_OT_TOTAL AS COMPUTED_OT_TOTAL, COMPUTED_HOLIDAY_TOTAL AS COMPUTED_HOLIDAY_TOTAL, RUN_TOTAL_COST AS RUN_TOTAL_COST, RUN_TOTAL_HOURS AS RUN_TOTAL_HOURS, RUN_TOTAL_OT_HOURS AS RUN_TOTAL_OT_HOURS, RUN_TOTAL_PREMIUMS AS RUN_TOTAL_PREMIUMS, RUN_TOTAL_REG_HOURS AS RUN_TOTAL_REG_HOURS, RUN_TOTAL_SHIFTS AS RUN_TOTAL_SHIFTS, RUN_IS_DELETED AS RUN_IS_DELETED, RUN_TOTAL_UNAVAILABILITIES AS RUN_TOTAL_UNAVAILABILITIES, RUN_CREATE_TIME AS RUN_CREATE_TIME, RUN_UPDATE_TIME AS RUN_UPDATE_TIME, RUN_DELETE_TIME AS RUN_DELETE_TIME, PERIOD_START_TIME AS PERIOD_START_TIME, PERIOD_END_TIME AS PERIOD_END_TIME,
			PROPERTIES_PAY_RUN:Op::STRING AS PROPERTIES_PAY_RUN_OP, PROPERTIES_PAY_RUN:create_time::STRING AS PROPERTIES_PAY_RUN_CREATE_TIME, PROPERTIES_PAY_RUN:create_user_id::STRING AS PROPERTIES_PAY_RUN_CREATE_USER_ID, PROPERTIES_PAY_RUN:guid::STRING AS PROPERTIES_PAY_RUN_GUID, PROPERTIES_PAY_RUN:id::STRING AS PROPERTIES_PAY_RUN_ID, PROPERTIES_PAY_RUN:id_payroll_period::STRING AS PROPERTIES_PAY_RUN_ID_PAYROLL_PERIOD, PROPERTIES_PAY_RUN:idmasteraccount::STRING AS PROPERTIES_PAY_RUN_IDMASTERACCOUNT, PROPERTIES_PAY_RUN:total_cost::STRING AS PROPERTIES_PAY_RUN_TOTAL_COST, PROPERTIES_PAY_RUN:total_hours::STRING AS PROPERTIES_PAY_RUN_TOTAL_HOURS, PROPERTIES_PAY_RUN:total_ot_hours::STRING AS PROPERTIES_PAY_RUN_TOTAL_OT_HOURS, PROPERTIES_PAY_RUN:total_premiums::STRING AS PROPERTIES_PAY_RUN_TOTAL_PREMIUMS, PROPERTIES_PAY_RUN:total_reg_hours::STRING AS PROPERTIES_PAY_RUN_TOTAL_REG_HOURS, PROPERTIES_PAY_RUN:total_shifts::STRING AS PROPERTIES_PAY_RUN_TOTAL_SHIFTS, PROPERTIES_PAY_RUN:total_unavailabilities::STRING AS PROPERTIES_PAY_RUN_TOTAL_UNAVAILABILITIES, PROPERTIES_PAY_RUN:update_time::STRING AS PROPERTIES_PAY_RUN_UPDATE_TIME, PROPERTIES_PAY_RUN:update_user_id::STRING AS PROPERTIES_PAY_RUN_UPDATE_USER_ID, 
			PROPERTIES_PAY_ITEM:Op::STRING AS PROPERTIES_PAY_ITEM_OP, PROPERTIES_PAY_ITEM:guid_to::STRING AS PROPERTIES_PAY_ITEM_GUID_TO, PROPERTIES_PAY_ITEM:id::STRING AS PROPERTIES_PAY_ITEM_ID, PROPERTIES_PAY_ITEM:idemployee::STRING AS PROPERTIES_PAY_ITEM_IDEMPLOYEE, PROPERTIES_PAY_ITEM:idpaycode_holiday::STRING AS PROPERTIES_PAY_ITEM_IDPAYCODE_HOLIDAY, PROPERTIES_PAY_ITEM:idpaycode_overtime::STRING AS PROPERTIES_PAY_ITEM_IDPAYCODE_OVERTIME, PROPERTIES_PAY_ITEM:idpayitem::STRING AS PROPERTIES_PAY_ITEM_IDPAYITEM, PROPERTIES_PAY_ITEM:idpayrollrun::STRING AS PROPERTIES_PAY_ITEM_IDPAYROLLRUN, PROPERTIES_PAY_ITEM:is_holiday::STRING AS PROPERTIES_PAY_ITEM_IS_HOLIDAY, PROPERTIES_PAY_ITEM:memo::STRING AS PROPERTIES_PAY_ITEM_MEMO, PROPERTIES_PAY_ITEM:ot1::STRING AS PROPERTIES_PAY_ITEM_OT1, PROPERTIES_PAY_ITEM:ot2::STRING AS PROPERTIES_PAY_ITEM_OT2, PROPERTIES_PAY_ITEM:payroll_period_id::STRING AS PROPERTIES_PAY_ITEM_PAYROLL_PERIOD_ID, PROPERTIES_PAY_ITEM:quantity_holiday::STRING AS PROPERTIES_PAY_ITEM_QUANTITY_HOLIDAY, PROPERTIES_PAY_ITEM:quantity_holiday_units::STRING AS PROPERTIES_PAY_ITEM_QUANTITY_HOLIDAY_UNITS, PROPERTIES_PAY_ITEM:quantity_ot::STRING AS PROPERTIES_PAY_ITEM_QUANTITY_OT, PROPERTIES_PAY_ITEM:quantity_ot_units::STRING AS PROPERTIES_PAY_ITEM_QUANTITY_OT_UNITS, PROPERTIES_PAY_ITEM:quantity_reg::STRING AS PROPERTIES_PAY_ITEM_QUANTITY_REG, PROPERTIES_PAY_ITEM:quantity_reg_units::STRING AS PROPERTIES_PAY_ITEM_QUANTITY_REG_UNITS, PROPERTIES_PAY_ITEM:rate::STRING AS PROPERTIES_PAY_ITEM_RATE, PROPERTIES_PAY_ITEM:rate_holiday::STRING AS PROPERTIES_PAY_ITEM_RATE_HOLIDAY, PROPERTIES_PAY_ITEM:rate_ot::STRING AS PROPERTIES_PAY_ITEM_RATE_OT, PROPERTIES_PAY_ITEM:reg::STRING AS PROPERTIES_PAY_ITEM_REG, PROPERTIES_PAY_ITEM:type::STRING AS PROPERTIES_PAY_ITEM_TYPE
        FROM ALAYACARE_${var.SF_ENVIRONMENT}UCTION."5C3EE5FE-45A5-4DA7-A35B-BD7CDAFE3548".SHARED_PAYROLL_ITEM;

	SELECT CONCAT(''Message : '',"number of rows inserted",'' Rows Inserted.'') into :return_result FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));
	return return_result;
END;

 EOT
}

