resource "snowflake_procedure" "DISC_ALAYACARE_GET_DO_NOT_SEND" {
	name ="GET_DO_NOT_SEND"
	database = "DISC_${var.SF_ENVIRONMENT}"
	schema = "ALAYACARE"
	language  = "SQL"
	return_type = "VARCHAR(16777216)"
	execute_as = "OWNER"
	statement = <<-EOT

DECLARE
--*****************************************************************************************************************************
-- NAME:  GET_DO_NOT_SEND 
--
-- PURPOSE: USING THIS SP FOR DISCOVERY TABLE LOAD
--
-- DEVELOPMENT LOG:
-- DATE        		AUTHOR                	NOTES:
-- ----------  		-------------------   	-----------------------------------------------------------------------------------------------
-- 2021-11-11		UNKNOWN					INITIAL DEVELOPMENT
-- 2023-09-05  		RAVI SUTHAR            	MIGRATED JavaScript to SQL
--*****************************************************************************************************************************
    return_result varchar(1000);
BEGIN
	
    INSERT OVERWRITE INTO ALAYACARE.DO_NOT_SEND (
        CLIENT_ID, EMPLOYEE_ID, BLOCK_TYPE, CREATE_DATE, DO_NOT_SEND_REASON, BRANCH_ID,
		PROPERTIES_DO_NOT_SEND_OP, PROPERTIES_DO_NOT_SEND_BLOCKED_GUID, PROPERTIES_DO_NOT_SEND_COMMENTS, PROPERTIES_DO_NOT_SEND_CREATE_TIME, PROPERTIES_DO_NOT_SEND_CREATE_USER_ID, PROPERTIES_DO_NOT_SEND_GUID, PROPERTIES_DO_NOT_SEND_UPDATE_TIME, PROPERTIES_DO_NOT_SEND_UPDATE_USER_ID)
        SELECT CLIENT_ID AS CLIENT_ID, EMPLOYEE_ID AS EMPLOYEE_ID, BLOCK_TYPE AS BLOCK_TYPE, CREATE_DATE AS CREATE_DATE, DO_NOT_SEND_REASON AS DO_NOT_SEND_REASON, BRANCH_ID,
			PROPERTIES_DO_NOT_SEND:Op::STRING AS PROPERTIES_DO_NOT_SEND_OP, PROPERTIES_DO_NOT_SEND:blocked_guid::STRING AS PROPERTIES_DO_NOT_SEND_BLOCKED_GUID, PROPERTIES_DO_NOT_SEND:comments::STRING AS PROPERTIES_DO_NOT_SEND_COMMENTS, PROPERTIES_DO_NOT_SEND:create_time::STRING AS PROPERTIES_DO_NOT_SEND_CREATE_TIME, PROPERTIES_DO_NOT_SEND:create_user_id::STRING AS PROPERTIES_DO_NOT_SEND_CREATE_USER_ID, PROPERTIES_DO_NOT_SEND:guid::STRING AS PROPERTIES_DO_NOT_SEND_GUID, PROPERTIES_DO_NOT_SEND:update_time::STRING AS PROPERTIES_DO_NOT_SEND_UPDATE_TIME, PROPERTIES_DO_NOT_SEND:update_user_id::STRING AS PROPERTIES_DO_NOT_SEND_UPDATE_USER_ID
        FROM ALAYACARE_${var.SF_ENVIRONMENT}UCTION."5C3EE5FE-45A5-4DA7-A35B-BD7CDAFE3548".SHARED_DO_NOT_SEND;

	SELECT CONCAT(''Message : '',"number of rows inserted",'' Rows Inserted.'') into :return_result FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));
	return return_result;
END;

 EOT
}

