resource "snowflake_procedure" "DISC_ALAYACARE_GET_TBL_ACC_INVOICE_TIER_4" {
	name ="GET_TBL_ACC_INVOICE_TIER_4"
	database = "DISC_${var.SF_ENVIRONMENT}"
	schema = "ALAYACARE"
	language  = "SQL"
	return_type = "VARCHAR(16777216)"
	execute_as = "OWNER"
	statement = <<-EOT

DECLARE
--*****************************************************************************************************************************
-- NAME:  GET_TBL_ACC_INVOICE_TIER_4 
--
-- PURPOSE: USING THIS SP FOR DISCOVERY TABLE LOAD
--
-- DEVELOPMENT LOG:
-- DATE        		AUTHOR                	NOTES:
-- ----------  		-------------------   	-----------------------------------------------------------------------------------------------
-- 2021-11-11		UNKNOWN					INITIAL DEVELOPMENT
-- 2023-09-05  		RAVI SUTHAR            	MIGRATED JavaScript to SQL
--*****************************************************************************************************************************
    return_result varchar(1000);
BEGIN
	
INSERT OVERWRITE INTO ALAYACARE.TBL_ACC_INVOICE_TIER_4 
select ID ,PROPERTIES,
PROPERTIES[''Op'']::VARCHAR(100) AS PROPERTIES_OP,
PROPERTIES[''balance'']::VARCHAR(100) AS PROPERTIES_BALANCE,
PROPERTIES[''bill_to'']::VARCHAR AS PROPERTIES_BILL_TO,
PROPERTIES[''bill_to_guid'']::VARCHAR(100) AS PROPERTIES_BILL_TO_GUID,
PROPERTIES[''billed_by_hour'']::VARCHAR(100) AS PROPERTIES_BILLED_BY_HOUR,
PROPERTIES[''billed_by_visit'']::VARCHAR(100) AS PROPERTIES_BILLED_BY_VISIT,
PROPERTIES[''client_premiums_subtotal'']::VARCHAR(100) AS PROPERTIES_CLIENT_PREMIUMS_SUBTOTAL,
PROPERTIES[''create_time'']::VARCHAR(100) AS PROPERTIES_CREATE_TIME,
PROPERTIES[''create_user_id'']::VARCHAR(100) AS PROPERTIES_CREATE_USER_ID,
PROPERTIES[''funder_id'']::VARCHAR(100) AS PROPERTIES_FUNDER_ID,
PROPERTIES[''guid'']::VARCHAR(100) AS PROPERTIES_GUID,
PROPERTIES[''guid_to'']::VARCHAR(100) AS PROPERTIES_GUID_TO,
PROPERTIES[''id'']::VARCHAR(100) AS PROPERTIES_ID,
PROPERTIES[''id_billing_period'']::VARCHAR(100) AS PROPERTIES_ID_BILLING_PERIOD,
PROPERTIES[''idmASteraccount'']::VARCHAR(100) AS PROPERTIES_IDMASTERACCOUNT,
PROPERTIES[''idterm'']::VARCHAR(100) AS PROPERTIES_IDTERM,
PROPERTIES[''income_items_subtotal'']::VARCHAR(100) AS PROPERTIES_INCOME_ITEMS_SUBTOTAL,
PROPERTIES[''invoice_date'']::VARCHAR(100) AS PROPERTIES_INVOICE_DATE,
PROPERTIES[''invoice_number'']::VARCHAR(100) AS PROPERTIES_INVOICE_NUMBER,
PROPERTIES[''invoice_version'']::VARCHAR(100) AS PROPERTIES_INVOICE_VERSION,
PROPERTIES[''invoicing_model'']::VARCHAR(100) AS PROPERTIES_INVOICING_MODEL,
PROPERTIES[''is_ad_hoc'']::VARCHAR(100) AS PROPERTIES_IS_AD_HOC,
PROPERTIES[''master_invoice_id'']::VARCHAR(100) AS PROPERTIES_MASTER_INVOICE_ID,
PROPERTIES[''memo'']::VARCHAR(100) AS PROPERTIES_MEMO,
PROPERTIES[''payor_id'']::VARCHAR(100) AS PROPERTIES_PAYOR_ID,
PROPERTIES[''send_to'']::VARCHAR AS PROPERTIES_SEND_TO,
PROPERTIES[''send_to_guid'']::VARCHAR(100) AS PROPERTIES_SEND_TO_GUID,
PROPERTIES[''service_provided_to'']::VARCHAR AS PROPERTIES_SERVICE_PROVIDED_TO,
PROPERTIES[''service_provided_to_guid'']::VARCHAR(100) AS PROPERTIES_SERVICE_PROVIDED_TO_GUID,
PROPERTIES[''status'']::VARCHAR(100) AS PROPERTIES_STATUS,
PROPERTIES[''subtotal'']::VARCHAR(100) AS PROPERTIES_SUBTOTAL,
PROPERTIES[''supplies_subtotal'']::VARCHAR(100) AS PROPERTIES_SUPPLIES_SUBTOTAL,
PROPERTIES[''total'']::VARCHAR(100) AS PROPERTIES_TOTAL,
PROPERTIES[''total_client_premiums'']::VARCHAR(100) AS PROPERTIES_TOTAL_CLIENT_PREMIUMS,
PROPERTIES[''total_income_items'']::VARCHAR(100) AS PROPERTIES_TOTAL_INCOME_ITEMS,
PROPERTIES[''total_premiums'']::VARCHAR(100) AS PROPERTIES_TOTAL_PREMIUMS,
PROPERTIES[''total_supplies'']::VARCHAR(100) AS PROPERTIES_TOTAL_SUPPLIES,
PROPERTIES[''total_visits'']::VARCHAR(100) AS PROPERTIES_TOTAL_VISITS,
PROPERTIES[''update_time'']::VARCHAR(100) AS PROPERTIES_UPDATE_TIME,
PROPERTIES[''update_user_id'']::VARCHAR(100) PROPERTIES_AS_UPDATE_USER_ID,
PROPERTIES[''visits_and_premiums_subtotal'']::VARCHAR(100) AS PROPERTIES_VISITS_AND_PREMIUMS_SUBTOTAL,
PROPERTIES[''entry_date'']::VARCHAR(100) AS PROPERTIES_ENTRY_DATE,
PROPERTIES[''pdf_url'']::VARCHAR(100) AS PROPERTIES_PDF_URL,
PROPERTIES[''deleted_at'']::VARCHAR(100) AS PROPERTIES_DELETED_AT,
PROPERTIES[''deleted_by'']::VARCHAR(100) AS PROPERTIES_DELETED_BY,
PROPERTIES[''is_deleted'']::VARCHAR(100) AS PROPERTIES_IS_DELETED
from ALAYACARE_${var.SF_ENVIRONMENT}UCTION."5C3EE5FE-45A5-4DA7-A35B-BD7CDAFE3548".SHARED_TBL_ACC_INVOICE_TIER_4;

;

	SELECT CONCAT(''Message : '',"number of rows inserted",'' Rows Inserted.'') into :return_result FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));
	return return_result;
END;

 EOT
}

