resource "snowflake_procedure" "DISC_ALAYACARE_GET_CLAIMS" {
	name ="GET_CLAIMS"
	database = "DISC_${var.SF_ENVIRONMENT}"
	schema = "ALAYACARE"
	language  = "SQL"
	return_type = "VARCHAR(16777216)"
	execute_as = "OWNER"
	statement = <<-EOT

DECLARE
--*****************************************************************************************************************************
-- NAME:  GET_CLAIMS 
--
-- PURPOSE: USING THIS SP FOR DISCOVERY TABLE LOAD
--
-- DEVELOPMENT LOG:
-- DATE        		AUTHOR                	NOTES:
-- ----------  		-------------------   	-----------------------------------------------------------------------------------------------
-- 2021-11-11		UNKNOWN					INITIAL DEVELOPMENT
-- 2023-09-05  		RAVI SUTHAR            	MIGRATED JavaScript to SQL
--*****************************************************************************************************************************
    return_result varchar(1000);
BEGIN
	
    INSERT OVERWRITE INTO ALAYACARE.CLAIMS (
        CLAIM_ID, CLIENT_ID, BILLCODE_ID, FUNDER_ID, VISIT_ID, INVOICE_ID, INTERNAL_CLAIM_NUMBER, INTERNAL_CLAIM_CONTROL_NUMBER, CLAIM_STATUS, IS_PREPARING, IS_OPEN, IS_MARKED_FOR_SUBMISSION, UPDATE_FLOW, SERVICED_AT_DATE, DELAY_REASON_CODE, DENIAL_REASON, QUANTITY, BALANCE, DUE, PAID, CURRENT_STATUS_DATE, BANKING_BALANCE, BANK_USED, BANK_AMOUNT, INVOICE_ITEM_QTY, INVOICE_SENT_DATE, BILLING_INCREMENT, BANK_SUM, VISIT_QTY_HOURS, VISIT_QTY)
        SELECT CLAIM_ID AS CLAIM_ID, CLIENT_ID AS CLIENT_ID, BILLCODE_ID AS BILLCODE_ID, FUNDER_ID AS FUNDER_ID, VISIT_ID AS VISIT_ID, INVOICE_ID AS INVOICE_ID, INTERNAL_CLAIM_NUMBER AS INTERNAL_CLAIM_NUMBER, INTERNAL_CLAIM_CONTROL_NUMBER AS INTERNAL_CLAIM_CONTROL_NUMBER, CLAIM_STATUS AS CLAIM_STATUS, IS_PREPARING AS IS_PREPARING, IS_OPEN AS IS_OPEN, IS_MARKED_FOR_SUBMISSION AS IS_MARKED_FOR_SUBMISSION, UPDATE_FLOW AS UPDATE_FLOW, SERVICED_AT_DATE AS SERVICED_AT_DATE, DELAY_REASON_CODE AS DELAY_REASON_CODE, DENIAL_REASON AS DENIAL_REASON, QUANTITY AS QUANTITY, BALANCE AS BALANCE, DUE AS DUE, PAID AS PAID, CURRENT_STATUS_DATE AS CURRENT_STATUS_DATE, BANKING_BALANCE AS BANKING_BALANCE, BANK_USED AS BANK_USED, BANK_AMOUNT AS BANK_AMOUNT, INVOICE_ITEM_QTY AS INVOICE_ITEM_QTY, INVOICE_SENT_DATE AS INVOICE_SENT_DATE, BILLING_INCREMENT AS BILLING_INCREMENT, BANK_SUM AS BANK_SUM, VISIT_QTY_HOURS AS VISIT_QTY_HOURS, VISIT_QTY AS VISIT_QTY 
        FROM ALAYACARE_${var.SF_ENVIRONMENT}UCTION."5C3EE5FE-45A5-4DA7-A35B-BD7CDAFE3548".SHARED_CLAIMS;

	SELECT CONCAT(''Message : '',"number of rows inserted",'' Rows Inserted.'') into :return_result FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));
	return return_result;
END;

 EOT
}

