resource "snowflake_view" "DW_STAGE_SANDATAIMPORT_DIM_INVOICE_TEMP_VIEW" {
	database = "DW_${var.SF_ENVIRONMENT}"
	schema = "STAGE"
	name = "SANDATAIMPORT_DIM_INVOICE_TEMP_VIEW"
	statement = <<-SQL
	 
WITH CLIENT AS
(
	SELECT * FROM
	(
		SELECT CLIENTID, MASTER_ID,AGENCYID
		FROM DISC_DEDUPE_${var.SF_ENVIRONMENT}.SANDATAIMPORT.CLIENT_MASTER_LIST
        WHERE AGENCYID=8485 
	)
	UNION
	SELECT * FROM
	(
		SELECT DISTINCT CLIENTID, MASTER_ID,AGENCYID
		FROM DISC_DEDUPE_${var.SF_ENVIRONMENT}.SANDATAIMPORT.CLIENT_MATCH_LIST
		WHERE CLIENTID NOT IN (SELECT CLIENTID FROM DISC_DEDUPE_${var.SF_ENVIRONMENT}.SANDATAIMPORT.CLIENT_MASTER_LIST ) 
        AND AGENCYID=8485
	)
)
SELECT
md5(inv.AGENCYID ||'-'|| inv.INVOICENUMBER ||'-'|| 'SANDATAIMPORT') AS OLD_INVOICE_KEY ,

CASE WHEN D.SERVICEID in ('VBPCG') 
		THEN md5('CC_'||inv.AGENCYID ||'-'|| inv.INVOICENUMBER ||'-'|| 'SANDATAIMPORT')
		ELSE md5(inv.AGENCYID ||'-'|| inv.INVOICENUMBER ||'-'|| 'SANDATAIMPORT') END AS NEW_INVOICE_KEY,
inv.AGENCYID AS OLD_SYSTEM_CODE ,

CASE WHEN D.SERVICEID in ('VBPCG')
			THEN 'CC_'||inv.AGENCYID
			ELSE INV.AGENCYID END AS NEW_SYSTEM_CODE

FROM DISC_${var.SF_ENVIRONMENT}.SANDATAIMPORT.SANDATA_INVOICEHEADER inv
LEFT JOIN DISC_${var.SF_ENVIRONMENT}.SANDATAIMPORT.SANDATA_INVOICEDETAILS D ON D.AGENCYID = inv.AGENCYID 
				AND D.INVOICENUMBER = inv.INVOICENUMBER 
LEFT JOIN DISC_${var.SF_ENVIRONMENT}.SANDATAIMPORT.SANDATA_PAYORS pay ON inv.payorid = pay.PAYORID 
				AND inv.BILLCODE = pay.BILLCODE
    			AND inv.AGENCYID = pay.AGENCYID
LEFT JOIN DISC_${var.SF_ENVIRONMENT}.SANDATAIMPORT.SANDATA_CLIENTADMISSIONS ADM
    			ON ADM.AGENCYID = INV.AGENCYID 
    			AND ADM.ADMISSIONID = INV.ADMISSIONID
LEFT JOIN CLIENT CL ON CL.AGENCYID= ADM.AGENCYID AND ADM.CLIENTID = CL.CLIENTID
WHERE inv.AGENCYID = '8485'  AND D.SERVICEID in ('VBPCG')

GROUP BY 
	inv.AGENCYID ,
	D.SERVICEID ,
	CL.AGENCYID ,
	inv.INVOICENUMBER,
	CL.MASTER_ID;
SQL
	or_replace = true 
	is_secure = false 
}

