resource "snowflake_view" "DW_STAGE_VW_CURRENT_SANDATAIMPORT_DIM_INVOICE" {
	database = "DW_${var.SF_ENVIRONMENT}"
	schema = "STAGE"
	name = "VW_CURRENT_SANDATAIMPORT_DIM_INVOICE"
	statement = <<-SQL
	 (
SELECT  INVOICE_KEY 
FROM (
WITH CLIENT AS
(
	SELECT * FROM
	(
		SELECT CLIENTID, MASTER_ID,AGENCYID
		FROM DISC_DEDUPE_${var.SF_ENVIRONMENT}.SANDATAIMPORT.CLIENT_MASTER_LIST
        WHERE AGENCYID=8485 
	)
	UNION
	SELECT * FROM
	(
		SELECT DISTINCT CLIENTID, MASTER_ID,AGENCYID
		FROM DISC_DEDUPE_${var.SF_ENVIRONMENT}.SANDATAIMPORT.CLIENT_MATCH_LIST
		WHERE CLIENTID NOT IN (SELECT CLIENTID FROM DISC_DEDUPE_${var.SF_ENVIRONMENT}.SANDATAIMPORT.CLIENT_MASTER_LIST ) 
        AND AGENCYID=8485
	))
SELECT
CASE WHEN D.SERVICEID IN ('CARECO','VBPCG') 
			THEN md5('CC_'||inv.AGENCYID ||'-'|| inv.INVOICENUMBER ||'-'|| 'SANDATAIMPORT') 
			ELSE md5(inv.AGENCYID ||'-'|| inv.INVOICENUMBER ||'-'|| 'SANDATAIMPORT') END AS INVOICE_KEY --PK
			,D.SERVICEID
FROM DISC_${var.SF_ENVIRONMENT}.SANDATAIMPORT.SANDATA_INVOICEHEADER inv
LEFT JOIN DISC_${var.SF_ENVIRONMENT}.SANDATAIMPORT.SANDATA_INVOICEDETAILS D ON D.AGENCYID = inv.AGENCYID AND D.INVOICENUMBER = inv.INVOICENUMBER 
LEFT JOIN DISC_${var.SF_ENVIRONMENT}.SANDATAIMPORT.SANDATA_PAYORS pay ON inv.payorid = pay.PAYORID AND inv.BILLCODE = pay.BILLCODE
    AND inv.AGENCYID = pay.AGENCYID
LEFT JOIN DISC_${var.SF_ENVIRONMENT}.SANDATAIMPORT.SANDATA_CLIENTADMISSIONS ADM
    ON ADM.AGENCYID = INV.AGENCYID AND ADM.ADMISSIONID = INV.ADMISSIONID
LEFT JOIN CLIENT CL ON CL.AGENCYID= ADM.AGENCYID AND ADM.CLIENTID = CL.CLIENTID
WHERE inv.AGENCYID = '8485' --limit to PA ONLY
AND (inv.ETL_LAST_UPDATED_DATE >= '1900-01-01'
	OR pay.ETL_LAST_UPDATED_DATE >= '1900-01-01') ) T GROUP BY invoice_key);
SQL
	or_replace = true 
	is_secure = false 
}

