resource "snowflake_view" "DW_STAGE_VW_CURRENT_CCSI_DIM_BRANCH" {
	database = "DW_${var.SF_ENVIRONMENT}"
	schema = "STAGE"
	name = "VW_CURRENT_CCSI_DIM_BRANCH"
	statement = <<-SQL
	 
WITH OFFICE_NUMBER AS 
(
	SELECT  B.BRANCH_CODE,
	CASE WHEN B.BRANCH_CODE IN ('CEN') THEN 236
	 WHEN B.BRANCH_CODE IN ('CHI') THEN 244
	 WHEN B.BRANCH_CODE IN ('ESL') THEN 375
	 WHEN B.BRANCH_CODE IN ('FAI') THEN 324
	 WHEN B.BRANCH_CODE IN ('GRV') THEN 478
	 WHEN B.BRANCH_CODE IN ('HAR') THEN 427
	 WHEN B.BRANCH_CODE IN ('JLT') THEN 558
	 WHEN B.BRANCH_CODE IN ('OAK') THEN 625
	 WHEN B.BRANCH_CODE IN ('PIT') THEN 748
	 WHEN B.BRANCH_CODE IN ('QUY') THEN 789
	 WHEN B.BRANCH_CODE IN ('ROC') THEN 762
	 WHEN B.BRANCH_CODE IN ('SPI') THEN 774
	 WHEN B.BRANCH_CODE IN ('VLG') THEN 854
ELSE NULL
END AS OFFICE_NUMBER
FROM DISC_${var.SF_ENVIRONMENT}.CCSI.BRANCH_MAPPING B
)
, MANAGER AS 
(
	SELECT B.BRANCH_CODE, CASE WHEN B.BRANCH_CODE IN ('CEN') THEN 'CHERRI HILTIBIDAL'
	 WHEN B.BRANCH_CODE IN ('CHI') THEN 'SAMANTHA DAVIES'
	 WHEN B.BRANCH_CODE IN ('ESL') THEN 'BETH LOYD'
	 WHEN B.BRANCH_CODE IN ('FAI') THEN 'GEORGIA JOHNSTON'
	 WHEN B.BRANCH_CODE IN ('GRV') THEN 'CHERYL COOL'
	 WHEN B.BRANCH_CODE IN ('HAR') THEN 'VIVIAN DICKERSON'
	 WHEN B.BRANCH_CODE IN ('JLT') THEN 'DONNA KOLOFA'
	 WHEN B.BRANCH_CODE IN ('OAK') THEN 'TONYA RUSH'
 	 WHEN B.BRANCH_CODE IN ('PIT') THEN 'KRISTEN CROSSMAN'
	 WHEN B.BRANCH_CODE IN ('QUY') THEN 'LAURY CLARK'
	 WHEN B.BRANCH_CODE IN ('ROC') THEN 'RUTH MORRISON'
	 WHEN B.BRANCH_CODE IN ('SPI') THEN 'TANYA BOYER'
	 WHEN B.BRANCH_CODE IN ('VLG') THEN 'STACEY DALZELL'
	 ELSE NULL
END AS MANAGER
FROM DISC_${var.SF_ENVIRONMENT}.CCSI.BRANCH_MAPPING B
)
SELECT 
MD5('CCSI' || '-' || B.BRANCH_CODE || '-' || 'CCSI') AS BRANCH_KEY         
FROM DISC_${var.SF_ENVIRONMENT}.CCSI.BRANCH_MAPPING B
LEFT JOIN OFFICE_NUMBER N ON N.BRANCH_CODE = B.BRANCH_CODE
LEFT JOIN MANAGER M ON M.BRANCH_CODE = B.BRANCH_CODE;
SQL
	or_replace = true 
	is_secure = false 
}

