resource "snowflake_view" "DW_STAGE_VW_CURRENT_SANDATAIMPORT_FACT_VISIT_EXCEPTION" {
	database = "DW_${var.SF_ENVIRONMENT}"
	schema = "STAGE"
	name = "VW_CURRENT_SANDATAIMPORT_FACT_VISIT_EXCEPTION"
	statement = <<-SQL
	 WITH VISITS_WITH_EXCEPTIONS AS (
	SELECT
		VISITS.AGENCYID,
		VISITS.SCHEDULEID,
		VISITS.SCHEDULEDATE::TIMESTAMP_NTZ AS SCHEDULEDATE,
		TRIM(exc.value)::STRING AS EXCEPTION_CODE,
		NULLIF(TRIM(VISITS.REASONCODE),'') AS REASON_CODE, 
		NULLIF(TRIM(VISITS.RESOLUTIONCODE),'') AS RESOLUTION_CODE -- Bring Resolution description AFTER response FROM sandata
	FROM
		DISC_${var.SF_ENVIRONMENT}.SANDATAIMPORT.SANDATA_SCHEDULES VISITS
	,LATERAL FLATTEN(input => SPLIT(VISITS.EXCEPTIONCODE, '|')) exc 
	WHERE 
		NULLIF(EXCEPTION_CODE,'') IS NOT NULL AND TRIM(EXCEPTIONCODE) <> '0' AND TRIM(VISITS.AGENCYID) IN ('8485')
	GROUP BY
		VISITS.AGENCYID, VISITS.SCHEDULEID, VISITS.SCHEDULEDATE, EXCEPTION_CODE, VISITS.REASONCODE, VISITS.RESOLUTIONCODE
	ORDER BY
		VISITS.SCHEDULEDATE
)
, EXCEPTIONS_1 AS
(
	SELECT
		MD5(SV.AGENCYID || '-' || SV.SCHEDULEID || '-' || SCH.EXCEPTION_CODE || '-' || 'SANDATAIMPORT') AS VISIT_EXCEPTION_KEY
	FROM
		VISITS_WITH_EXCEPTIONS SCH
	INNER JOIN
		DISC_${var.SF_ENVIRONMENT}.BI_REPOSITORY.SANDATAVISITS SV
		ON SV.AGENCYID = SCH.AGENCYID
			AND SV.SCHEDULEID = SCH.SCHEDULEID
	LEFT JOIN 
		DISC_${var.SF_ENVIRONMENT}.SANDATAIMPORT.SANDATA_EXTERNALREASONCODES ERC 
		ON ERC.AGENCYID = SCH.AGENCYID
			AND ERC.CODE = SCH.REASON_CODE
	LEFT JOIN 
		DISC_${var.SF_ENVIRONMENT}.SANDATAIMPORT.SANDATA_MANUAL_EXTERNALRESOLUTIONCODES MERC 
		ON MERC.AGENCYID = SCH.AGENCYID
			AND MERC.CODE = SCH.RESOLUTION_CODE
	WHERE SV.AGENCYID = '8485' AND 
		NVL(SV.STAFFAGENCYID,'') <> '' AND SV.CLIENTID IS NOT NULL
			AND NVL(SV.ADMISSIONTYPE, '') <> '' AND LEN(NVL(SV.STATUS,'')) <= 2 -- Exclude (7) bad data records
)
, EXCEPTIONS_2 AS
(
	SELECT
		MD5(SV.AGENCYID || '-' || SV.SCHEDULEID || '-' || SCH.EXCEPTION_CODE || '-' || 'SANDATAIMPORT') AS VISIT_EXCEPTION_KEY
	FROM
		VISITS_WITH_EXCEPTIONS SCH
	INNER JOIN
		DISC_${var.SF_ENVIRONMENT}.SANDATAIMPORT.SANDATA_VISITS SV
		ON SV.AGENCYID = SCH.AGENCYID
			AND SV.SCHEDULEID = SCH.SCHEDULEID
	LEFT JOIN 
		DISC_${var.SF_ENVIRONMENT}.SANDATAIMPORT.SANDATA_EXTERNALREASONCODES ERC 
		ON ERC.AGENCYID = SCH.AGENCYID
			AND ERC.CODE = SCH.REASON_CODE
	LEFT JOIN 
		DISC_${var.SF_ENVIRONMENT}.SANDATAIMPORT.SANDATA_MANUAL_EXTERNALRESOLUTIONCODES MERC 
		ON MERC.AGENCYID = SCH.AGENCYID
			AND MERC.CODE = SCH.RESOLUTION_CODE
	WHERE SV.AGENCYID = '8485' --AND SV.ADJUSTEDTIMEOUT IS NOT NULL
		AND SV.STAFFAGENCYID <> ''
)
SELECT
	DATA.VISIT_EXCEPTION_KEY
FROM
	EXCEPTIONS_1 DATA
UNION
SELECT
	DATA.VISIT_EXCEPTION_KEY
FROM
	EXCEPTIONS_2 DATA;
SQL
	or_replace = true 
	is_secure = false 
}

