resource "snowflake_view" "DW_STAGE_VW_CURRENT_CCSI_DIM_INVOICE" {
	database = "DW_${var.SF_ENVIRONMENT}"
	schema = "STAGE"
	name = "VW_CURRENT_CCSI_DIM_INVOICE"
	statement = <<-SQL
	 
WITH DIM_CLIENT AS
(  
SELECT CLIENT_IDOA_NO,USED_FOR_AREA,MASTER_ID FROM (SELECT CLIENT_IDOA_NO ,USED_FOR_AREA,
(RECORD_NUMBER  || '-' ||  NVL(USED_FOR_AREA, 'CCSI') || '-' || 'CCSI') AS MASTER_ID,'MASTER' AS TYPE,
ROW_NUMBER () OVER (PARTITION BY CLIENT_IDOA_NO ,USED_FOR_AREA ORDER BY TRY_TO_DATE(UPDATED_DATE,'MM/DD/YY') DESC
,TRY_TO_DATE(CREATED_DATE,'MM/DD/YY') DESC,TRY_TO_DATE(ACTION_DATE,'YYYYMMDD') DESC,RECORD_NUMBER DESC) AS RN
FROM DISC_DEDUPE_${var.SF_ENVIRONMENT}.CCSI.CLIENT_MASTER_LIST_CCSI) WHERE RN=1
UNION
SELECT CLIENT_IDOA_NO,USED_FOR_AREA,MASTER_ID FROM (SELECT CLIENT_IDOA_NO,USED_FOR_AREA,
(MASTER_ID) AS MASTER_ID,'MATCH' AS TYPE,
ROW_NUMBER() OVER (PARTITION BY CLIENT_IDOA_NO ,USED_FOR_AREA ORDER BY TRY_TO_DATE(UPDATED_DATE,'MM/DD/YY') DESC
,TRY_TO_DATE(CREATED_DATE,'MM/DD/YY') DESC,TRY_TO_DATE(ACTION_DATE,'YYYYMMDD') DESC,RECORD_NUMBER DESC) AS RN 
FROM (SELECT * FROM DISC_DEDUPE_${var.SF_ENVIRONMENT}.CCSI.CLIENT_MATCH_LIST_CCSI M WHERE NOT EXISTS (SELECT * FROM
DISC_DEDUPE_${var.SF_ENVIRONMENT}.CCSI.CLIENT_MASTER_LIST_CCSI MA WHERE M.CLIENT_IDOA_NO= MA.CLIENT_IDOA_NO AND 
M.USED_FOR_AREA = MA.USED_FOR_AREA)))
)
SELECT DISTINCT
	MD5(MIN(RECORD_NUMBER)|| '-' || 'MCOINV' || '-' || 'CCSI') AS INVOICE_KEY,
	MD5(C.MASTER_ID) AS CLIENT_KEY,
	CASE WHEN LENGTH(SERVICE_MONTH)>6 THEN LEFT(TRIM(REGEXP_REPLACE(SERVICE_MONTH,'\\-|\\(|\\/|\\ |[a-zA-z.]','')),6)
	ELSE TRIM(REGEXP_REPLACE(SERVICE_MONTH,'\\-|\\(|\\/|\\ |[a-zA-z.]','')) END AS PERIOD,
	MD5('CCSI' || '-' || B.BRANCH_CODE || '-' || 'CCSI') AS BRANCH_KEY
    FROM DISC_${var.SF_ENVIRONMENT}.CCSI.MCOINV AS M
    LEFT JOIN DISC_${var.SF_ENVIRONMENT}.CCSI.BRANCH_MAPPING B ON M.CCSI_OFFICE = B.BRANCH_CODE 
    JOIN DIM_CLIENT C ON C.CLIENT_IDOA_NO = M.CLIENT_ID AND M.CCSI_OFFICE = C.USED_FOR_AREA 
    GROUP BY 2,3,4
UNION
SELECT DISTINCT
	MD5(MIN(RECORD_NUMBER)|| '-' || 'OTHERINV' || '-' || 'CCSI') AS INVOICE_KEY,
	MD5(C.MASTER_ID) AS CLIENT_KEY,
	CASE WHEN LENGTH(O.DATE_OF_SERVICE)>6 THEN LEFT(TRIM(REGEXP_REPLACE(O.DATE_OF_SERVICE,'\\-|\\(|\\/|\\ |[a-zA-z.]','')),6)
	ELSE TRIM(REGEXP_REPLACE(O.DATE_OF_SERVICE,'\\-|\\(|\\/|\\ |[a-zA-z.]','')) END AS PERIOD,
	MD5('CCSI' || '-' || B.BRANCH_CODE || '-' || 'CCSI') AS BRANCH_KEY
    FROM DISC_${var.SF_ENVIRONMENT}.CCSI.OTHERINV AS O
    LEFT JOIN DISC_${var.SF_ENVIRONMENT}.CCSI.BRANCH_MAPPING B ON O.AREA = B.BRANCH_CODE 
    JOIN DIM_CLIENT C ON C.CLIENT_IDOA_NO = O.CLIENT_ID AND O.AREA = C.USED_FOR_AREA
    GROUP BY 2,3,4;
SQL
	or_replace = true 
	is_secure = false 
}

