resource "snowflake_view" "DW_STAGE_VW_CURRENT_DELETED_MATRIXCARE_FACT_VISIT" {
	database = "DW_${var.SF_ENVIRONMENT}"
	schema = "STAGE"
	name = "VW_CURRENT_DELETED_MATRIXCARE_FACT_VISIT"
	statement = <<-SQL
	 
WITH SCHEDULE_PAYERS AS
	(
SELECT DISTINCT SCHCP_SCHEDULEID
	,FIRST_VALUE(SCHCP_PAYERID) OVER (PARTITION BY SCHCP_SCHEDULEID ORDER BY SCHCP_SEQNO DESC) SCHCP_PAYERID
	,FIRST_VALUE(COALESCE(ETL_LAST_UPDATED_DATE, '1/1/1900')) OVER (PARTITION BY SCHCP_SCHEDULEID ORDER BY SCHCP_SEQNO DESC) ETL_LAST_UPDATED_DATE
	FROM DISC_${var.SF_ENVIRONMENT}.MATRIXCARE.STVHC_T_SCHEDULEPAYERS 
	)
, CLIENT_PAYERS AS
	(
		SELECT DISTINCT CLIPAY_CLIENTID
		,FIRST_VALUE(CLIPAY_PAYERID) OVER (PARTITION BY CLIPAY_CLIENTID ORDER BY CLIPAY_SEQNO DESC) CLIPAY_PAYERID
		,FIRST_VALUE(COALESCE(ETL_LAST_UPDATED_DATE, '1/1/1900')) OVER (PARTITION BY CLIPAY_CLIENTID ORDER BY CLIPAY_SEQNO DESC) ETL_LAST_UPDATED_DATE
		FROM DISC_${var.SF_ENVIRONMENT}.MATRIXCARE.STVHC_T_CLIENTPAYERS 
	)
, PAYER_BRANCH AS
		 (
			 SELECT  DISTINCT PAYBR_BRANCH_ID 
			,FIRST_VALUE(PAYBR_PAYERID) OVER (PARTITION BY PAYBR_BRANCH_ID ORDER BY PAYBR_CREATEDDATE DESC) PAYBR_PAYERID
			,FIRST_VALUE(COALESCE(ETL_LAST_UPDATED_DATE, '1/1/1900')) OVER (PARTITION BY PAYBR_BRANCH_ID ORDER BY PAYBR_CREATEDDATE DESC) ETL_LAST_UPDATED_DATE
			FROM DISC_${var.SF_ENVIRONMENT}.MATRIXCARE.STVHC_T_PAYERBRANCHES 
		) 	
,ADM_AUTH AS 
		( 
		 SELECT DISTINCT ADM.ADM_ID ,ADM.ADM_SUPERVISORID ,ADM.ADM_COORDINATORID ,ADM.ADM_INTERNALCASEMGRID ,AUTH_PAYERID,
		 AUTH_BEGINDATE, AUTH_ENDDATE ,AUTH_SERVICECODEID 
		 FROM DISC_${var.SF_ENVIRONMENT}.MATRIXCARE.STVHC_T_ADMISSIONS ADM 
		 LEFT JOIN DISC_${var.SF_ENVIRONMENT}.MATRIXCARE.STVHC_T_AUTHORIZATION AUTH ON ADM.ADM_ID =AUTH_ADMISSIONID
		)	
, INVOICE_PAYERS AS
	(	
		SELECT DISTINCT INVD_SCHEDULEID
		,FIRST_VALUE(INVD_SCHEDULEPAYERID) OVER(PARTITION BY INVD_SCHEDULEID ORDER BY INVH_INVOICEDATE DESC) INV_PAYERID
		,FIRST_VALUE(INH.ETL_LAST_UPDATED_DATE) OVER(PARTITION BY INVD_SCHEDULEID ORDER BY INVH_INVOICEDATE DESC) ETL_LAST_UPDATED_DATE
		FROM DISC_${var.SF_ENVIRONMENT}.MATRIXCARE.STVHC_T_INVOICEHEADER INH 
	 	JOIN  DISC_${var.SF_ENVIRONMENT}.MATRIXCARE.STVHC_T_INVOICEDETAILS IND ON INH.INVH_ID = IND.INVD_INVHID 
	)
, BILL_RATES AS
	(
		SELECT * FROM 
		(
		SELECT SCHEDULEID,starttime, endtime, unittype,units,actualrate
		,ROW_NUMBER() OVER (PARTITION  BY SCHEDULEID ORDER BY RBS_ID DESC) AS ROWRBS_ID 
		,MAX(COALESCE(ETL_LAST_UPDATED_DATE, '1/1/1900')) OVER (PARTITION  BY SCHEDULEID ORDER BY RBS_ID DESC)  ETL_LAST_UPDATED_DATE
		FROM DISC_${var.SF_ENVIRONMENT}.MATRIXCARE.STVHC_T_RATEBILLSHIFTS 
		) WHERE ROWRBS_ID =1
	)
SELECT DISTINCT
	MD5('MATRIXCARE' || '-' || SCH_ID || '-' || 'MATRIXCARE') AS VISIT_KEY
FROM DISC_${var.SF_ENVIRONMENT}.MATRIXCARE.HIST_STVHC_T_SCHEDULES AS SCH
LEFT JOIN DISC_${var.SF_ENVIRONMENT}.MATRIXCARE.STVHC_T_SCHEDULESTATUS AS SCHSTATUS ON SCH.SCH_SCHEDULESTATUSID = SCHSTATUS.SCHST_ID 
LEFT JOIN DISC_${var.SF_ENVIRONMENT}.MATRIXCARE.STVHC_T_CAREGIVER AS CARE ON CARE.CAR_ID = SCH.SCH_CAREGIVERID
LEFT JOIN DISC_${var.SF_ENVIRONMENT}.MATRIXCARE.MATRIXCARE_MASTER_EMPLOYEE_MAPPING_ALL AS EMPLOYEE_MAPPING ON EMPLOYEE_MAPPING.EMPLOYEE_NUMBER = SCH.SCH_CAREGIVERID 
LEFT JOIN DISC_${var.SF_ENVIRONMENT}.MATRIXCARE.MATRIXCARE_MASTER_CLIENT_MAPPING_ALL AS CLIENT_MAPPING ON CLIENT_MAPPING.CLIENT_NUMBER = SCH.SCH_CLIENTID 
LEFT JOIN BILL_RATES BR ON BR.SCHEDULEID = SCH.SCH_ID
LEFT JOIN DISC_${var.SF_ENVIRONMENT}.MATRIXCARE.STVHC_T_BRANCHES AS BRANCH ON BRANCH.BR_ID = SCH.SCH_BRANCHID 
LEFT JOIN DISC_${var.SF_ENVIRONMENT}.MATRIXCARE.MATRIXCARE_MASTER_BRANCH_MAPPING BRANCH_MAPPING ON BRANCH_MAPPING.OFFICE_CODE = SCH.SCH_BRANCHID::STRING AND BRANCH_MAPPING.SOURCE_SYSTEM_ID = 7 AND BRANCH_MAPPING.SYSTEM_CODE = 'MATRIXCARE' 
LEFT JOIN SCHEDULE_PAYERS AS SCHPAYER ON SCH.SCH_ID = SCHPAYER.SCHCP_SCHEDULEID
LEFT JOIN CLIENT_PAYERS CP ON SCH.SCH_CLIENTID = CP.CLIPAY_CLIENTID 
LEFT JOIN PAYER_BRANCH PB ON PB.PAYBR_BRANCH_ID = SCH.SCH_BRANCHID 
LEFT JOIN INVOICE_PAYERS INV ON INV.INVD_SCHEDULEID = SCH.SCH_ID
LEFT JOIN ADM_AUTH ADM ON ADM.ADM_ID = SCH.SCH_ADMISSIONID AND TO_DATE(SCH.SCH_STARTTIME) BETWEEN ADM.AUTH_BEGINDATE 
AND ADM.AUTH_ENDDATE AND SCH.SCH_SERVICECODEID = ADM.AUTH_SERVICECODEID	AND 
COALESCE (SCHPAYER.SCHCP_PAYERID,CP.CLIPAY_PAYERID,INV.INV_PAYERID,PB.PAYBR_PAYERID) = ADM.AUTH_PAYERID
WHERE SCH.ETL_DELETED_FLAG = 1 AND SCH.ETL_LAST_UPDATED_DATE::DATE IN (SELECT MAX(ETL_LAST_UPDATED_DATE)::DATE FROM DISC_${var.SF_ENVIRONMENT}.MATRIXCARE.HIST_STVHC_T_SCHEDULES );
SQL
	or_replace = true 
	is_secure = false 
}

