resource "snowflake_view" "DW_STAGE_VW_CURRENT_PAYLOCITY_DIM_EMPLOYEE" {
	database = "DW_${var.SF_ENVIRONMENT}"
	schema = "STAGE"
	name = "VW_CURRENT_PAYLOCITY_DIM_EMPLOYEE"
	statement = <<-SQL
	 WITH EMPLOYEE_CHECK_DATE AS 
(
SELECT
		COMPANYID,
		EMPLOYEEID AS EMPLOYEE_ID,
		MIN(CHECKDATE) AS FIRST_CHECK_DATE,
		MAX(CHECKDATE) AS LAST_CHECK_DATE
FROM
		DISC_${var.SF_ENVIRONMENT}.PAYLOCITY.PAY_STATEMENT_SUMMARY
GROUP BY
		COMPANYID,
		EMPLOYEEID
)
SELECT
	DISTINCT
MD5(ED.COMPANYID || '-' || TRIM(EMPLOYEEID) || '-' || ' PAYLOCITY') AS EMPLOYEE_KEY
FROM DISC_DEDUPE_${var.SF_ENVIRONMENT}.PAYLOCITY.EMPLOYEE_MASTER_LIST AS ED;
SQL
	or_replace = true 
	is_secure = false 
}

