resource "snowflake_view" "DW_STAGE_VW_CURRENT_DELETED_SANDATAIMPORT_DIM_CONTRACT" {
	database = "DW_${var.SF_ENVIRONMENT}"
	schema = "STAGE"
	name = "VW_CURRENT_DELETED_SANDATAIMPORT_DIM_CONTRACT"
	statement = <<-SQL
	 WITH MAPPING AS (
    SELECT DISTINCT
		CA.ADMISSIONTYPE AS CONTRACT_CODE,
		CA.AGENCYID AS SYSTEM_CODE,
		COALESCE(M.CONTRACT_NAME, 'Unknown') AS CONTRACT_NAME,
		COALESCE(M.REVENUE_CATEGORY, 'HC') AS REVENUE_CATEGORY,
		COALESCE(M.REVENUE_SUBCATEGORY_CODE, 'HC') AS REVENUE_SUBCATEGORY_CODE,
		COALESCE(M.REVENUE_SUBCATEGORY_NAME, 'HOME CARE') AS REVENUE_SUBCATEGORY_NAME,
		COALESCE(M.BILLABLE_FLAG, TRUE) AS BILLABLE_FLAG,
		COALESCE(M.PAYABLE_FLAG, TRUE) AS PAYABLE_FLAG,
		COALESCE(M.MILEAGE_FLAG, FALSE) AS MILEAGE_FLAG,
		CASE WHEN SANDATA_ADMSN.SERVICEID IN ('CARECO','VBPCG')
			THEN 'CARECO'
			ELSE NULL END AS SERVICE
    FROM DISC_${var.SF_ENVIRONMENT}.SANDATAIMPORT.HIST_SANDATA_CLIENTADMISSIONS CA
    LEFT JOIN HAH.FACT_REVENUE_SUBCATEGORY_CONTRACT_MAPPING M
    	ON M.SOURCE_SYSTEM_ID = 4 AND M.SYSTEM_CODE = CA.AGENCYID AND M.CONTRACT_CODE = CA.ADMISSIONTYPE
    LEFT JOIN DISC_${var.SF_ENVIRONMENT}.SANDATAIMPORT.SANDATA_ADMISSIONSERVICES SANDATA_ADMSN 
    	ON SANDATA_ADMSN.ADMISSIONID = CA.ADMISSIONID
	WHERE CA.AGENCYID = '8485'
		AND (CA.ETL_DELETED_FLAG = TRUE AND CAST(CA.ETL_LAST_UPDATED_DATE AS DATE) IN (SELECT CAST(MAX(ETL_LAST_UPDATED_DATE) AS DATE) FROM DISC_${var.SF_ENVIRONMENT}.SANDATAIMPORT.HIST_SANDATA_CLIENTADMISSIONS)) 
)
SELECT
CASE WHEN SERVICE IN ('CARECO')
	THEN md5('CC_'||C.SYSTEM_CODE || '-' || C.CONTRACT_CODE || '-'  ||  'SANDATAIMPORT')
	ELSE md5(C.SYSTEM_CODE || '-' || C.CONTRACT_CODE || '-'  ||  'SANDATAIMPORT')
	END AS CONTRACT_KEY
FROM MAPPING AS C;
SQL
	or_replace = true 
	is_secure = false 
}

