resource "snowflake_procedure" "DW_INTEGRATION_DIM_CLIENT_MERGED_POSTPROCESSING" {
	name ="DIM_CLIENT_MERGED_POSTPROCESSING"
	database = "DW_${var.SF_ENVIRONMENT}"
	schema = "INTEGRATION"
	language  = "SQL"

	arguments {
		name = "STR_ETL_TASK_KEY"
		type = "VARCHAR(16777216)"
}	

	arguments {
		name = "STR_CDC_START"
		type = "VARCHAR(16777216)"
}	

	arguments {
		name = "STR_CDC_END"
		type = "VARCHAR(16777216)"
}	
	return_type = "VARCHAR(16777216)"
	execute_as = "OWNER"
	statement = <<-EOT

DECLARE
    return_result varchar(1000);
BEGIN

--*****************************************************************************************************************************
-- NAME:  DIM_CLIENT_MERGED_POSTPROCESSING
--
-- PURPOSE: Creates one row per client 
--
-- DEVELOPMENT LOG:
-- DATE        AUTHOR                NOTES:
-- --------    -------------------   -----------------------------------------------------------------------------------------------
-- 		  					        Initial development
-- 01/23/2023  DIYA MISTRY          Leveraged dedupe for PRIME(OH)
-- 01/25/2023  DIYA MISTRY          Leveraged dedupe for OSHAH,OPENSYSTEM AND 8485(SANDATA)
-- 01/26/2023  DIYA MISTRY          Leveraged dedupe for OSHAH - DE and OPENSYSTEMS - DE
-- 03/14/2023  DIYA MISTRY			REMOVED DEVERO(15)
-- 06/05/2023  DEEPEN GAJJAR        ADDED REFERRALS FIELD
-- 07/24/2023  deepen gajjar        added referral key field
-- 09/04/2023  jigar prajapati      remove MS and added from dedupe table
-- 10/18/2023  deepen gajjar		added client_status field.
-- 11/09/2023  deepen gajjar        addded hispanic_or_latino field
-- 11/21/2023  deepen gajjar        added discharged_reason field
--*****************************************************************************************************************************
INSERT OVERWRITE INTO DW_${var.SF_ENVIRONMENT}.INTEGRATION.DIM_CLIENT_MERGED
WITH CLIENT_DEDUPE AS
(SELECT * FROM DW_${var.SF_ENVIRONMENT}.INTEGRATION.DIM_CLIENT_MERGED_DEDUPE
), CLIENTS AS (
SELECT * FROM DW_${var.SF_ENVIRONMENT}.INTEGRATION.VW_DIM_CLIENT_MERGED WHERE SOURCE_SYSTEM_ID NOT IN (''13'',''14'',''16'')
AND SYSTEM_CODE NOT IN (''OPENSYSTEMS - PA'',''OSHAH - PA'',''8485'')
AND SYSTEM_CODE NOT IN (''OPENSYSTEMS - DE'',''OSHAH - DE'')
AND SYSTEM_CODE NOT IN (''OSHAH - MS'')
AND NOT(
(SOURCE_SYSTEM_ID = 3 AND SYSTEM_CODE IN (''GA'', ''AL'',''MS'')) OR
(SOURCE_SYSTEM_ID IN (1,2)) OR
(SOURCE_SYSTEM_ID = 9 AND SYSTEM_CODE IN (''ALABAMA (3554)'', ''GEORGIA (1002)'')))
AND ORIGINAL_CLIENT_KEY NOT IN (SELECT ORIGINAL_CLIENT_KEY FROM CLIENT_DEDUPE)
UNION
SELECT * FROM CLIENT_DEDUPE
)
SELECT 
MER.ORIGINAL_CLIENT_KEY,
MER.ORIGINAL_SOURCE_SYSTEM_ID,
MER.ORIGINAL_SYSTEM_CODE,
MER.ORIGINAL_CLIENT_NUMBER,
MER.ORIGINAL_AGENCY,
MER.CLIENT_KEY,
MER.CLIENT_NUMBER,
MER.SYSTEM_CODE,
MER.SOURCE_SYSTEM_ID,
MER.CLIENT_PID,
MER.CLIENT_DOB,
MER.CLIENT_DATE_OF_DEATH,
MER.CLIENT_GENDER,
MER.CLIENT_ETHNICITY,
C.HISPANIC_OR_LATINO,
MER.CLIENT_MARITAL_STATUS,
MER.CLIENT_SALUTATION,
MER.CLIENT_FIRST_NAME,
MER.CLIENT_MIDDLE_NAME,
MER.CLIENT_LAST_NAME,
MER.CLIENT_NAME,
MER.CLIENT_ADDRESS1,
MER.CLIENT_ADDRESS2,
MER.CLIENT_CITY,
MER.CLIENT_STATE_CODE,
MER.CLIENT_ZIP,
MER.CLIENT_CLN_ADDRESS1,
MER.CLIENT_CLN_ADDRESS2,
MER.CLIENT_CLN_CITY,
MER.CLIENT_CLN_STATE_CODE,
MER.CLIENT_CLN_ZIP,
MER.CLIENT_STD_ADDRESS1,
MER.CLIENT_STD_ADDRESS2,
MER.CLIENT_STD_CITY,
MER.CLIENT_STD_STATE_CODE,
MER.CLIENT_STD_ZIP,
MER.CLIENT_HOME_PHONE,
MER.CLIENT_CELL_PHONE,
MER.CLIENT_WORK_PHONE,
MER.CLIENT_FAX_NUMBER,
MER.CLIENT_PERSONAL_EMAIL,
MER.REFERRAL_DATE,
MER.DAYS_TO_SERVICE,
MER.CONTRACT_BEGIN_DATE,
MER.CONTRACT_END_DATE,
MER.FIRST_SERVICE_DATE,
MER.LAST_SERVICE_DATE,
MER.BEGIN_DATE,
MER.END_DATE,
MER.ACTIVE_CLIENT_FLAG,
C.CLIENT_STATUS,
c.DISCHARGE_REASON,
MER.ON_HOLD_FLAG,
MER.ON_HOLD_START_DATE,
MER.ON_HOLD_END_DATE,
MER.LINKED_ID,
MER.ACQUIRED_FROM_COMPANY_KEY,
MER.ACQUIRED_FROM_COMPANY_ID,
MER.ACQUIRED_FROM_COMPANY_FULL_NAME,
MER.ACQUISITION_DATE,
MER.ACQUISITION_FLAG,
MER.ADMISSION_DATE,
MER.ADMISSION_FLAG,
MER.CLIENT_CONVERTED_FLAG,
MER.PRIMARY_SUPERVISOR_KEY,
MER.PRIMARY_SUPERVISOR_CODE,
MER.PRIMARY_SUPERVISOR_NAME,
MER.SECONDARY_SUPERVISOR_KEY,
MER.SECONDARY_SUPERVISOR_CODE,
MER.SECONDARY_SUPERVISOR_NAME,
MER.PRIMARY_BRANCH_KEY,
MER.PRIMARY_BRANCH_NAME,
MER.PRIMARY_BRANCH_STATE,
MER.GUARANTOR_NAME,
MER.NOTES,
MER.AGENCY,
r.REFERRER_NAME,
c.REFERRER_KEY,
MER.MEDICAID_ID,
MER.EFFECTIVE_FROM_DATE,
MER.EFFECTIVE_TO_DATE,
MER.ETL_TASK_KEY,
MER.ETL_INSERTED_TASK_KEY,
MER.ETL_INSERTED_DATE,
MER.ETL_INSERTED_BY,
MER.ETL_LAST_UPDATED_DATE,
MER.ETL_LAST_UPDATED_BY,
MER.ETL_DELETED_FLAG,
MER.ETL_INFERRED_MEMBER_FLAG,
MER.DERIVED_REFERRAL_DATE,
MER.DERIVED_CONTRACT_BEGIN_DATE,
MER.DERIVED_CONTRACT_END_DATE,
MER.DERIVED_FIRST_SERVICE_DATE,
MER.DERIVED_LAST_SERVICE_DATE,
MER.DERIVED_BEGIN_DATE,
MER.DERIVED_END_DATE,
MER.DERIVED_DAYS_TO_SERVICE
FROM CLIENTS MER
LEFT JOIN HAH.DIM_CLIENT c ON mer.client_key = c.CLIENT_KEY
LEFT JOIN HAH.DIM_REFERRER R ON r.REFERRER_KEY = c.REFERRER_KEY;

SELECT CONCAT(''Message : '',"number of rows inserted",'' Rows Inserted.'') into :return_result FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));
return return_result;
END;

 EOT
}

