resource "snowflake_procedure" "DW_INTEGRATION_DIM_SURVEY_RESPONSE_HEADER_MERGED_POSTPROCESSING" {
	name ="DIM_SURVEY_RESPONSE_HEADER_MERGED_POSTPROCESSING"
	database = "DW_${var.SF_ENVIRONMENT}"
	schema = "INTEGRATION"
	language  = "SQL"

	arguments {
		name = "STR_ETL_TASK_KEY"
		type = "VARCHAR(16777216)"
}	

	arguments {
		name = "STR_CDC_START"
		type = "VARCHAR(16777216)"
}	

	arguments {
		name = "STR_CDC_END"
		type = "VARCHAR(16777216)"
}	
	return_type = "VARCHAR(16777216)"
	execute_as = "OWNER"
	statement = <<-EOT

DECLARE
    return_result varchar(1000);
BEGIN
    INSERT OVERWRITE INTO DW_${var.SF_ENVIRONMENT}.INTEGRATION.DIM_SURVEY_RESPONSE_HEADER_MERGED
	SELECT 
	S.SURVEY_RESPONSE_HEADER_KEY, 
	S.SURVEY_KEY, 
	S.SURVEY_ID, 
	S.RECORD_ID, 
	COALESCE(CM.CLIENT_KEY, S.CLIENT_KEY) AS CLIENT_KEY,
	S.CLIENT_KEY AS ORIGINAL_CLIENT_KEY,
	COALESCE(EM.EMPLOYEE_KEY, S.EMPLOYEE_KEY) AS EMPLOYEE_KEY,
	S.EMPLOYEE_KEY AS ORIGINAL_EMPLOYEE_KEY, 
	COALESCE(BM.BRANCH_KEY, S.BRANCH_KEY) AS BRANCH_KEY,
	S.BRANCH_KEY AS ORIGINAL_BRANCH_KEY,
	S.PARTNER_KEY, 
	COALESCE(CM.SOURCE_SYSTEM_ID, S.SOURCE_SYSTEM_ID)  AS SOURCE_SYSTEM_ID, 
	S.SOURCE_SYSTEM_ID AS 	ORIGNIAL_SOURCE_SYSTEM_ID, 
	S.SYSTEM_CODE, 
	S.STATUS, 
	S.PROGRESS, 
	S.COMPLETED_FLAG, 
	S.RECORDED_DATE, 
	S.START_DATE, 
	S.END_DATE, 
	S.DURATION_IN_SECONDS, 
	S.LANGUAGE, 
	S.LATITUDE, 
	S.LONGITUDE, 
	S.IP_ADDRESS, 
	S.EXTERNAL_REFERENCE, 
	S.DISTRIBUTION_CHANNEL, 
	S.ETL_TASK_KEY, 
	S.ETL_INSERTED_TASK_KEY, 	
	S.ETL_INSERTED_DATE, 
	S.ETL_INSERTED_BY, 
	S.ETL_LAST_UPDATED_DATE, 
	S.ETL_LAST_UPDATED_BY, 
	S.ETL_DELETED_FLAG

	FROM HAH.DIM_SURVEY_RESPONSE_HEADER   S
	LEFT JOIN INTEGRATION.DIM_BRANCH_MERGED  BM
		ON BM.ORIGINAL_BRANCH_KEY = S.BRANCH_KEY
	LEFT JOIN INTEGRATION.DIM_CLIENT_MERGED  CM
		ON CM.ORIGINAL_CLIENT_KEY = S.CLIENT_KEY
	LEFT JOIN INTEGRATION.DIM_EMPLOYEE_MERGED EM
		ON EM.ORIGINAL_EMPLOYEE_KEY = S.EMPLOYEE_KEY;

SELECT CONCAT(''Message : '',"number of rows inserted",'' Rows Inserted.'') into :return_result FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));
return return_result;
END;

 EOT
}

