resource "snowflake_procedure" "DW_INTEGRATION_FACT_PARTNER_CONTRACT_SERVICE_MERGED_POSTPROCESSING" {
	name ="FACT_PARTNER_CONTRACT_SERVICE_MERGED_POSTPROCESSING"
	database = "DW_${var.SF_ENVIRONMENT}"
	schema = "INTEGRATION"
	language  = "SQL"

	arguments {
		name = "STR_ETL_TASK_KEY"
		type = "VARCHAR(16777216)"
}	

	arguments {
		name = "STR_CDC_START"
		type = "VARCHAR(16777216)"
}	

	arguments {
		name = "STR_CDC_END"
		type = "VARCHAR(16777216)"
}	
	return_type = "VARCHAR(16777216)"
	execute_as = "OWNER"
	statement = <<-EOT

DECLARE
  RETURN_RESULT VARCHAR(1000);
BEGIN
--***************************************************************************************************************************
-- DEVELOPMENT LOG:
-- DATE        	AUTHOR                	NOTES:
-- --------    	-------------------   	-----------------------------------------------------------------------------------------------
--02/02/2024    NUTAN JAGNADE            INITIAL DEVELOPMENT
--***************************************************************************************************************************
 	INSERT OVERWRITE INTO DW_${var.SF_ENVIRONMENT}.INTEGRATION.FACT_PARTNER_CONTRACT_SERVICE_MERGED 
SELECT PC1.PARTNER_CONTRACT_SERVICE_KEY AS ORIGINAL_PARTNER_CONTRACT_SERVICE_KEY,
       PC1.PARTNER_CONTRACT_KEY AS ORIGINAL_PARTNER_CONTRACT_KEY,
       PC1.PARTNER_CODE AS ORIGINAL_PARTNER_CODE,
	   PC1.PARTNER_NAME AS ORIGINAL_PARTNER_NAME,
	   PC1.SOURCE_SYSTEM_ID AS ORIGINAL_SOURCE_SYSTEM_ID,
       PC1.SYSTEM_CODE AS ORIGINAL_SYSTEM_CODE,
       PC2.PARTNER_CONTRACT_SERVICE_KEY,
	   PC2.SOURCE_SYSTEM_ID ,
	   PC2.SYSTEM_CODE ,
	   COALESCE(PC1.STATE,PC2.STATE) AS STATE,
	   COALESCE(PC2.PARTNER_CONTRACT_KEY,PC1.PARTNER_CONTRACT_KEY) AS PARTNER_CONTRACT_KEY,
       COALESCE(PC2.PARTNER_CODE,PC1.PARTNER_CODE) AS PARTNER_CODE ,
	   COALESCE(PC2.PARTNER_NAME,PC1.PARTNER_NAME) AS PARTNER_NAME ,
	   PC1.CONTRACT_CODE,
	   PC1.CONTRACT_NAME,
	   PC1.SERVICE_KEY,
	   PC1.SERVICE_CODE,
	   PC1.SERVICE_NAME,
	   PC1.BILLING_KEY,
	   PC1.BILL_CODE,
	   PC1.BILL_NAME,
	   PC1.BILLABLE_FLAG,
	   PC1.BILL_TYPE,
	   PC1.BILL_UOM,
	   PC1.SCHEDULE_TYPE,
	   PC1.SCHEDULE_UOM,
	   PC1.AUTHORIZATION_REQUIRED_FLAG,
	   PC1.PAYABLE_FLAG,
	   PC1.EXPENSE_FLAG,
	   PC1.MILEAGE_FLAG,
	   :STR_ETL_TASK_KEY AS ETL_TASK_KEY
	, :STR_ETL_TASK_KEY AS ETL_INSERTED_TASK_KEY
	, Convert_timezone(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ AS ETL_INSERTED_DATE
	, CURRENT_USER AS ETL_INSERTED_BY
	, Convert_timezone(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ AS ETL_LAST_UPDATED_DATE
	, CURRENT_USER AS ETL_LAST_UPDATED_BY
	, 0 AS ETL_DELETED_FLAG
FROM HAH.FACT_PARTNER_CONTRACT_SERVICE AS PC1
LEFT JOIN HAH.FACT_PARTNER_CONTRACT_SERVICE PC2 ON 
PC1.SYSTEM_CODE = PC2.ORIGINAL_SYSTEM_CODE AND UPPER(TRIM(PC1.CONTRACT_CODE)) = UPPER(TRIM(PC2.CONTRACT_CODE)) 
AND UPPER(TRIM(PC1.CONTRACT_NAME)) = UPPER(TRIM(PC2.CONTRACT_NAME)) and PC1.STATE=PC2.STATE
WHERE PC1.SOURCE_SYSTEM_ID not in(28,29);
RETURN ''SUCCESS'';
end;

 EOT
}

