resource "snowflake_procedure" "DISC_TRUSTPOINTDATA_LOCATIONS_LOAD" {
	name ="LOCATIONS_LOAD"
	database = "DISC_${var.SF_ENVIRONMENT}"
	schema = "TRUSTPOINTDATA"
	language  = "SQL"

	arguments {
		name = "STR_ETL_TASK_KEY"
		type = "VARCHAR(16777216)"
}	

	arguments {
		name = "STR_CDC_START"
		type = "VARCHAR(16777216)"
}	

	arguments {
		name = "STR_CDC_END"
		type = "VARCHAR(16777216)"
}	
	return_type = "VARCHAR(16777216)"
	execute_as = "OWNER"
	statement = <<-EOT


CREATE OR REPLACE TABLE DISC_${var.SF_ENVIRONMENT}.TRUSTPOINTDATA.TRUSTPOINT_LOC AS 

SELECT DISTINCT 
	WP.$1 AS "COST_FULL_NAME",
	WP.$2 AS "LEVEL",
	WP.$3 AS "ACCOUNTS",
	WP.$4 AS "NAME",
	WP.$5 AS "COST_ABBR",
	WP.$6 AS "CHILDREN",
	WP.$7 AS "DESCENDENTS",
	WP.$8 AS "FULL_ABBR_NAME",
	WP.$9 AS "EXTERNAL_ID",
	WP.$10 AS "COST_DESCRIPTION",
	WP.$11 AS "NAME_1",
	WP.$12 AS "NAME_2",
	WP.$13 AS "ABBREV_1",
	WP.$14 AS "ABBREV_2",
	WP.$15 AS "EXTERNAL_ID_1",
	WP.$16 AS "EXTERNAL_ID_2",
	WP.$17 AS "DESCRIPTION_2",
	WP.$18 AS "ADDRESS_1",
	WP.$19 AS "ADDRESS_2",
	WP.$20 AS "CITY",
	WP.$21 AS "ZIP_CODE",
	WP.$22 AS "STATE",
	WP.$23 AS "SYSTEM_ID",
	WP.$24 AS "PARENT_NAME",
	WP.$25 AS "PARENT_FULL_PATH",
	WP.$26 AS "PARENT_EXTERNAL_ID",
	WP.$27 AS "PARENT_ADDRESS_1",
	WP.$28 AS "PARENT_ADDRESS_2",
	WP.$29 AS "PARENT_CITY",
	WP.$30 AS "PARENT_ZIP_CODE",
	WP.$31 AS "PARENT_STATE"
FROM @DISC_${var.SF_ENVIRONMENT}.STAGE.AZSTAGEPROD/TRUSTPOINT_LOC/trustpoint_loc_1 (FILE_FORMAT => DW_${var.SF_ENVIRONMENT}.PUBLIC.CSV_FORMAT_TRUSTPOINT) WP;


 EOT
}

