CREATE OR REPLACE FILE FORMAT DISC_PROD.PUBLIC.XML_STRIPOUT_FORMAT_AB
	TYPE = XML
	IGNORE_UTF8_ERRORS = TRUE
	STRIP_OUTER_ELEMENT = TRUE
COMMENT='XML file format with stripped outer element for XML load - Abhishek'
;