CREATE OR REPLACE TABLE DW_PROD.HAH.FACT_SYSTEM_CUTOVER_DATE_2_0 (
	SOURCE_SYSTEM_ID NUMBER(38,0),
	SYSTEM_CODE VARCHAR(20),
	OFFICE_STATE_CODE VARCHAR(2),
	BRANCH_KEY VARCHAR(32),
	CONTRACT_KEY VARCHAR(32),
	PARTNER_CONTRACT_SERVICE_KEY VARCHAR(32),
	START_DATE DATE,
	END_DATE DATE
);