CREATE OR REPLACE TABLE DW_PROD.STAGE.OBP_FACT_SURVEY_RESPONSE_DETAIL (
	SURVEY_RESPONSE_DETAIL_KEY VARCHAR(32) NOT NULL,
	SURVEY_KEY VARCHAR(32) NOT NULL,
	SURVEY_ID VARCHAR(50) NOT NULL,
	SURVEY_RESPONSE_HEADER_KEY VARCHAR(32) NOT NULL,
	SURVEY_QUESTION_KEY VARCHAR(32),
	QUESTION_ID VARCHAR(50) NOT NULL,
	ANSWER VARCHAR(16777216),
	ETL_TASK_KEY NUMBER(10,0),
	ETL_INSERTED_TASK_KEY NUMBER(10,0),
	ETL_INSERTED_DATE TIMESTAMP_NTZ(9),
	ETL_INSERTED_BY VARCHAR(16777216),
	ETL_LAST_UPDATED_DATE TIMESTAMP_NTZ(9),
	ETL_LAST_UPDATED_BY VARCHAR(16777216),
	ETL_DELETED_FLAG BOOLEAN,
	constraint PK_SURVEY_RESPONSE primary key (SURVEY_RESPONSE_DETAIL_KEY)
);