CREATE OR REPLACE TABLE DW_PROD.HAH.DIM_ZIP_CODE (
	ZIP_CODE VARCHAR(5),
	LATITUDE NUMBER(10,7),
	LONGITUDE NUMBER(10,7),
	CITY_PRIMARY_NAME VARCHAR(50),
	COUNTY_NAME VARCHAR(50),
	STATE_NAME VARCHAR(30),
	STATE_ISO_CODE VARCHAR(2),
	STATE_ANSI_CODE VARCHAR(2),
	STATE_FIPS VARCHAR(2),
	COUNTRY_ISO_CODE VARCHAR(3),
	COUNTRY_COMMON_NAME VARCHAR(50),
	COUNTRY_OFFICIAL_NAME VARCHAR(50)
);