CREATE OR REPLACE TABLE DW_PROD.HAH.FACT_SURVEY_RESPONSE_SCALE_MAPPING (
	SURVEY_QUESTION_KEY VARCHAR(32),
	SOURCE_SYSTEM_ID NUMBER(38,0),
	SYSTEM_CODE VARCHAR(20),
	QUESTION_TEXT VARCHAR(500),
	QUESTION_ID VARCHAR(50),
	ANSWER VARCHAR(16777216),
	ANSWER_SCALE NUMBER(38,0)
);