CREATE OR REPLACE TABLE DW_PROD.REPORT.ONHOLDCLIENTHISTORY_PA (
	CLIENTID NUMBER(10,0),
	CLIENT_KEY VARCHAR(32),
	SOURCE_SYSTEM_ID NUMBER(1,0),
	SYSTEM_CODE VARCHAR(2),
	ONHOLDSTARTDATE DATE,
	ONHOLDENDDATE VARCHAR(16777216),
	ACTIVE BOOLEAN,
	ETL_INSERTED_DATE DATE,
	ETL_TASK_KEY NUMBER(1,0)
);