CREATE OR REPLACE TABLE DW_PROD.HAH.FACT_SURVEY_COLUMN_MAPPING (
	SURVEY_KEY VARCHAR(32) NOT NULL,
	SURVEY_ID VARCHAR(50) NOT NULL,
	SOURCE_COLUMN_NAME VARCHAR(200),
	DESTINATION_COLUMN_NAME VARCHAR(200)
);