CREATE OR REPLACE TABLE DW_PROD.HAH.FACT_REVENUE_SUBCATEGORY_USAGE (
	REVENUE_SUBCATEGORY_USAGE_KEY VARCHAR(32) NOT NULL,
	REVENUE_CATEGORY VARCHAR(50),
	REVENUE_SUBCATEGORY_CODE VARCHAR(10),
	REVENUE_SUBCATEGORY_NAME VARCHAR(50),
	DASHBOARD_REPORT_NAME VARCHAR(100) NOT NULL,
	METRIC_NAME VARCHAR(25),
	INCLUDE_FLAG BOOLEAN NOT NULL,
	ETL_TASK_KEY NUMBER(38,0) NOT NULL,
	ETL_INSERTED_TASK_KEY NUMBER(38,0) NOT NULL,
	ETL_INSERTED_DATE TIMESTAMP_NTZ(9) NOT NULL,
	ETL_INSERTED_BY VARCHAR(100) NOT NULL,
	ETL_LAST_UPDATED_DATE TIMESTAMP_NTZ(9) NOT NULL,
	ETL_LAST_UPDATED_BY VARCHAR(100) NOT NULL,
	ETL_DELETED_FLAG BOOLEAN NOT NULL,
	ETL_INFERRED_MEMBER_FLAG BOOLEAN NOT NULL,
	constraint PK_FACT_REVENUE_SUBCATEGORY_USAGE primary key (REVENUE_SUBCATEGORY_USAGE_KEY)
);