CREATE OR REPLACE TABLE DW_PROD.REPORT.DISCOVERY_TO_BUSINESS_AUDIT (
	TASK VARCHAR(50),
	DISC_DB VARCHAR(20),
	DISC_PROD_SOURCE VARCHAR(20),
	DISC_TABLE_COUNT NUMBER(38,0),
	DW_PROD_TABLE VARCHAR(50),
	DW_DB VARCHAR(20),
	DW_SOURCE VARCHAR(20),
	DW_TABLE_COUNT NUMBER(38,0),
	COUNT_DIFF NUMBER(38,0),
	PERCENT_OF_VARIANCE VARCHAR(10),
	INSERT_DATE DATE
);