CREATE OR REPLACE TABLE DW_PROD.PUBLIC.CLIENT_TENURE_DERIVED_MONTHLY_METRICS_BKCP_19102023 (
	CLIENT_KEY VARCHAR(32),
	SERVICE_MONTH DATE,
	FIRST_SERVICE_DATE DATE,
	LATEST_SERVICE_DATE DATE,
	TENURE_OF_SERVICE_MONTHS VARCHAR(5),
	CLIENT_DOB DATE,
	CLIENT_AGE_AS_OF_SERVICE_MONTH VARCHAR(200),
	ETL_TASK_KEY NUMBER(38,0),
	ETL_INSERTED_TASK_KEY NUMBER(38,0),
	ETL_INSERTED_DATE TIMESTAMP_NTZ(9),
	ETL_INSERTED_BY VARCHAR(100),
	ETL_LAST_UPDATED_DATE TIMESTAMP_NTZ(9),
	ETL_LAST_UPDATED_BY VARCHAR(100)
);