CREATE OR REPLACE TABLE DW_PROD.REPORT.ONHOLDCLIENTHISTORY_DATAFLEX (
	CLIENT_KEY VARCHAR(32),
	NUMBER NUMBER(10,0),
	SOURCESYSTEMID NUMBER(1,0),
	DBNAME VARCHAR(10),
	ONHOLDSTARTDATE DATE,
	ONHOLDENDDATE DATE,
	ACTIVE BOOLEAN,
	ETL_INSERTED_DATE DATE,
	ETL_TASK_KEY NUMBER(1,0)
);