CREATE OR REPLACE TABLE DW_PROD.HAH.FACT_BRANCH_MANAGER_MAPPING (
	OFFICE_SYSTEM_CODE VARCHAR(20) NOT NULL,
	OFFICE_CODE VARCHAR(5) NOT NULL,
	OFFICE_SOURCE_SYSTEM_ID NUMBER(38,0),
	PRIMARY_MANAGER_NAME VARCHAR(100) NOT NULL,
	PRIMARY_MANAGER_EMPLOYEE_ID VARCHAR(50) NOT NULL,
	PRIMARY_MANAGER_SYSTEM_CODE VARCHAR(20) NOT NULL,
	PRIMARY_MANAGER_SOURCE_SYSTEM_ID NUMBER(38,0),
	PRIMARY_BRANCH_EMAIL VARCHAR(100),
	SECONDARY_MANAGER_NAME VARCHAR(100),
	SECONDARY_MANAGER_EMPLOYEE_ID VARCHAR(50),
	SECONDARY_MANAGER_SYSTEM_CODE VARCHAR(20),
	SECONDARY_MANAGER_SOURCE_SYSTEM_ID NUMBER(38,0),
	SECONDARY_BRANCH_EMAIL VARCHAR(100),
	ETL_LAST_UPDATED_DATE TIMESTAMP_NTZ(9) NOT NULL DEFAULT CAST(CONVERT_TIMEZONE('UTC', CAST(CURRENT_TIMESTAMP() AS TIMESTAMP_TZ(9))) AS TIMESTAMP_NTZ(9)),
	constraint PK_FACT_BRANCH_MANAGER_MAPPING primary key (OFFICE_SYSTEM_CODE, OFFICE_CODE)
);