CREATE OR REPLACE TABLE DW_PROD.REPORT.GP_CROSSWALK_LIST (
	WORKDAY_INTERNAL_ID VARCHAR(50),
	CURRENT_PAYROLL_EMPLOYEE_ID VARCHAR(50),
	CURRENT_PAYROLL_SOURCE_SYSTEM VARCHAR(16777216),
	FIRST_NAME_FROM_CROSSWALK VARCHAR(50),
	LAST_NAME_FROM_CROSSWALK VARCHAR(50),
	EMPLOYEE_DOB VARCHAR(16777216),
	SSN_FROM_CROSSWALK VARCHAR(25),
	LEGACY_PAYROLL_EMPLOYEE_ID VARCHAR(16777216),
	LEGACY_PAYROLL_SOURCE_SYSTEM VARCHAR(16777216),
	IS_MIGRATED BOOLEAN
)COMMENT='TABLE CREATED FOR ITXEE-1463'
;