CREATE OR REPLACE TABLE DW_PROD.HAH.FACT_COMPANY_STATE_SYSTEM (
	COMPANY_STATE_KEY VARCHAR(100),
	BUSINESS_KEY VARCHAR(100),
	COMPANY_ID NUMBER(38,0),
	COMPANY_LEGAL_NAME VARCHAR(500),
	COMPANY_COMMON_NAME VARCHAR(500),
	FEIN VARCHAR(15),
	SYSTEM_TYPE VARCHAR(100),
	STATE VARCHAR(100),
	START_DATE DATE,
	END_DATE DATE,
	CURRENT_FLAG BOOLEAN,
	SOURCE_SYSTEM_ID VARCHAR(100),
	SYSTEM_CODE VARCHAR(100),
	LEGAL_STATE VARCHAR(100)
);