CREATE OR REPLACE TABLE DW_PROD.REPORT.TAKING_MONTHLY_SNAPSHOT_FOR_RCM_TABLES (
	TABLE_NAME VARCHAR(100),
	BEFORE_COUNT NUMBER(38,0),
	AFTER_COUNT NUMBER(38,0),
	START_TIME TIMESTAMP_NTZ(9),
	END_TIME TIMESTAMP_NTZ(9),
	INSERTED_BY VARCHAR(100) NOT NULL
);