CREATE OR REPLACE TABLE DW_PROD.INTEGRATION.DIM_CLIENT_MATCH (
	ORIGINAL_RECORD_ID VARCHAR(16777216),
	MASTER_ID VARCHAR(16777216),
	CLUSTER_ID VARCHAR(16777216),
	CLIENT_NUMBER NUMBER(38,0),
	BEGIN_DATE DATE,
	RECORD_ORDER NUMBER(18,0),
	CLIENT_FIRST_NAME VARCHAR(50),
	CLIENT_LAST_NAME VARCHAR(50),
	CLIENT_MIDDLE_NAME VARCHAR(10),
	CLIENT_NAME VARCHAR(150),
	CLIENT_DOB DATE,
	CLIENT_PID VARCHAR(32),
	CLIENT_CITY VARCHAR(50),
	CLIENT_ZIP VARCHAR(12),
	CLIENT_CELL_PHONE VARCHAR(20)
);