CREATE OR REPLACE TABLE DW_PROD.INTEGRATION.FACT_BRANCH_PAYROLL_PERIODS_MERGED (
	BRANCH_PAYROLL_PERIODS_KEY VARCHAR(32),
	BRANCH_KEY VARCHAR(32),
	OFFICE_STATE_CODE VARCHAR(2),
	DETAILED_OFFICE_NAME VARCHAR(100),
	ORIGINAL_BRANCH_KEY VARCHAR(32),
	PERIOD_START_DATE DATE,
	PERIOD_END_DATE DATE,
	CHECK_DATE DATE,
	ETL_TASK_KEY NUMBER(38,0),
	ETL_INSERTED_TASK_KEY NUMBER(38,0),
	ETL_INSERTED_DATE TIMESTAMP_NTZ(9),
	ETL_INSERTED_BY VARCHAR(100),
	ETL_LAST_UPDATED_DATE TIMESTAMP_NTZ(9),
	ETL_LAST_UPDATED_BY VARCHAR(100),
	ETL_DELETED_FLAG BOOLEAN,
	ETL_INFERRED_MEMBER_FLAG BOOLEAN
);