CREATE OR REPLACE TABLE DW_PROD.PUBLIC.EMPLOYEE_CROSS_WALK_MERGED_TEST (
	ID NUMBER(38,0),
	LATEST_ENTERPRISE_ID NUMBER(38,0),
	OLD_ENTERPRISE_ID NUMBER(38,0),
	MERGE_REASON VARCHAR(100),
	ACTIVE_FLAG BOOLEAN,
	INSERTED_DATE TIMESTAMP_NTZ(9),
	INSERTED_BY VARCHAR(100)
);