CREATE OR REPLACE TABLE DW_PROD.REPORT.COVID_19_DAILYVISITHOURSCOUNTRECENT4WEEKS (
	WEEK_OF_YEAR NUMBER(38,0),
	WEEK VARCHAR(200),
	STATE VARCHAR(2),
	BRANCH_NAME VARCHAR(100),
	BRANCH_KEY VARCHAR(38),
	EVENTSTATUS VARCHAR(30),
	CURRENTWEEKHOURS NUMBER(10,2),
	PREVIOUS4THWEEKHOURS NUMBER(10,2),
	ROLLING4WEEKSHOURS NUMBER(10,2),
	PREVIOUSROLLING4WEEKSHOURS NUMBER(10,2),
	PREVIOUSTOPREVIOUSROLLING4WEEKS NUMBER(10,2)
);