CREATE OR REPLACE TABLE DW_PROD.REPORT.EMPLOYEE_PHONE_NUMBERS (
	EMPLOYEE_KEY VARCHAR(32),
	SYSTEM_NAME VARCHAR(20),
	STATE VARCHAR(2),
	FULL_BRANCH_NAME VARCHAR(50),
	BRANCH_NAME VARCHAR(40),
	ID VARCHAR(20),
	CATEGORY VARCHAR(15),
	FIRST_NAME VARCHAR(55),
	LAST_NAME VARCHAR(55),
	EMP_PHONE1 NUMBER(38,0),
	EMP_PHONE2 NUMBER(38,0),
	EMP_PHONE3 NUMBER(38,0),
	ACTIVE_EMPLOYEE_FLAG BOOLEAN,
	DERIVED_ACTIVE_EMPLOYEE_FLAG BOOLEAN,
	LATEST_SERVICE_DATE DATE,
	LATEST_CHECK_DATE DATE
);