CREATE OR REPLACE TABLE DW_PROD.HAH.DIM_DIAGNOSIS_2_0 (
	DIAGNOSIS_KEY VARCHAR(32),
	ICD9 BOOLEAN,
	ICD10 BOOLEAN,
	DIAGNOSIS_CODE VARCHAR(16777216),
	PARENT_CODE_INDICATOR BOOLEAN,
	SHORT_DESC VARCHAR(100),
	LONG_DESC VARCHAR(300),
	ETL_TASK_KEY NUMBER(38,0),
	ETL_INSERTED_TASK_KEY NUMBER(38,0),
	ETL_INSERTED_DATE TIMESTAMP_NTZ(9),
	ETL_INSERTED_BY VARCHAR(100),
	ETL_LAST_UPDATED_DATE TIMESTAMP_NTZ(9),
	ETL_LAST_UPDATED_BY VARCHAR(100),
	ETL_DELETED_FLAG BOOLEAN
);