resource "snowflake_procedure" "DW_STAGE_MERGE_STAGE_SANDATAIMPORT_FACT_VISIT_CHECK" {
	name ="MERGE_STAGE_SANDATAIMPORT_FACT_VISIT_CHECK"
	database = "DW_${var.SF_ENVIRONMENT}"
	schema = "STAGE"
	language  = "JAVASCRIPT"
	return_type = "VARCHAR(16777216)"
	execute_as = "OWNER"
	statement = <<-EOT


    var sqlCmd = "";
    var sqlStmt = "";
    var result = "";

    try {
      var sqlCmd = `
    MERGE INTO STAGE.SANDATA_FACT_VISIT_CHECK TGT 
USING STAGE.SANDATA_STAGE_FACT_VISIT_CHECK STAGE 
ON TGT.VISIT_KEY = STAGE.VISIT_KEY
WHEN MATCHED THEN 
UPDATE SET 
    TGT.REPORT_DATE= STAGE.REPORT_DATE
   ,TGT.BRANCH_KEY= STAGE.BRANCH_KEY
   ,TGT.CLIENT_KEY= STAGE.CLIENT_KEY
   ,TGT.CONTRACT_KEY= STAGE.CONTRACT_KEY
   ,TGT.EMPLOYEE_KEY= STAGE.EMPLOYEE_KEY
   ,TGT.SOURCE_SYSTEM_ID= STAGE.SOURCE_SYSTEM_ID
   ,TGT.SUPERVISOR_KEY= STAGE.SUPERVISOR_KEY
   ,TGT.SERVICE_DATE= STAGE.SERVICE_DATE
   ,TGT.PAYROLL_DATE= STAGE.PAYROLL_DATE
   ,TGT.BRANCH_NAME= STAGE.BRANCH_NAME
   ,TGT.CLIENT_NUMBER= STAGE.CLIENT_NUMBER
   ,TGT.CONTRACT_CODE= STAGE.CONTRACT_CODE
   ,TGT.EMPLOYEE_ID= STAGE.EMPLOYEE_ID
   ,TGT.SYSTEM_CODE= STAGE.SYSTEM_CODE
   ,TGT.SUPERVISOR_CODE= STAGE.SUPERVISOR_CODE
   ,TGT.CLEAN_SHIFT_FLAG= STAGE.CLEAN_SHIFT_FLAG
   ,TGT.STATUS_CODE= STAGE.STATUS_CODE
   ,TGT.STATUS_DESCRIPTION= STAGE.STATUS_DESCRIPTION
   ,TGT.CANCEL_REASON_CODE= STAGE.CANCEL_REASON_CODE
   ,TGT.CANCEL_REASON_DESCRIPTION= STAGE.CANCEL_REASON_DESCRIPTION
   ,TGT.CANCEL_REASON_NOTES= STAGE.CANCEL_REASON_NOTES
   ,TGT.EXCEPTION_REASON_FLAG= STAGE.EXCEPTION_REASON_FLAG
   ,TGT.RESOLUTION_CODE= STAGE.RESOLUTION_CODE
   ,TGT.RESOLUTION_DESCRIPTION= STAGE.RESOLUTION_DESCRIPTION
   ,TGT.REJECTION_CODE= STAGE.REJECTION_CODE
   ,TGT.REJECTION_DESCRIPTION= STAGE.REJECTION_DESCRIPTION
   ,TGT.BILL_CODE= STAGE.BILL_CODE
   ,TGT.BILL_RATE= STAGE.BILL_RATE
   ,TGT.OVERHEAD_RATE= STAGE.OVERHEAD_RATE
   ,TGT.HOURS_SERVED= STAGE.HOURS_SERVED
   ,TGT.COMMENTS= STAGE.COMMENTS
   ,TGT.IS_EVV_FLAG= STAGE.IS_EVV_FLAG
   ,TGT.TIMESHEET_TYPE= STAGE.TIMESHEET_TYPE
   ,TGT.TRACKING_ID= STAGE.TRACKING_ID
   ,TGT.ETL_TASK_KEY= STAGE.ETL_TASK_KEY
   ,TGT.ETL_LAST_UPDATED_DATE= STAGE.ETL_LAST_UPDATED_DATE
   ,TGT.ETL_LAST_UPDATED_BY= STAGE.ETL_LAST_UPDATED_BY
   ,TGT.ETL_DELETED_FLAG= STAGE.ETL_DELETED_FLAG
WHEN NOT MATCHED THEN 
INSERT ( 
    VISIT_KEY
   ,REPORT_DATE
   ,BRANCH_KEY
   ,CLIENT_KEY
   ,CONTRACT_KEY
   ,EMPLOYEE_KEY
   ,SOURCE_SYSTEM_ID
   ,SUPERVISOR_KEY
   ,SERVICE_DATE
   ,PAYROLL_DATE
   ,BRANCH_NAME
   ,CLIENT_NUMBER
   ,CONTRACT_CODE
   ,EMPLOYEE_ID
   ,SYSTEM_CODE
   ,SUPERVISOR_CODE
   ,CLEAN_SHIFT_FLAG
   ,STATUS_CODE
   ,STATUS_DESCRIPTION
   ,CANCEL_REASON_CODE
   ,CANCEL_REASON_DESCRIPTION
   ,CANCEL_REASON_NOTES
   ,EXCEPTION_REASON_FLAG
   ,RESOLUTION_CODE
   ,RESOLUTION_DESCRIPTION
   ,REJECTION_CODE
   ,REJECTION_DESCRIPTION
   ,BILL_CODE
   ,BILL_RATE
   ,OVERHEAD_RATE
   ,HOURS_SERVED
   ,COMMENTS
   ,IS_EVV_FLAG
   ,TIMESHEET_TYPE
   ,TRACKING_ID
   ,ETL_TASK_KEY
   ,ETL_INSERTED_TASK_KEY
   ,ETL_INSERTED_DATE
   ,ETL_INSERTED_BY
   ,ETL_LAST_UPDATED_DATE
   ,ETL_LAST_UPDATED_BY
   ,ETL_DELETED_FLAG
) 
VALUES (
    STAGE.VISIT_KEY
   ,STAGE.REPORT_DATE
   ,STAGE.BRANCH_KEY
   ,STAGE.CLIENT_KEY
   ,STAGE.CONTRACT_KEY
   ,STAGE.EMPLOYEE_KEY
   ,STAGE.SOURCE_SYSTEM_ID
   ,STAGE.SUPERVISOR_KEY
   ,STAGE.SERVICE_DATE
   ,STAGE.PAYROLL_DATE
   ,STAGE.BRANCH_NAME
   ,STAGE.CLIENT_NUMBER
   ,STAGE.CONTRACT_CODE
   ,STAGE.EMPLOYEE_ID
   ,STAGE.SYSTEM_CODE
   ,STAGE.SUPERVISOR_CODE
   ,STAGE.CLEAN_SHIFT_FLAG
   ,STAGE.STATUS_CODE
   ,STAGE.STATUS_DESCRIPTION
   ,STAGE.CANCEL_REASON_CODE
   ,STAGE.CANCEL_REASON_DESCRIPTION
   ,STAGE.CANCEL_REASON_NOTES
   ,STAGE.EXCEPTION_REASON_FLAG
   ,STAGE.RESOLUTION_CODE
   ,STAGE.RESOLUTION_DESCRIPTION
   ,STAGE.REJECTION_CODE
   ,STAGE.REJECTION_DESCRIPTION
   ,STAGE.BILL_CODE
   ,STAGE.BILL_RATE
   ,STAGE.OVERHEAD_RATE
   ,STAGE.HOURS_SERVED
   ,STAGE.COMMENTS
   ,STAGE.IS_EVV_FLAG
   ,STAGE.TIMESHEET_TYPE
   ,STAGE.TRACKING_ID
   ,STAGE.ETL_TASK_KEY
   ,STAGE.ETL_INSERTED_TASK_KEY
   ,STAGE.ETL_INSERTED_DATE
   ,STAGE.ETL_INSERTED_BY
   ,STAGE.ETL_LAST_UPDATED_DATE
   ,STAGE.ETL_LAST_UPDATED_BY
   ,STAGE.ETL_DELETED_FLAG
)

    `;
      sqlStmt = snowflake.createStatement( {sqlText: sqlCmd} );
      rs = sqlStmt.execute();
      sqlCmd = 
            `SELECT "number of rows inserted", "number of rows updated"
              FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))`;
      sqlStmt = snowflake.createStatement( {sqlText: sqlCmd} );
      rs = sqlStmt.execute();
          rs.next();
          result += ''{"Inserted": "'' + rs.getColumnValue(1) + ''", "Updated": "'' + rs.getColumnValue(2) +''", "ErrorCode":"NA", "ErrorState":"NA", "ErrorMessage":"NA", "ErrorStackTrace":"NA"}'';
    }
    catch (err) {
        result = ''{"Inserted": "0", "Updated": "0", "ErrorCode":"''+ err.code +''", "ErrorState":"''+ err.state +''", "ErrorMessage":"''+ err.message +''", "ErrorStackTrace":"''+ err.stackTraceTxt +''"}'';
    }
    return result;
    
 EOT
}

