CREATE OR REPLACE PROCEDURE DW_PROD.HAH.GET_STAGE_SANDATAIMPORT_ORPHAN_BRANCH("STR_ETL_TASK_KEY" VARCHAR(16777216), "STR_CDC_START" VARCHAR(16777216), "STR_CDC_END" VARCHAR(16777216))
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
  RETURN_RESULT VARCHAR(1000);
BEGIN
--*****************************************************************************************************************************
-- NAME:  SANDATAIMPORT_ORPHAN_BRANCH
--
-- PURPOSE: 
--
-- DEVELOPMENT LOG:
-- DATE			AUTHOR					NOTES:
-- --------		-------------------		---------------------------------------------------------------------------------------
-- 12/05/2023	TRUSHALI RAMOLIYA			Initial Development
--*****************************************************************************************************************************

INSERT OVERWRITE INTO DW_PROD.STAGE.SANDATAIMPORT_ORPHAN_BRANCH

--NO RESPECTIVE VALUE FOR COLUMN  -  LOCATIONID(EMPTY STRING) FOR TABLE DISC_PROD.BI_REPOSITORY.SANDATAVISITS

SELECT 
md5( ''8485'' || ''-'' || '''' || ''-'' || ''SANDATAIMPORT'') AS BRANCH_KEY,
''UNKNOWN'' AS BRANCH_NAME ,
''8485'' AS SYSTEM_CODE,
4 AS SOURCE_SYSTEM_ID,
''AMS'' AS SOURCE_SYSTEM_TYPE,
-1 AS OFFICE_NUMBER,
-1 AS OFFICE_CODE,
''UNKNOWN'' AS OFFICE_NAME,
''UNKNOWN'' AS OFFICE_NAME_ALT,
NULL AS DEPARTMENT_NAME,
NULL AS BRANCH_SERVICE_LINE,
FALSE AS PARENT_FLAG,
md5( ''8485'' || ''-'' || '''' || ''-'' || ''SANDATAIMPORT'') AS PARENT_BRANCH_KEY,
-1 AS PARENT_OFFICE_NUMBER,
-1 AS PARENT_OFFICE_CODE,
''PA'' || '' - '' || ''UNKNOWN'' || '' ('' || -1 || '')''  AS PARENT_BRANCH_NAME,
NULL AS OFFICE_ADDRESS1,
NULL AS OFFICE_ADDRESS2,
NULL AS OFFICE_CITY,
''PA'' AS OFFICE_STATE_CODE,
NULL AS OFFICE_ZIP,
NULL AS OFFICE_PHONE,
NULL AS OFFICE_TOLL_FREE_PHONE,
NULL AS OFFICE_FAX,
''PA'' || '' - '' || ''UNKNOWN'' ||  '' ('' || -1 || '')''  AS DETAILED_OFFICE_NAME,
12 AS REGION_NUMBER,
''PENNSYLVANIA'' AS REGION_NAME,
NULL AS REGION_MANAGER,
NULL AS REGION_MANAGER_EMPLOYEE_KEY,
NULL AS SUBREGION_NAME,
NULL AS PRIMARY_BRANCH_MANAGER_NAME,
NULL AS PRIMARY_BRANCH_EMAIL,
NULL AS PRIMARY_BRANCH_MANAGER_EMPLOYEE_KEY,
NULL AS SECONDARY_BRANCH_MANAGER_NAME,
NULL AS SECONDARY_BRANCH_EMAIL,
NULL AS SECONDARY_BRANCH_MANAGER_EMPLOYEE_KEY,
NULL AS RISKCONNECT_NODE_KEY,
NULL AS RISKCONNECT_NAME,
NULL AS HR_OFFICE_NUMBER,
NULL AS HR_OFFICE_NAME,
FALSE AS ACTIVE_FLAG,
TO_DATE(''1900-01-01'', ''YYYY-MM-DD'') AS EFFECTIVE_FROM_DATE,
TO_DATE(''9999-12-31'', ''YYYY-MM-DD'') AS EFFECTIVE_TO_DATE,
:STR_ETL_TASK_KEY AS ETL_TASK_KEY,
:STR_ETL_TASK_KEY AS ETL_INSERTED_TASK_KEY,
convert_timezone(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ AS ETL_INSERTED_DATE,
CURRENT_USER AS ETL_INSERTED_BY,
convert_timezone(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ AS ETL_LAST_UPDATED_DATE,
CURRENT_USER AS ETL_LAST_UPDATED_BY,
FALSE AS ETL_DELETED_FLAG,
FALSE AS ETL_INFERRED_MEMBER_FLAG 
UNION
--NO RESPECTIVE VALUE FOR COLUMN  -  LOCATIONID(-1) FOR TABLE DISC_PROD.SANDATAIMPORT.SANDATA_VISITS
SELECT 
md5( ''8485'' || ''-'' || ''-1'' || ''-'' || ''SANDATAIMPORT'') AS BRANCH_KEY,
''UNKNOWN'' AS BRANCH_NAME ,
''8485'' AS SYSTEM_CODE,
4 AS SOURCE_SYSTEM_ID,
''AMS'' AS SOURCE_SYSTEM_TYPE,
-1 AS OFFICE_NUMBER,
-1 AS OFFICE_CODE,
''UNKNOWN'' AS OFFICE_NAME,
''UNKNOWN'' AS OFFICE_NAME_ALT,
NULL AS DEPARTMENT_NAME,
NULL AS BRANCH_SERVICE_LINE,
FALSE AS PARENT_FLAG,
md5( ''8485'' || ''-'' || ''-1'' || ''-'' || ''SANDATAIMPORT'') AS PARENT_BRANCH_KEY,
-1 AS PARENT_OFFICE_NUMBER,
-1 AS PARENT_OFFICE_CODE,
''PA'' || '' - '' || ''UNKNOWN'' ||  '' ('' || -1 || '')''  AS PARENT_BRANCH_NAME,
NULL AS OFFICE_ADDRESS1,
NULL AS OFFICE_ADDRESS2,
NULL AS OFFICE_CITY,
''PA'' AS OFFICE_STATE_CODE,
NULL AS OFFICE_ZIP,
NULL AS OFFICE_PHONE,
NULL AS OFFICE_TOLL_FREE_PHONE,
NULL AS OFFICE_FAX,
''PA'' || '' - '' || ''UNKNOWN'' ||  '' ('' || -1 || '')'' AS DETAILED_OFFICE_NAME,
12 AS REGION_NUMBER,
''PENNSYLVANIA'' AS REGION_NAME,
NULL AS REGION_MANAGER,
NULL AS REGION_MANAGER_EMPLOYEE_KEY,
NULL AS SUBREGION_NAME,
NULL AS PRIMARY_BRANCH_MANAGER_NAME,
NULL AS PRIMARY_BRANCH_EMAIL,
NULL AS PRIMARY_BRANCH_MANAGER_EMPLOYEE_KEY,
NULL AS SECONDARY_BRANCH_MANAGER_NAME,
NULL AS SECONDARY_BRANCH_EMAIL,
NULL AS SECONDARY_BRANCH_MANAGER_EMPLOYEE_KEY,
NULL AS RISKCONNECT_NODE_KEY,
NULL AS RISKCONNECT_NAME,
NULL AS HR_OFFICE_NUMBER,
NULL AS HR_OFFICE_NAME,
FALSE AS ACTIVE_FLAG,
TO_DATE(''1900-01-01'', ''YYYY-MM-DD'') AS EFFECTIVE_FROM_DATE,
TO_DATE(''9999-12-31'', ''YYYY-MM-DD'') AS EFFECTIVE_TO_DATE,
:STR_ETL_TASK_KEY AS ETL_TASK_KEY,
:STR_ETL_TASK_KEY AS ETL_INSERTED_TASK_KEY,
convert_timezone(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ AS ETL_INSERTED_DATE,
CURRENT_USER AS ETL_INSERTED_BY,
convert_timezone(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ AS ETL_LAST_UPDATED_DATE,
CURRENT_USER AS ETL_LAST_UPDATED_BY,
FALSE AS ETL_DELETED_FLAG,
FALSE AS ETL_INFERRED_MEMBER_FLAG ;
SELECT CONCAT (''MESSAGE : '',"number of rows inserted",'' Rows Inserted.'') into :return_result FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));
	RETURN return_result;
    END;
    ';