CREATE OR REPLACE PROCEDURE DW_PROD.HAH.DELETE_STAGE_EDISON_DIM_VISIT_STATUS_MAPPING()
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
  RETURN_RESULT VARCHAR(1000);
BEGIN
  DELETE FROM DW_PROD.HAH.DIM_VISIT_STATUS_MAPPING WHERE SOURCE_SYSTEM_ID= 17 AND SYSTEM_CODE =''EDISON'' AND VISIT_STATUS_KEY 
  NOT IN (SELECT VISIT_STATUS_KEY FROM DW_PROD.STAGE.EDISON_DIM_VISIT_STATUS_MAPPING);
  SELECT CONCAT (''MESSAGE : '',"number of rows deleted",'' Rows Deleted.'') into :return_result FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));
	RETURN return_result;
  END;
';