CREATE OR REPLACE PROCEDURE DW_PROD.HAH.GET_STAGE_CCSI_DIM_INVOICE_STATUS_MAPPING("STR_ETL_TASK_KEY" VARCHAR(16777216), "STR_CDC_START" VARCHAR(16777216), "STR_CDC_END" VARCHAR(16777216))
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
BEGIN
--*****************************************************************************************************************************
-- DEVELOPMENT LOG:
-- DATE        AUTHOR                NOTES:
-- --------    -------------------   -----------------------------------------------------------------------------------------------
-- 21/04/23    Pinkal Panchal        Initial Development
--*****************************************************************************************************************************

INSERT OVERWRITE INTO STAGE.CCSI_DIM_INVOICE_STATUS_MAPPING
WITH DIM_CLIENT AS
(  
SELECT CLIENT_IDOA_NO,USED_FOR_AREA,MASTER_ID FROM (SELECT CLIENT_IDOA_NO ,USED_FOR_AREA,
(RECORD_NUMBER  || ''-'' ||  NVL(USED_FOR_AREA, ''CCSI'') || ''-'' || ''CCSI'') AS MASTER_ID,''MASTER'' AS TYPE,
ROW_NUMBER () OVER (PARTITION BY CLIENT_IDOA_NO ,USED_FOR_AREA ORDER BY TRY_TO_DATE(UPDATED_DATE,''MM/DD/YY'') DESC
,TRY_TO_DATE(CREATED_DATE,''MM/DD/YY'') DESC,TRY_TO_DATE(ACTION_DATE,''YYYYMMDD'') DESC,RECORD_NUMBER DESC) AS RN
FROM DISC_DEDUPE_PROD.CCSI.CLIENT_MASTER_LIST_CCSI) WHERE RN=1
UNION
SELECT CLIENT_IDOA_NO,USED_FOR_AREA,MASTER_ID FROM (SELECT CLIENT_IDOA_NO,USED_FOR_AREA,
(MASTER_ID) AS MASTER_ID,''MATCH'' AS TYPE,
ROW_NUMBER() OVER (PARTITION BY CLIENT_IDOA_NO ,USED_FOR_AREA ORDER BY TRY_TO_DATE(UPDATED_DATE,''MM/DD/YY'') DESC
,TRY_TO_DATE(CREATED_DATE,''MM/DD/YY'') DESC,TRY_TO_DATE(ACTION_DATE,''YYYYMMDD'') DESC,RECORD_NUMBER DESC) AS RN 
FROM (SELECT * FROM DISC_DEDUPE_PROD.CCSI.CLIENT_MATCH_LIST_CCSI M WHERE NOT EXISTS (SELECT * FROM
DISC_DEDUPE_PROD.CCSI.CLIENT_MASTER_LIST_CCSI MA WHERE M.CLIENT_IDOA_NO= MA.CLIENT_IDOA_NO AND 
M.USED_FOR_AREA = MA.USED_FOR_AREA)))
)
, RAWVRFP_Data AS
(
SELECT DISTINCT RECORD_NUMBER
                ,CLIENT_ID
                ,AREA_2
                ,TRY_TO_DATE(PERIOD_DATE, ''MMDDYY'') AS PERIOD_DATE
FROM DISC_PROD.CCSI.RAWVRFP 
WHERE PERIOD_DATE IS NOT NULL
            AND TRY_TO_DATE(PERIOD_DATE, ''MMDDYY'') > ''2015-12-31''
            AND DAY_OF_SERVICE  IS NOT NULL
            AND CLIENT_ID IS NOT NULL
            AND SERVICE_TYPE = ''021''
)
, INVOICE_STATUS_MAPPING AS 
(
SELECT 
    MIN(RECORD_NUMBER)||''MCOINV'' AS INVOICE_NUMBER,
    C.CLIENT_IDOA_NO,C.USED_FOR_AREA,B.BRANCH_CODE,
    CASE WHEN LENGTH(SERVICE_MONTH)>6 THEN LEFT(TRIM(REGEXP_REPLACE(SERVICE_MONTH,''\\\\-|\\\\(|\\\\/|\\\\ |[a-zA-z.]'','''')),6)
    ELSE TRIM(REGEXP_REPLACE(SERVICE_MONTH,''\\\\-|\\\\(|\\\\/|\\\\ |[a-zA-z.]'','''')) END AS PERIOD,
    CASE WHEN SUM(M.DOLLAR_AMOUNT) = SUM(M.BALANCE) THEN ''BILLED''
        WHEN SUM(M.BALANCE) <= 0 THEN ''PAID''
        WHEN SUM(M.BALANCE) > 0 THEN ''PARTIAL PAY''
        ELSE ''UNKNOWN'' 
    END AS DERIVED_INVOICE_STATUS
FROM DISC_PROD.CCSI.MCOINV AS M
LEFT JOIN DISC_PROD.CCSI.BRANCH_MAPPING B ON M.CCSI_OFFICE = B.BRANCH_CODE 
JOIN DIM_CLIENT C ON C.CLIENT_IDOA_NO = M.CLIENT_ID AND M.CCSI_OFFICE = C.USED_FOR_AREA 
GROUP BY 2,3,4,5
UNION 
SELECT
    MIN(RECORD_NUMBER)||''OTHERINV'' AS INVOICE_NUMBER,
    C.CLIENT_IDOA_NO,C.USED_FOR_AREA,B.BRANCH_CODE,
    CASE WHEN LENGTH(O.DATE_OF_SERVICE)>6 THEN LEFT(TRIM(REGEXP_REPLACE(O.DATE_OF_SERVICE,''\\\\-|\\\\(|\\\\/|\\\\ |[a-zA-z.]'','''')),6)
    ELSE TRIM(REGEXP_REPLACE(O.DATE_OF_SERVICE,''\\\\-|\\\\(|\\\\/|\\\\ |[a-zA-z.]'','''')) END AS PERIOD,
    CASE  WHEN SUM(O.AMOUNT_BILLED) = SUM(O.BALANCE) THEN ''BILLED''
        WHEN SUM(O.BALANCE) <= 0 THEN ''PAID''
        WHEN SUM(O.BALANCE) > 0 THEN ''PARTIAL PAY''
        ELSE ''UNKNOWN'' 
    END AS DERIVED_INVOICE_STATUS
FROM DISC_PROD.CCSI.OTHERINV AS O
LEFT JOIN DISC_PROD.CCSI.BRANCH_MAPPING B ON O.AREA  = B.BRANCH_CODE 
JOIN DIM_CLIENT C ON C.CLIENT_IDOA_NO = O.CLIENT_ID AND O.AREA = C.USED_FOR_AREA
GROUP BY 2,3,4,5
UNION 
SELECT 
    (R.RECORD_NUMBER || R.CLIENT_ID) AS INVOICE_NUMBER,
    C.CLIENT_IDOA_NO,C.USED_FOR_AREA,B.BRANCH_CODE,
    TO_CHAR(PERIOD_DATE, ''YYYYMM'') AS PERIOD,
    ''UNKNOWN'' AS DERIVED_INVOICE_STATUS
FROM RAWVRFP_Data R
LEFT JOIN DISC_PROD.CCSI.BRANCH_MAPPING B ON R.AREA_2 = B.BRANCH_CODE 
JOIN DIM_CLIENT C ON R.CLIENT_ID = C.CLIENT_IDOA_NO AND R.AREA_2 = C.USED_FOR_AREA 
)
SELECT DISTINCT
    8 AS SOURCE_SYSTEM_ID,
    ''CCSI'' AS SYSTEM_CODE,
    INV.DERIVED_INVOICE_STATUS,
    MD5(SOURCE_SYSTEM_ID || ''-'' || INV.DERIVED_INVOICE_STATUS || ''-'' || SYSTEM_CODE) AS INVOICE_STATUS_KEY,
     ---- ETL FIELDS
    :STR_ETL_TASK_KEY AS ETL_TASK_KEY,
    :STR_ETL_TASK_KEY AS ETL_INSERTED_TASK_KEY,                    
    convert_timezone(''UTC'', CURRENT_TIMESTAMP)::timestamp_ntz as ETL_INSERTED_DATE,
    CURRENT_USER as ETL_INSERTED_BY,
    convert_timezone(''UTC'', CURRENT_TIMESTAMP)::timestamp_ntz as ETL_LAST_UPDATED_DATE,
    CURRENT_USER as ETL_LAST_UPDATED_BY
FROM INVOICE_STATUS_MAPPING INV
;
RETURN ''SUCCESS'';
END;
';