CREATE OR REPLACE PROCEDURE DW_PROD.HAH.MERGE_STAGE_QUALTRICS_FACT_SURVEY_OPTOUT()
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
BEGIN

MERGE INTO DW_PROD.HAH.FACT_SURVEY_OPTOUT TGT 
USING DW_PROD.STAGE.QUALTRICS_FACT_SURVEY_OPTOUT STAGE 
ON TGT.FACT_SURVEY_OPTOUT_KEY = STAGE.QUALTRICS_FACT_SURVEY_OPTOUT_KEY
WHEN MATCHED THEN 
UPDATE SET 
    TGT.CONTACTID= STAGE.CONTACTID
   ,TGT.FIRSTNAME= STAGE.FIRSTNAME
   ,TGT.LASTNAME = STAGE.LASTNAME 
   ,TGT.EMPLOYEE_KEY= STAGE.EMPLOYEE_KEY
   ,TGT.wh_EMPLOYEE_KEY= STAGE.wh_EMPLOYEE_KEY
   ,TGT.CLIENT_KEY= STAGE.CLIENT_KEY
   ,TGT.wh_CLIENT_KEY= STAGE.wh_CLIENT_KEY
   ,TGT.UNSUBSCRIBE_START_DATE= STAGE.UNSUBSCRIBE_START_DATE
   ,TGT.UNSUBSCRIBE_END_DATE= STAGE.UNSUBSCRIBE_END_DATE
   ,TGT.SOURCE_SYSTEM_ID= STAGE.SOURCE_SYSTEM_ID
   ,TGT.source_system_code= STAGE.source_system_code
   ,TGT.ETL_TASK_KEY= STAGE.ETL_TASK_KEY
   ,TGT.ETL_INSERTED_DATE= STAGE.ETL_INSERTED_DATE
   ,TGT.ETL_INSERTED_BY= STAGE.ETL_INSERTED_BY
   ,TGT.ETL_LAST_UPDATED_DATE= STAGE.ETL_LAST_UPDATED_DATE
   ,TGT.ETL_LAST_UPDATED_BY= STAGE.ETL_LAST_UPDATED_BY
   ,TGT.ETL_DELETED_FLAG= STAGE.ETL_DELETED_FLAG   
   
WHEN NOT MATCHED THEN 
INSERT ( 
    FACT_SURVEY_OPTOUT_KEY,
    CONTACTID,
	FIRSTNAME,
    LASTNAME,
    EMPLOYEE_KEY,
    wh_EMPLOYEE_KEY,
    CLIENT_KEY,
    wh_CLIENT_KEY,
    UNSUBSCRIBE_START_DATE,
    UNSUBSCRIBE_END_DATE,
    SOURCE_SYSTEM_ID,
    source_system_code, 
	ETL_TASK_KEY,
	ETL_INSERTED_DATE,
	ETL_INSERTED_BY,
	ETL_LAST_UPDATED_DATE,
	ETL_LAST_UPDATED_BY,
	ETL_DELETED_FLAG
) 
VALUES ( 
        STAGE.QUALTRICS_FACT_SURVEY_OPTOUT_KEY,
    STAGE.CONTACTID,
	STAGE.FIRSTNAME,
    STAGE.LASTNAME,
    STAGE.EMPLOYEE_KEY,
    STAGE.wh_EMPLOYEE_KEY,
    STAGE.CLIENT_KEY,
    STAGE.wh_CLIENT_KEY, 
    STAGE.UNSUBSCRIBE_START_DATE,
    STAGE.UNSUBSCRIBE_END_DATE,
    STAGE.SOURCE_SYSTEM_ID,
    STAGE.source_system_code, 
	STAGE.ETL_TASK_KEY,
	STAGE.ETL_INSERTED_DATE,
	STAGE.ETL_INSERTED_BY,
	STAGE.ETL_LAST_UPDATED_DATE,
	STAGE.ETL_LAST_UPDATED_BY,
	STAGE.ETL_DELETED_FLAG
	
);

END;
';