CREATE OR REPLACE PROCEDURE DW_PROD.HAH.DELETE_STAGE_EMPEONEDISON_DIM_PAYCODE_MAPPING()
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
  RETURN_RESULT VARCHAR;
BEGIN
		DELETE FROM HAH.DIM_PAYCODE_MAPPING 
		WHERE SOURCE_SYSTEM_ID = 22 AND SYSTEM_CODE LIKE ''%EMPEONEDISON'' AND PAYCODE_MAPPING_KEY
    	NOT IN (SELECT PAYCODE_MAPPING_KEY FROM STAGE.EMPEONEDISON_DIM_PAYCODE_MAPPING);
	SELECT CONCAT(''Message : '',"number of rows deleted", '' Rows Deleted.'') into :return_result FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));
	RETURN RETURN_RESULT;
END;
';