CREATE OR REPLACE PROCEDURE DW_PROD.HAH.DELETE_STAGE_OSHAH_DIM_BRANCH()
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
BEGIN
 
DELETE FROM DW_PROD.HAH.DIM_BRANCH WHERE SOURCE_SYSTEM_ID =17 AND SYSTEM_CODE  ILIKE ''%OSHAH%''
  AND BRANCH_KEY  NOT IN (SELECT BRANCH_KEY FROM DW_PROD.STAGE.OSHAH_DIM_BRANCH);
RETURN ''SUCCESS'';
END;
';