CREATE OR REPLACE PROCEDURE DW_PROD.HAH.MERGE_STAGE_ZENDESK_FACT_TICKET()
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
  RETURN_RESULT VARCHAR(1000);
BEGIN
    MERGE INTO HAH.FACT_TICKET TGT 
	USING STAGE.ZENDESK_FACT_TICKET STG 
	ON TGT.TICKET_KEY = STG.TICKET_KEY
	WHEN MATCHED THEN 
	UPDATE SET 
		 TGT.SYSTEM_CODE = STG.SYSTEM_CODE
		,TGT.TICKET_KEY = STG.TICKET_KEY
		,TGT.ID = STG.ID
		,TGT.SOURCE_SYSTEM_ID = STG.SOURCE_SYSTEM_ID
		,TGT.VIA = STG.VIA
		,TGT.STATUS = STG.STATUS
		,TGT.PRIORITY = STG.PRIORITY
		,TGT.TYPE = STG.TYPE
		,TGT.REQUESTER_ID = STG.REQUESTER_ID
		,TGT.SUBMITTER_ID = STG.SUBMITTER_ID
		,TGT.WH_EMPLOYEE_KEY = STG.WH_EMPLOYEE_KEY
		,TGT.EMPLOYEE_KEY = STG.EMPLOYEE_KEY
		,TGT.SUBMITTER_KEY = STG.SUBMITTER_KEY
		,TGT.ASSIGNEE_ID = STG.ASSIGNEE_ID
		,TGT.ASSIGNEE_NAME = STG.ASSIGNEE_NAME
		,TGT.RECIPIENT = STG.RECIPIENT
		,TGT.SATISFACTION_RATING = STG.SATISFACTION_RATING
		,TGT.IS_PUBLIC = STG.IS_PUBLIC
		,TGT.SUBJECT = STG.SUBJECT
		,TGT.DESCRIPTION = STG.DESCRIPTION
		,TGT.ORGANIZATION_ID = STG.ORGANIZATION_ID
		,TGT.BRANCH_KEY = STG.BRANCH_KEY
		,TGT.OFFICE_STATE_CODE = STG.OFFICE_STATE_CODE
		,TGT.BRAND_ID = STG.BRAND_ID
		,TGT.COLLABORATOR_IDS = STG.COLLABORATOR_IDS
		,TGT.EMAIL_CC_IDS = STG.EMAIL_CC_IDS
		,TGT.EXTERNAL_ID = STG.EXTERNAL_ID
		,TGT.FOLLOWER_IDS = STG.FOLLOWER_IDS
		,TGT.FOLLOWUP_IDS = STG.FOLLOWUP_IDS
		,TGT.GROUP_ID = STG.GROUP_ID
		,TGT.GROUP_TITLE = STG.GROUP_TITLE
		,TGT.GROUP_DESCRIPTION = STG.GROUP_DESCRIPTION
		,TGT.SHARING_AGREEMENT_IDS = STG.SHARING_AGREEMENT_IDS
		,TGT.TICKET_FORM_ID = STG.TICKET_FORM_ID
		,TGT.TICKET_FORM_NAME = STG.TICKET_FORM_NAME
		,TGT.URL = STG.URL
		,TGT.CREATED_AT = STG.CREATED_AT
		,TGT.UPDATED_AT = STG.UPDATED_AT
        ,TGT.TKT_METRICS_ID = STG.TKT_METRICS_ID
		,TGT.FIRST_RESOLUTION_TIME_IN_MINUTES_CALENDAR = STG.FIRST_RESOLUTION_TIME_IN_MINUTES_CALENDAR
		,TGT.REPLY_TIME_IN_MINUTES_CALENDAR = STG.REPLY_TIME_IN_MINUTES_CALENDAR
		,TGT.FULL_RESOLUTION_TIME_IN_MINUTES_CALENDAR = STG.FULL_RESOLUTION_TIME_IN_MINUTES_CALENDAR
		,TGT.REQUESTER_WAIT_TIME_IN_MINUTES_CALENDAR = STG.REQUESTER_WAIT_TIME_IN_MINUTES_CALENDAR
		,TGT.ON_HOLD_TIME_IN_MINUTES_CALENDAR = STG.ON_HOLD_TIME_IN_MINUTES_CALENDAR
		,TGT.AGENT_WAIT_TIME_IN_MINUTES_CALENDAR = STG.AGENT_WAIT_TIME_IN_MINUTES_CALENDAR
		,TGT.REOPENS = STG.REOPENS
		,TGT.REPLIES = STG.REPLIES
		,TGT.GROUP_STATIONS = STG.GROUP_STATIONS
		,TGT.ASSIGNEE_STATIONS = STG.ASSIGNEE_STATIONS
		,TGT.ASSIGNEE_UPDATED_AT = STG.ASSIGNEE_UPDATED_AT
		,TGT.REQUESTER_UPDATED_AT = STG.REQUESTER_UPDATED_AT
		,TGT.STATUS_UPDATED_AT = STG.STATUS_UPDATED_AT
		,TGT.INITIALLY_ASSIGNED_AT = STG.INITIALLY_ASSIGNED_AT
		,TGT.ASSIGNED_AT = STG.ASSIGNED_AT
		,TGT.SOLVED_AT = STG.SOLVED_AT
		,TGT.LATEST_COMMENT_ADDED_AT = STG.LATEST_COMMENT_ADDED_AT
		,TGT.CUSTOM_STATUS_UPDATED_AT = STG.CUSTOM_STATUS_UPDATED_AT
		,TGT.URL_TKT_METRICS = STG.URL_TKT_METRICS
		,TGT.EMPLOYEE_TYPE = STG.EMPLOYEE_TYPE
		,TGT.CALLER_TYPE = STG.CALLER_TYPE
		,TGT.REQUESTER_NAME = STG.REQUESTER_NAME
		,TGT.REQUESTER_PHONE_NUMBER = STG.REQUESTER_PHONE_NUMBER
		,TGT.REQUESTER_PHONE_NUMBER_CALLMAX = STG.REQUESTER_PHONE_NUMBER_CALLMAX
		,TGT.REQUESTER_EMAIL = STG.REQUESTER_EMAIL
		,TGT.CAREGIVER_NAME = STG.CAREGIVER_NAME
		,TGT.CLIENT_NAME = STG.CLIENT_NAME
		,TGT.CALL_MAX_CALL_NOTES = STG.CALL_MAX_CALL_NOTES
		,TGT.RESOLUTION_COMMENT = STG.RESOLUTION_COMMENT
		,TGT.TOTAL_TIME_SPENT = STG.TOTAL_TIME_SPENT
		,TGT.TIME_SPENT_LAST_UPDATE = STG.TIME_SPENT_LAST_UPDATE
		,TGT.SYSTEM = STG.SYSTEM
		,TGT.TICKET_CASE_TYPE = STG.TICKET_CASE_TYPE
		,TGT.MARKET = STG.MARKET
        ,TGT.PROBLEM_TYPE = STG.PROBLEM_TYPE
		,TGT.ETL_TASK_KEY = STG.ETL_TASK_KEY
		,TGT.ETL_LAST_UPDATED_DATE = STG.ETL_LAST_UPDATED_DATE
		,TGT.ETL_LAST_UPDATED_BY = STG.ETL_LAST_UPDATED_BY
		,TGT.ETL_DELETED_FLAG = STG.ETL_DELETED_FLAG    
	WHEN NOT MATCHED THEN 
	INSERT (
		 SYSTEM_CODE
		,TICKET_KEY
		,ID
		,SOURCE_SYSTEM_ID
		,VIA
		,STATUS
		,PRIORITY
		,TYPE
		,REQUESTER_ID
		,SUBMITTER_ID
		,WH_EMPLOYEE_KEY
		,EMPLOYEE_KEY
		,SUBMITTER_KEY
		,ASSIGNEE_ID
		,ASSIGNEE_NAME
		,RECIPIENT
		,SATISFACTION_RATING
		,IS_PUBLIC
		,SUBJECT
		,DESCRIPTION
		,ORGANIZATION_ID
		,BRANCH_KEY
		,OFFICE_STATE_CODE
		,BRAND_ID
		,COLLABORATOR_IDS
		,EMAIL_CC_IDS
		,EXTERNAL_ID
		,FOLLOWER_IDS
		,FOLLOWUP_IDS
		,GROUP_ID
		,GROUP_TITLE
		,GROUP_DESCRIPTION
		,SHARING_AGREEMENT_IDS
		,TICKET_FORM_ID
		,TICKET_FORM_NAME
		,URL
		,CREATED_AT
		,UPDATED_AT
		,TKT_METRICS_ID
		,FIRST_RESOLUTION_TIME_IN_MINUTES_CALENDAR
		,REPLY_TIME_IN_MINUTES_CALENDAR
		,FULL_RESOLUTION_TIME_IN_MINUTES_CALENDAR
		,REQUESTER_WAIT_TIME_IN_MINUTES_CALENDAR
		,ON_HOLD_TIME_IN_MINUTES_CALENDAR
		,AGENT_WAIT_TIME_IN_MINUTES_CALENDAR
		,REOPENS
		,REPLIES
		,GROUP_STATIONS
		,ASSIGNEE_STATIONS
		,ASSIGNEE_UPDATED_AT
		,REQUESTER_UPDATED_AT
		,STATUS_UPDATED_AT
		,INITIALLY_ASSIGNED_AT
		,ASSIGNED_AT
		,SOLVED_AT
		,LATEST_COMMENT_ADDED_AT
		,CUSTOM_STATUS_UPDATED_AT
		,URL_TKT_METRICS,
		EMPLOYEE_TYPE,
		CALLER_TYPE,
		REQUESTER_NAME,
		REQUESTER_PHONE_NUMBER,
		REQUESTER_PHONE_NUMBER_CALLMAX,
		REQUESTER_EMAIL,
		CAREGIVER_NAME,
		CLIENT_NAME,
		CALL_MAX_CALL_NOTES,
		RESOLUTION_COMMENT,
		TOTAL_TIME_SPENT,
		TIME_SPENT_LAST_UPDATE,
		SYSTEM,
		TICKET_CASE_TYPE,
		MARKET
        ,PROBLEM_TYPE
		,ETL_TASK_KEY
		,ETL_INSERTED_TASK_KEY
		,ETL_INSERTED_DATE
		,ETL_INSERTED_BY
		,ETL_LAST_UPDATED_DATE
		,ETL_LAST_UPDATED_BY
		,ETL_DELETED_FLAG
		) 
	VALUES (
		 STG.SYSTEM_CODE
		,STG.TICKET_KEY
		,STG.ID
		,STG.SOURCE_SYSTEM_ID
		,STG.VIA
		,STG.STATUS
		,STG.PRIORITY
		,STG.TYPE
		,STG.REQUESTER_ID
		,STG.SUBMITTER_ID
		,STG.WH_EMPLOYEE_KEY
		,STG.EMPLOYEE_KEY
		,STG.SUBMITTER_KEY
		,STG.ASSIGNEE_ID
		,STG.ASSIGNEE_NAME
		,STG.RECIPIENT
		,STG.SATISFACTION_RATING
		,STG.IS_PUBLIC
		,STG.SUBJECT
		,STG.DESCRIPTION
		,STG.ORGANIZATION_ID
		,STG.BRANCH_KEY
		,STG.OFFICE_STATE_CODE
		,STG.BRAND_ID
		,STG.COLLABORATOR_IDS
		,STG.EMAIL_CC_IDS
		,STG.EXTERNAL_ID
		,STG.FOLLOWER_IDS
		,STG.FOLLOWUP_IDS
		,STG.GROUP_ID
		,STG.GROUP_TITLE
		,STG.GROUP_DESCRIPTION
		,STG.SHARING_AGREEMENT_IDS
		,STG.TICKET_FORM_ID
		,STG.TICKET_FORM_NAME
		,STG.URL
		,STG.CREATED_AT
		,STG.UPDATED_AT
		,STG.TKT_METRICS_ID
		,STG.FIRST_RESOLUTION_TIME_IN_MINUTES_CALENDAR
		,STG.REPLY_TIME_IN_MINUTES_CALENDAR
		,STG.FULL_RESOLUTION_TIME_IN_MINUTES_CALENDAR
		,STG.REQUESTER_WAIT_TIME_IN_MINUTES_CALENDAR
		,STG.ON_HOLD_TIME_IN_MINUTES_CALENDAR
		,STG.AGENT_WAIT_TIME_IN_MINUTES_CALENDAR
		,STG.REOPENS
		,STG.REPLIES
		,STG.GROUP_STATIONS
		,STG.ASSIGNEE_STATIONS
		,STG.ASSIGNEE_UPDATED_AT
		,STG.REQUESTER_UPDATED_AT
		,STG.STATUS_UPDATED_AT
		,STG.INITIALLY_ASSIGNED_AT
		,STG.ASSIGNED_AT
		,STG.SOLVED_AT
		,STG.LATEST_COMMENT_ADDED_AT
		,STG.CUSTOM_STATUS_UPDATED_AT
		,STG.URL_TKT_METRICS
		,STG.EMPLOYEE_TYPE
		,STG.CALLER_TYPE
		,STG.REQUESTER_NAME
		,STG.REQUESTER_PHONE_NUMBER
		,STG.REQUESTER_PHONE_NUMBER_CALLMAX
		,STG.REQUESTER_EMAIL
		,STG.CAREGIVER_NAME
		,STG.CLIENT_NAME
		,STG.CALL_MAX_CALL_NOTES
		,STG.RESOLUTION_COMMENT
		,STG.TOTAL_TIME_SPENT
		,STG.TIME_SPENT_LAST_UPDATE
		,STG.SYSTEM
		,STG.TICKET_CASE_TYPE
		,STG.MARKET
        ,STG.PROBLEM_TYPE
		,STG.ETL_TASK_KEY
		,STG.ETL_INSERTED_TASK_KEY
		,STG.ETL_INSERTED_DATE
		,STG.ETL_INSERTED_BY
		,STG.ETL_LAST_UPDATED_DATE
		,STG.ETL_LAST_UPDATED_BY
		,STG.ETL_DELETED_FLAG
		);
SELECT CONCAT (''MESSAGE : '',"number of rows inserted",'' Rows Inserted & '',"number of rows updated",'' Rows Updated. '') into :return_result FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));
	RETURN return_result;
END;
    ';