CREATE OR REPLACE PROCEDURE DW_PROD.HAH.DELETE_STAGE_OSHAH_FACT_VISIT()
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
BEGIN
DELETE FROM DW_PROD.HAH.FACT_VISIT WHERE SOURCE_SYSTEM_ID =17 AND SYSTEM_CODE ILIKE ''%OSHAH%'' AND VISIT_KEY
  NOT IN (SELECT VISIT_KEY FROM DW_PROD.STAGE.OSHAH_FACT_VISIT);
RETURN ''SUCCESS'';
END;
';