CREATE OR REPLACE PROCEDURE DW_PROD.HAH.DELETE_STAGE_COSTALSYNCDATA_FACT_PARTNER_CONTRACT_SERVICE()
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
    RETURN_RESULT VARCHAR;
BEGIN
DELETE FROM DW_PROD.HAH.FACT_PARTNER_CONTRACT_SERVICE WHERE SOURCE_SYSTEM_ID IN(1,2)
AND PARTNER_CONTRACT_SERVICE_KEY  NOT IN (SELECT PARTNER_CONTRACT_SERVICE_KEY FROM DW_PROD."STAGE".COSTALSYNCDATA_FACT_PARTNER_CONTRACT_SERVICE);
SELECT CONCAT(''Message : '',"number of rows deleted", '' Rows Deleted.'') into :return_result FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));
return return_result;
END;
';