CREATE OR REPLACE PROCEDURE DW_PROD.HAH.GET_STAGE_OPENSYSTEMS_FACT_CLIENT_SERVICE_BKCP2610("STR_ETL_TASK_KEY" VARCHAR(16777216), "STR_CDC_START" VARCHAR(16777216), "STR_CDC_END" VARCHAR(16777216))
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
    return_result VARCHAR;
BEGIN
--*****************************************************************************************************************************
-- NAME:  OPENSYSTEMS FACT CLIENT SERVICE
--
-- PURPOSE: Populates Stage OPENSYSTEMS FACT CLIENT SERVICE
--
--
-- DEVELOPMENT LOG:
-- DATE        AUTHOR                NOTES:
-- --------    -------------------   -----------------------------------------------------------------------------------------------
-- 2/28/23     SANKET JAIN           Initial version
--*****************************************************************************************************************************
	
INSERT OVERWRITE INTO DW_PROD."STAGE".OPENSYSTEMS_FACT_CLIENT_SERVICE_bkcp2610
WITH CLIENT AS
(SELECT * FROM
	(SELECT PATIENTID, MASTER_ID, AGENCYID, LASTNAME, FIRSTNAME, OFFICEID 
	 FROM DISC_DEDUPE_PROD.HHAEXCHANGEOPENSYSTEMS.CLIENT_MASTER_LIST)
UNION
SELECT * FROM
    (SELECT DISTINCT CML.PATIENTID, MASTER_ID, CML.AGENCYID, CML.LASTNAME, CML.FIRSTNAME, CML.OFFICEID
	 FROM DISC_DEDUPE_PROD.HHAEXCHANGEOPENSYSTEMS.CLIENT_MATCH_LIST CML
	 WHERE CML.PATIENTID NOT IN (SELECT PATIENTID FROM DISC_DEDUPE_PROD.HHAEXCHANGEOPENSYSTEMS.CLIENT_MASTER_LIST))
),
Capping_Hours_at24_Per_Day AS (
SELECT AUTHORIZATIONID
   	 , PA.PATIENTID
   	 , PA.SERVICECODEID
   	 , DD.CALENDAR_DATE
   	 , DECODE(DAYNAME(DD.CALENDAR_DATE)
   				 , ''Sat'', PA.SATHOURS
   		   		 , ''Sun'', PA.SUNHOURS
   		   		 , ''Mon'', PA.MONHOURS
   		   		 , ''Tue'', PA.TUEHOURS
   		   		 , ''Wed'', PA.WEDHOURS
   		   		 , ''Thu'', PA.THUHOURS
   		   		 , ''Fri'', PA.FRIHOURS
   		   	 , 0) AS AUTH_HOURS_PER_DAY
   	 , DECODE(DAYNAME(DD.CALENDAR_DATE)
   				 , ''Sat'', IFF(PA.SATHOURS>0,1,0)
   		   		 , ''Sun'', IFF(PA.SUNHOURS>0,1,0)
   		   		 , ''Mon'', IFF(PA.MONHOURS>0,1,0)
   		   		 , ''Tue'', IFF(PA.TUEHOURS>0,1,0)
   		   		 , ''Wed'', IFF(PA.WEDHOURS>0,1,0)
   		   		 , ''Thu'', IFF(PA.THUHOURS>0,1,0)
   		   		 , ''Fri'', IFF(PA.FRIHOURS>0,1,0)
   		   	 , 0) AS DAYS
--	 , IFF(AUTH_HOURS_PER_DAY >24, 24, AUTH_HOURS_PER_DAY) AS HOURS_AUTHORIZED 
     , AUTH_HOURS_PER_DAY as HOURS_AUTHORIZED
	 , AUTH_HOURS_PER_DAY AS HOURS_AUTHORIZED_NON_ADJUSTED
	 , IFF(AUTH_HOURS_PER_DAY >24,TRUE,FALSE) AS FLAG
FROM DISC_PROD.HHAEXCHANGEOPENSYSTEMS.PATIENTAUTHORIZATION  PA
INNER JOIN DW_PROD.HAH.DIM_DATE DD
    ON DD.CALENDAR_DATE BETWEEN PA.FROMDATE AND PA.TODATE
WHERE PERIOD = ''Day''
UNION ALL
SELECT PA.AUTHORIZATIONID
   	 , PA.PATIENTID
   	 , PA.SERVICECODEID
   	 , DD.CALENDAR_DATE
   	 , PA.MAXUNITSFORPERIOD/7.00 AS AUTH_HOURS_PER_DAY
   	 , 1 AS DAYS
--   	 , IFF(AUTH_HOURS_PER_DAY >24, 24, AUTH_HOURS_PER_DAY) AS HOURS_AUTHORIZED
     , AUTH_HOURS_PER_DAY as HOURS_AUTHORIZED
   	 , AUTH_HOURS_PER_DAY AS HOURS_AUTHORIZED_NON_ADJUSTED
   	 , IFF(AUTH_HOURS_PER_DAY >24,TRUE,FALSE) AS FLAG
FROM DISC_PROD.HHAEXCHANGEOPENSYSTEMS.PATIENTAUTHORIZATION PA
INNER JOIN DW_PROD.HAH.DIM_DATE DD
    ON DD.CALENDAR_DATE::DATE BETWEEN PA.FROMDATE::DATE AND PA.TODATE::DATE
WHERE PA.PERIOD = ''Week''
UNION ALL
SELECT PA.AUTHORIZATIONID
   	 , PA.PATIENTID
   	 , PA.SERVICECODEID
   	 , DD.CALENDAR_DATE
   	 , PA.MAXUNITSFORPERIOD/(DAY(LAST_DAY(DD.CALENDAR_DATE))*1.00) AS AUTH_HOURS_PER_DAY
   	 , 1 AS DAYS
--   	 , IFF(AUTH_HOURS_PER_DAY >24, 24, AUTH_HOURS_PER_DAY) AS HOURS_AUTHORIZED
     ,AUTH_HOURS_PER_DAY as HOURS_AUTHORIZED
   	 , AUTH_HOURS_PER_DAY AS HOURS_AUTHORIZED_NON_ADJUSTED
   	 , IFF(AUTH_HOURS_PER_DAY >24,TRUE,FALSE) AS FLAG
FROM DISC_PROD.HHAEXCHANGEOPENSYSTEMS.PATIENTAUTHORIZATION PA
INNER JOIN DW_PROD.HAH.DIM_DATE DD
    ON DD.CALENDAR_DATE::DATE BETWEEN PA.FROMDATE::DATE AND PA.TODATE::DATE
WHERE PA.PERIOD = ''Monthly''
UNION ALL
SELECT PA.AUTHORIZATIONID
   	 , PA.PATIENTID
   	 , PA.SERVICECODEID
   	 , DD.CALENDAR_DATE
  	 , CASE WHEN FROMDATE = TODATE 
   	   			 THEN PA.MAXUNITSFORPERIOD
   	   		ELSE PA.MAXUNITSFORPERIOD/IFF(FROMDATE != TODATE, DATEDIFF(DAY, FROMDATE, TODATE)+1, 1) * 1.00
   	   END AUTH_HOURS_PER_DAY
   	 , 1 AS DAYS  
--  	, IFF(AUTH_HOURS_PER_DAY >24, 24, AUTH_HOURS_PER_DAY) AS HOURS_AUTHORIZED
     ,AUTH_HOURS_PER_DAY as HOURS_AUTHORIZED
   	 , AUTH_HOURS_PER_DAY AS HOURS_AUTHORIZED_NON_ADJUSTED
   	 , IFF(AUTH_HOURS_PER_DAY >24,TRUE,FALSE) AS FLAG
FROM DISC_PROD.HHAEXCHANGEOPENSYSTEMS.PATIENTAUTHORIZATION PA
INNER JOIN DW_PROD.HAH.DIM_DATE DD
    ON DD.CALENDAR_DATE::DATE BETWEEN PA.FROMDATE::DATE AND PA.TODATE::DATE
WHERE PERIOD = ''Entire Period'')
,Cleaned_Auth AS
(
    SELECT AO.PATIENTID
   		 , AO.SERVICECODEID
   		 , AO.AUTHORIZATIONID
   		 , AO.FLAG
   		 , SUM(DAYS) AS DAYS
   		 , SUM(HOURS_AUTHORIZED) AS HOURS_AUTHORIZED
   		 , SUM(HOURS_AUTHORIZED_NON_ADJUSTED) AS HOURS_AUTHORIZED_NON_ADJUSTED
    FROM Capping_Hours_at24_Per_Day AO
    INNER JOIN DISC_PROD.HHAEXCHANGEOPENSYSTEMS.PATIENTAUTHORIZATION PA
   	 ON PA.AUTHORIZATIONID = AO.AUTHORIZATIONID
    GROUP BY AO.PATIENTID, AO.SERVICECODEID,AO.AUTHORIZATIONID,AO.FLAG
)
SELECT 
	DISTINCT MD5(''OPENSYSTEMS'' 
			 || ''-'' || PA.AUTHORIZATIONID 
			 || ''-'' || ''HHAEXCHANGE'') AS CLIENT_SERVICE_KEY
	,17 AS SOURCE_SYSTEM_ID
	,CONCAT(''OPENSYSTEMS - '',O.STATE) AS SYSTEM_CODE
	,MD5(''OPENSYSTEMS''
	 || ''-'' || IFNULL(SC.AGENCYID, -1) 
	 || ''-'' || IFNULL(PR.PAYERID, -1) 
	 || ''-'' || IFNULL(SC.CONTRACTID, -1) 
 	 || ''-'' || IFNULL(SC.SERVICECODEID, -1) 
	 || ''-'' || IFNULL(SC.VISITTYPE, ''-1'') 
	 || ''-'' || IFNULL(SC.RATETYPETEXT, ''-1'')
	 || ''-'' || ''HHAEXCHANGE'') AS PARTNER_CONTRACT_SERVICE_KEY
	,MD5(''OPENSYSTEMS''
	 || ''-'' || CLIENT.PATIENTID
     || ''-'' || P.ADMISSIONID 
     || ''-'' || SC.SERVICECODEID
     || ''-'' || ''HHAEXCHANGE'') AS CLIENT_ADMISSION_KEY
	,MD5(''OPENSYSTEMS''
	 || ''-'' || CLIENT.MASTER_ID
	 || ''-'' || ''HHAEXCHANGE'') AS CLIENT_KEY
	,MD5(''OPENSYSTEMS''
	 || ''-'' || SC.SERVICECODEID 
	 || ''-'' || ''HHAEXCHANGE'') AS SERVICE_KEY
	,SC.SERVICECODE AS BILL_CODE 
	,SC.RATETYPETEXT AS BILL_TYPE
    ,CASE WHEN CR.UNITS = 1 THEN ''Hourly''
          WHEN CR.UNITS = 2 THEN ''Half Hours''
          WHEN CR.UNITS = 4 THEN ''Quarter Hours''
     ELSE NULL END AS  BILL_UOM
    ,SC.RATETYPETEXT AS SCHEDULE_TYPE
    ,SC.RATETYPETEXT AS SCHEDULE_UOM
    ,PA.DISCIPLINE AS AUTHORIZAITON_DISCIPLINE
    ,PA.FROMDATE AS AUTHORIZATION_DATE
    ,PA.FROMDATE AS AUTHORIZATION_PERIOD_START_DATE
    ,IFF(PA.TODATE > (SELECT MAX(CALENDAR_DATE) FROM DW_PROD.HAH.DIM_DATE ),(SELECT MAX(CALENDAR_DATE) FROM DW_PROD.HAH.DIM_DATE),PA.TODATE)AS AUTHORIZATION_PERIOD_END_DATE
    ,CA.DAYS AS EFFECTIVE_DAYS
	,CONCAT(TRIM(PA.TYPE),'' '',''Authorization'')AS AUTHORIZATION_TYPE
    ,PA.PERIOD AS AUTHORIZATION_UOM
--    ,CASE WHEN PA.PERIOD !=''Day'' AND MAXUNITSFORPERIOD  IN (0) OR MAXUNITSFORAUTH=''0'' THEN TRUE 
--    	  WHEN PA.PERIOD =''Day'' AND  PA.MONHOURS+PA.TUEHOURS+PA.WEDHOURS+PA.THUHOURS+PA.FRIHOURS+PA.SATHOURS+PA.SUNHOURS=0 THEN TRUE 
--     --ELSE FALSE END AS UNLIMITED_UNITS_FLAG	 
    ,NULL AS AUTH_INFO
    ,CASE WHEN PA.PERIOD =''Day'' THEN COALESCE(NULLIFZERO(PA.MONHOURS),NULLIFZERO(PA.TUEHOURS),NULLIFZERO(PA.WEDHOURS),NULLIFZERO(PA.THUHOURS),NULLIFZERO(PA.FRIHOURS),NULLIFZERO(PA.SATHOURS),NULLIFZERO(PA.SUNHOURS),0)
    	  ELSE PA.MAXUNITSFORPERIOD END AS AUTHORIZATION_MAX_UNITS_BY_UOM
    ,CA.HOURS_AUTHORIZED_NON_ADJUSTED AS AUTHORIZATION_MAX_UNITS
    ,CASE WHEN PA.PERIOD =''Day'' THEN COALESCE(NULLIFZERO(PA.MONHOURS),NULLIFZERO(PA.TUEHOURS),NULLIFZERO(PA.WEDHOURS),NULLIFZERO(PA.THUHOURS),NULLIFZERO(PA.FRIHOURS),NULLIFZERO(PA.SATHOURS),NULLIFZERO(PA.SUNHOURS),0)
    	  WHEN PA.PERIOD =''Entire Period'' AND CA.FLAG = 1 THEN CA.HOURS_AUTHORIZED
    	  WHEN PA.PERIOD =''Monthly'' AND CA.FLAG = 1 THEN CA.HOURS_AUTHORIZED/(DATEDIFF(MONTH, PA.FROMDATE, PA.TODATE)+1)
    	  WHEN PA.PERIOD =''Week'' AND CA.FLAG =1 THEN CA.HOURS_AUTHORIZED/(DATEDIFF(WEEK, PA.FROMDATE, PA.TODATE)+1)
     ELSE PA.MAXUNITSFORPERIOD END AS AUTHORIZATION_MAX_UNITS_ADJUSTED_BY_UOM  
    ,CA.HOURS_AUTHORIZED AS AUTHORIZATION_MAX_UNITS_ADJUSTED
   	,IFF(CURRENT_DATE() BETWEEN PA.FROMDATE AND PA.TODATE,TRUE,FALSE) AS ACTIVE_FLAG
	,CASE WHEN AUTHORIZATIONNUMBER ILIKE ''%TEMP%'' AND MAXUNITSFORPERIOD  >=900 THEN TRUE 
            WHEN AUTHORIZATIONNUMBER ILIKE ''%TEMP%'' AND MAXUNITSFORPERIOD  <900   THEN FALSE 
            ELSE FALSE END AS INVALID_FLAG
	,CASE WHEN PA.ISDELETED =''Y'' THEN TRUE ELSE FALSE END AS CANCELLED_FLAG
   	,:STR_ETL_TASK_KEY AS ETL_TASK_KEY
   	,:STR_ETL_TASK_KEY AS ETL_INSERTED_TASK_KEY
   	,CONVERT_TIMEZONE(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ AS ETL_INSERTED_DATE
    ,CURRENT_USER as ETL_INSERTED_BY
    ,CONVERT_TIMEZONE(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ AS ETL_LAST_UPDATED_DATE
    ,CURRENT_USER as ETL_LAST_UPDATED_BY
    ,0 AS ETL_DELETED_FLAG
FROM DISC_PROD.HHAEXCHANGEOPENSYSTEMS.PATIENTAUTHORIZATION PA 
JOIN CLIENT ON CLIENT.PATIENTID = PA.PATIENTID
LEFT JOIN DISC_PROD.HHAEXCHANGEOPENSYSTEMS.PATIENTS P ON P.PATIENTID = CLIENT.PATIENTID
LEFT JOIN DISC_PROD.HHAEXCHANGEOPENSYSTEMS.OFFICE_OFFICES_REPL O ON CLIENT.OFFICEID = O.OFFICEID
LEFT JOIN Cleaned_Auth CA ON  CA.AUTHORIZATIONID = PA.AUTHORIZATIONID
JOIN DISC_PROD.HHAEXCHANGEOPENSYSTEMS.SERVICECODES SC ON SC.CONTRACTID = PA.CONTRACTID
   	 	 AND SC.SERVICECODEID = PA.SERVICECODEID
LEFT JOIN DISC_PROD.HHAEXCHANGEOPENSYSTEMS.CONTRACTS C ON SC.CONTRACTID = C.CONTRACTID
LEFT JOIN DISC_PROD.HHAEXCHANGEOPENSYSTEMS.CONTRACTRATES CR 
	ON  SC.SERVICECODEID  = CR.SERVICECODEID 
	AND CR.TODATE :: DATE > GETDATE()
	AND CR.FROMDATE :: DATE <= GETDATE()
LEFT JOIN DISC_PROD.HHAEXCHANGEOPENSYSTEMS.PAYER_REPL  PR
   ON IFNULL(PR.CONTRACTID,PR.PAYERID) = SC.CONTRACTID;
   
   
return ''SUCCESS'';
end;
';