CREATE OR REPLACE PROCEDURE DW_PROD.HAH.GET_STAGE_OSHAH_DIM_INVOICE_STATUS_MAPPING("STR_ETL_TASK_KEY" VARCHAR(16777216), "STR_CDC_START" VARCHAR(16777216), "STR_CDC_END" VARCHAR(16777216))
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
BEGIN
--*****************************************************************************************************************************
-- DEVELOPMENT LOG:
-- DATE        AUTHOR                NOTES:
-- --------    -------------------   -----------------------------------------------------------------------------------------------
-- 21/04/23    Pinkal Panchal        Initial Development
-- 07/12/23    Sandesh Gosavi        update code to use config flag
-- 12/09/2023  Pradeep Thippani      Changed INVOICE_STATUS logic and Added INVOICE_DETAILS cte for RCM
--*****************************************************************************************************************************

INSERT OVERWRITE INTO DW_PROD.STAGE.OSHAH_DIM_INVOICE_STATUS_MAPPING
WITH INVOICE_DETAILS AS (
SELECT
       HEADER.INVOICEHEADERID
     , MAX(PAY.PAIDDATE::DATE) AS FINAL_PAYMENT
     , MIN(HEADER.INVOICEDATE::DATE) AS FIRST_PAYMENT
     , SUM(DETAIL.BILLEDAMOUNT) AS INVOICE_BILLED_AMOUNT
     , SUM(BILL.PAIDAMOUNT) AS PAID_AMOUNT
     , SUM(BILL.WRITEOFF) AS WRITEOFFAMOUNT
     , SUM(BILL.ADJUSTMENT+BILL.TTADJUSTMENT+BILL.OTHERADJUSTMENT) AS ADJUSTMENTS
FROM DISC_PROD.HHAEXCHANGEOSHAH.TBLVISITS_REPL VISIT 
INNER  JOIN DISC_PROD.HHAEXCHANGEOSHAH.TBLINVOICEDETAILS_REPL DETAIL 
    ON DETAIL.VISITID = VISIT.VISITID AND DETAIL.PATIENTID = VISIT.PATIENTID
INNER JOIN DISC_PROD.HHAEXCHANGEOSHAH.TBLINVOICEHEADER_REPL HEADER 
    ON HEADER.INVOICEHEADERID = DETAIL.INVOICEHEADERID AND HEADER.PATIENTID = DETAIL.PATIENTID
LEFT JOIN DISC_PROD.HHAEXCHANGEOSHAH.BILLING_PAIDVISITS_REPL BILL
    ON BILL.VISITID = VISIT.VISITID AND BILL.PATIENTID = VISIT.PATIENTID
-- PAYMENTS Join change on 19/04/23 for RCM by Pinkal
LEFT JOIN DISC_PROD.HHAEXCHANGEOSHAH.PAYMENTS PAY 
    ON BILL.VISITID = PAY.VISITID   AND BILL.PATIENTID = PAY.PATIENTID AND BILL.PAYMENTDETAILID = PAY.PAYMENTID
GROUP BY HEADER.INVOICEHEADERID)--Added cte on 12/09/2023 for RCM by Pradeep
SELECT DISTINCT
	17 AS SOURCE_SYSTEM_ID,
	CONCAT(''OSHAH - '', TRIM(OFFICE.STATE)) AS SYSTEM_CODE,
    CASE WHEN (NVL(INV.INVOICEAMOUNT,0)-NVL(INVOICE.PAID_AMOUNT,0)) <= 0 THEN ''PAID''
         WHEN NVL(INVOICE.PAID_AMOUNT,0) >0  AND (NVL(INV.INVOICEAMOUNT,0)-NVL(INVOICE.PAID_AMOUNT,0))> 0 THEN ''PARTIAL PAY''
    ELSE ''BILLED'' END AS DERIVED_INVOICE_STATUS,
-- changes made on 12/09/2023 for RCM
--	CASE WHEN INV.PAYMENTSTATUS = 0 THEN ''BILLED''
--		WHEN INV.PAYMENTSTATUS = 1 THEN ''PAID''
--		WHEN INV.PAYMENTSTATUS = 2 THEN ''PARTIAL PAY''
--	ELSE ''UNKNOWN'' END AS DERIVED_INVOICE_STATUS,
	MD5(SOURCE_SYSTEM_ID || ''-'' || DERIVED_INVOICE_STATUS || ''-'' || SYSTEM_CODE) AS INVOICE_STATUS_KEY
	,
       ---- ETL FIELDS
    :STR_ETL_TASK_KEY AS ETL_TASK_KEY,
    :STR_ETL_TASK_KEY AS ETL_INSERTED_TASK_KEY,                    
	convert_timezone(''UTC'', CURRENT_TIMESTAMP)::timestamp_ntz as ETL_INSERTED_DATE,
	CURRENT_USER as ETL_INSERTED_BY,
	convert_timezone(''UTC'', CURRENT_TIMESTAMP)::timestamp_ntz as ETL_LAST_UPDATED_DATE,
	CURRENT_USER as ETL_LAST_UPDATED_BY
FROM DISC_PROD.HHAEXCHANGEOSHAH.TBLINVOICEHEADER_REPL INV
INNER JOIN INVOICE_DETAILS INVOICE --Added on 12/09/2023 for RCM by Pradeep
      ON INV.INVOICEHEADERID = INVOICE.INVOICEHEADERID
LEFT JOIN DISC_PROD.HHAEXCHANGEOSHAH.OFFICE_OFFICES_REPL OFFICE ON INV.OFFICEID = OFFICE.OFFICEID
WHERE OFFICE.STATE IN (SELECT STATE FROM DISC_PROD.HHAEXCHANGEOSHAH.CONFIGURATION WHERE CONFIG = TRUE);
RETURN ''SUCCESS'';
END;
';