CREATE OR REPLACE PROCEDURE DW_PROD.HAH.MERGE_STAGE_ROSTER_FACT_CLIENT_STATUS_HISTORY()
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS 'DECLARE RETURN_RESULT VARCHAR;
BEGIN
-----------------------------------------------------------------------
-- 03/10/2023    Pooja Deokate		 Adding new Client Status History
-----------------------------------------------------------------------
MERGE INTO DW_PROD.HAH.FACT_CLIENT_STATUS_HISTORY AS TGT
USING DW_PROD.STAGE.ROSTER_FACT_CLIENT_STATUS_HISTORY STAGE
	ON TGT.CLIENT_KEY = STAGE.CLIENT_KEY
    	AND TGT.END_DATE IS NULL
    	AND TGT.SOURCE_SYSTEM_ID IN (27,32,35)
WHEN NOT MATCHED THEN
INSERT 
(
	FACT_CLIENT_STATUS_HISTORY_KEY
	, CLIENT_KEY
    , SYSTEM_CODE
	, SOURCE_SYSTEM_ID
	, STATUS_SOURCE
	, START_DATE
	, END_DATE
	, CURRENT_RECORD_FLAG
	, ETL_TASK_KEY
	, ETL_INSERTED_TASK_KEY
	, ETL_INSERTED_DATE
	, ETL_INSERTED_BY
	, ETL_LAST_UPDATED_DATE
	, ETL_LAST_UPDATED_BY
)
VALUES 
(
	STAGE.FACT_CLIENT_STATUS_HISTORY_KEY
	, STAGE.CLIENT_KEY
    , STAGE.SYSTEM_CODE
	, STAGE.SOURCE_SYSTEM_ID
	, STAGE.STATUS_SOURCE
	, STAGE.START_DATE
	, STAGE.END_DATE
	, STAGE.CURRENT_RECORD_FLAG	
	, STAGE.ETL_TASK_KEY
	, STAGE.ETL_INSERTED_TASK_KEY
	, STAGE.ETL_INSERTED_DATE
	, STAGE.ETL_INSERTED_BY
	, STAGE.ETL_LAST_UPDATED_DATE
	, STAGE.ETL_LAST_UPDATED_BY
);
---------------------------------------------------------
-- Fetching updated/inserted count from last result scan
---------------------------------------------------------
SELECT CONCAT(''Message : '',"number of rows inserted", '' Rows Inserted '') 
INTO :RETURN_RESULT 
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));
--------------------------------------------------------------------
-- Updating end date of client for respective roster, if applicable
--------------------------------------------------------------------
UPDATE DW_PROD.HAH.FACT_CLIENT_STATUS_HISTORY STATUS_HISTORY
SET STATUS_HISTORY.END_DATE = (ROSTER.START_DATE - 1)
	, STATUS_HISTORY.CURRENT_RECORD_FLAG = FALSE
	, STATUS_HISTORY.ETL_LAST_UPDATED_DATE = CURRENT_TIMESTAMP
	, STATUS_HISTORY.ETL_LAST_UPDATED_BY = CURRENT_USER
FROM DW_PROD.STAGE.ROSTER_FACT_CLIENT_STATUS_HISTORY ROSTER
WHERE STATUS_HISTORY.CLIENT_KEY NOT IN (SELECT CLIENT_KEY FROM DW_PROD.STAGE.ROSTER_FACT_CLIENT_STATUS_HISTORY)
		AND STATUS_HISTORY.END_DATE IS NULL 
		AND STATUS_HISTORY.SOURCE_SYSTEM_ID IN (27,32,35)
		AND ROSTER.SYSTEM_CODE = STATUS_HISTORY.SYSTEM_CODE;
RETURN RETURN_RESULT;
END';