CREATE OR REPLACE PROCEDURE DW_PROD.HAH.DELETE_STAGE_CS_FACT_SURVEY_QUESTION()
RETURNS VARCHAR(16777216)
LANGUAGE JAVASCRIPT
EXECUTE AS OWNER
AS '

  sqlCmd = `SELECT 1`;
//  rs = sqlStmt.execute();
  return ''Done'';

';