CREATE OR REPLACE PROCEDURE DW_PROD.HAH.DELETE_STAGE_PAYLOCITY_DIM_PAYCODE_MAPPING()
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
	BEGIN

	DELETE FROM HAH.DIM_PAYCODE_MAPPING WHERE SOURCE_SYSTEM_ID = 10 AND PAYCODE_MAPPING_KEY
    NOT IN (SELECT PAYCODE_MAPPING_KEY FROM STAGE.PAYLOCITY_DIM_PAYCODE_MAPPING);

	RETURN ''Message : Done'';
	END;
';