CREATE OR REPLACE PROCEDURE DW_PROD.HAH.GET_STAGE_ALLIANCE_DIM_SERVICES_1_0("STR_ETL_TASK_KEY" VARCHAR(16777216), "STR_CDC_START" VARCHAR(16777216), "STR_CDC_END" VARCHAR(16777216))
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
BEGIN
--*****************************************************************************************************************************
-- NAME:  ALLIANCE_DIM_SERVICES_1_0
--
-- PURPOSE: Creates one row per Invoice according to 
--
-- DEVELOPMENT LOG:ALLIANCE
-- DATE        	AUTHOR                	NOTES:
-- --------    	-------------------   	-----------------------------------------------------------------------------------------------
-- 07/28/2022	Leo Joy     			Initial development
--*****************************************************************************************************************************
--
INSERT OVERWRITE INTO STAGE.ALLIANCE_DIM_SERVICES_1_0
SELECT MD5(''ALLIANCE'' || ''-'' || SR.SERVICECODE || ''-'' || ''GENERATIONS'') AS SERVICE_KEY
	,''ALLIANCE'' AS SYSTEM_CODE 
	,19 AS SOURCE_SYSTEM_ID
	,SR.SERVICECODE AS SERVICE_CODE_ID
		, SR.DESCRIPTION AS NAME
		, NULL AS BILL_CODE_ID
		, NULL AS IS_EXPENCE
		, NULL AS IS_MULTIPLE
		, SR.ALTERNATESERVICEID1 AS OTHER_CODE
		, NULL AS DEFAULT_COST
		, NULL AS DEFAULT_PAY_UNIT_FLAG
		, NULL AS DEFAULT_BILL_UNIT_FLAG
		, NULL AS CATEGORY_ID
		, CASE WHEN SR.DESCRIPTION ILIKE ''%Mileage%'' THEN ''MILEAGE''
			   WHEN SR.DESCRIPTION ILIKE ''%TIME%'' 	 THEN ''TIME TRAVEL''
			   ELSE ''REGULAR''
			END AS PAYROLL_CODE
		, NULL AS DEFAULT_REIMBURSMENT
		, NULL AS WC
		, NULL AS SHIFT_PAY
		, NULL AS OT_PAY
		, NULL AS BILL_EXCLUDE_HOLIDAY
		, NULL AS PAY_EXCLUDED_HOLIDAY
		, NULL AS IS_CAT
		, NULL AS COMMISSION_RATE
		, NULL AS BONUS_POINTS
		, NULL AS ACTIVE
		, TRY_CAST(SR.REVENUECODE AS INTEGER) AS REVENUE_CODE
		, NULL AS PAY
		, NULL AS POC_FIRST_BIL_LABLE_FLAG
		, NULL AS EXPENCE_TYPE_ID
		, TO_DATE(SR.CREATED) AS CREATED_DATE
		, SR.CREATEDBY AS CREATED_USER
		, TO_DATE(SR.LASTUPDATED) AS MODIFIED_DATE
		, SR.UPDATEDBY AS MODIFIED_USER
		, NULL AS TS
		, NULL AS LIST_ITEM_TYPE
		, NULL AS RPT_GROUP_ID
		, NULL AS BRANCH_ID
		, NULL AS OVERRIDE_ID
		, SR.DESCRIPTION AS DESCRIPTION
		, NULL AS TAX_GROUP_ID
		, NULL AS LEGACY_ID
		, NULL AS LEGACY_BRANCH_ID
		, NULL AS ACCT_ID
		, NULL AS UPLOAD_TELEPHONY
		, NULL AS TELEPHONY_TASK_ID
		, NULL AS INCLUDE_EFT
		, NULL AS PROJECTED_AVG_BILL_VISIT
		, NULL AS PROJECTED_AVG_PAY_VISIT
		, NULL AS PROJECTED_AVG_PAY_HOURLY
		, NULL AS PROJECTED_AVG_BILL_HOURLY
		, NULL AS IS_COPY
		, NULL AS IS_WORKING
		, NULL AS DEDUCT_ARN
		, NULL AS LIVE_IN_RPT_HRS
		, NULL AS ACCT_CODE
		, NULL AS DISPLAY_ON_CLIENT_PORTAL
		, NULL AS DISPLAY_ON_CAREGIVER_PORTAL
		, NULL AS THERAPY_COUNTING_TYPE
		, NULL AS MEDICARE_DISCIPLINE
		, NULL AS DOC_TYPE
		, NULL AS IS_MULTIPLE_SERVICE
		, NULL AS INSERT_DATE
		, NULL AS UPDATE_DATE
		, FALSE AS DELETED_FLAG
		, NULL AS CHANGE_VERSION
		, NULL AS CHANGE_OPERATION,
		-- ETL Fields
				:STR_ETL_TASK_KEY AS ETL_TASK_KEY,
		        
		        
		        :STR_ETL_TASK_KEY AS ETL_INSERTED_TASK_KEY
 		, CONVERT_TIMEZONE(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ AS ETL_INSERTED_DATE
		, CURRENT_USER as ETL_INSERTED_BY
		, CONVERT_TIMEZONE(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ AS ETL_LAST_UPDATED_DATE
		, CURRENT_USER as ETL_LAST_UPDATED_BY
		, 0 AS ETL_DELETED_FLAG
		, 0 AS ETL_INFERRED_MEMBER_FLAG
FROM DISC_PROD.GENERATIONSALLIANCE.SERVICES SR;
RETURN ''SUCCESS'';
END; 
';