CREATE OR REPLACE PROCEDURE DW_PROD.HAH.GET_STAGE_PARADOX_CLONE_PROD_TO_DEV()
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS CALLER
AS '
BEGIN

    DELETE from DW_DEV.HAH.DIM_APPLICANT where source_system_id = 12  and system_code = ''PARADOX_PROD'';
    DELETE from DW_DEV.HAH.DIM_JOB where source_system_id = 12  and system_code = ''PARADOX_PROD'';
    DELETE from DW_DEV.HAH.FACT_APPLICANT_STATUS where source_system_id = 12  and system_code = ''PARADOX_PROD'';

    INSERT INTO DW_DEV.HAH.DIM_APPLICANT( APPLICANT_KEY,SOURCE_SYSTEM_ID,SYSTEM_CODE,LAST_NAME,FIRST_NAME,MIDDLE_NAME,APPLICANT_ID,SSN,EMAIL,MOBILE_PHONE,HOME_PHONE,DATE_OF_BIRTH,ADDRESS,ADDRESS_LINE_2,CITY,STATE,STATE_CODE,POSTAL,REFERRER,CATEGORIES,REFERENCES,LINKEDIN,WEBSITE_BLOG_PORTFOLIO,TWITTER,EARLIEST_START_DATE,AVAILABLE_WEEKENDS,AVAILABLE_EVENINGS,AVAILABLE_OVERTIME,LANGUAGES,DRIVERS_LICENSE,COMMERCIAL_DRIVERS_LICENSE,CAN_RELOCATE,CITIZEN_EMPLOYMENT_STATUS,HIGHEST_EDUCATION,COLLEGE_UNIVERSITY,GRADE_POINT_AVG,AGE_18,PILOT_FLIGHT_HOURS,PILOT_GRADE_RATINGS,FELONY_CONVICTION,FELONY_EXPLANATION,EEO_CATEGORY,EEO_SEX,EEO_RACE,EEO_ETHNICITY,EEO_DISABILITY,EEOC_VETERAN_STATUS,EEOC_DISABILITY_STATUS,ETL_TASK_KEY,ETL_INSERTED_TASK_KEY,ETL_INSERTED_DATE,ETL_INSERTED_BY,ETL_LAST_UPDATED_DATE,ETL_LAST_UPDATED_BY,ETL_DELETED_FLAG , LINKED_ID, LOCATION_HIERARCHY, STATUS)-- Inserted -- Inserted
    SELECT APPLICANT_KEY,SOURCE_SYSTEM_ID, ''PARADOX_PROD'' SYSTEM_CODE,LAST_NAME,FIRST_NAME,MIDDLE_NAME,APPLICANT_ID,SSN,EMAIL,MOBILE_PHONE,HOME_PHONE,DATE_OF_BIRTH,ADDRESS,ADDRESS_LINE_2,CITY,STATE,STATE_CODE,POSTAL,REFERRER,CATEGORIES,REFERENCES,LINKEDIN,WEBSITE_BLOG_PORTFOLIO,TWITTER,EARLIEST_START_DATE,AVAILABLE_WEEKENDS,AVAILABLE_EVENINGS,AVAILABLE_OVERTIME,LANGUAGES,DRIVERS_LICENSE,COMMERCIAL_DRIVERS_LICENSE,CAN_RELOCATE,CITIZEN_EMPLOYMENT_STATUS,HIGHEST_EDUCATION,COLLEGE_UNIVERSITY,GRADE_POINT_AVG,AGE_18,PILOT_FLIGHT_HOURS,PILOT_GRADE_RATINGS,FELONY_CONVICTION,FELONY_EXPLANATION,EEO_CATEGORY,EEO_SEX,EEO_RACE,EEO_ETHNICITY,EEO_DISABILITY,EEOC_VETERAN_STATUS,EEOC_DISABILITY_STATUS,ETL_TASK_KEY,ETL_INSERTED_TASK_KEY,ETL_INSERTED_DATE,ETL_INSERTED_BY,ETL_LAST_UPDATED_DATE,ETL_LAST_UPDATED_BY,ETL_DELETED_FLAG
	, NULL AS LINKED_ID, NULL AS LOCATION_HIERARCHY, NULL AS STATUS
    from DW_PROD.HAH.DIM_APPLICANT where source_system_id = 12  and system_code = ''PARADOX'';

    INSERT INTO DW_DEV.HAH.DIM_JOB(JOB_KEY,SOURCE_SYSTEM_ID, SYSTEM_CODE,JOB_ID,STATE,CITY,JOB_POSTING_DATE,JOB_CLOSING_DATE,JOB_CREATED_DATE,JOB_TITLE,JOB_TITLE_CODE,JOB_FAMILY,JOB_FAMILY_CODE,JOB_OWNER,JOB_OWNER_ID,JOB_STATUS,LOCATION_NAME,EXTERNAL_JOB_REFERENCE_NUMBER,ARCHIVED,REQ_AGE,REQ_AGE_GROUP,JOB_POSTING_LINK,ETL_TASK_KEY,ETL_INSERTED_TASK_KEY,ETL_INSERTED_DATE,ETL_INSERTED_BY,ETL_LAST_UPDATED_DATE,ETL_LAST_UPDATED_BY,ETL_DELETED_FLAG,BRANCH_KEY)
    SELECT JOB_KEY,SOURCE_SYSTEM_ID, ''PARADOX_PROD'' SYSTEM_CODE,JOB_ID,STATE,CITY,JOB_POSTING_DATE,JOB_CLOSING_DATE,JOB_CREATED_DATE,JOB_TITLE,JOB_TITLE_CODE,JOB_FAMILY,JOB_FAMILY_CODE,JOB_OWNER,JOB_OWNER_ID,JOB_STATUS,LOCATION_NAME,EXTERNAL_JOB_REFERENCE_NUMBER,ARCHIVED,REQ_AGE,REQ_AGE_GROUP,JOB_POSTING_LINK,ETL_TASK_KEY,ETL_INSERTED_TASK_KEY,ETL_INSERTED_DATE,ETL_INSERTED_BY,ETL_LAST_UPDATED_DATE,ETL_LAST_UPDATED_BY,ETL_DELETED_FLAG,BRANCH_KEY
    from DW_PROD.HAH.DIM_JOB where source_system_id = 12  and system_code = ''PARADOX'';

    INSERT INTO DW_DEV.HAH.FACT_APPLICANT_STATUS(APPLICANT_STATUS_KEY,SOURCE_SYSTEM_ID, SYSTEM_CODE,APPLICANT_KEY,JOB_KEY,JOB_FAMILY,CANDIDATE_ID,DATE_APPLIED,CONVERSATION_INPROGRESS_DATETIME,INTERVIEW_SCHEDULED_DATETIME,INTERVIEW_RESCHEDULED_DATETIME,INTERVIEW_COMPLETED_DATETIME,INTERVIEW_NO_AVAILABILITY_DATETIME,INTERVIEW_NO_SHOW_DATETIME, NUMBER_OF_TIMES_INTERVIEW_SCHEDULED,Application_and_Background_Check_Consent_Form_Complete_DATETIME,OFFERS_SENT_DATETIME,OFFERS_ACCEPTED_DATETIME,ONBOARDING_SENT_DATETIME,ONBOARDING_COMPLETED_DATETIME,HIRED_DATETIME,OFFER_DECLINED_DATETIME,REJECTED_DATETIME,REJECTION_REASON,MOST_RECENT_STAGE_DATETIME,APPLICANT_STATUS,PRIOR_STATUS,PRIOR_STATUS_DATETIME,BRANCH_KEY,BRANCH_NAME,SANDATA_EMPLOYEE_ID,  SOURCE,ETL_TASK_KEY,ETL_INSERTED_TASK_KEY,ETL_INSERTED_DATE,ETL_INSERTED_BY,ETL_LAST_UPDATED_DATE,ETL_LAST_UPDATED_BY,ETL_DELETED_FLAG,BRANCH_STATE_CODE)
    SELECT APPLICANT_STATUS_KEY,SOURCE_SYSTEM_ID, ''PARADOX_PROD'' SYSTEM_CODE,APPLICANT_KEY,JOB_KEY,JOB_FAMILY,CANDIDATE_ID,DATE_APPLIED,CONVERSATION_INPROGRESS_DATETIME,INTERVIEW_SCHEDULED_DATETIME,INTERVIEW_RESCHEDULED_DATETIME,INTERVIEW_COMPLETED_DATETIME,INTERVIEW_NO_AVAILABILITY_DATETIME,INTERVIEW_NO_SHOW_DATETIME, NUMBER_OF_TIMES_INTERVIEW_SCHEDULED,Application_and_Background_Check_Consent_Form_Complete_DATETIME,OFFERS_SENT_DATETIME,OFFERS_ACCEPTED_DATETIME,ONBOARDING_SENT_DATETIME,ONBOARDING_COMPLETED_DATETIME,HIRED_DATETIME,OFFER_DECLINED_DATETIME,REJECTED_DATETIME,REJECTION_REASON,MOST_RECENT_STAGE_DATETIME,APPLICANT_STATUS,PRIOR_STATUS,PRIOR_STATUS_DATETIME,BRANCH_KEY,BRANCH_NAME,NULL SANDATA_EMPLOYEE_ID,  SOURCE,ETL_TASK_KEY,ETL_INSERTED_TASK_KEY,ETL_INSERTED_DATE,ETL_INSERTED_BY,ETL_LAST_UPDATED_DATE,ETL_LAST_UPDATED_BY,ETL_DELETED_FLAG,BRANCH_STATE_CODE
    from DW_PROD.HAH.FACT_APPLICANT_STATUS where source_system_id = 12  and system_code = ''PARADOX'';
	
	DELETE FROM DW_DEV.HAH.DIM_JOB
    WHERE job_key IN (SELECT JOB_KEY FROM (select COUNT(*),JOB_KEY from DW_DEV.HAH.DIM_JOB
    GROUP BY JOB_KEY
    HAVING COUNT(*)>1))AND "SYSTEM_CODE" =''PARADOX_PROD'';
	
    RETURN ''SUCESS'';
END
';