CREATE OR REPLACE PROCEDURE DW_PROD.HAH.DELETE_STAGE_HAH_REPORTING_FACT_WRITEOFF()
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
	day_Of_Week int;
	return_result VARCHAR (1000);
BEGIN
	SELECT dayofweek(current_timestamp()) into day_Of_Week;
	if (day_Of_Week = 0) then
     DELETE FROM DW_PROD.HAH.FACT_WRITEOFF WHERE SOURCE_SYSTEM_ID = 3 AND WRITEOFF_KEY NOT IN (SELECT WRITEOFF_KEY FROM DW_PROD.STAGE.VW_CURRENT_HAH_REPORTING_FACT_WRITEOFF);
  else
     DELETE FROM DW_PROD.HAH.FACT_WRITEOFF WHERE SOURCE_SYSTEM_ID = 3 AND WRITEOFF_KEY IN (SELECT WRITEOFF_KEY FROM DW_PROD.STAGE.VW_CURRENT_DELETED_HAH_REPORTING_FACT_WRITEOFF);
end if;
	
	SELECT CONCAT (''MESSAGE : '',"number of rows deleted",'' Rows Deleted.'') into :return_result FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));
	RETURN return_result;
  END;
';