CREATE OR REPLACE PROCEDURE DW_PROD.HAH.GET_STAGE_SANDATAIMPORT_FACT_PARTNER_CONTRACT_SERVICE("STR_ETL_TASK_KEY" VARCHAR(16777216), "STR_CDC_START" VARCHAR(16777216), "STR_CDC_END" VARCHAR(16777216))
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
BEGIN

--*****************************************************************************************************************************
-- NAME:  SANDATA FACT PARTNER CONTRACT SERVICE
--
-- PURPOSE: Populates Stage SANDATA FACT PARTNER CONTRACT SERVICE
--
--
-- DEVELOPMENT LOG:
-- DATE        AUTHOR                NOTES:
-- --------    -------------------   -----------------------------------------------------------------------------------------------
-- 04/03/23     VIJAY SHARMA          Initial version
-- 04/07/23	 	VIJAY SHARMA		  Modified logic to include contracts and services from Sandata visits, BI_REPOSITORY Visits and Client admissions
-- 04/12/23     VIJAY SHARMA          Remove CONTRACT from SERVICE_KEY
-- 12/25/23 	Shraddha Sejpal		  Added State
--*****************************************************************************************************************************

INSERT OVERWRITE INTO STAGE.SANDATAIMPORT_FACT_PARTNER_CONTRACT_SERVICE
WITH INVOICEDETAILS AS (
	SELECT DISTINCT HCPCS,AGENCYID ,INVOICENUMBER ,SERVICEID  
	,UNITTYPEID ,RATE 
	FROM DISC_PROD.SANDATAIMPORT.SANDATA_INVOICEDETAILS
	WHERE AGENCYID = ''8485''
	AND NVL(HCPCS,'''') <> ''''
	AND RATE NOT IN (0.00, 0.01) AND (UNITTYPEID IS NOT NULL OR UNITTYPEID <>'''')
),
UNITTYPE AS
(
	SELECT DISTINCT * FROM 
	(
		SELECT row_number() OVER (PARTITION BY SCHEDULEID ORDER BY rate desc) rn,AGENCYID ,AUTHORIZATIONID,SCHEDULEID,
				CASE UNITTYPE WHEN ''01'' THEN ''Hourly'' 
					  	  	  WHEN ''02'' THEN ''Visit'' 
					  	  	  WHEN ''05'' THEN ''Hourly'' 
					  	  	  WHEN ''06'' THEN ''Per Diem'' 
			else NULL END AS UNITTYPE 
		FROM DISC_PROD.SANDATAIMPORT.SANDATA_SCHEDULESCLIENTS
		WHERE AGENCYID =''8485'' AND RATE NOT IN (0.00, 0.01) AND (UNITTYPE IS NOT NULL OR UNITTYPE <>'''')
	)
	WHERE rn=1 
)
--Taken contract and service from Client admissions
SELECT DISTINCT
CASE WHEN AUTH.SERVICEID IN (''CARECO'' , ''VBPCG'')	
THEN MD5(''CC_''||IFNULL(CAD.AGENCYID,-1) || ''-'' || IFNULL(P.PAYORID,-1) || ''-'' || IFNULL(CAD.ADMISSIONTYPE , ''UNKNOWN'') || ''-'' ||
			IFNULL(NULLIF(AUTH.SERVICEID,'''') , ''UNKNOWN'') || ''-'' || 
			COALESCE(U.UNITTYPE, ''UNKNOWN'') || ''-'' || ''SANDATAIMPORT'' )
ELSE MD5(IFNULL(CAD.AGENCYID,-1) || ''-'' || IFNULL(P.PAYORID,-1) || ''-'' || IFNULL(CAD.ADMISSIONTYPE , ''UNKNOWN'') || ''-'' ||
			IFNULL(NULLIF(AUTH.SERVICEID,'''') , ''UNKNOWN'') || ''-'' || 
			COALESCE(U.UNITTYPE, ''UNKNOWN'') || ''-'' || ''SANDATAIMPORT'' )
END AS PARTNER_CONTRACT_SERVICE_KEY,
4 AS SOURCE_SYSTEM_ID,
CASE WHEN AUTH.SERVICEID IN (''CARECO'' , ''VBPCG'')	
		THEN ''CC_''||CAD.AGENCYID
		ELSE IFNULL(CAD.AGENCYID,''-1'') END AS SYSTEM_CODE,
''PA'' AS STATE,
MD5(IFNULL(CAD.AGENCYID,''-1'') || ''-'' || IFNULL(P.PAYORID,''-1'') || ''-'' || IFNULL(CAD.ADMISSIONTYPE , ''UNKNOWN'') || ''-'' || ''SANDATAIMPORT'') AS PARTNER_CONTRACT_KEY,
--MD5(IFNULL(P.PAYORID,-1) || ''-'' || ''SANDATAIMPORT'') AS PARTNER_KEY,
COALESCE(P.PAYORID , ''-1'') AS PARTNER_CODE, --?
COALESCE(P."NAME" , ''UNKNOWN'') AS PARTNER_NAME,
COALESCE(CAD.ADMISSIONTYPE, ''UNKNOWN'') AS CONTRACT_CODE,
COALESCE(M.CONTRACT_NAME, ''Unknown'') AS CONTRACT_NAME,
--
CASE WHEN AUTH.SERVICEID IN (''CARECO'' , ''VBPCG'') 
	THEN MD5(''CC_''||IFNULL(CAD.AGENCYID,-1) || ''-'' || IFNULL(AUTH.SERVICEID , ''UNKNOWN'') || ''-'' || ''SANDATAIMPORT'')
	ELSE MD5(IFNULL(CAD.AGENCYID,-1) || ''-'' || IFNULL(AUTH.SERVICEID , ''UNKNOWN'') || ''-'' || ''SANDATAIMPORT'')
	END AS SERVICE_KEY,
IFNULL(AUTH.SERVICEID , ''UNKNOWN'') AS SERVICE_CODE,
S.DESCRIPTION AS SERVICE_NAME,
--
--md5(INV.AGENCYID ||''-''|| INV.INVOICENUMBER ||''-''|| IFNULL(D.RATE,-1) ||''-''|| ''SANDATAIMPORT'') AS BILLING_KEY,
--INV.BILLCODE AS BILL_CODE,
NULL AS BILLING_KEY,
IFNULL(S.SERVICECODE , ''UNKNOWN'') AS BILL_CODE, --taken AS DEFAULT FOR now 
--D.HCPCS AS BILL_NAME,
NULL AS BILL_NAME,
COALESCE(M.BILLABLE_FLAG, TRUE) AS BILLABLE_FLAG,
CASE WHEN S.DEFAULTBILLTYPE= ''01'' THEN ''Hourly''
	 WHEN S.DEFAULTBILLTYPE= ''02'' THEN ''Visit''
	 WHEN S.DEFAULTBILLTYPE= ''05'' THEN ''Unit'' 
	 ELSE ''Unknown'' END AS BILL_TYPE,
--CASE WHEN D.UNITTYPEID = ''01'' THEN ''Hourly''
--WHEN D.UNITTYPEID = ''02'' THEN ''Visit''
----WHEN D.UNITTYPEID = ''05'' THEN ''Unit''
--WHEN D.UNITTYPEID = ''05'' THEN ''Hourly'' -- AS per Visit
--WHEN D.UNITTYPEID = ''06'' THEN ''Per Diem''
--ELSE ''UNKNOWN'' END AS BILL_UOM,
NULL AS BILL_UOM,
--
COALESCE(U.UNITTYPE, ''Unknown'') AS SCHEDULE_TYPE,
NULL AS SCHEDULE_UOM,
--
TRUE AS AUTHORIZATION_REQUIRED_FLAG, --?
COALESCE(M.PAYABLE_FLAG, TRUE) AS PAYABLE_FLAG,
FALSE AS EXPENSE_FLAG,--?
COALESCE(M.MILEAGE_FLAG, FALSE) AS MILEAGE_FLAG
    ---- ETL FIELDS ----
	, :STR_ETL_TASK_KEY AS ETL_TASK_KEY
	, :STR_ETL_TASK_KEY AS ETL_INSERTED_TASK_KEY
	, Convert_timezone(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ AS ETL_INSERTED_DATE
	, CURRENT_USER AS ETL_INSERTED_BY
	, Convert_timezone(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ AS ETL_LAST_UPDATED_DATE
	, CURRENT_USER AS ETL_LAST_UPDATED_BY
	, 0 AS ETL_DELETED_FLAG
FROM DISC_PROD.SANDATAIMPORT.SANDATA_CLIENTADMISSIONS CAD 
LEFT JOIN DISC_PROD.SANDATAIMPORT.SANDATA_AUTHORIZATIONS AUTH 
	ON CAD.ADMISSIONID = AUTH.ADMISSIONID AND CAD.AGENCYID = AUTH.AGENCYID
LEFT JOIN DISC_PROD.SANDATAIMPORT.SANDATA_SERVICES S 
     			ON AUTH.AGENCYID = S.AGENCYID  AND AUTH.SERVICEID =S.SERVICECODE
LEFT JOIN  DISC_PROD.SANDATAIMPORT.SANDATA_PAYORS P
     			ON AUTH.PAYORID =P.PAYORID AND AUTH.AGENCYID = P.AGENCYID
LEFT JOIN UNITTYPE U ON CAD.AGENCYID = U.AGENCYID  AND AUTH.AUTHID =U.AUTHORIZATIONID
LEFT JOIN HAH.FACT_REVENUE_SUBCATEGORY_CONTRACT_MAPPING M
    	ON M.SOURCE_SYSTEM_ID = 4 AND M.SYSTEM_CODE = CAD.AGENCYID AND M.CONTRACT_CODE = CAD.ADMISSIONTYPE
 WHERE CAD.AGENCYID = ''8485''
UNION
--Taken contract and service from BI_REPOSITORY Visits
 SELECT DISTINCT
 CASE WHEN  SV.SERVICEID IN (''CARECO'',''VBPCG'')
	THEN MD5(
            ''CC_''||IFNULL(SV.AGENCYID,-1) || ''-'' ||
            IFNULL(P.PAYORID,-1) || ''-'' ||
            IFNULL(SV.ADMISSIONTYPE , ''UNKNOWN'') || ''-'' ||
            IFNULL(NULLIF(SV.SERVICEID,'''') , ''UNKNOWN'') || ''-'' ||
		  COALESCE(U.UNITTYPE, ''UNKNOWN'') || ''-'' ||
            ''SANDATAIMPORT''
	)
	ELSE MD5(
            IFNULL(SV.AGENCYID,-1) || ''-'' ||
            IFNULL(P.PAYORID,-1) || ''-'' ||
            IFNULL(SV.ADMISSIONTYPE , ''UNKNOWN'') || ''-'' ||
            IFNULL(NULLIF(SV.SERVICEID,'''') , ''UNKNOWN'') || ''-'' ||
		  COALESCE(U.UNITTYPE, ''UNKNOWN'') || ''-'' ||
            ''SANDATAIMPORT''
	) END AS PARTNER_CONTRACT_SERVICE_KEY,
4 AS SOURCE_SYSTEM_ID,
CASE WHEN SV.SERVICEID IN (''CARECO'' , ''VBPCG'')	
		THEN ''CC_''||SV.AGENCYID
		ELSE IFNULL(SV.AGENCYID,''-1'') END AS SYSTEM_CODE,
''PA'' AS STATE,
MD5(IFNULL(SV.AGENCYID,''-1'') || ''-'' || IFNULL(P.PAYORID,''-1'') || ''-'' || IFNULL(SV.ADMISSIONTYPE , ''UNKNOWN'') || ''-'' || ''SANDATAIMPORT'') AS PARTNER_CONTRACT_KEY,
--MD5(IFNULL(P.PAYORID,-1) || ''-'' || ''SANDATAIMPORT'') AS PARTNER_KEY,
COALESCE(P.PAYORID , ''-1'') AS PARTNER_CODE, --?
COALESCE(P."NAME" , ''UNKNOWN'') AS PARTNER_NAME,
COALESCE(SV.ADMISSIONTYPE, ''UNKNOWN'') AS CONTRACT_CODE,
COALESCE(M.CONTRACT_NAME, ''Unknown'') AS CONTRACT_NAME,--
CASE WHEN SV.SERVICEID IN (''CARECO'' , ''VBPCG'') 
	THEN MD5(''CC_''||IFNULL(SV.AGENCYID,-1) || ''-'' || IFNULL(NULLIF(SV.SERVICEID,'''') , ''UNKNOWN'') || ''-'' || ''SANDATAIMPORT'')
	ELSE MD5(IFNULL(SV.AGENCYID,-1) || ''-'' || IFNULL(NULLIF(SV.SERVICEID,'''') , ''UNKNOWN'') || ''-'' || ''SANDATAIMPORT'')
	END AS SERVICE_KEY,
IFNULL(NULLIF(SV.SERVICEID,'''') , ''UNKNOWN'') AS SERVICE_CODE,
S.DESCRIPTION AS SERVICE_NAME,
--
--md5(INV.AGENCYID ||''-''|| INV.INVOICENUMBER ||''-''|| IFNULL(D.RATE,-1) ||''-''|| ''SANDATAIMPORT'') AS BILLING_KEY,
--INV.BILLCODE AS BILL_CODE,
NULL AS BILLING_KEY,
IFNULL(S.SERVICECODE , ''UNKNOWN'') AS BILL_CODE, --taken AS DEFAULT FOR now 
--D.HCPCS AS BILL_NAME,
NULL AS BILL_NAME,
COALESCE(M.BILLABLE_FLAG, TRUE) AS BILLABLE_FLAG,
CASE WHEN S.DEFAULTBILLTYPE= ''01'' THEN ''Hourly''
	 WHEN S.DEFAULTBILLTYPE= ''02'' THEN ''Visit''
	 WHEN S.DEFAULTBILLTYPE= ''05'' THEN ''Unit'' 
	 ELSE ''Unknown'' END AS BILL_TYPE,
--CASE WHEN D.UNITTYPEID = ''01'' THEN ''Hourly''
--WHEN D.UNITTYPEID = ''02'' THEN ''Visit''
----WHEN D.UNITTYPEID = ''05'' THEN ''Unit''
--WHEN D.UNITTYPEID = ''05'' THEN ''Hourly'' -- AS per Visit
--WHEN D.UNITTYPEID = ''06'' THEN ''Per Diem''
--ELSE ''Unknown'' END AS BILL_UOM,
NULL AS BILL_UOM,
--
COALESCE(U.UNITTYPE, ''Unknown'') AS SCHEDULE_TYPE,
NULL AS SCHEDULE_UOM,
--
TRUE AS AUTHORIZATION_REQUIRED_FLAG, --?
COALESCE(M.PAYABLE_FLAG, TRUE) AS PAYABLE_FLAG,
FALSE AS EXPENSE_FLAG,--?
COALESCE(M.MILEAGE_FLAG, FALSE) AS MILEAGE_FLAG
    ---- ETL FIELDS ----
	, :STR_ETL_TASK_KEY AS ETL_TASK_KEY
	, :STR_ETL_TASK_KEY AS ETL_INSERTED_TASK_KEY
	, Convert_timezone(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ AS ETL_INSERTED_DATE
	, CURRENT_USER AS ETL_INSERTED_BY
	, Convert_timezone(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ AS ETL_LAST_UPDATED_DATE
	, CURRENT_USER AS ETL_LAST_UPDATED_BY
	, 0 AS ETL_DELETED_FLAG
FROM DISC_PROD.BI_REPOSITORY.SANDATAVISITS SV
LEFT JOIN DISC_PROD.SANDATAIMPORT.SANDATA_CLIENTADMISSIONS CAD 
	ON CAD.AGENCYID = SV.AGENCYID AND CAD.ADMISSIONID = SV.ADMISSIONID
LEFT JOIN UNITTYPE U ON SV.AGENCYID= U.AGENCYID AND SV.SCHEDULEID = U.SCHEDULEID	
LEFT JOIN DISC_PROD.SANDATAIMPORT.SANDATA_PAYORS P ON P."NAME" = SV.PAYORNAME AND P.AGENCYID = SV.AGENCYID
LEFT JOIN DISC_PROD.SANDATAIMPORT.SANDATA_SERVICES S 
     			ON SV.AGENCYID = S.AGENCYID  AND SV.SERVICEID =S.SERVICECODE
LEFT JOIN HAH.FACT_REVENUE_SUBCATEGORY_CONTRACT_MAPPING M
    	ON M.SOURCE_SYSTEM_ID = 4 AND M.SYSTEM_CODE = SV.AGENCYID AND M.CONTRACT_CODE = SV.ADMISSIONTYPE
 WHERE SV.AGENCYID = ''8485''
 UNION
--Taken contract and service from Sandata visits
 SELECT DISTINCT 
CASE WHEN F.SERVICEID IN (''CARECO'',''VBPCG'')	
		THEN MD5(''CC_''||IFNULL(F.AGENCYID,-1) || ''-'' ||
			IFNULL(INV_H.PAYORID,-1) || ''-'' ||
            IFNULL(F.CLIENTADMITTYPE, ''UNKNOWN'') || ''-'' ||
            IFNULL(NULLIF(F.SERVICEID,'''') , ''UNKNOWN'') || ''-'' ||
		  COALESCE(U.UNITTYPE, ''UNKNOWN'') || ''-'' ||
            ''SANDATAIMPORT'')
		ELSE MD5(IFNULL(F.AGENCYID,-1) || ''-'' ||
            IFNULL(INV_H.PAYORID,-1) || ''-'' ||
            IFNULL(F.CLIENTADMITTYPE, ''UNKNOWN'') || ''-'' ||
            IFNULL(NULLIF(F.SERVICEID,'''') , ''UNKNOWN'') || ''-'' ||
		  COALESCE(U.UNITTYPE, ''UNKNOWN'') || ''-'' ||
            ''SANDATAIMPORT'') END AS   PARTNER_CONTRACT_SERVICE_KEY,            
4 AS SOURCE_SYSTEM_ID,
CASE WHEN F.SERVICEID IN (''CARECO'' , ''VBPCG'')	
		THEN ''CC_''||F.AGENCYID
		ELSE IFNULL(F.AGENCYID,''-1'') END AS SYSTEM_CODE,
''PA'' AS STATE,
MD5(IFNULL(F.AGENCYID,''-1'') || ''-'' || IFNULL(INV_H.PAYORID,''-1'') || ''-'' || IFNULL(F.CLIENTADMITTYPE , ''UNKNOWN'') || ''-'' || ''SANDATAIMPORT'') AS PARTNER_CONTRACT_KEY,
--MD5(IFNULL(P.PAYORID,-1) || ''-'' || ''SANDATAIMPORT'') AS PARTNER_KEY,
COALESCE(P.PAYORID , ''-1'') AS PARTNER_CODE, --?
COALESCE(P."NAME" , ''UNKNOWN'') AS PARTNER_NAME,
COALESCE(F.CLIENTADMITTYPE, ''UNKNOWN'') AS CONTRACT_CODE,
COALESCE(M.CONTRACT_NAME, ''Unknown'') AS CONTRACT_NAME,
--
CASE WHEN F.SERVICEID IN (''CARECO'' , ''VBPCG'') 
	THEN MD5(''CC_''||IFNULL(F.AGENCYID,-1) || ''-'' || IFNULL(NULLIF(F.SERVICEID,'''') , ''UNKNOWN'') || ''-'' || ''SANDATAIMPORT'')
	ELSE MD5(IFNULL(F.AGENCYID,-1) || ''-'' || IFNULL(NULLIF(F.SERVICEID,'''') , ''UNKNOWN'') || ''-'' || ''SANDATAIMPORT'')
	END AS SERVICE_KEY,
IFNULL(NULLIF(F.SERVICEID,'''') , ''UNKNOWN'') AS SERVICE_CODE,
S.DESCRIPTION AS SERVICE_NAME,
--
--md5(INV.AGENCYID ||''-''|| INV.INVOICENUMBER ||''-''|| IFNULL(D.RATE,-1) ||''-''|| ''SANDATAIMPORT'') AS BILLING_KEY,
--INV.BILLCODE AS BILL_CODE,
NULL AS BILLING_KEY,
IFNULL(S.SERVICECODE , ''UNKNOWN'') AS BILL_CODE, --taken AS DEFAULT FOR now 
--D.HCPCS AS BILL_NAME,
NULL AS BILL_NAME,
COALESCE(M.BILLABLE_FLAG, TRUE) AS BILLABLE_FLAG,
CASE WHEN S.DEFAULTBILLTYPE= ''01'' THEN ''Hourly''
	 WHEN S.DEFAULTBILLTYPE= ''02'' THEN ''Visit''
	 WHEN S.DEFAULTBILLTYPE= ''05'' THEN ''Unit'' 
	 ELSE ''Unknown'' END AS BILL_TYPE,
--CASE WHEN D.UNITTYPEID = ''01'' THEN ''Hourly''
--WHEN D.UNITTYPEID = ''02'' THEN ''Visit''
----WHEN D.UNITTYPEID = ''05'' THEN ''Unit''
--WHEN D.UNITTYPEID = ''05'' THEN ''Hourly'' -- AS per Visit
--WHEN D.UNITTYPEID = ''06'' THEN ''Per Diem''
--ELSE ''UNKNOWN'' END AS BILL_UOM,
NULL AS BILL_UOM,
--
COALESCE(U.UNITTYPE, ''Unknown'') AS SCHEDULE_TYPE,
NULL AS SCHEDULE_UOM,
--
TRUE AS AUTHORIZATION_REQUIRED_FLAG, --?
COALESCE(M.PAYABLE_FLAG, TRUE) AS PAYABLE_FLAG,
FALSE AS EXPENSE_FLAG,--?
COALESCE(M.MILEAGE_FLAG, FALSE) AS MILEAGE_FLAG
    ---- ETL FIELDS ----
	, :STR_ETL_TASK_KEY AS ETL_TASK_KEY
	, :STR_ETL_TASK_KEY AS ETL_INSERTED_TASK_KEY
	, Convert_timezone(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ AS ETL_INSERTED_DATE
	, CURRENT_USER AS ETL_INSERTED_BY
	, Convert_timezone(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ AS ETL_LAST_UPDATED_DATE
	, CURRENT_USER AS ETL_LAST_UPDATED_BY
	, 0 AS ETL_DELETED_FLAG
FROM DISC_PROD.SANDATAIMPORT.SANDATA_VISITS F
LEFT JOIN UNITTYPE U ON F.AGENCYID= U.AGENCYID AND F.SCHEDULEID = U.SCHEDULEID 	
LEFT JOIN DISC_PROD.SANDATAIMPORT.SANDATA_INVOICEHEADER INV_H ON INV_H.INVOICENUMBER =F.INVOICENUMBER 
	AND INV_H.AGENCYID = F.AGENCYID
LEFT JOIN  DISC_PROD.SANDATAIMPORT.SANDATA_PAYORS P
     			ON INV_H.PAYORID =P.PAYORID AND F.AGENCYID = P.AGENCYID
LEFT JOIN DISC_PROD.SANDATAIMPORT.SANDATA_SERVICES S 
     			ON F.AGENCYID = S.AGENCYID  AND F.SERVICEID =S.SERVICECODE
LEFT JOIN HAH.FACT_REVENUE_SUBCATEGORY_CONTRACT_MAPPING M
    	ON M.SOURCE_SYSTEM_ID = 4 AND M.SYSTEM_CODE = F.AGENCYID AND M.CONTRACT_CODE = F.CLIENTADMITTYPE
 WHERE F.AGENCYID = ''8485'';

RETURN ''SUCCESS'';
end;
';