CREATE OR REPLACE PROCEDURE DW_PROD.HAH.DELETE_STAGE_ALLIANCE_DIM_SUPERVISOR()
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
	BEGIN 
DELETE FROM DW_PROD.HAH.DIM_SUPERVISOR WHERE SOURCE_SYSTEM_ID=19
	AND SYSTEM_CODE=''ALLIANCE'' AND SUPERVISOR_KEY
	NOT IN (SELECT SUPERVISOR_KEY FROM DW_PROD.STAGE.ALLIANCE_DIM_SUPERVISOR);
	RETURN ''SUCCESS'';
END;
';