CREATE OR REPLACE PROCEDURE DW_PROD.HAH.DELETE_STAGE_CCSI_DIM_CLIENT()
RETURNS VARCHAR(16777216)
LANGUAGE JAVASCRIPT
EXECUTE AS OWNER
AS '
  sqlCmd = `DELETE FROM DW_PROD.HAH.DIM_CLIENT WHERE SOURCE_SYSTEM_ID =8 AND CLIENT_KEY \\
  NOT IN (SELECT CLIENT_KEY FROM DW_PROD.STAGE.CCSI_DIM_CLIENT)`;
  sqlStmt = snowflake.createStatement( {sqlText: sqlCmd} );
  rs = sqlStmt.execute();
  return ''Done'';
';