CREATE OR REPLACE PROCEDURE DW_PROD.HAH.FACT_VISIT_EXCEPTION_POSTPROCESSING("STR_ETL_TASK_KEY" VARCHAR(16777216), "STR_CDC_START" VARCHAR(16777216), "STR_CDC_END" VARCHAR(16777216))
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
	DECLARE
		return_result VARCHAR;
	BEGIN
		DELETE FROM DW_PROD.HAH.FACT_VISIT_EXCEPTION WHERE VISIT_KEY NOT IN (SELECT VISIT_KEY FROM DW_PROD.HAH.FACT_VISIT);
	
		SELECT CONCAT(''Message : '',"number of rows deleted", '' Rows Deleted.'') into :return_result FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

	RETURN return_result;
	END;
';