CREATE OR REPLACE PROCEDURE DW_PROD.HAH.DELETE_STAGE_GATOR_DIM_PARTNER_CONTRACT()
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
  return_result VARCHAR;
BEGIN
return ''Done'';
END;
';