CREATE OR REPLACE PROCEDURE DW_PROD.HAH.GET_STAGE_EDISON_DIM_INVOICE_VISIT_LINKAGE("STR_ETL_TASK_KEY" VARCHAR(16777216), "STR_CDC_START" VARCHAR(16777216), "STR_CDC_END" VARCHAR(16777216))
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
BEGIN
--*****************************************************************************************************************************
-- NAME:  EDISON_DIM_INVOICE_VISIT_LINKAGE
--
-- DEVELOPMENT LOG:A
-- DATE         AUTHOR              NOTES:
-- --------     ------------------- -----------------------------------------------------------------------------------------------
-- 06/12/23		Preeti Sharma		Initial Development

--*****************************************************************************************************************************
--
INSERT OVERWRITE INTO STAGE.EDISON_DIM_INVOICE_VISIT_LINKAGE
SELECT
MD5(''EDISON'' ||''-''|| INVOICE.INVOICEDETAILID ||''-''|| INVOICE.VISITID ||''-''|| ''EDISON'') AS REVENUE_KEY
,MD5(''EDISON'' || ''-'' || COALESCE(VISITS.VISITID,INVOICE.VISITID) || ''-'' || '' EDISON'') AS VISIT_KEY
,CAST(COALESCE(VISITS.VISITID,INVOICE.VISITID) AS VARCHAR) AS VISIT_ID
,DATE_TRUNC(DAY, VR.VISITDATE) AS SERVICE_DATE
,''EDISON'' AS SYSTEM_CODE
,17 AS SOURCE_SYSTEM_ID
,:STR_ETL_TASK_KEY AS ETL_TASK_KEY
,:STR_ETL_TASK_KEY AS ETL_INSERTED_TASK_KEY                     
,convert_timezone(''UTC'', CURRENT_TIMESTAMP)::timestamp_ntz as ETL_INSERTED_DATE
,CURRENT_USER as ETL_INSERTED_BY
,convert_timezone(''UTC'', CURRENT_TIMESTAMP)::timestamp_ntz as ETL_UPDATED_DATE
,CURRENT_USER as ETL_LAST_UPDATED_BY
,0 as ETL_DELETED_FLAG
FROM DISC_PROD.HHAEXCHANGEEDISON.TBLINVOICEDETAILS_REPL INVOICE
LEFT JOIN DISC_PROD.HHAEXCHANGEEDISON.VISITINFO_REPL VISITS
ON  VISITS.VISITID = INVOICE.VISITID AND VISITS.PRIMARYSERVICECODEID = INVOICE.INVSERVICECODEID
AND VISITS.AGENCYID = INVOICE.AGENCYID 
LEFT JOIN 
(
	SELECT * FROM DISC_PROD.HHAEXCHANGEEDISON.TBLVISITS_REPL VR
	QUALIFY ROW_NUMBER() OVER(PARTITION BY VR.VISITID ORDER BY VR.CREATEDDATE DESC, VR.LASTMODIFIEDDATE DESC) = 1
) VR
ON VISITS.VISITID = VR.VISITID AND VISITS.AGENCYID = VR.AGENCYID
WHERE VISITS.AGENCYID = 155
; 

RETURN ''SUCCESS'';
END;
';