CREATE OR REPLACE PROCEDURE DW_PROD.HAH.DELETE_STAGE_ALLIANCE_DIM_SERVICES_1_0()
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
  BEGIN
DELETE FROM DW_PROD.HAH.DIM_SERVICES_1_0 WHERE SOURCE_SYSTEM_ID =19 
	AND SYSTEM_CODE = ''ALLIANCE'' AND SERVICE_KEY
  NOT IN (SELECT SERVICE_KEY FROM DW_PROD.STAGE.ALLIANCE_DIM_SERVICES_1_0);
RETURN ''SUCCESS'';
END;
';