CREATE OR REPLACE PROCEDURE DW_PROD.HAH.GET_STAGE_NAVISION_DIM_BRANCH("STR_ETL_TASK_KEY" VARCHAR(16777216), "STR_CDC_START" VARCHAR(16777216), "STR_CDC_END" VARCHAR(16777216))
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
BEGIN

--*****************************************************************************************************************************
-- NAME: NAVISION_DIM_BRANCH
--
-- PURPOSE: Creates one row per branch as per Navision
--
-- DEVELOPMENT LOG:
	
-- DATE        AUTHOR                				NOTES:
-- --------    -------------------------------   	--------------------------------------------------------------------------
-- 10/12/22    Aditya Shukla / Jigar Prajapati       Initial development
-- 05/29/23	   Shikhar Saxena						 Changed the logic to add SOURCE_SYSTEM_TYPE field
--*****************************************************************************************************************************

	INSERT OVERWRITE INTO STAGE.NAVISION_DIM_BRANCH

	WITH MANAGER AS 
	(
		SELECT B.BRANCH_CODE, 
		CASE WHEN B.BRANCH_CODE IN (''CEN'') THEN ''CHERRI HILTIBIDAL''
			WHEN B.BRANCH_CODE IN (''CHI'') THEN ''SAMANTHA DAVIES''
			WHEN B.BRANCH_CODE IN (''ESL'') THEN ''BETH LOYD''
			WHEN B.BRANCH_CODE IN (''FAI'') THEN ''GEORGIA JOHNSTON''
			WHEN B.BRANCH_CODE IN (''GRV'') THEN ''CHERYL COOL''
			WHEN B.BRANCH_CODE IN (''HAR'') THEN ''VIVIAN DICKERSON''
			WHEN B.BRANCH_CODE IN (''JLT'') THEN ''DONNA KOLOFA''
			WHEN B.BRANCH_CODE IN (''OAK'') THEN ''TONYA RUSH''
		 	WHEN B.BRANCH_CODE IN (''PIT'') THEN ''KRISTEN CROSSMAN''
			WHEN B.BRANCH_CODE IN (''QUY'') THEN ''LAURY CLARK''
			WHEN B.BRANCH_CODE IN (''ROC'') THEN ''RUTH MORRISON''
			WHEN B.BRANCH_CODE IN (''SPI'') THEN ''TANYA BOYER''
			WHEN B.BRANCH_CODE IN (''VLG'') THEN ''STACEY DALZELL''
		ELSE NULL
		END AS MANAGER
		FROM DISC_PROD.NAVISION.BRANCH_MAPPING B
	)
	SELECT DISTINCT 
		MD5(''NAVISION'' || ''-'' || B.BRANCH_CODE || B.BRANCH_NAME || ''-'' || ''NAVISION'') AS BRANCH_KEY,          
		UPPER(TRIM(B.BRANCH_NAME)) AS BRANCH_NAME,
		''NAVISION'' AS SYSTEM_CODE,
		21 AS SOURCE_SYSTEM_ID,
		SOURCE_SYSTEM.SOURCE_SYSTEM_TYPE,
		B.CODE AS OFFICE_NUMBER,
		B.BRANCH_CODE AS OFFICE_CODE,
		UPPER(TRIM(B.BRANCH_NAME)) AS OFFICE_NAME,
		UPPER(TRIM(B.BRANCH_NAME)) AS OFFICE_NAME_ALT,
		UPPER(TRIM(B.BRANCH_NAME)) AS DEPARTMENT_NAME,
		NULL AS BRANCH_SERVICE_LINE,
		TRUE AS PARENT_FLAG,
		MD5(''NAVISION'' || ''-'' || B.BRANCH_CODE || B.BRANCH_NAME || ''-'' || ''NAVISION'') AS PARENT_BRANCH_KEY,
		B.CODE AS PARENT_OFFICE_NUMBER,
		B.BRANCH_CODE AS PARENT_OFFICE_CODE,
		B.STATE || '' - '' || UPPER(TRIM(B.BRANCH_NAME)) || '' ('' ||  B.CODE || '')'' AS PARENT_BRANCH_NAME,
		TRIM(B.ADDRESS)  AS OFFICE_ADDRESS1,
		NULL AS OFFICE_ADDRESS2,
		TRIM(B.CITY) AS OFFICE_CITY,
		B.STATE AS OFFICE_STATE_CODE,
		B.ZIP AS OFFICE_ZIP,
		B.PHONE AS  OFFICE_PHONE,
		B.TOLL_FREE_PHONE AS OFFICE_TOLL_FREE_PHONE,
		B.FAX AS OFFICE_FAX,
		B.STATE || '' - '' || UPPER(TRIM(B.BRANCH_NAME)) || '' ('' || B.CODE || '')'' AS DETAILED_OFFICE_NAME,
		NULL AS REGION_NUMBER,
		''IL – NAVISION''  AS REGION_NAME,
		CASE WHEN B.BRANCH_CODE IN (''CEN'', ''ESL'', ''FAI'', ''PIT'', ''QUY'', ''SPI'', ''VLG'') THEN  ''KRISTEN KROSSMAN''
			 WHEN B.BRANCH_CODE IN (''CHI'', ''GRV'', ''HAR'', ''JLT'', ''OAK'', ''ROC'') THEN  ''TONYA RUSH''
		ELSE NULL END AS  REGION_MANAGER,
		NULL AS REGION_MANAGER_EMPLOYEE_KEY,
		NULL AS SUBREGION_NAME,
		M.MANAGER AS PRIMARY_BRANCH_MANAGER_NAME,
		UPPER (B.EMAIL) AS PRIMARY_BRANCH_EMAIL,
		NULL AS PRIMARY_BRANCH_MANAGER_EMPLOYEE_KEY,
		NULL AS SECONDARY_BRANCH_MANAGER_NAME,
		NULL AS SECONDARY_BRANCH_EMAIL,
		NULL AS SECONDARY_BRANCH_MANAGER_EMPLOYEE_KEY,
		NULL AS RISKCONNECT_NODE_KEY,
		NULL AS RISKCONNECT_NAME,
		NULL AS HR_OFFICE_NUMBER,
		NULL AS HR_OFFICE_NAME,
		TRUE AS ACTIVE_FLAG,
		TO_DATE(''1900-01-01'', ''YYYY-MM-DD'') AS EFFECTIVE_FROM_DATE,
		TO_DATE(''9999-12-31'', ''YYYY-MM-DD'') AS EFFECTIVE_TO_DATE,
			:STR_ETL_TASK_KEY AS ETL_TASK_KEY,
			:STR_ETL_TASK_KEY AS ETL_INSERTED_TASK_KEY,  
			convert_timezone(''UTC'', CURRENT_TIMESTAMP)::timestamp_ntz as ETL_INSERTED_DATE,
			CURRENT_USER as ETL_INSERTED_BY ,
			convert_timezone(''UTC'', CURRENT_TIMESTAMP)::timestamp_ntz as ETL_LAST_UPDATED_DATE,
			CURRENT_USER as ETL_LAST_UPDATED_BY,
			0 as ETL_DELETED_FLAG,
			0 as ETL_INFERRED_MEMBER_FLAG
	FROM DISC_PROD.NAVISION.BRANCH_MAPPING B
	LEFT JOIN MANAGER M 
		ON M.BRANCH_CODE = B.BRANCH_CODE
	LEFT JOIN HAH.DIM_SOURCE_SYSTEM AS SOURCE_SYSTEM WHERE SOURCE_SYSTEM.SOURCE_SYSTEM_ID = 21;
END;
';