CREATE OR REPLACE PROCEDURE DW_PROD.HAH.GET_STAGE_CLEARCARE_FACT_PARTNER_CONTRACT_SERVICE("STR_ETL_TASK_KEY" VARCHAR(16777216), "STR_CDC_START" VARCHAR(16777216), "STR_CDC_END" VARCHAR(16777216))
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
BEGIN

--*****************************************************************************************************************************
-- NAME: CLEARCARE FACT PARTNER CONTRACT SERVICE
--
-- PURPOSE: Populates Stage CLEARCARE FACT PARTNER CONTRACT SERVICE
--
--
-- DEVELOPMENT LOG:
-- DATE        AUTHOR                NOTES:
-- --------    -------------------   -----------------------------------------------------------------------------------------------
-- 10/31/23     Sagar Gulghane        Initial version
-- 12/25/23     Shraddha Sejpal       Added State
--*****************************************************************************************************************************

INSERT OVERWRITE INTO DW_PROD.STAGE.CLEARCARE_FACT_PARTNER_CONTRACT_SERVICE

WITH pcs AS (
SELECT 
    DISTINCT 
        MD5(''CLEARCARE'' || ''-'' || NVL(PCM.PAYOR_ID,''-1'') || ''-'' || NVL(PP.SERVICE_NAME,''-1'')  || ''-'' ||  COALESCE(CA.BILL_RATE_NAME,''UNKNOWN'')  || ''-'' || COALESCE(CA.BILL_RATE_TYPE ,''-1'') || ''-'' || ''CLEARCARE'') AS PARTNER_CONTRACT_SERVICE_KEY,
         16 AS SOURCE_SYSTEM_ID,
        ''CLEARCARE'' AS SYSTEM_CODE,
        ''OH'' AS STATE,
         MD5(''CLEARCARE'' || ''-''|| NVL(PCM.PAYOR_ID,-1) || ''-''|| COALESCE(CA.BILL_RATE_NAME,''UNKNOWN'') || ''-''|| COALESCE(CA.BILL_RATE_TYPE ,''-1'')  || ''-''|| ''CLEARCARE'' ) AS PARTNER_CONTRACT_KEY,
       COALESCE(PCM.PAYOR_ID,''-1'')  AS PARTNER_CODE,
       COALESCE(DPP.PAYOR_NAME,''UNKNOWN'')  AS PARTNER_NAME,
     CASE WHEN CA.BILL_RATE_NAME = '''' AND CA.BILL_RATE_TYPE = 4 THEN ''Non-Billable''
         WHEN CA.BILL_RATE_NAME = '''' AND CA.BILL_RATE_TYPE = 3 THEN ''Live-In''
         WHEN CA.BILL_RATE_NAME = '''' AND CA.BILL_RATE_TYPE = 2 THEN ''Visit''
         WHEN CA.BILL_RATE_NAME = '''' AND CA.BILL_RATE_TYPE = 1 THEN ''Hourly''
         ELSE CA.BILL_RATE_NAME 
    END AS CONTRACT_CODE,
 CASE WHEN CA.BILL_RATE_NAME = '''' AND CA.BILL_RATE_TYPE = 4 THEN ''Non-Billable''
         WHEN CA.BILL_RATE_NAME = '''' AND CA.BILL_RATE_TYPE = 3 THEN ''Live-In''
         WHEN CA.BILL_RATE_NAME = '''' AND CA.BILL_RATE_TYPE = 2 THEN ''Visit''
         WHEN CA.BILL_RATE_NAME = '''' AND CA.BILL_RATE_TYPE = 1 THEN ''Hourly''
         ELSE CA.BILL_RATE_NAME   END  AS CONTRACT_NAME,
--  NVL(PP.SERVICE_NAME,
--  ''-1'') AS SERVICE_CODE_ID,
    MD5(
        ''CLEARCARE'' || ''-'' || COALESCE(PP.SERVICE_NAME,''UNKNOWN'')|| ''-'' || ''CLEARCARE'') AS SERVICE_KEY,
    PP.SERVICE_NAME AS SERVICE_CODE,
    PP.SERVICE_NAME AS SERVICE_NAME,
    NULL AS BILLING_KEY,
    NULL AS BILL_CODE,
    NULL AS BILL_NAME , -- it''s also contract NAME 
    CASE WHEN CA.BILL_RATE_TYPE = 4 THEN FALSE
        ELSE TRUE
    END AS BILLABLE_FLAG,
    CASE WHEN BR."TYPE" = 1 THEN ''Hourly''
     WHEN BR."TYPE" = 2 THEN ''Visit''
     WHEN BR."TYPE" = 3 THEN ''Live-In''
     WHEN BR."TYPE" = 4 THEN ''Non-Billable'' ELSE ''Hourly''
    END AS BILL_TYPE,
    NULL AS BILL_UOM,
    CASE WHEN CA.BILL_RATE_TYPE = 1 THEN ''Hourly''
     WHEN CA.BILL_RATE_TYPE = 2 THEN ''Visit''
     WHEN CA.BILL_RATE_TYPE = 3 THEN ''Live-In''
     WHEN CA.BILL_RATE_TYPE = 4 THEN ''Non-Billable'' ELSE ''Hourly''
    END AS SCHEDULE_TYPE -- CHECK WITH bill_u it_type OF fact_visit
    ,  CASE WHEN CA.BILL_RATE_TYPE = 1 THEN ''Hourly''
     WHEN CA.BILL_RATE_TYPE = 2 THEN ''Visit''
     WHEN CA.BILL_RATE_TYPE = 3 THEN ''Live-In''
     WHEN CA.BILL_RATE_TYPE = 4 THEN ''Non-Billable'' ELSE ''Hourly''
    END  AS SCHEDULE_UOM,
    TRUE AS AUTHORIZATION_REQUIRED_FLAG ,-- DIM_CON.,
    NULL AS PAYABLE_FLAG,
    NULL AS EXPENSE_FLAG,
    FALSE  AS MILEAGE_FLAG
FROM
    DISC_PROD.CLEARCARE.CARELOGS_CARELOG CA
LEFT JOIN DISC_PROD.CLEARCARE.BILLING_CLIENTAUTHORIZATION AU  
      ON AU.CLIENT_ID=CA.PATIENT_ID AND AU.AGENCY_ID =CA.AGENCY_ID 
 AND AU.ID =CA.AUTHORIZATION_ID::VARCHAR --AND AU.BILL_RATE_ID =CA.BILL_RATE_OBJ_ID AND AU.START_DATE BETWEEN CA.CLOCK_IN AND CA.CLOCK_OUT
LEFT JOIN DISC_PROD.CLEARCARE.PATIENT_PATIENT PA ON PA.ID = CA.PATIENT_ID
LEFT JOIN DISC_PROD.CLEARCARE.AGENCY_AGENCYLOCATION AG ON AG.ID = PA.LOCATION_ID
LEFT JOIN DISC_PROD.CLEARCARE.PROFILE_PARENTPAYERSERVICE PP ON
    PP.id = AU.service_id
LEFT JOIN DISC_PROD.CLEARCARE.BILLING_BILLRATE BR ON
    AU.BILL_RATE_ID = BR.ID 
LEFT JOIN DISC_PROD.PAYOR_contract_UI.PAYOR_contract_MAPPING PCM ON
    CASE
        WHEN CA.BILL_RATE_NAME = ''''
        AND CA.BILL_RATE_TYPE = 4 THEN ''Non-Billable''
        WHEN CA.BILL_RATE_NAME = ''''
        AND CA.BILL_RATE_TYPE = 3 THEN ''Live-In''
        WHEN CA.BILL_RATE_NAME = ''''
        AND CA.BILL_RATE_TYPE = 2 THEN ''Visit''
        WHEN CA.BILL_RATE_NAME = ''''
        AND CA.BILL_RATE_TYPE = 1 THEN ''Hourly''
        ELSE CA.BILL_RATE_NAME
    END = PCM.CONTRACT_CODE AND PCM.ORIGINAL_SOURCE_SYSTEM_ID=16
LEFT JOIN  DISC_PROD.PAYOR_CONTRACT_UI.PAYOR AS DPP  ON PCM.PAYOR_ID = DPP.PAYOR_ID   
WHERE AG.AGENCY_ID =2459
UNION 
SELECT 
    DISTINCT 
        MD5(''CLEARCARE'' || ''-'' || NVL(PCM.PAYOR_ID,''-1'') || ''-'' || NVL(PP.SERVICE_NAME,''-1'') || ''-'' || COALESCE(BR."NAME",''UNKOWN'') || ''-'' || COALESCE(CA.BILL_RATE_TYPE ,''-1'') || ''-'' || ''CLEARCARE'') AS PARTNER_CONTRACT_SERVICE_KEY,
        16 AS SOURCE_SYSTEM_ID,
        ''CLEARCARE'' AS SYSTEM_CODE,
        ''OH'' AS STATE,
         MD5(''CLEARCARE'' || ''-''|| NVL(PCM.PAYOR_ID,-1) || ''-''|| BR."NAME"  || ''-''|| COALESCE(CA.BILL_RATE_TYPE ,''-1'') || ''-'' || ''CLEARCARE'' ) AS PARTNER_CONTRACT_KEY,
     COALESCE(PCM.PAYOR_ID,''-1'')  AS PARTNER_CODE,
       COALESCE(DPP.PAYOR_NAME,''UNKNOWN'')  AS PARTNER_NAME,
        BR."NAME"  AS  contract_CODE,
        BR."NAME"  AS contract_NAME,
--      NVL(PP.SERVICE_NAME,
--      ''-1'') AS SERVICE_CODE_ID,
        MD5(
        ''CLEARCARE'' || ''-'' || COALESCE(PP.SERVICE_NAME,''UNKNOWN'')|| ''-'' || ''CLEARCARE'') AS SERVICE_KEY,
        PP.SERVICE_NAME AS SERVICE_CODE,
        PP.SERVICE_NAME AS SERVICE_NAME,
        NULL AS BILLING_KEY,
        NULL AS BILL_CODE,
        NULL AS BILL_NAME , -- it''s also contract NAME 
        CASE WHEN CA.BILL_RATE_TYPE = 4 THEN FALSE
            ELSE TRUE
        END AS BILLABLE_FLAG,
        CASE WHEN BR."TYPE"  = 1 THEN ''Hourly''
         WHEN BR."TYPE" = 2 THEN ''Visit''
         WHEN BR."TYPE" = 3 THEN ''Live-In''
         WHEN BR."TYPE" = 4 THEN ''Non-Billable'' ELSE ''Hourly''
        END AS BILL_TYPE,
        NULL AS BILL_UOM,
        CASE WHEN CA.BILL_RATE_TYPE = 1 THEN ''Hourly''
     WHEN CA.BILL_RATE_TYPE = 2 THEN ''Visit''
     WHEN CA.BILL_RATE_TYPE = 3 THEN ''Live-In''
     WHEN CA.BILL_RATE_TYPE = 4 THEN ''Non-Billable'' ELSE ''Hourly''
    END AS SCHEDULE_TYPE -- CHECK WITH bill_u it_type OF fact_visit
    ,  CASE WHEN CA.BILL_RATE_TYPE = 1 THEN ''Hourly''
     WHEN CA.BILL_RATE_TYPE = 2 THEN ''Visit''
     WHEN CA.BILL_RATE_TYPE = 3 THEN ''Live-In''
     WHEN CA.BILL_RATE_TYPE = 4 THEN ''Non-Billable'' ELSE ''Hourly''
    END  AS SCHEDULE_UOM,
        TRUE AS AUTHORIZATION_REQUIRED_FLAG ,-- DIM_CON.,
        NULL AS PAYABLE_FLAG,
        NULL AS EXPENSE_FLAG,
        FALSE  AS MILEAGE_FLAG
FROM  DISC_PROD.CLEARCARE.BILLING_BILLRATE BR 
LEFT JOIN DISC_PROD.CLEARCARE.BILLING_CLIENTAUTHORIZATION AU 
ON AU.BILL_RATE_ID = BR.ID 
  LEFT JOIN   DISC_PROD.CLEARCARE.CARELOGS_CARELOG CA ON AU.ID = CA.AUTHORIZATION_ID
-- ON AU.CLIENT_ID=CA.PATIENT_ID AND AU.AGENCY_ID =CA.AGENCY_ID 
-- AND AU.AUTHORIZATION_ID =CA.AUTHORIZATION_ID::VARCHAR AND AU.BILL_RATE_ID =CA.BILL_RATE_OBJ_ID AND AU.START_DATE BETWEEN CA.CLOCK_IN AND CA.CLOCK_OUT 
--LEFT JOIN DISC_PROD.CLEARCARE.BILLING_CLIENTAUTHORIZATION AU 
--    --AU.ID = CA.AUTHORIZATION_ID AND AU.AGENCY_ID=CA.AGENCY_ID   
LEFT JOIN DISC_PROD.CLEARCARE.PATIENT_PATIENT PA ON PA.ID = CA.PATIENT_ID
LEFT JOIN DISC_PROD.CLEARCARE.AGENCY_AGENCYLOCATION AG ON AG.ID = PA.LOCATION_ID
LEFT JOIN DISC_PROD.CLEARCARE.PROFILE_PARENTPAYERSERVICE PP ON
    PP.id = AU.service_id
LEFT JOIN DISC_PROD.PAYOR_contract_UI.PAYOR_contract_MAPPING PCM ON
      CASE
        WHEN CA.BILL_RATE_NAME = ''''
        AND CA.BILL_RATE_TYPE = 4 THEN ''Non-Billable''
        WHEN CA.BILL_RATE_NAME = ''''
        AND CA.BILL_RATE_TYPE = 3 THEN ''Live-In''
        WHEN CA.BILL_RATE_NAME = ''''
        AND CA.BILL_RATE_TYPE = 2 THEN ''Visit''
        WHEN CA.BILL_RATE_NAME = ''''
        AND CA.BILL_RATE_TYPE = 1 THEN ''Hourly''
        ELSE CA.BILL_RATE_NAME
    END = PCM.CONTRACT_CODE AND PCM.ORIGINAL_SOURCE_SYSTEM_ID=16
LEFT JOIN  DISC_PROD.PAYOR_CONTRACT_UI.PAYOR AS DPP  ON PCM.PAYOR_ID = DPP.PAYOR_ID WHERE AG.AGENCY_ID =2459 
) --SELECT DISTINCT 1,  SCHEDULE_TYPE  FROM pcs ;--WHERE PARENT_CONTRACT_SERVICE_KEY=''703c1e24e38024341f59a1779c126248''
SELECT *,:STR_ETL_TASK_KEY AS ETL_TASK_KEY
        ,:STR_ETL_TASK_KEY AS ETL_INSERTED_TASK_KEY
        ,convert_timezone(''UTC'', CURRENT_TIMESTAMP)::timestamp_ntz as ETL_INSERTED_DATE
        ,CURRENT_USER as ETL_INSERTED_BY 
        ,convert_timezone(''UTC'', CURRENT_TIMESTAMP)::timestamp_ntz as ETL_LAST_UPDATED_DATE
        ,CURRENT_USER as ETL_LAST_UPDATED_BY
        ,0 as ETL_DELETED_FLAG FROM PCS ;
RETURN ''SUCCESS'';
end;
';