CREATE OR REPLACE PROCEDURE DW_PROD.HAH.DELETE_STAGE_HM_DIM_SURVEY_RESPONSE_HEADER()
RETURNS VARCHAR(16777216)
LANGUAGE JAVASCRIPT
EXECUTE AS OWNER
AS '

  sqlCmd = `SELECT 1`;
//  rs = sqlStmt.execute();
  return ''Done'';

';