CREATE OR REPLACE PROCEDURE DW_PROD.HAH.GET_STAGE_COSTALSYNCDATA_FACT_PARTNER_CONTRACT_SERVICE("STR_ETL_TASK_KEY" VARCHAR(16777216), "STR_CDC_START" VARCHAR(16777216), "STR_CDC_END" VARCHAR(16777216))
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
BEGIN
    --*****************************************************************************************************************************
-- NAME:  COSTALSYNCDATA_FACT_PARTNER_CONTRACT_SERVICE
--
-- PURPOSE: Populates Stage COSTALSYNCDATA FACT PARTNER CONTRACT SERVICE
--
-- DEVELOPMENT LOG:
-- DATE        AUTHOR                NOTES:
-- (MM/DD/YY)	
-- --------    -------------------   -----------------------------------------------------------------------------------------------
-- 11/01/23    NUTAN JAGNADE          Initial Development
--*****************************************************************************************************************************

INSERT OVERWRITE INTO STAGE.COSTALSYNCDATA_FACT_PARTNER_CONTRACT_SERVICE

SELECT DISTINCT 
MD5(S.DB || ''-'' || IFF(LEN(NVL(TRIM( l.State_Code), '''')) = 2,NULLIF(trim(l.STATE_CODE),''''),COALESCE(off.STATE, ''GA'')) || ''-'' || COALESCE(PCM.PAYOR_ID,''-1'') || ''-'' || COALESCE(TRIM(S.PLAN_CODE),''UNKNOWN'') || ''-'' || ''COSTALSYNCDATA'') AS PARTNER_CONTRACT_SERVICE_KEY ,
case when TRIM(S.DB) = ''SHC_ALTRUS'' then 1 else 2 end SOURCE_SYSTEM_ID ,
S.DB AS SYSTEM_CODE,
IFF(LEN(NVL(TRIM( l.State_Code), '''')) = 2,NULLIF(trim(l.STATE_CODE),''''),COALESCE(off.STATE, ''GA''))AS STATE,
MD5(NVL(PCM.ORIGINAL_SYSTEM_CODE,''UNKNWON'') || ''-'' || NVL(PCM.PAYOR_ID,''-1'') || ''-'' || NVL(PCM.CONTRACT_CODE,''UNKNOWN'') || ''-'' || ''COSTALSYNCDATA'') AS PARTNER_CONTRACT_KEY ,
NVL(PCM.PAYOR_ID,''-1'') AS PARTNER_CODE,
NVL(PCM.PAYOR_NAME,''UNKNOWN'') AS PARTNER_NAME,
S.PLAN_CODE AS CONTRACT_CODE,
PCM.CONTRACT_NAME AS CONTRACT_NAME,
MD5(S.DB || ''-'' || PCM.CONTRACT_CODE || ''-'' || ''COSTALSYNCDATA'') AS SERVICE_KEY ,
PCM.CONTRACT_CODE AS SERVICE_CODE,
NULL AS SERVICE_DESCRIPTION,
NULL AS BILLING_KEY,
NULL AS BILL_CODE,
NULL AS BILL_NAME,
TRUE AS BILLABLE_FLAG,
''UNKNOWN'' AS BILL_TYPE,
NULL AS BILL_UOM,
''UNKNOWN'' AS SCHEDULE_TYPE,
NULL AS SCHEDULE_UOM,
TRUE AS AUTHORIZATION_REQUIRED_FLAG,
TRUE AS PAYABLE_FLAG,
FALSE EXPENSE_FLAG,
FALSE MILEAGE_FLAG,
:STR_ETL_TASK_KEY AS ETL_TASK_KEY,
:STR_ETL_TASK_KEY AS ETL_INSERTED_TASK_KEY,
Convert_timezone(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ AS ETL_INSERTED_DATE,
CURRENT_USER AS ETL_INSERTED_BY,
Convert_timezone(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ AS ETL_LAST_UPDATED_DATE,
CURRENT_USER AS ETL_LAST_UPDATED_BY,
0 AS ETL_DELETED_FLAG 
FROM DISC_PROD.COSTALSYNCDATA.CV_SCHEDULES S 
LEFT JOIN DISC_PROD.CostalSyncData.CV_Locations l ON UPPER( TRIM( l.LOCATION_CODE)) = UPPER( TRIM( s.LOCATION_CODE))
LEFT JOIN DISC_PROD.STAGE.COASTAL_OFFICE_MAPPING t On TRIM( t.DB) = TRIM( l.DB) AND TRIM( t.LOCATION_CODE) = TRIM( l.Location_Code)
LEFT JOIN ( SELECT * FROM DISC_PROD.HAHUSERS.LOGIN_OFFICE WHERE STATE IN (''GA'', ''SC'')
		AND TRY_CAST(OFFICENUMBER AS INT) IS NOT NULL
		AND TRY_CAST(OFFICENUMBER AS INT) <> 205)AS off 
ON off.OFFICENUMBER = t.HAH_OFFICE_NUMBER
LEFT JOIN DISC_PROD.PAYOR_CONTRACT_UI.PAYOR_CONTRACT_MAPPING PCM ON S.DB=PCM.ORIGINAL_SYSTEM_CODE 
AND trim(S.PLAN_CODE)=trim(PCM.CONTRACT_CODE)
UNION 
SELECT DISTINCT 
MD5(S.DB || ''-'' || IFF(LEN(NVL(TRIM( l.State_Code), '''')) = 2,NULLIF(trim(l.STATE_CODE),''''),COALESCE(off.STATE, ''GA'')) || ''-'' ||  COALESCE(PCM.PAYOR_ID,''-1'') || ''-'' || COALESCE(TRIM(S.CURRENT_PLAN_CODE),''UNKNOWN'') || ''-'' || ''COSTALSYNCDATA'') AS PARTNER_CONTRACT_SERVICE_KEY ,
case when TRIM(S.DB) = ''SHC_ALTRUS'' then 1 else 2 end SOURCE_SYSTEM_ID ,
S.DB AS SYSTEM_CODE,
IFF(LEN(NVL(TRIM( l.State_Code), '''')) = 2,NULLIF(trim(l.STATE_CODE),''''),COALESCE(off.STATE, ''GA'')) AS STATE,
MD5(NVL(PCM.ORIGINAL_SYSTEM_CODE,''UNKNWON'') || ''-'' || NVL(PCM.PAYOR_ID,''-1'') || ''-'' || NVL(PCM.CONTRACT_CODE,''UNKNOWN'') || ''-'' || ''COSTALSYNCDATA'') AS PARTNER_CONTRACT_KEY ,
NVL(PCM.PAYOR_ID,''-1'') AS PARTNER_CODE,
NVL(PCM.PAYOR_NAME,''UNKNOWN'') AS PARTNER_NAME,
S.CURRENT_PLAN_CODE AS CONTRACT_CODE,
PCM.CONTRACT_NAME AS CONTRACT_NAME,
MD5(S.DB || ''-'' || PCM.CONTRACT_CODE || ''-'' || ''COSTALSYNCDATA'') AS SERVICE_KEY ,
PCM.CONTRACT_CODE AS SERVICE_CODE,
NULL AS SERVICE_DESCRIPTION,
NULL AS BILLING_KEY,
NULL AS BILL_CODE,
NULL AS BILL_NAME,
TRUE AS BILLABLE_FLAG,
''UNKNOWN'' AS BILL_TYPE,
NULL AS BILL_UOM,
''UNKNOWN'' AS SCHEDULE_TYPE,
NULL AS SCHEDULE_UOM,
TRUE AS AUTHORIZATION_REQUIRED_FLAG,
TRUE AS PAYABLE_FLAG,
FALSE EXPENSE_FLAG,
FALSE MILEAGE_FLAG,
:STR_ETL_TASK_KEY AS ETL_TASK_KEY,
:STR_ETL_TASK_KEY AS ETL_INSERTED_TASK_KEY,
Convert_timezone(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ AS ETL_INSERTED_DATE,
CURRENT_USER AS ETL_INSERTED_BY,
Convert_timezone(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ AS ETL_LAST_UPDATED_DATE,
CURRENT_USER AS ETL_LAST_UPDATED_BY,
0 AS ETL_DELETED_FLAG 
FROM DISC_PROD.COSTALSYNCDATA.CV_ADMISSIONS s
LEFT JOIN DISC_PROD.CostalSyncData.CV_Locations l ON UPPER( TRIM( l.LOCATION_CODE)) = UPPER( TRIM( s.LOCATION_CODE))
LEFT JOIN DISC_PROD.STAGE.COASTAL_OFFICE_MAPPING t On TRIM( t.DB) = TRIM( l.DB) AND TRIM( t.LOCATION_CODE) = TRIM( l.Location_Code)
LEFT JOIN ( SELECT * FROM DISC_PROD.HAHUSERS.LOGIN_OFFICE WHERE STATE IN (''GA'', ''SC'')
		AND TRY_CAST(OFFICENUMBER AS INT) IS NOT NULL
		AND TRY_CAST(OFFICENUMBER AS INT) <> 205)AS off 
ON off.OFFICENUMBER = t.HAH_OFFICE_NUMBER
LEFT JOIN DISC_PROD.PAYOR_CONTRACT_UI.PAYOR_CONTRACT_MAPPING PCM ON S.DB=PCM.ORIGINAL_SYSTEM_CODE 
AND trim(S.CURRENT_PLAN_CODE)=trim(PCM.CONTRACT_CODE);
return ''SUCCESS'';
END;
';