CREATE OR REPLACE PROCEDURE DW_PROD.HAH.GET_STAGE_PARADOX_FACT_APPLICANT_WITH_PDR_STATUS("STR_ETL_TASK_KEY" VARCHAR(16777216), "STR_CDC_START" VARCHAR(16777216), "STR_CDC_END" VARCHAR(16777216))
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
BEGIN
--*****************************************************************************************************************************
-- NAME:  PARADOX_FACT_APPLICANT_WITH_PDR_STATUS
--
-- PURPOSE: Creates one row per APPLICANT With Pending document review or Hired status from PARADOX
--
-- PRODELOPMENT LOG:
-- DATE        AUTHOR                               NOTES:
-- --------    -------------------                  ---------------------------------------------------------------------------
-- 03/02/2023  Manmohan Soni       					Initial PRODelopment
--*****************************************************************************************************************************
--

INSERT OVERWRITE INTO DW_PROD.STAGE.PARADOX_FACT_APPLICANT_WITH_PDR_STATUS
WITH CANDIDATES_WITH_PDR_STATUS AS (
    SELECT DISTINCT CANDIDATE_ID, REQUISITION_ID, STATUS, MAX(STATUS_CHANGE_DATE) STATUS_CHANGE_DATE  
    FROM DISC_PROD.PARADOX.CANDIDATE_JOURNEY_STATUS_HISTORY
    WHERE 
        UPPER(STATUS) IN (''ORIENTATION/ HIRED: PENDING DOCUMENT REVIEW'', ''ORIENTATION/ HIRED: HIRED'')
    GROUP BY 1, 2, 3
)
, F AS (
    SELECT
        distinct
        CS.CANDIDATE_ID,
        A.FIRST_NAME FIRST_NAME,
        A.MIDDLE_NAME MIDDLE_NAME,
        A.LAST_NAME LAST_NAME,
        A.SSN Social_Security_Number,
        A.DATE_OF_BIRTH DATE_OF_BIRTH,
        A.EMAIL EMAIL,
        COALESCE(CS.CANDIDATE_TIMEZONE, Z.TIMEZONE) TIME_ZONE,
        A.ADDRESS ADDRESS,
        A.ADDRESS_LINE_2 ADDRESS_LINE_2,
        A.CITY CITY,
        G.STATE_ISO_CODE || '' '' || REPLACE(G.COUNTY_NAME, '' County'', '''') COUNTY,
        COALESCE(DSA.STATE_ISO_CODE, UPPER(A.STATE)) STATE,
        A.POSTAL ZIP_CODE,
        CS.CANDIDATE_LOCATION_COUNTRY COUNTRY,
        J.LOCATION_NAME BRANCH_GROUP,
        COALESCE(DSJ.STATE_ISO_CODE, UPPER(J.STATE)) BRANCH_STATE, 
        A.MOBILE_PHONE PHONE,
        A.HOME_PHONE HOME_PHONE,
        A.EEO_SEX GENDER,
        GL.GROUP_ID ALAYACARE_GROUP_ID,
        CCL.ID ALAYACARE_COST_CENTER_ID,
        J.JOB_TITLE POSITION_JOB,
        ADMIN_ROLE.ID ALAYACARE_ADMIN_ROLE_ID,
        FIELD_ROLE.ID ALAYACARE_FIELD_ROLE_PORTAL_ID,
        NULL HAH_OFFICE_NUMBER, -- FIELD USED FOR MO STATE
        CS.CAPTURE_START_DATE CREATED_DATE,
        PDR.STATUS_CHANGE_DATE UPDATED_DATE,
        PDR.STATUS STATUS, 
        TRUE NEWLY_CREATED_FLAG,
        NULL RHAPSODY_DATE_UPDATED,
        :STR_ETL_TASK_KEY ETL_TASK_KEY,
        :STR_ETL_TASK_KEY ETL_INSERTED_TASK_KEY,
        CONVERT_TIMEZONE(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ AS ETL_INSERTED_DATE,
        CURRENT_USER AS ETL_INSERTED_BY,
        CONVERT_TIMEZONE(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ AS ETL_LAST_UPDATED_DATE,
        CURRENT_USER AS ETL_LAST_UPDATED_BY,
        0 AS ETL_DELETED_FLAG
    FROM DW_PROD.HAH.FACT_APPLICANT_STATUS S
        INNER JOIN DW_PROD.HAH.DIM_APPLICANT A ON S.APPLICANT_KEY = A.APPLICANT_KEY
        INNER JOIN DW_PROD.HAH.DIM_JOB J ON S.JOB_KEY = J.JOB_KEY
        INNER JOIN CANDIDATES_WITH_PDR_STATUS PDR ON S.CANDIDATE_ID = PDR.CANDIDATE_ID AND J.JOB_ID = PDR.REQUISITION_ID
        LEFT JOIN DISC_PROD.PARADOX.CANDIDATE_SPECIFIC CS ON S.CANDIDATE_ID = CS.CANDIDATE_ID
        LEFT JOIN DISC_PROD.ALAYACARE.TBL_COST_CENTRES_TIER_4 CCL ON REGEXP_REPLACE(TRIM(UPPER(CS.CANDIDATE_LOCATION__LEVEL_2)), '' OFFICE'', '''') = TRIM(UPPER(CCL.PROPERTIES_DESCRIPTION)) 
        LEFT JOIN DISC_PROD.ALAYACARE.GROUPS GL ON REGEXP_REPLACE(TRIM(UPPER(CS.CANDIDATE_LOCATION__LEVEL_2)), '' OFFICE'', '''') = TRIM(UPPER(GL.PROPERTIES_DESCRIPTION))
        LEFT JOIN DISC_PROD.PARADOX.JOB_TITLE_TO_ALAYACARE_SECURITY_ROLE_MAPPING_GA ROLE_MAPPING ON UPPER(TRIM(ROLE_MAPPING.JOB_TITLE)) = UPPER(TRIM(J.JOB_TITLE))
        LEFT JOIN DISC_PROD.PARADOX.ROLES ADMIN_ROLE ON UPPER(TRIM(ROLE_MAPPING.ALAYACARE_ADMIN_PORTAL_ROLE)) = UPPER(TRIM(ADMIN_ROLE.DESCRIPTION)) AND ADMIN_ROLE.CATEGORY = ''admin''
        LEFT JOIN DISC_PROD.PARADOX.ROLES FIELD_ROLE ON UPPER(TRIM(ROLE_MAPPING.ALAYACARE_FIELD_PORTAL_ROLE)) = UPPER(TRIM(FIELD_ROLE.DESCRIPTION)) AND FIELD_ROLE.CATEGORY = ''staff''
        LEFT JOIN DW_PROD.HAH.DIM_GEOGRAPHY G ON A.POSTAL = G.ZIP_CODE
        LEFT JOIN DW_PROD.HAH.DIM_ZIP_CODE_DETAILED Z ON A.POSTAL = Z.ZIP
        LEFT JOIN DW_PROD.HAH.DIM_STATE DSJ
            ON UPPER(J.STATE) = UPPER(DSJ.STATE_NAME)
        LEFT JOIN DW_PROD.HAH.DIM_STATE DSA
            ON UPPER(A.STATE) = UPPER(DSA.STATE_NAME)
        WHERE
            S.SOURCE_SYSTEM_ID = 12
            and UPPER(J.STATE) = ''GEORGIA''
)
SELECT * FROM F;


    RETURN ''SUCCESS'';
END;
';