CREATE OR REPLACE PROCEDURE DW_PROD.HAH.DELETE_STAGE_SANDATAIMPORT_FACT_INVOICE_TRACKING()
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
    return_result varchar(1000);
BEGIN
	SELECT dayofweek(current_timestamp()) into day_Of_Week;
	if (day_Of_Week = 0) then
		DELETE FROM DW_PROD.HAH.FACT_INVOICE_TRACKING WHERE SOURCE_SYSTEM_ID = 4 AND INVOICE_TRACKING_KEY NOT IN (SELECT INVOICE_TRACKING_KEY FROM DW_PROD.STAGE.VW_CURRENT_SANDATAIMPORT_FACT_INVOICE_TRACKING);
   else
		DELETE FROM DW_PROD.HAH.FACT_INVOICE_TRACKING WHERE SOURCE_SYSTEM_ID = 4 AND INVOICE_TRACKING_KEY IN (SELECT INVOICE_TRACKING_KEY FROM DW_PROD.STAGE.VW_CURRENT_DELETED_SANDATAIMPORT_FACT_INVOICE_TRACKING);
  end if;
		  SELECT CONCAT(''Message : '',"number of rows deleted",'' Rows Deleted.'') into :return_result FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));
  return return_result;
 
END;
';