CREATE OR REPLACE PROCEDURE DW_PROD.REPORT.GET_REPORT_CLIENT_CONVERSION("STR_ETL_TASK_KEY" VARCHAR(16777216), "STR_CDC_START" VARCHAR(16777216), "STR_CDC_END" VARCHAR(16777216))
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
  RETURN_RESULT VARCHAR(1000);
BEGIN
    INSERT OVERWRITE INTO REPORT.CLIENT_CONVERSION
WITH CONVERTED AS
(SELECT
     V.BRANCH_KEY
    ,V.SUPERVISOR_KEY
    ,DATE_TRUNC(''month'',V.REPORT_DATE) AS REPORT_DATE
    ,(IFF(C.CLIENT_CONVERTED_FLAG = 1,COUNT (DISTINCT V.CLIENT_KEY), 0)) AS CONVERTED_CLIENT
    ,SUM(IFF(DATE_TRUNC(''month'',C.FIRST_SERVICE_DATE) = DATE_TRUNC(''month'',V.REPORT_DATE), 1,0)) AS NEW_CLIENT
    ,SUM(IFF(DATE_TRUNC(''month'',C.LAST_SERVICE_DATE) = DATE_TRUNC(''month'',V.REPORT_DATE), 1,0)) AS LOST_CLIENT
    ,SUM(IFF(DATE_TRUNC(''month'',C.REFERRAL_DATE) = DATE_TRUNC(''month'',V.REPORT_DATE), 1,0)) AS REFERRED_LAST_MONTH
    ,SUM(IFF((DATE_TRUNC(''month'',C.REFERRAL_DATE) = DATE_TRUNC(''month'',V.REPORT_DATE)) AND (DATE_TRUNC(''month'',C.FIRST_SERVICE_DATE) = DATE_TRUNC(''month'',V.REPORT_DATE)),1,0)) CONVERTED_LAST_MONTH
    FROM DW_PROD.HAH.FACT_VISIT V
    JOIN DW_PROD.HAH.DIM_CLIENT C ON V.CLIENT_KEY = C.CLIENT_KEY
 --WHERE REPORT_DATE = ''2019-11-01''-- AND SUPERVISOR_KEY = ''cbad3684db0f5812b55d5b6dcfa2dc54'' --AND C.CLIENT_CONVERTED_FLAG = 1

 GROUP BY
 V.BRANCH_KEY
 ,V.SUPERVISOR_KEY
 ,DATE_TRUNC(''month'',V.REPORT_DATE)
 ,C.CLIENT_CONVERTED_FLAG
  ),
CNT AS (

   SELECT
     V.BRANCH_KEY
    ,V.SUPERVISOR_KEY
    ,DATE_TRUNC(''month'',V.REPORT_DATE) AS REPORT_DATE
    ,COUNT (DISTINCT V.CLIENT_NUMBER) AS COUNT_CLIENTS
    ,MAX(CON.CONVERTED_CLIENT) AS CONVERTED_CLIENTS
    ,MAX (CON.NEW_CLIENT) AS NEW_CLIENTS
    ,MAX (CON.LOST_CLIENT) AS LOST_CLIENTS
    ,MAX (CON.REFERRED_LAST_MONTH) AS REFERRED_LAST_MONTH
    ,MAX(CON.CONVERTED_LAST_MONTH) AS CONVERTED_LAST_MONTH
  FROM DW_PROD.HAH.FACT_VISIT V
  FULL OUTER JOIN CONVERTED CON ON CON.BRANCH_KEY = V.BRANCH_KEY AND CON.SUPERVISOR_KEY = V.SUPERVISOR_KEY AND CON.REPORT_DATE = DATE_TRUNC(''month'',V.REPORT_DATE)
 -- WHERE V.REPORT_DATE = ''2019-11-01''-- AND V.SUPERVISOR_KEY = ''cbad3684db0f5812b55d5b6dcfa2dc54''
  GROUP BY
    V.BRANCH_KEY
   ,V.SUPERVISOR_KEY
   ,DATE_TRUNC(''month'',V.REPORT_DATE)

 )

SELECT
     CNT.BRANCH_KEY
    ,CNT.SUPERVISOR_KEY
    ,CNT.REPORT_DATE
    ,CNT.COUNT_CLIENTS
    ,CNT.CONVERTED_CLIENTS
    ,MAX(CONVERTED_CLIENTS/COUNT_CLIENTS) AS CONVERSION_ALL_TIME
    ,CNT.NEW_CLIENTS
    ,CNT.LOST_CLIENTS
    ,CNT.REFERRED_LAST_MONTH
    ,CNT.CONVERTED_LAST_MONTH
    ,MAX(CONVERTED_LAST_MONTH/NULLIF(CNT.NEW_CLIENTS,0)) AS CONVERSION_MONTH
    ,CNT.NEW_CLIENTS - CNT.LOST_CLIENTS AS CLIENT_NET_CHANGE
    ,1 AS NEW_CLIENT
    ,-1 AS ETL_TASK_KEY
    ,-1 AS ETL_INSERTED_TASK_KEY
    ,convert_timezone(''UTC'', CURRENT_TIMESTAMP)::timestamp_ntz as ETL_INSERTED_DATE
    ,CURRENT_USER as ETL_INSERTED_BY
    ,convert_timezone(''UTC'', CURRENT_TIMESTAMP)::timestamp_ntz as ETL_LAST_UPDATED_DATE
    ,CURRENT_USER as ETL_LAST_UPDATED_BY
    ,0 as ETL_DELETED_FLAG
    ,0 as ETL_INFERRED_MEMBER_FLAG
FROM CNT

GROUP BY 1,2,3,4,5,CNT.NEW_CLIENTS,CNT.LOST_CLIENTS,CNT.REFERRED_LAST_MONTH,CNT.CONVERTED_LAST_MONTH;
  SELECT CONCAT (''MESSAGE : '',"number of rows inserted",'' Rows Inserted.'') into :return_result FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));
	RETURN return_result;
    END;
    ';