CREATE OR REPLACE PROCEDURE DW_PROD.HAH.GET_STAGE_EDISON_DIM_BILLING("STR_ETL_TASK_KEY" VARCHAR(16777216), "STR_CDC_START" VARCHAR(16777216), "STR_CDC_END" VARCHAR(16777216))
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
BEGIN
--****************************************************************************************************************************
-- NAME:  EDISON_DIM_PARTNER
--
-- PURPOSE: Creates one row per PARTNER according to EDISON 
--
-- DEVELOPMENT LOG:
-- DATE        AUTHOR                NOTES:
-- --------    -------------------   ------------------------------------------------------------------------------------------
-- 03/22/23     SANKET JAIN          Initial development
--*****************************************************************************************************************************

INSERT OVERWRITE INTO STAGE.EDISON_DIM_BILLING

SELECT DISTINCT MD5(''EDISON'' || ''-'' || SC.SERVICECODEID || ''-'' || NVL(VOR.REVENUE_SUBCATEGORY_CODE,''-1'') || ''-'' || ''HHAEXCHANGE'') AS BILLING_KEY
		, 17 AS SOURCE_SYSTEM_ID
		, ''EDISON'' AS SYSTEM_CODE   	 
   	 	, SC.SERVICECODEID AS BILL_CODE
		, SC.SERVICECODE AS BILL_NAME
		, SC.SERVICECODE AS BILL_DESCRIPTION
		, SC.RATETYPETEXT AS BILL_TYPE
		, CASE WHEN CR.UNITS = 1 THEN ''Hourly''
        	   WHEN CR.UNITS = 2 THEN ''Half Hours''
        	   WHEN CR.UNITS = 4 THEN ''Quarter Hours''
          ELSE NULL END AS BILL_UOM
		, COALESCE(CR.RATE,IR.BILLEDRATE) AS BILL_RATE
		, CR.FROMDATE AS RATE_EFFECTIVE_START_DATE
		, COALESCE(VOR.REVENUE_CATEGORY,''UNKNOWN'')
		, COALESCE(VOR.REVENUE_SUBCATEGORY_CODE,''UNKNOWN'')
		, COALESCE(VOR.REVENUE_SUBCATEGORY_NAME,''UNKNOWN'')
		, NULL AS GL_CODE
		, NULL AS GL_NAME
	 	, NULL AS GL_DESCRIPTION
		, CASE WHEN SC.STATUS = ''Active'' THEN TRUE ELSE FALSE END AS ACTIVE_FLAG
		, :STR_ETL_TASK_KEY AS ETL_TASK_KEY
	 	, :STR_ETL_TASK_KEY AS ETL_INSERTED_TASK_KEY
	    , Convert_timezone(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ AS ETL_INSERTED_DATE
		, CURRENT_USER AS ETL_INSERTED_BY
		, Convert_timezone(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ AS ETL_LAST_UPDATED_DATE
		, CURRENT_USER AS ETL_LAST_UPDATED_BY
	 	, 0 AS ETL_DELETED_FLAG
		, CR.TODATE AS RATE_EFFECTIVE_END_DATE
FROM DISC_PROD.HHAEXCHANGEEDISON.SERVICECODES SC
LEFT JOIN DISC_PROD.HHAEXCHANGEEDISON.Contracts c  on SC.ContractID = c.ContractID
LEFT JOIN DISC_PROD.HHAEXCHANGEEDISON.Payer_REPL PR ON  COALESCE(PR.ContractID,PR.PayerID) = SC.ContractID
LEFT JOIN DISC_PROD.HHAEXCHANGEEDISON.CONTRACTRATES CR ON CR.AGENCYID = SC.AGENCYID
    	AND CR.SERVICECODEID = SC.SERVICECODEID
    	AND CR.TODATE :: DATE > GETDATE()
    	AND CR.FROMDATE :: DATE <= GETDATE()
LEFT JOIN DISC_PROD.HHAEXCHANGEEDISON.VW_EDISON_REVENUE_SEG  vor ON vor.SERVICECODEID = sc.SERVICECODEID
LEFT JOIN (SELECT *FROM  DISC_PROD.HHAEXCHANGEEDISON.TBLINVOICEDETAILS_REPL
			QUALIFY ROW_NUMBER() OVER(PARTITION BY INVSERVICECODEID ORDER BY VISITDATE DESC) = 1 )IR
		ON IR.INVSERVICECODEID = SC.SERVICECODEID 
QUALIFY ROW_NUMBER() OVER(PARTITION BY BILLING_KEY ORDER BY RATE_EFFECTIVE_START_DATE DESC)= 1 ;

return ''SUCCESS'';
END;
';