resource "snowflake_procedure" "DW_PUBLIC_FACT_EMPLOYEE_ACQUIRED_MERGED_POSTPROCESSING" {
	name ="FACT_EMPLOYEE_ACQUIRED_MERGED_POSTPROCESSING"
	database = "DW_${var.SF_ENVIRONMENT}"
	schema = "PUBLIC"
	language  = "JAVASCRIPT"

	arguments {
		name = "STR_ETL_TASK_KEY"
		type = "VARCHAR(16777216)"
}	

	arguments {
		name = "STR_CDC_START"
		type = "VARCHAR(16777216)"
}	

	arguments {
		name = "STR_CDC_END"
		type = "VARCHAR(16777216)"
}	
	return_type = "VARCHAR(16777216)"
	execute_as = "OWNER"
	statement = <<-EOT

        var sql = `
    INSERT OVERWRITE INTO DW_${var.SF_ENVIRONMENT}.HAH.FACT_EMPLOYEE_ACQUIRED_MERGED
WITH ccsi_EMPLOYEE AS(
SELECT DISTINCT cm.EMPLOYEE_KEY FROM HAH.FACT_VISIT visit
JOIN HAH.DIM_BRANCH branch ON visit.BRANCH_KEY = branch.BRANCH_KEY
JOIN INTEGRATION.DIM_EMPLOYEE_MERGED cm ON visit.EMPLOYEE_KEY = cm.ORIGINAL_EMPLOYEE_KEY
WHERE visit.SERVICE_DATE >= ''2021-07-01'' AND branch.SOURCE_SYSTEM_ID = 8
),
dataflex_Employee AS(
SELECT DISTINCT cm.EMPLOYEE_KEY FROM HAH.FACT_VISIT visit
JOIN HAH.DIM_BRANCH branch ON visit.BRANCH_KEY = branch.BRANCH_KEY
JOIN INTEGRATION.DIM_EMPLOYEE_MERGED cm ON visit.EMPLOYEE_KEY = cm.ORIGINAL_EMPLOYEE_KEY
WHERE visit.SERVICE_DATE >= ''2021-07-01'' AND branch.SOURCE_SYSTEM_ID = 3
),
inter AS (
SELECT EMPLOYEE_KEY FROM ccsi_Employee
INTERSECT
SELECT EMPLOYEE_KEY FROM dataflex_Employee
),
ALTAMAHA_EMPLOYEE AS 
(SELECT 
MD5(NVL(TRIM(COMPANY.PROPERTIES_TBL_GT_ACCOUNT_DESCRIPTION), ''Unknown'') || '' ('' || NVL(E.BRANCH_ID,''-1'') || '')'' || ''-'' || E.MASTER_ID || ''-'' || ''ALAYACARE'') AS EMPLOYEE_KEY,
NVL(TRIM(COMPANY.PROPERTIES_TBL_GT_ACCOUNT_DESCRIPTION), ''Unknown'') || '' ('' || NVL(E.BRANCH_ID,''-1'') || '')'' AS SYSTEM_CODE

FROM DISC_DEDUPE_${var.SF_ENVIRONMENT}.ALAYACARE.EMPLOYEE_MASTER_LIST E
INNER JOIN DISC_${var.SF_ENVIRONMENT}.ALAYACARE.EMPLOYEE EMP
ON EMP.EMPLOYEE_ID  = E.EMPLOYEE_ID 
AND EMP.PROFILE_ACQUIRED_BUSINESS_  = ''Altamaha''
LEFT JOIN DISC_${var.SF_ENVIRONMENT}.ALAYACARE.BRANCH AS COMPANY
ON COMPANY.BRANCH_ID = E.BRANCH_ID 
UNION
SELECT 
MD5(NVL(TRIM(COMPANY.PROPERTIES_TBL_GT_ACCOUNT_DESCRIPTION), ''Unknown'') || '' ('' || NVL(E.BRANCH_ID,''-1'') || '')'' || ''-'' || E.MASTER_ID || ''-'' || ''ALAYACARE'') AS EMPLOYEE_KEY,
NVL(TRIM(COMPANY.PROPERTIES_TBL_GT_ACCOUNT_DESCRIPTION), ''Unknown'') || '' ('' || NVL(E.BRANCH_ID,''-1'') || '')'' AS SYSTEM_CODE

FROM DISC_DEDUPE_${var.SF_ENVIRONMENT}.ALAYACARE.EMPLOYEE_MATCH_LIST E
INNER JOIN DISC_${var.SF_ENVIRONMENT}.ALAYACARE.EMPLOYEE EMP
ON EMP.EMPLOYEE_ID  = E.ID AND E.ID <> E.MASTER_ID 
AND EMP.PROFILE_ACQUIRED_BUSINESS_  = ''Altamaha''
LEFT JOIN DISC_${var.SF_ENVIRONMENT}.ALAYACARE.BRANCH AS COMPANY
ON COMPANY.BRANCH_ID = E.BRANCH_ID )
SELECT DISTINCT int.EMPLOYEE_KEY,clm.original_EMPLOYEE_KEY, 
clm.ORIGINAL_SOURCE_SYSTEM_ID,clm.SOURCE_SYSTEM_ID,original_system_code,system_code,
TRUE as Acquired_Flag, ''CCSI Acquired'' as NOtes,
CONVERT_TIMEZONE(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ AS ETL_INSERTED_DATE,
CURRENT_USER AS ETL_INSERTED_BY,
CONVERT_TIMEZONE(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ AS ETL_LAST_UPDATED_DATE,
CURRENT_USER AS ETL_LAST_UPDATED_BY
FROM inter int
inner join integration.dim_EMPLOYEE_merged clm
on clm.EMPLOYEE_KEY = int.EMPLOYEE_KEY
and ORIGINAL_SOURCE_SYSTEM_ID = 8 
WHERE int.EMPLOYEE_KEY IN (SELECT EMPLOYEE_KEY FROM inter)
UNION ALL
SELECT EMPLOYEE_KEY,EMPLOYEE_KEY,9,9,SYSTEM_CODE,SYSTEM_CODE,TRUE,''Altamaha'',
CONVERT_TIMEZONE(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ AS ETL_INSERTED_DATE,
CURRENT_USER AS ETL_INSERTED_BY,
CONVERT_TIMEZONE(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ AS ETL_LAST_UPDATED_DATE,
CURRENT_USER AS ETL_LAST_UPDATED_BY from Altamaha_EMPLOYEE
UNION
SELECT DISTINCT EMPLOYEE_KEY,original_EMPLOYEE_KEY,
ORIGINAL_SOURCE_SYSTEM_ID,SOURCE_SYSTEM_ID,original_system_code,system_code,
TRUE as Acquired_Flag,
''Praetorian'' as Notes,
CONVERT_TIMEZONE(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ AS ETL_INSERTED_DATE,
CURRENT_USER AS ETL_INSERTED_BY,
CONVERT_TIMEZONE(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ AS ETL_LAST_UPDATED_DATE,
CURRENT_USER AS ETL_LAST_UPDATED_BY
FROM dw_dev.integration.dim_EMPLOYEE_MERGED where
EMPLOYEE_key in (
  select employee_key from hah.dim_employee where payroll_id in
  (select EMPLOYEEID from DISC_${var.SF_ENVIRONMENT}.EMPLOYEESETUP.ES_ENTRIESDATA where referral in (''Praetorian'',''Praetorian Employee'')))
  and SOURCE_SYSTEM_ID = 3
;`;
          try {
                snowflake.execute (
                    {sqlText: sql}
                    );
                return "Succeeded.";   // Return a success/error indicator.
                }
            catch (err)  {
                return "Failed: " + err;   // Return a success/error indicator.
                }  
          
 EOT
}

