resource "snowflake_view" "DISC_SANDATAIMPORT_SANDATA_MANUAL_EXCEPTIONCODES" {
	database = "DISC_${var.SF_ENVIRONMENT}"
	schema = "SANDATAIMPORT"
	name = "SANDATA_MANUAL_EXCEPTIONCODES"
	statement = <<-SQL
	 WITH AGENCIES AS (
	SELECT
		DISTINCT AGENCYID
	FROM
		SANDATAIMPORT.SANDATA_EXCEPTIONCODES 
)
,
ALL_CODES AS (
	SELECT
		TRIM($2) AS EXCEPTION_CODE,
		TRIM($1) AS EXCEPTION_DESC
	FROM
		@DISC_${var.SF_ENVIRONMENT}.STAGE.AWSAZSTAGEPROD/Files/sandata-ALL-manual-exception-codes.csv --RSUTHAR/KDHOKAI - CHANGE FILE FORMAT & STAGE
	LIMIT NULL OFFSET 1
)
SELECT
	AGENCIES.*,
	ALL_CODES.*
FROM
	ALL_CODES,
	AGENCIES;
SQL
	or_replace = true 
	is_secure = false 
}

