resource "snowflake_view" "DISC_DEVERO_VIEW_DEVERO_FACILITY" {
	database = "DISC_${var.SF_ENVIRONMENT}"
	schema = "DEVERO"
	name = "VIEW_DEVERO_FACILITY"
	statement = <<-SQL
	 (
WITH RESULT_DATA AS
(
SELECT 	DISTINCT
          F.FACILITY_ID
		, XMLGET(PARSE_XML(F.FACILITY_XML), 'NAME'):"$"::STRING AS NAME
		, XMLGET(PARSE_XML(F.FACILITY_XML), 'FACILITY_TYPE'):"$"::STRING AS FACILITY_TYPE
		, XMLGET(PARSE_XML(F.FACILITY_XML), 'TYPE_OTHER_TEXT'):"$"::STRING AS TYPE_OTHER_TEXT
		, XMLGET(PARSE_XML(F.FACILITY_XML), 'ADDRESS_1'):"$"::STRING AS ADDRESS_1
		, XMLGET(PARSE_XML(F.FACILITY_XML), 'ADDRESS_2'):"$"::STRING AS ADDRESS_2
		, XMLGET(PARSE_XML(F.FACILITY_XML), 'CITY'):"$"::STRING AS CITY
		, XMLGET(PARSE_XML(F.FACILITY_XML), 'STATE'):"$"::STRING AS STATE
		, XMLGET(PARSE_XML(F.FACILITY_XML), 'ZIP_CODE'):"$"::STRING AS ZIP_CODE
		, XMLGET(PARSE_XML(F.FACILITY_XML), 'PHONE'):"$"::STRING AS PHONE
		, XMLGET(PARSE_XML(F.FACILITY_XML), 'FAX'):"$"::STRING AS FAX
		, XMLGET(PARSE_XML(F.FACILITY_XML), 'EMAIL'):"$"::STRING AS EMAIL
		, XMLGET(PARSE_XML(F.FACILITY_XML), 'FACILITY_CODE'):"$"::STRING AS FACILITY_CODE
		, XMLGET(PARSE_XML(F.FACILITY_XML), 'EXTERNAL_ID'):"$"::STRING AS EXTERNAL_ID
		, XMLGET(PARSE_XML(F.FACILITY_XML), 'NPI_NO'):"$"::STRING AS NPI_NO
		, XMLGET(PARSE_XML(F.FACILITY_XML), 'PROTOCOL'):"$"::STRING AS PROTOCOL
		, NULL AS AGENCY_IDS -- FACILITY.VALUE :"$" :: STRING AS AGENCY_ID
		, XMLGET(PARSE_XML(F.FACILITY_XML), 'ACTIVE'):"$"::STRING AS ACTIVE
		, XMLGET(PARSE_XML(F.FACILITY_XML), 'DATE_MODIFIED'):"$"::STRING AS DATE_MODIFIED
		, F.ETL_TASK_KEY
		, F.ETL_INSERTED_TASK_KEY
		, F.ETL_INSERTED_DATE
		, F.ETL_INSERTED_BY
		, F.ETL_LAST_UPDATED_DATE
		, F.ETL_LAST_UPDATED_BY
		, F.ETL_DELETED_FLAG
		, ROW_NUMBER() OVER(PARTITION BY FACILITY_ID ORDER BY DATE_MODIFIED DESC) AS LATEST_MODIFIED
  FROM DISC_${var.SF_ENVIRONMENT}.DEVERO.HIST_${var.SF_ENVIRONMENT}ERO_FACILITY  F
--, LATERAL FLATTEN(XMLGET(PARSE_XML(F.FACILITY_XML), 'AGENCY_IDS'):"$":: ARRAY) FACILITY
--WHERE DATE(F.ETL_LAST_UPDATED_DATE) = COALESCE((
--SELECT MAX(DATE(ETL_LAST_UPDATED_DATE)) FROM DISC_${var.SF_ENVIRONMENT}.DEVERO.HIST_${var.SF_ENVIRONMENT}ERO_FACILITY),DATE(GETDATE()))
  )
  SELECT 
  FACILITY_ID,
	NAME,
	FACILITY_TYPE,
	TYPE_OTHER_TEXT,
	ADDRESS_1,
	ADDRESS_2,
	CITY,
	STATE,
	ZIP_CODE,
	PHONE,
	FAX,
	EMAIL,
	FACILITY_CODE,
	EXTERNAL_ID,
	NPI_NO,
	PROTOCOL,
	AGENCY_IDS,
	ACTIVE,
	DATE_MODIFIED,
	ETL_TASK_KEY,
	ETL_INSERTED_TASK_KEY,
	ETL_INSERTED_DATE,
	ETL_INSERTED_BY,
	ETL_LAST_UPDATED_DATE,
	ETL_LAST_UPDATED_BY,
	ETL_DELETED_FLAG
  FROM RESULT_DATA
 WHERE LATEST_MODIFIED = 1
);
SQL
	or_replace = true 
	is_secure = false 
}

