resource "snowflake_view" "DISC_DEVERO_VIEW_DEVERO_MEDICATION" {
	database = "DISC_${var.SF_ENVIRONMENT}"
	schema = "DEVERO"
	name = "VIEW_DEVERO_MEDICATION"
	statement = <<-SQL
	 (
WITH RESULT_DATA AS 
(
SELECT DISTINCT
	  PATIENT_CODE
	, XMLGET(MED.VALUE, 'CHART_ID'):"$"::STRING AS CHART_ID
	, XMLGET(MED.VALUE, 'CHART_NUMBER'):"$"::STRING AS CHART_NUMBER
	, XMLGET(MED.VALUE, 'FORM_ID'):"$"::STRING AS FORM_ID
	, XMLGET(MED.VALUE, 'FORM_MEDICATION_ID'):"$"::STRING AS FORM_MEDICATION_ID
	, XMLGET(MED.VALUE, 'SEQ_NUM'):"$"::STRING AS SEQ_NUM
	, XMLGET(MED.VALUE, 'MEDICATION_NAME'):"$"::STRING AS MEDICATION_NAME
	, XMLGET(MED.VALUE, 'NDC'):"$"::STRING AS NDC
	, XMLGET(MED.VALUE, 'DATE_CREATED'):"$"::STRING AS DATE_CREATED
	, XMLGET(MED.VALUE, 'DATE_MODIFIED'):"$"::STRING AS DATE_MODIFIED
	, XMLGET(MED.VALUE, 'START_DATE'):"$"::STRING AS START_DATE
	, XMLGET(MED.VALUE, 'DC_DATE'):"$"::STRING AS DC_DATE
	, XMLGET(MED.VALUE, 'TEACH_DATE'):"$"::STRING AS TEACH_DATE
	, XMLGET(MED.VALUE, 'ORDER_TYPE'):"$"::STRING AS ORDER_TYPE
	, XMLGET(MED.VALUE, 'ROUTE'):"$"::STRING AS ROUTE
	, XMLGET(MED.VALUE, 'DOSE'):"$"::STRING AS DOSE
	, XMLGET(MED.VALUE, 'AMOUNT'):"$"::STRING AS AMOUNT
	, XMLGET(MED.VALUE, 'AMOUNT_UNITS'):"$"::STRING AS AMOUNT_UNITS
	, XMLGET(MED.VALUE, 'FREQUENCY'):"$"::STRING AS FREQUENCY
	, XMLGET(MED.VALUE, 'CLASSIFICATION'):"$"::STRING AS CLASSIFICATION
	, XMLGET(MED.VALUE, 'INDICATION'):"$"::STRING AS INDICATION
	, XMLGET(MED.VALUE, 'IS_HOSPICE_COVERED'):"$"::STRING AS IS_HOSPICE_COVERED
	, XMLGET(MED.VALUE, 'IS_CHANGE_IN_COVERAGE'):"$"::STRING AS IS_CHANGE_IN_COVERAGE
	, ETL_TASK_KEY
	, ETL_INSERTED_TASK_KEY
	, ETL_INSERTED_DATE
	, ETL_INSERTED_BY
	, ETL_LAST_UPDATED_DATE
	, ETL_LAST_UPDATED_BY
	, ETL_DELETED_FLAG
	, ROW_NUMBER() OVER(PARTITION BY PATIENT_CODE ORDER BY DATE_MODIFIED DESC) AS LATEST_MODIFIED
  FROM DISC_${var.SF_ENVIRONMENT}.DEVERO.HIST_${var.SF_ENVIRONMENT}ERO_MEDICATION
, LATERAL FLATTEN(PARSE_XML(MEDICATION_XML):"$") MED
--WHERE GET(MED.VALUE, '@') = 'MEDICATION'AND  DATE(ETL_LAST_UPDATED_DATE) = COALESCE((
--SELECT MAX(DATE(ETL_LAST_UPDATED_DATE)) FROM DISC_${var.SF_ENVIRONMENT}.DEVERO.HIST_${var.SF_ENVIRONMENT}ERO_MEDICATION ),DATE(GETDATE()))
)
SELECT PATIENT_CODE
	, CHART_ID
	, CHART_NUMBER
	, FORM_ID
	, FORM_MEDICATION_ID
	, SEQ_NUM
	, MEDICATION_NAME
	, NDC
	, DATE_CREATED
	, DATE_MODIFIED
	, START_DATE
	, DC_DATE
	, TEACH_DATE
	, ORDER_TYPE
	, ROUTE
	, DOSE
	, AMOUNT
	, AMOUNT_UNITS
	, FREQUENCY
	, CLASSIFICATION
	, INDICATION
	, IS_HOSPICE_COVERED
	, IS_CHANGE_IN_COVERAGE
	, ETL_TASK_KEY
	, ETL_INSERTED_TASK_KEY
	, ETL_INSERTED_DATE
	, ETL_INSERTED_BY
	, ETL_LAST_UPDATED_DATE
	, ETL_LAST_UPDATED_BY
	, ETL_DELETED_FLAG
FROM RESULT_DATA
WHERE LATEST_MODIFIED = 1
);
SQL
	or_replace = true 
	is_secure = false 
}

