resource "snowflake_view" "DISC_DEVERO_VIEW_DEVERO_COUNTY_AGENCY" {
	database = "DISC_${var.SF_ENVIRONMENT}"
	schema = "DEVERO"
	name = "VIEW_DEVERO_COUNTY_AGENCY"
	statement = <<-SQL
	 (
	SELECT DISTINCT
	C.COUNTY_ID
			, COUNTY.VALUE:"$"::STRING AS AGENCY_ID
			, C.ETL_TASK_KEY
			, C.ETL_INSERTED_TASK_KEY
			, C.ETL_INSERTED_DATE
			, C.ETL_INSERTED_BY
			, C.ETL_LAST_UPDATED_DATE
			, C.ETL_LAST_UPDATED_BY
			, C.ETL_DELETED_FLAG
			,ROW_NUMBER() OVER(PARTITION BY COUNTY_ID,AGENCY_ID ORDER BY DATE_MODIFIED DESC) AS LATEST_MODIFIED
	FROM DISC_${var.SF_ENVIRONMENT}.DEVERO.HIST_${var.SF_ENVIRONMENT}ERO_COUNTY C
  , LATERAL FLATTEN(XMLGET(PARSE_XML(C.COUNTY_XML), 'AGENCY_IDS'):"$":: ARRAY) COUNTY
--WHERE DATE(C.ETL_LAST_UPDATED_DATE) = COALESCE((
--SELECT MAX(DATE(ETL_LAST_UPDATED_DATE)) FROM DISC_${var.SF_ENVIRONMENT}.DEVERO.HIST_${var.SF_ENVIRONMENT}ERO_COUNTY),DATE(GETDATE()))
)
SELECT
    COUNTY_ID,
	AGENCY_ID,
	ETL_TASK_KEY,
	ETL_INSERTED_TASK_KEY,
	ETL_INSERTED_DATE,
	ETL_INSERTED_BY,
	ETL_LAST_UPDATED_DATE,
	ETL_LAST_UPDATED_BY,
	ETL_DELETED_FLAG
FROM RESULT_DATA
WHERE LATEST_MODIFIED = 1
);
SQL
	or_replace = true 
	is_secure = false 
}

