resource "snowflake_view" "DISC_DEVERO_VIEW_DEVERO_FORM_MARKS" {
	database = "DISC_${var.SF_ENVIRONMENT}"
	schema = "DEVERO"
	name = "VIEW_DEVERO_FORM_MARKS"
	statement = <<-SQL
	 (
WITH RESULT_DATA AS
(
SELECT DISTINCT
		  F.FORM_ID
		, XMLGET(FORM_MARKS.VALUE, 'MARK_NAME'):"$" :: STRING AS MARK_NAME
		, XMLGET(FORM_MARKS.VALUE, 'MARK_DATE'):"$" :: STRING AS MARK_DATE
		, XMLGET(FORM_MARKS.VALUE, 'MARK_EFFECTIVE_DATE'):"$" :: STRING AS MARK_EFFECTIVE_DATE
		, XMLGET(FORM_MARKS.VALUE, 'CAREGIVER_CODE'):"$":: STRING AS CAREGIVER_CODE
	 	, F.ETL_TASK_KEY
		, F.ETL_INSERTED_TASK_KEY
		, F.ETL_INSERTED_DATE
		, F.ETL_INSERTED_BY
		, F.ETL_LAST_UPDATED_DATE
		, F.ETL_LAST_UPDATED_BY
		, F.ETL_DELETED_FLAG
		, ROW_NUMBER() OVER(PARTITION BY F.FORM_ID,MARK_NAME,MARK_DATE,MARK_EFFECTIVE_DATE ORDER BY DATE_MODIFIED DESC) AS LATEST_MODIFIED
FROM DISC_${var.SF_ENVIRONMENT}.DEVERO.HIST_${var.SF_ENVIRONMENT}ERO_FORM F(NODE)
,LATERAL FLATTEN (XMLGET(PARSE_XML(F.FORM_XML) ,'FORM_MARKS'):"$") FORM_MARKS
--WHERE DATE(F.ETL_LAST_UPDATED_DATE) = COALESCE((
--SELECT MAX(DATE(ETL_LAST_UPDATED_DATE)) FROM DISC_${var.SF_ENVIRONMENT}.DEVERO.HIST_${var.SF_ENVIRONMENT}ERO_FORM),DATE(GETDATE()))
)
SELECT 
 FORM_ID
		, MARK_NAME
		, MARK_DATE
		, MARK_EFFECTIVE_DATE
		, CAREGIVER_CODE
		, ETL_TASK_KEY
		, ETL_INSERTED_TASK_KEY
		, ETL_INSERTED_DATE
		, ETL_INSERTED_BY
		, ETL_LAST_UPDATED_DATE
		, ETL_LAST_UPDATED_BY
		, ETL_DELETED_FLAG
FROM RESULT_DATA
WHERE LATEST_MODIFIED = 1
);
SQL
	or_replace = true 
	is_secure = false 
}

