CREATE OR REPLACE TABLE DISC_PROD.HEALTH_NAVIGATOR.DIAGNOSIS_REASON_INTERVENTION__C (
	ID VARCHAR(18),
	LASTMODIFIEDDATE TIMESTAMP_NTZ(9),
	ISDELETED BOOLEAN,
	LASTVIEWEDDATE TIMESTAMP_NTZ(9),
	HEALTH_CONDITION__C VARCHAR(18),
	LASTREFERENCEDDATE TIMESTAMP_NTZ(9),
	REASON_INTERVENTION__C VARCHAR(18),
	NAME VARCHAR(80),
	SYSTEMMODSTAMP TIMESTAMP_NTZ(9),
	CREATEDBYID VARCHAR(18),
	OWNERID VARCHAR(18),
	CREATEDDATE TIMESTAMP_NTZ(9),
	LASTMODIFIEDBYID VARCHAR(18)
);