CREATE OR REPLACE TABLE DISC_PROD.HEALTH_NAVIGATOR.REASON_INTERVENTION__C (
	ID VARCHAR(18),
	LASTMODIFIEDDATE TIMESTAMP_NTZ(9),
	ISDELETED BOOLEAN,
	LASTVIEWEDDATE TIMESTAMP_NTZ(9),
	LASTREFERENCEDDATE TIMESTAMP_NTZ(9),
	CLIENT__C VARCHAR(18),
	NAME VARCHAR(80),
	SYSTEMMODSTAMP TIMESTAMP_NTZ(9),
	CREATEDBYID VARCHAR(18),
	OWNERID VARCHAR(18),
	REASON__C VARCHAR(18),
	IS_RECOMMENDED__C BOOLEAN,
	CREATEDDATE TIMESTAMP_NTZ(9),
	LASTACTIVITYDATE DATE,
	INTERVENTION__C VARCHAR(18),
	LASTMODIFIEDBYID VARCHAR(18)
);