CREATE OR REPLACE TABLE DISC_PROD.ALAYACARE.CLIENT_STATUS (
	ID VARCHAR(250),
	CLIENT_ID NUMBER(38,0),
	CLIENT_STATUS VARCHAR(250),
	EFFECTIVE_DATE TIMESTAMP_NTZ(9),
	EFFECTIVE_DATE_TO TIMESTAMP_NTZ(9),
	REASON_CODE VARCHAR(250),
	CREATION_DATE TIMESTAMP_NTZ(9),
	REVISION_DATE TIMESTAMP_NTZ(9),
	EMPLOYEE_CREATE_ID NUMBER(38,0),
	EMPLOYEE_UPDATE_ID NUMBER(38,0),
	SEQ NUMBER(18,0),
	BRANCH_ID NUMBER(38,0)
);