CREATE OR REPLACE TABLE DISC_PROD.ALAYACARE.USER_RATES (
	ID NUMBER(38,0),
	EMPLOYEE_ID NUMBER(38,0),
	CUSTOM_RATE FLOAT,
	PAY_CODE_RATE FLOAT,
	RATE_START_DATE TIMESTAMP_NTZ(9),
	PAY_CODE VARCHAR(250),
	RATE_TYPE VARCHAR(250),
	PROPERTIES_USER_RATES_PAYROLL_ITEM_ID VARCHAR(250),
	PROPERTIES_USER_RATES_ID VARCHAR(250),
	PROPERTIES_USER_RATES_START_DATE VARCHAR(250),
	PROPERTIES_USER_RATES_RATE VARCHAR(250),
	PROPERTIES_USER_RATES_OVERRIDE_TYPE VARCHAR(250),
	PROPERTIES_USER_RATES_EMPLOYEE_ID VARCHAR(250),
	PROPERTIES_USER_RATES_OP VARCHAR(250)
);