CREATE OR REPLACE TABLE DISC_PROD.HEALTH_NAVIGATOR.SURVEYFEED (
	ID VARCHAR(18),
	PARENTID VARCHAR(18),
	BESTCOMMENTID VARCHAR(18),
	LASTMODIFIEDDATE TIMESTAMP_NTZ(9),
	ISDELETED BOOLEAN,
	TITLE VARCHAR(255),
	SYSTEMMODSTAMP TIMESTAMP_NTZ(9),
	TYPE VARCHAR(40),
	LINKURL VARCHAR(1000),
	CREATEDBYID VARCHAR(18),
	INSERTEDBYID VARCHAR(18),
	CREATEDDATE TIMESTAMP_NTZ(9),
	COMMENTCOUNT NUMBER(9,0),
	RELATEDRECORDID VARCHAR(18),
	LIKECOUNT NUMBER(9,0),
	BODY VARCHAR(10000),
	ISRICHTEXT BOOLEAN
);