CREATE OR REPLACE TABLE DISC_PROD.GENERATIONSALLIANCE.SALESREP (
	SALESREPID NUMBER(10,0) NOT NULL,
	FIRSTNAME VARCHAR(25),
	LASTNAME VARCHAR(25),
	CREATED TIMESTAMP_NTZ(9),
	CREATEDBY VARCHAR(15),
	UPDATED TIMESTAMP_NTZ(9),
	UPDATEDBY VARCHAR(15),
	STATUS VARCHAR(1),
	SYS_CHANGE_VERSION NUMBER(18,0),
	SYS_CHANGE_OPERATION VARCHAR(1),
	ETL_TASK_KEY NUMBER(38,0) NOT NULL,
	ETL_INSERTED_TASK_KEY NUMBER(38,0) NOT NULL,
	ETL_INSERTED_DATE TIMESTAMP_NTZ(9) NOT NULL,
	ETL_INSERTED_BY VARCHAR(100) NOT NULL,
	ETL_LAST_UPDATED_DATE TIMESTAMP_NTZ(9) NOT NULL,
	ETL_LAST_UPDATED_BY VARCHAR(100) NOT NULL,
	ETL_DELETED_FLAG BOOLEAN NOT NULL
);