CREATE OR REPLACE TABLE DISC_PROD.HEALTH_NAVIGATOR.HEALTHCLOUDGA__CROSSOBJECTRELATIONSHIP__C (
	ID VARCHAR(18),
	LASTMODIFIEDDATE TIMESTAMP_NTZ(9),
	ISDELETED BOOLEAN,
	LASTVIEWEDDATE TIMESTAMP_NTZ(9),
	HEALTHCLOUDGA__FROMOBJECT__C VARCHAR(99),
	LASTREFERENCEDDATE TIMESTAMP_NTZ(9),
	NAME VARCHAR(80),
	SYSTEMMODSTAMP TIMESTAMP_NTZ(9),
	HEALTHCLOUDGA__RELATIONSHIP__C VARCHAR(99),
	CREATEDBYID VARCHAR(18),
	OWNERID VARCHAR(18),
	CREATEDDATE TIMESTAMP_NTZ(9),
	HEALTHCLOUDGA__REVERSERELATIONSHIP__C VARCHAR(99),
	HEALTHCLOUDGA__TOOBJECT__C VARCHAR(99),
	LASTMODIFIEDBYID VARCHAR(18)
);