CREATE OR REPLACE TABLE DISC_PROD.ZENDESK.HIST_TICKET_METRICS (
	SOURCE VARCHAR(3),
	ID VARCHAR(16777216),
	JSON_DATA VARIANT,
	ETL_TASK_KEY NUMBER(9,0),
	ETL_INSERTED_TASK_KEY NUMBER(9,0),
	ETL_INSERTED_DATE TIMESTAMP_NTZ(9),
	ETL_INSERTED_BY VARCHAR(16777216),
	ETL_LAST_UPDATED_DATE TIMESTAMP_NTZ(9),
	ETL_LAST_UPDATED_BY VARCHAR(16777216),
	ETL_DELETED_FLAG NUMBER(1,0)
);