CREATE OR REPLACE TABLE DISC_PROD.UTIL.MIGRATED_BRANCH_BY_SOURCESYSTEM (
	OFFICE_NAME VARCHAR(100),
	OFFICE_NUMBER NUMBER(38,0),
	SYSTEM_CODE VARCHAR(20),
	SOURCE_SYSTEM_ID NUMBER(38,0),
	CUTTOFF_DATE DATE
);