CREATE OR REPLACE TABLE DISC_PROD.HEALTH_NAVIGATOR.SURVEYEMAILBRANDING (
	ID VARCHAR(18),
	FROMEMAILADDRESS VARCHAR(80),
	LASTMODIFIEDDATE TIMESTAMP_NTZ(9),
	ISDELETED BOOLEAN,
	FOOTERIMAGEID VARCHAR(18),
	MASTERLABEL VARCHAR(80),
	SUBJECT VARCHAR(255),
	SYSTEMMODSTAMP TIMESTAMP_NTZ(9),
	CREATEDBYID VARCHAR(18),
	LANGUAGE VARCHAR(40),
	HEADERIMAGEID VARCHAR(18),
	CREATEDDATE TIMESTAMP_NTZ(9),
	BODY VARCHAR(4000),
	DEVELOPERNAME VARCHAR(80),
	LASTMODIFIEDBYID VARCHAR(18)
);