CREATE OR REPLACE TABLE DISC_PROD.HAH_REPORTING.AGING_SUMMARY_CONTRACTS (
	DFDB VARCHAR(12),
	CONTRACTCODE VARCHAR(5),
	CONTRACTNAME VARCHAR(50),
	PAYMENTMETHOD VARCHAR(5),
	BILLPERSONCODE VARCHAR(5),
	BILLPERSONNAME VARCHAR(50),
	BILLPERSONOFFICE VARCHAR(50),
	FILTERINGBILLPERSONOFFICE BOOLEAN,
	SYS_CHANGE_VERSION NUMBER(18,0),
	SYS_CHANGE_OPERATION VARCHAR(1),
	ETL_TASK_KEY NUMBER(38,0),
	ETL_INSERTED_TASK_KEY NUMBER(38,0),
	ETL_INSERTED_DATE TIMESTAMP_NTZ(9),
	ETL_INSERTED_BY VARCHAR(100),
	ETL_LAST_UPDATED_DATE TIMESTAMP_NTZ(9),
	ETL_LAST_UPDATED_BY VARCHAR(100),
	ETL_DELETED_FLAG BOOLEAN
);