CREATE OR REPLACE TABLE DISC_PROD.HEALTH_NAVIGATOR.CASETEAMTEMPLATEMEMBER (
	ID VARCHAR(18),
	TEAMROLEID VARCHAR(18),
	TEAMTEMPLATEID VARCHAR(18),
	LASTMODIFIEDDATE TIMESTAMP_NTZ(9),
	MEMBERID VARCHAR(18),
	CREATEDBYID VARCHAR(18),
	CREATEDDATE TIMESTAMP_NTZ(9),
	LASTMODIFIEDBYID VARCHAR(18),
	SYSTEMMODSTAMP TIMESTAMP_NTZ(9)
);