CREATE OR REPLACE TABLE DISC_PROD.HEALTH_NAVIGATOR.HEALTHCLOUDGA__RECIPROCALROLE__C (
	ID VARCHAR(18),
	LASTMODIFIEDDATE TIMESTAMP_NTZ(9),
	ISDELETED BOOLEAN,
	HEALTHCLOUDGA__INVERSEROLE__C VARCHAR(80),
	LASTVIEWEDDATE TIMESTAMP_NTZ(9),
	LASTREFERENCEDDATE TIMESTAMP_NTZ(9),
	HEALTHCLOUDGA__RELATIONSHIPTYPE__C VARCHAR(255),
	NAME VARCHAR(80),
	SYSTEMMODSTAMP TIMESTAMP_NTZ(9),
	CREATEDBYID VARCHAR(18),
	OWNERID VARCHAR(18),
	HEALTHCLOUDGA__CREATEINVERSEROLE__C BOOLEAN,
	CREATEDDATE TIMESTAMP_NTZ(9),
	RECORDTYPEID VARCHAR(18),
	HEALTHCLOUDGA__SOURCESYSTEMID__C VARCHAR(100),
	HEALTHCLOUDGA__INVERSERELATIONSHIP__C VARCHAR(18),
	LASTMODIFIEDBYID VARCHAR(18)
);