CREATE OR REPLACE TABLE DISC_PROD.PUBLIC.PIPELINE_ADHOC_PROCESSING (
	ID NUMBER(38,0),
	SOURCESYSTEM VARCHAR(100),
	QUERY VARCHAR(1000),
	FLAG VARCHAR(100),
	LAST_RUNDATE VARCHAR(100),
	SOURCE_CONTAINER VARCHAR(100),
	SOURCE_DIRECTORY VARCHAR(100),
	ARCHIVE_CONTAINER VARCHAR(100),
	ARCHIVE_DIRECTORY VARCHAR(100)
);