CREATE OR REPLACE TABLE DISC_PROD.PAYOR_CONTRACT_UI.REVENUE_SUBCATEGORY (
	REVENUE_CATEGORY_CODE VARCHAR(10) NOT NULL,
	REVENUE_CATEGORY_NAME VARCHAR(50) NOT NULL,
	REVENUE_SUBCATEGORY_CODE VARCHAR(10) NOT NULL,
	REVENUE_SUBCATEGORY_NAME VARCHAR(50) NOT NULL,
	ETL_TASK_KEY NUMBER(38,0) NOT NULL,
	ETL_INSERTED_TASK_KEY NUMBER(38,0) NOT NULL,
	ETL_INSERTED_DATE TIMESTAMP_NTZ(9) NOT NULL,
	ETL_INSERTED_BY VARCHAR(100) NOT NULL,
	ETL_LAST_UPDATED_DATE TIMESTAMP_NTZ(9) NOT NULL,
	ETL_LAST_UPDATED_BY VARCHAR(100) NOT NULL,
	constraint PK_REVENUE_CATEGORY_REVENUE_CATEGORY_CODE_0 primary key (REVENUE_CATEGORY_CODE, REVENUE_SUBCATEGORY_CODE)
);