CREATE OR REPLACE TABLE DISC_PROD.WORKDAY.WORKER_PERSONAL (
	EMPLOYEE_ID VARCHAR(100) NOT NULL,
	GENDER VARCHAR(20),
	BIRTH_DATE DATE,
	MARITAL_STATUS VARCHAR(15),
	ETHNICITY VARCHAR(16777216),
	HISPANIC_OR_LATINO BOOLEAN,
	LANDING_INSERTED_DATE TIMESTAMP_NTZ(9),
	LANDING_INSERTED_BY VARCHAR(16777216),
	PROCESSED_TIMESTAMP TIMESTAMP_NTZ(9),
	ETL_INSERTED_BY VARCHAR(16777216),
	ETL_LAST_UPDATED_DATE TIMESTAMP_NTZ(9),
	ETL_LAST_UPDATED_BY VARCHAR(16777216),
	ETL_DELETED_FLAG BOOLEAN,
	FILE VARCHAR(16777216),
	ETL_TASK_KEY NUMBER(38,0),
	ETL_INSERTED_DATE TIMESTAMP_NTZ(9)
);