CREATE OR REPLACE TABLE DISC_PROD.GENERATIONSALLIANCE.PASSWORDHISTORY (
	USERREFERENCEID VARCHAR(100) NOT NULL,
	USERTYPE VARCHAR(50) NOT NULL,
	OLDPASSWORD VARCHAR(500),
	OLDPASSWORDSTRONG VARCHAR(1000),
	SYS_CHANGE_VERSION NUMBER(18,0),
	SYS_CHANGE_OPERATION VARCHAR(1),
	ETL_TASK_KEY NUMBER(38,0) NOT NULL,
	ETL_INSERTED_TASK_KEY NUMBER(38,0) NOT NULL,
	ETL_INSERTED_DATE TIMESTAMP_NTZ(9) NOT NULL,
	ETL_INSERTED_BY VARCHAR(100) NOT NULL,
	ETL_LAST_UPDATED_DATE TIMESTAMP_NTZ(9) NOT NULL,
	ETL_LAST_UPDATED_BY VARCHAR(100) NOT NULL,
	ETL_DELETED_FLAG BOOLEAN NOT NULL
);