CREATE OR REPLACE TABLE DISC_PROD.ASR.ASR_SERVICE_TYPE_MAPPING (
	SERVICE_TYPE_ID NUMBER(38,0),
	SERVICE_TYPE_NAME VARCHAR(64),
	BASE_RATE NUMBER(38,2),
	UNIT_RATE_15_MINS NUMBER(38,2),
	IS_FIXED_RATE BOOLEAN
);