CREATE OR REPLACE TABLE DISC_PROD.BI_REPOSITORY.GA_COASTALALTRUS_DEPARTMENTMAPPING (
	GA_DB VARCHAR(1),
	DEPARTMENT VARCHAR(10),
	BRANCHNAME VARCHAR(100),
	OFFICENUMBER NUMBER(10,0),
	SYS_CHANGE_VERSION NUMBER(18,0),
	SYS_CHANGE_OPERATION VARCHAR(1),
	ETL_TASK_KEY NUMBER(38,0),
	ETL_INSERTED_TASK_KEY NUMBER(38,0),
	ETL_INSERTED_DATE TIMESTAMP_NTZ(9),
	ETL_INSERTED_BY VARCHAR(100),
	ETL_LAST_UPDATED_DATE TIMESTAMP_NTZ(9),
	ETL_LAST_UPDATED_BY VARCHAR(100),
	ETL_DELETED_FLAG BOOLEAN
);