CREATE OR REPLACE TABLE DISC_PROD.HEALTH_NAVIGATOR.SURVEYVERSIONADDLINFO (
	ID VARCHAR(18),
	LASTMODIFIEDDATE TIMESTAMP_NTZ(9),
	ISDELETED BOOLEAN,
	SURVEYQUESTIONID VARCHAR(18),
	ENGAGEMENTCONTEXTMETADATA VARCHAR(255),
	EMAILSENDER VARCHAR(400),
	INVITATIONSHARINGROLE VARCHAR(255),
	NAME VARCHAR(255),
	SYSTEMMODSTAMP TIMESTAMP_NTZ(9),
	CREATEDBYID VARCHAR(18),
	LANGUAGE VARCHAR(255),
	CREATEDDATE TIMESTAMP_NTZ(9),
	SURVEYVERSIONID VARCHAR(18),
	LASTMODIFIEDBYID VARCHAR(18)
);