CREATE OR REPLACE TABLE DISC_PROD.CCSI.DESKINFO (
	RECORD_NUMBER NUMBER(38,0),
	AREA VARCHAR(200),
	DESK_DESIGNATOR VARCHAR(100),
	SUPERVISOR_INITIAL VARCHAR(100),
	SUPERVISOR_NAME VARCHAR(200),
	CREATED_DATE VARCHAR(200),
	CREATED_BY VARCHAR(200),
	UPDATED_DATE VARCHAR(200),
	UPDATED_BY VARCHAR(200),
	ETL_TASK_KEY NUMBER(38,0),
	ETL_INSERTED_TASK_KEY NUMBER(38,0),
	ETL_INSERTED_DATE TIMESTAMP_NTZ(9),
	ETL_INSERTED_BY VARCHAR(200),
	ETL_LAST_UPDATED_DATE TIMESTAMP_NTZ(9),
	ETL_LAST_UPDATED_BY VARCHAR(200),
	ETL_DELETED_FLAG BOOLEAN
);