CREATE OR REPLACE TABLE DISC_PROD.ZENDESK.USERS_WITH_ERROR (
	TYPE VARCHAR(10),
	SOURCE VARCHAR(10),
	ID VARCHAR(20),
	EXTERNAL_ID VARCHAR(15),
	NAME VARCHAR(50),
	EMPLOYEE_KEY VARCHAR(100),
	DETAILS VARCHAR(1000),
	STATUS VARCHAR(10),
	ETL_INSERTED_DATE TIMESTAMP_NTZ(9)
);