CREATE OR REPLACE TABLE DISC_PROD.ALAYACARE.EMPLOYMENT_TYPE (
	LAKE_ID NUMBER(38,0),
	EMPLOYEE_ID NUMBER(38,0),
	EMPLOYMENT_NAME VARCHAR(250),
	ELIGIBLE_FOR_HOLIDAYS NUMBER(38,0),
	PROPERTIES VARCHAR(250)
);