CREATE OR REPLACE TABLE DISC_PROD.JAZZHR.APPLICANTTOJOBS (
	ID VARCHAR(100),
	APPLICANT_ID VARCHAR(100),
	JOB_ID VARCHAR(100),
	RATING VARCHAR(20),
	WORKFLOW_STEP_ID VARCHAR(20),
	DATE VARCHAR(10),
	ETL_TASK_KEY NUMBER(38,0),
	ETL_INSERTED_TASK_KEY NUMBER(38,0),
	ETL_INSERTED_DATE TIMESTAMP_NTZ(9),
	ETL_INSERTED_BY VARCHAR(100),
	ETL_LAST_UPDATED_DATE TIMESTAMP_NTZ(9),
	ETL_LAST_UPDATED_BY VARCHAR(100),
	ETL_DELETED_FLAG BOOLEAN
);