CREATE OR REPLACE TABLE DISC_PROD.HEALTH_NAVIGATOR.USERROLE (
	ID VARCHAR(18),
	LASTMODIFIEDDATE TIMESTAMP_NTZ(9),
	PORTALACCOUNTOWNERID VARCHAR(18),
	CONTACTACCESSFORACCOUNTOWNER VARCHAR(40),
	ROLLUPDESCRIPTION VARCHAR(80),
	OPPORTUNITYACCESSFORACCOUNTOWNER VARCHAR(40),
	CASEACCESSFORACCOUNTOWNER VARCHAR(40),
	NAME VARCHAR(80),
	SYSTEMMODSTAMP TIMESTAMP_NTZ(9),
	PARENTROLEID VARCHAR(18),
	DEVELOPERNAME VARCHAR(80),
	LASTMODIFIEDBYID VARCHAR(18),
	PORTALACCOUNTID VARCHAR(18),
	PORTALTYPE VARCHAR(40)
);