CREATE OR REPLACE TABLE DISC_PROD.ALAYACARE.CLIENT_RISK (
	CLIENT_ID NUMBER(38,0),
	RISK VARCHAR(16777216),
	CATEGORY VARCHAR(250),
	SEVERITY VARCHAR(250),
	EMPLOYEE_CREATE_ID NUMBER(38,0),
	RISK_CREATE_TIME TIMESTAMP_NTZ(9),
	RISK_UPDATE_TIME TIMESTAMP_NTZ(9)
);