CREATE OR REPLACE TABLE DISC_PROD.HHAEXCHANGEEDISON.POCMASTER_REPL (
	AGENCYID NUMBER(10,0),
	POCMASTERID NUMBER(19,0),
	POCMASTERTYPE NUMBER(3,0),
	PERSONALCATEGORYID NUMBER(19,0),
	DENYIFMANAGEDCARE NUMBER(19,0),
	CREATEDBY NUMBER(19,0),
	CREATEDDATE TIMESTAMP_NTZ(9),
	SYS_CHANGE_VERSION NUMBER(18,0),
	SYS_CHANGE_OPERATION VARCHAR(1),
	ETL_TASK_KEY NUMBER(38,0),
	ETL_INSERTED_TASK_KEY NUMBER(38,0),
	ETL_INSERTED_DATE TIMESTAMP_NTZ(9),
	ETL_INSERTED_BY VARCHAR(100),
	ETL_LAST_UPDATED_DATE TIMESTAMP_NTZ(9),
	ETL_LAST_UPDATED_BY VARCHAR(100),
	ETL_DELETED_FLAG BOOLEAN
);