CREATE OR REPLACE TABLE DISC_PROD.STAGE.ADAPTIVE_CONTRACTCODE_MAPPING_MI (
	PAYOR_ID NUMBER(38,0) NOT NULL,
	SERVICE_CODE VARCHAR(10) NOT NULL,
	STATE VARCHAR(2) NOT NULL,
	CONTRACT_CODE VARCHAR(10)
);