CREATE OR REPLACE TABLE DISC_PROD.WORKDAY.HIST_WORKER_SUMMARY (
	EMPLOYEE_ID VARCHAR(100) NOT NULL,
	NAME VARCHAR(200),
	ELIGIBILITY BOOLEAN,
	LANDING_INSERTED_DATE TIMESTAMP_NTZ(9),
	LANDING_INSERTED_BY VARCHAR(16777216),
	PROCESSED_TIMESTAMP TIMESTAMP_NTZ(9),
	ETL_INSERTED_BY VARCHAR(16777216),
	ETL_DELETED_FLAG BOOLEAN,
	FILE VARCHAR(16777216),
	ETL_TASK_KEY NUMBER(38,0),
	ETL_INSERTED_DATE TIMESTAMP_NTZ(9)
);