CREATE OR REPLACE TABLE DISC_PROD.HHAEXCHANGEOPENSYSTEMS.INITIATEPROCESSINGDETAIL (
	AGENCYID NUMBER(10,0) NOT NULL,
	AUTOPROCESSSETUPID NUMBER(10,0) NOT NULL,
	PROCESSNAME VARCHAR(500),
	LASTEXECUTED VARCHAR(16),
	USERNAME VARCHAR(50),
	DURATION VARCHAR(8),
	PROCESSINFO VARCHAR(8000),
	OFFICES VARCHAR(8000),
	SYS_CHANGE_VERSION NUMBER(18,0),
	SYS_CHANGE_OPERATION VARCHAR(1),
	ETL_TASK_KEY NUMBER(38,0) NOT NULL,
	ETL_INSERTED_TASK_KEY NUMBER(38,0) NOT NULL,
	ETL_INSERTED_DATE TIMESTAMP_NTZ(9) NOT NULL,
	ETL_INSERTED_BY VARCHAR(100) NOT NULL,
	ETL_LAST_UPDATED_DATE TIMESTAMP_NTZ(9) NOT NULL,
	ETL_LAST_UPDATED_BY VARCHAR(100) NOT NULL,
	ETL_DELETED_FLAG BOOLEAN NOT NULL
);