CREATE OR REPLACE TABLE DISC_PROD.HEALTH_NAVIGATOR.CAREPROGRAMENROLLEEHISTORY (
	ID VARCHAR(18),
	FIELD VARCHAR(255),
	ISDELETED BOOLEAN,
	CREATEDBYID VARCHAR(18),
	OLDVALUE VARCHAR(255),
	CAREPROGRAMENROLLEEID VARCHAR(18),
	CREATEDDATE TIMESTAMP_NTZ(9),
	DATATYPE VARCHAR(40),
	NEWVALUE VARCHAR(255)
);