CREATE OR REPLACE TABLE DISC_PROD.HEALTH_NAVIGATOR.ACCOUNTTEAMMEMBER (
	ID VARCHAR(18),
	LASTMODIFIEDDATE TIMESTAMP_NTZ(9),
	ISDELETED BOOLEAN,
	ACCOUNTID VARCHAR(18),
	CASEACCESSLEVEL VARCHAR(40),
	TITLE VARCHAR(80),
	TEAMMEMBERROLE VARCHAR(255),
	ACCOUNTACCESSLEVEL VARCHAR(40),
	SYSTEMMODSTAMP TIMESTAMP_NTZ(9),
	CONTACTACCESSLEVEL VARCHAR(40),
	CREATEDBYID VARCHAR(18),
	OPPORTUNITYACCESSLEVEL VARCHAR(40),
	USERID VARCHAR(18),
	CREATEDDATE TIMESTAMP_NTZ(9),
	PHOTOURL VARCHAR(255),
	LASTMODIFIEDBYID VARCHAR(18),
	ACTIVE__C BOOLEAN
);