CREATE OR REPLACE TABLE DISC_PROD.GENERATIONSALLIANCE.ICD10DIAGNOSIS (
	VERSION VARCHAR(4) NOT NULL,
	ORDERNUMBER VARCHAR(6) NOT NULL,
	ICD10CODE VARCHAR(7),
	HEADER BOOLEAN,
	SHORTDESCR VARCHAR(230),
	LONGDESCR VARCHAR(230),
	SYS_CHANGE_VERSION NUMBER(18,0),
	SYS_CHANGE_OPERATION VARCHAR(1),
	ETL_TASK_KEY NUMBER(38,0) NOT NULL,
	ETL_INSERTED_TASK_KEY NUMBER(38,0) NOT NULL,
	ETL_INSERTED_DATE TIMESTAMP_NTZ(9) NOT NULL,
	ETL_INSERTED_BY VARCHAR(100) NOT NULL,
	ETL_LAST_UPDATED_DATE TIMESTAMP_NTZ(9) NOT NULL,
	ETL_LAST_UPDATED_BY VARCHAR(100) NOT NULL,
	ETL_DELETED_FLAG BOOLEAN NOT NULL
);