CREATE OR REPLACE TABLE DISC_PROD.HEALTH_NAVIGATOR.HEALTHCLOUDGA__CAREPLANTEMPLATEPROBLEM__C (
	ID VARCHAR(18),
	HEALTHCLOUDGA__PRIORITY__C VARCHAR(255),
	LASTMODIFIEDDATE TIMESTAMP_NTZ(9),
	ISDELETED BOOLEAN,
	HEALTHCLOUDGA__CATEGORY__C VARCHAR(255),
	HEALTHCLOUDGA__SORTORDER__C NUMBER(15,0),
	HEALTHCLOUDGA__DESCRIPTION__C VARCHAR(255),
	NAME VARCHAR(80),
	SYSTEMMODSTAMP TIMESTAMP_NTZ(9),
	CREATEDBYID VARCHAR(18),
	OWNERID VARCHAR(18),
	CREATEDDATE TIMESTAMP_NTZ(9),
	HEALTHCLOUDGA__CAREPLANTEMPLATE__C VARCHAR(18),
	HEALTHCLOUDGA__ACTIVE__C BOOLEAN,
	LASTMODIFIEDBYID VARCHAR(18)
);