CREATE OR REPLACE TABLE DISC_PROD.GPSYNCDATA.HIST_UPR40300 (
	ADDLDESC VARCHAR(131),
	CHANGEBY_I VARCHAR(15),
	CHANGEDATE_I TIMESTAMP_NTZ(9),
	DEPRTMNT VARCHAR(7),
	DEX_ROW_ID NUMBER(10,0),
	DSCRIPTN VARCHAR(31),
	NOTEINDX NUMBER(19,5),
	SYS_CHANGE_VERSION NUMBER(18,0),
	SYS_CHANGE_OPERATION VARCHAR(1),
	ETL_TASK_KEY NUMBER(38,0),
	ETL_INSERTED_TASK_KEY NUMBER(38,0),
	ETL_INSERTED_DATE TIMESTAMP_NTZ(9),
	ETL_INSERTED_BY VARCHAR(100),
	ETL_LAST_UPDATED_DATE TIMESTAMP_NTZ(9),
	ETL_LAST_UPDATED_BY VARCHAR(100),
	ETL_DELETED_FLAG BOOLEAN
);