CREATE OR REPLACE TABLE DISC_PROD.NAVISION.EMPLOYEE_PAYROLL_CONTROL (
	TIMESTAMP VARCHAR(30),
	EMPLOYEE_NO_ VARCHAR(30),
	PAY_CONTROL_CODE VARCHAR(30),
	MONTHLY_SCHEDULE VARCHAR(30),
	ACTIVE VARCHAR(30),
	PAYROLL_POSTING_GROUP VARCHAR(30),
	ORDER_NO_ VARCHAR(30),
	DESCRIPTION VARCHAR(30),
	ETL_TASK_KEY NUMBER(1,0),
	ETL_INSERTED_TASK_KEY NUMBER(1,0),
	ETL_INSERTED_DATE DATE,
	ETL_INSERTED_BY VARCHAR(16777216),
	ETL_LAST_UPDATED_DATE DATE,
	ETL_LAST_UPDATED_BY VARCHAR(16777216),
	ETL_DELETED_FLAG BOOLEAN
);