CREATE OR REPLACE TABLE DISC_PROD.PUBLIC.PIPELINE_CONFIG_DISCOVERY_CONDITION_20230212 (
	ID NUMBER(38,0) NOT NULL,
	SOURCESYSTEM VARCHAR(50) NOT NULL,
	SCHEMANAME VARCHAR(500) NOT NULL,
	TABLENAME VARCHAR(1000) NOT NULL,
	DISCCONDITION VARCHAR(500) NOT NULL,
	INSERTDATE TIMESTAMP_NTZ(9) NOT NULL,
	constraint PK_ID primary key (ID)
);