CREATE OR REPLACE TABLE DISC_PROD.ALAYACARE.OFFER_RESPONSE (
	RESP_ID NUMBER(38,0),
	OFFER_ID NUMBER(38,0),
	OFFER_GUID_TO NUMBER(38,0),
	OFFER_STATUS_UPDATE_EMPLOYEE_ID NUMBER(38,0),
	OFFER_CREATION_EMPLOYEE_ID NUMBER(38,0),
	RESP_EMPLOYEE_ID NUMBER(38,0),
	RESP_UPDATE_EMPLOYEE_ID NUMBER(38,0),
	OFFER_DUE_DATE_ID TIMESTAMP_NTZ(9),
	OFFER_STATUS_UPDATE_DATE_ID TIMESTAMP_NTZ(9),
	OFFER_CREATION_DATE_ID TIMESTAMP_NTZ(9),
	RESP_UPDATE_DATE_ID TIMESTAMP_NTZ(9),
	OFFER_STATUS VARCHAR(16777216),
	RESP_COMMENT VARCHAR(16777216),
	RESP_ACTIVE NUMBER(38,0),
	RESP_STATUS VARCHAR(16777216),
	RESP_RECEIVED NUMBER(1,0),
	REC_START_DATE TIMESTAMP_NTZ(9)
);