CREATE OR REPLACE TABLE DISC_PROD.COSTALSYNCDATA.CV_LOCATIONOFFICEBREAKDOWN (
	DB VARCHAR(15) NOT NULL,
	LOCATIONCODE VARCHAR(15) NOT NULL,
	DESCRIPTION VARCHAR(50),
	OFFICE VARCHAR(50) NOT NULL,
	ETL_TASK_KEY NUMBER(38,0) NOT NULL,
	ETL_INSERTED_TASK_KEY NUMBER(38,0) NOT NULL,
	ETL_INSERTED_DATE TIMESTAMP_NTZ(9) NOT NULL,
	ETL_INSERTED_BY VARCHAR(100) NOT NULL,
	ETL_LAST_UPDATED_DATE TIMESTAMP_NTZ(9) NOT NULL,
	ETL_LAST_UPDATED_BY VARCHAR(100) NOT NULL,
	ETL_DELETED_FLAG BOOLEAN NOT NULL
);