CREATE OR REPLACE TABLE DISC_PROD.HEALTH_NAVIGATOR.SURVEYQUESTIONCHOICE (
	ID VARCHAR(18),
	LASTMODIFIEDDATE TIMESTAMP_NTZ(9),
	ISDELETED BOOLEAN,
	CREATEDBYID VARCHAR(18),
	QUESTIONID VARCHAR(18),
	ISDEPRECATED BOOLEAN,
	CREATEDDATE TIMESTAMP_NTZ(9),
	SURVEYVERSIONID VARCHAR(18),
	DEVELOPERNAME VARCHAR(80),
	LASTMODIFIEDBYID VARCHAR(18),
	NAME VARCHAR(255),
	SYSTEMMODSTAMP TIMESTAMP_NTZ(9)
);