CREATE OR REPLACE TABLE DISC_PROD.ALAYACARE.AUDIT_VISIT_EMPLOYEE_CHANGE (
	VISIT_ID NUMBER(38,0),
	VISIT_START_TIME TIMESTAMP_NTZ(9),
	VISIT_END_TIME TIMESTAMP_NTZ(9),
	ACTION VARCHAR(10),
	EMPLOYEE_ID NUMBER(38,0),
	UPDATE_EMPLOYEE_ID NUMBER(38,0),
	UPDATE_TIME TIMESTAMP_NTZ(9),
	BRANCH_ID NUMBER(38,0)
);