CREATE OR REPLACE TABLE DISC_PROD.HEALTH_NAVIGATOR.TRIGGER_OBSERVATION__C (
	ID VARCHAR(18),
	ANSWER_VALUE__C VARCHAR(255),
	LASTMODIFIEDDATE TIMESTAMP_NTZ(9),
	ISDELETED BOOLEAN,
	LASTVIEWEDDATE TIMESTAMP_NTZ(9),
	OBSERVATION_QUESTION_CATALOG__C VARCHAR(18),
	LASTREFERENCEDDATE TIMESTAMP_NTZ(9),
	NAME VARCHAR(80),
	SYSTEMMODSTAMP TIMESTAMP_NTZ(9),
	CREATEDBYID VARCHAR(18),
	OWNERID VARCHAR(18),
	CREATEDDATE TIMESTAMP_NTZ(9),
	LASTMODIFIEDBYID VARCHAR(18)
);