CREATE OR REPLACE TABLE DISC_PROD.HEALTH_NAVIGATOR.SURVEYSUBJECT (
	ID VARCHAR(18),
	PARENTID VARCHAR(18),
	LASTMODIFIEDDATE TIMESTAMP_NTZ(9),
	ISDELETED BOOLEAN,
	SURVEYID VARCHAR(18),
	LASTVIEWEDDATE TIMESTAMP_NTZ(9),
	SURVEYRESPONSEID VARCHAR(18),
	LASTREFERENCEDDATE TIMESTAMP_NTZ(9),
	SUBJECTENTITYTYPE VARCHAR(255),
	SURVEYINVITATIONID VARCHAR(18),
	NAME VARCHAR(255),
	SYSTEMMODSTAMP TIMESTAMP_NTZ(9),
	CREATEDBYID VARCHAR(18),
	CREATEDDATE TIMESTAMP_NTZ(9),
	SUBJECTID VARCHAR(18),
	LASTMODIFIEDBYID VARCHAR(18)
);