CREATE OR REPLACE TABLE DISC_PROD.PUBLIC.SOURCE_DEST_ROWS_COUNT (
	SOURCESYSTEM VARCHAR(50),
	TABLE_NAME VARCHAR(16777216),
	ROW_COUNT NUMBER(38,0),
	SOURCE_COUNT NUMBER(18,0),
	TIMEUPDATED TIMESTAMP_LTZ(9)
);