CREATE OR REPLACE TABLE DISC_PROD.JAZZHR.APPLICANTS (
	ID VARCHAR(70),
	FIRST_NAME VARCHAR(50),
	LAST_NAME VARCHAR(50),
	PROSPECT_PHONE VARCHAR(50),
	APPLY_DATE DATE,
	JOB_ID VARCHAR(50),
	JOB_TITLE VARCHAR(100),
	ETL_TASK_KEY NUMBER(38,0),
	ETL_INSERTED_TASK_KEY NUMBER(38,0),
	ETL_INSERTED_DATE TIMESTAMP_NTZ(9),
	ETL_INSERTED_BY VARCHAR(100),
	ETL_LAST_UPDATED_DATE TIMESTAMP_NTZ(9),
	ETL_LAST_UPDATED_BY VARCHAR(100),
	ETL_DELETED_FLAG BOOLEAN
);