CREATE OR REPLACE TABLE DISC_PROD.HHAEXCHANGEEDISON.OFFICE_COLLECTIONREPRESENTATIVE_REPL (
	AGENCYID NUMBER(10,0),
	COLLECTIONREPID NUMBER(10,0),
	COLLECTIONREPNAME VARCHAR(100),
	ACTIVE BOOLEAN,
	CREATEDDATE TIMESTAMP_NTZ(9),
	LASTUPDATEDDATE TIMESTAMP_NTZ(9),
	CREATEDBY NUMBER(10,0),
	LASTUPDATEDBY NUMBER(10,0),
	SYS_CHANGE_VERSION NUMBER(18,0),
	SYS_CHANGE_OPERATION VARCHAR(1),
	ETL_TASK_KEY NUMBER(38,0),
	ETL_INSERTED_TASK_KEY NUMBER(38,0),
	ETL_INSERTED_DATE TIMESTAMP_NTZ(9),
	ETL_INSERTED_BY VARCHAR(100),
	ETL_LAST_UPDATED_DATE TIMESTAMP_NTZ(9),
	ETL_LAST_UPDATED_BY VARCHAR(100),
	ETL_DELETED_FLAG BOOLEAN
);