CREATE OR REPLACE TABLE DISC_PROD.ALAYACARE.SERVICE_HISTORY (
	SERVICE_ID NUMBER(38,0),
	SERVICE_CLIENT_ID NUMBER(38,0),
	SERVICE_BILL_CODE_ID NUMBER(38,0),
	STATUS_HISTORICAL VARCHAR(250),
	STATUS_REASON VARCHAR(250),
	CREATE_DATE TIMESTAMP_NTZ(9),
	REVISION_ID VARCHAR(250),
	REVISION_FROM TIMESTAMP_NTZ(9),
	REVISION_UNTIL TIMESTAMP_NTZ(9),
	LENGTH_OF_STAY NUMBER(38,0),
	BRANCH_ID NUMBER(38,0),
	SERVICE_FACILITY NUMBER(1,0),
	SERVICE_ASSIGNED_EMPLOYEE_ID NUMBER(38,0),
	SERVICE_BILLING_CONTACT_ID NUMBER(38,0)
);