CREATE OR REPLACE TABLE DISC_PROD.QUALTRICS_SURVEYS.QUALTRICS_DIRECTORY_CONTACTS (
	CONTACTID VARCHAR(20),
	FIRSTNAME VARCHAR(100),
	LASTNAME VARCHAR(100),
	EMAIL VARCHAR(100),
	PHONE VARCHAR(20),
	EXTREF VARCHAR(100),
	LANGUAGE VARCHAR(100),
	UNSUBSCRIBED VARCHAR(100),
	EMBEDDEDDATA VARCHAR(16777216),
	ETL_TASK_KEY NUMBER(38,0),
	ETL_INSERTED_TASK_KEY NUMBER(38,0),
	ETL_INSERTED_DATE TIMESTAMP_NTZ(9),
	ETL_INSERTED_BY VARCHAR(16777216),
	ETL_LAST_UPDATED_DATE TIMESTAMP_NTZ(9),
	ETL_LAST_UPDATED_BY VARCHAR(16777216),
	ETL_DELETED_FLAG BOOLEAN
);