CREATE OR REPLACE TABLE DISC_PROD.QUALTRICS_SURVEYS.QUALTRICS_CLIENT_MAPPING (
	ORIGINAL_CLIENT_KEY VARCHAR(16777216),
	ORIGINAL_CLIENT_NUMBER VARCHAR(16777216)
)COMMENT='This structure used to map DW_PROD.HAH.DIM_SURVEY_RESPONSE_HEADER Client Key having length < 32 with \r\nDW_PROD.INTEGRATION.DIM_CLIENT_MERGED  Client_key using Original Client Number'
;