resource "snowflake_view" "DISC_CCSI_CALLSFIELD" {
	database = "DISC_${var.SF_ENVIRONMENT}"
	schema = "CCSI"
	name = "CALLSFIELD"
	statement = <<-SQL
	 
SELECT RECORD_NUMBER,
	DATE_TIME,
	LOG_IN_OUT,
	EMP_ID,
	CALLER_ID,
	MINS_WORKED,
	SHARED,
	CLIENT_NAME,
	CLIENT_ID,
	OFFICE,
	DESK,
	SERVICE_TYPE,
	PROCESSED_MODULE,
	CREATED_DATE,
	CREATED_BY,
	UPDATED_DATE,
	UPDATED_BY,
	ETL_TASK_KEY,
	ETL_INSERTED_TASK_KEY,
	ETL_INSERTED_DATE,
	ETL_INSERTED_BY,
	ETL_LAST_UPDATED_DATE,
	ETL_LAST_UPDATED_BY,
	ETL_DELETED_FLAG
FROM CALLSFIELD_LATEST
UNION ALL 
SELECT RECORD_NUMBER,
	DATE_TIME,
	LOG_IN_OUT,
	EMP_ID,
	CALLER_ID,
	MINS_WORKED,
	SHARED,
	CLIENT_NAME,
	CLIENT_ID,
	OFFICE,
	DESK,
	SERVICE_TYPE,
	PROCESSED_MODULE,
	CREATED_DATE,
	CREATED_BY,
	UPDATED_DATE,
	UPDATED_BY,
	ETL_TASK_KEY,
	ETL_INSERTED_TASK_KEY,
	ETL_INSERTED_DATE,
	ETL_INSERTED_BY,
	ETL_LAST_UPDATED_DATE,
	ETL_LAST_UPDATED_BY,
	ETL_DELETED_FLAG
FROM CALLSFIELD_ARCHIVED;
SQL
	or_replace = true 
	is_secure = false 
}

