create or replace view DW_PROD.HAH.VW_FACT_BUDGET_MERGED(
	BUDGET_KEY,
	SYSTEM_CODE,
	SOURCE_SYSTEM_ID,
	CALENDAR_DATE,
	BRANCH_KEY,
	ORIGINAL_BRANCH_KEY,
	SERVICE_LINE_CODE,
	YEAR_MONTH,
	OFFICE_NUMBER,
	STATE_CODE,
	HOURS_BUDGETED_DAILY,
	HOURS_BUDGETED_MONTHLY,
	HOURS_BUDGETED_MONTHLY_ROLLING_TOTAL,
	REVENUE_BUDGETED_DAILY,
	REVENUE_BUDGETED_MONTHLY,
	REVENUE_BUDGETED_MONTHLY_ROLLING_TOTAL,
	CLIENT_COUNT_BUDGETED_DAILY,
	CLIENT_COUNT_BUDGETED_MONTHLY,
	CLIENT_COUNT_BUDGETED_MONTHLY_ROLLING_TOTAL,
	ETL_TASK_KEY,
	ETL_INSERTED_TASK_KEY,
	ETL_INSERTED_DATE,
	ETL_INSERTED_BY,
	ETL_LAST_UPDATED_DATE,
	ETL_LAST_UPDATED_BY,
	ETL_DELETED_FLAG
) as 
	SELECT BUDGET.BUDGET_KEY,
		COALESCE(
			CASE BRANCH_MERGED.SOURCE_SYSTEM_ID 
				WHEN 1 THEN 'CostalSyncData'
				WHEN 2 THEN 'CostalSyncData'
				WHEN 3 THEN 'DataFlexSyncData'
				WHEN 4 THEN 'SandataImport'
				-- For completeness
				WHEN 5 THEN 'GpSyncData'
				WHEN 6 THEN 'TrustPointData'
			END, BUDGET.SYSTEM_CODE) AS SYSTEM_CODE, 
		COALESCE(BRANCH_MERGED.SOURCE_SYSTEM_ID, BUDGET.SOURCE_SYSTEM_ID) AS SOURCE_SYSTEM_ID,
		BUDGET.CALENDAR_DATE,
		COALESCE(BRANCH_MERGED.BRANCH_KEY, BUDGET.BRANCH_KEY) AS BRANCH_KEY,
		BUDGET.BRANCH_KEY AS ORIGINAL_BRANCH_KEY,
		BUDGET.SERVICE_LINE_CODE,
		BUDGET.YEAR_MONTH,
		COALESCE(BRANCH_MERGED.OFFICE_NUMBER, BUDGET.OFFICE_NUMBER) AS OFFICE_NUMBER,
		COALESCE(BRANCH_MERGED.OFFICE_STATE_CODE, BUDGET.STATE_CODE) AS STATE_CODE,
		BUDGET.HOURS_BUDGETED_DAILY,
		BUDGET.HOURS_BUDGETED_MONTHLY,
		BUDGET.HOURS_BUDGETED_MONTHLY_ROLLING_TOTAL,
		BUDGET.REVENUE_BUDGETED_DAILY,
		BUDGET.REVENUE_BUDGETED_MONTHLY,
		BUDGET.REVENUE_BUDGETED_MONTHLY_ROLLING_TOTAL,
		BUDGET.CLIENT_COUNT_BUDGETED_DAILY,
		BUDGET.CLIENT_COUNT_BUDGETED_MONTHLY,
		BUDGET.CLIENT_COUNT_BUDGETED_MONTHLY_ROLLING_TOTAL,
		BUDGET.ETL_TASK_KEY,
		BUDGET.ETL_INSERTED_TASK_KEY,
		BUDGET.ETL_INSERTED_DATE,
		BUDGET.ETL_INSERTED_BY,
		BUDGET.ETL_LAST_UPDATED_DATE,
		BUDGET.ETL_LAST_UPDATED_BY,
		BUDGET.ETL_DELETED_FLAG
	FROM HAH.FACT_BUDGET AS BUDGET
	LEFT JOIN HAH.VW_DIM_BRANCH_MERGED AS BRANCH_MERGED
		ON BRANCH_MERGED.ORIGINAL_BRANCH_KEY = BUDGET.BRANCH_KEY;