create or replace view DW_PROD.STAGE.VW_CURRENT_DELETED_HAH_REPORTING_FACT_WRITEOFF(
	WRITEOFF_KEY
) as
SELECT
    md5(NVL(f.PERIOD::string, '') || '-' || NVL(off.OFFICENAME::string, 'Unknown') || '-' || NVL(f.CLIENTNUMBER::string, '') || '-'
		|| NVL(f.CONTRACTCODE, 'Unknown') || '-' || NVL(f.ADDITIONALITEM::string, 'Unknown') || '-'
		|| NVL(f.PAYDATE::string, '')  || '-' || NVL(f.DFDB,'')) AS WRITEOFF_KEY
FROM DISC_PROD.HAH_REPORTING.HIST_AGING_SUMMARY_AMOUNTDATA f
LEFT JOIN DISC_PROD.HAH_REPORTING.AGING_SUMMARY_OFFICES off
    on f.OFFICENUMBER = off.OFFICENUMBER
    and f.DFDB = off.DFDB
LEFT JOIN (SELECT DISTINCT CODE, REASON FROM DISC_PROD.HAH_REPORTING.AGING_SUMMARY_WRITEOFFCODES) wo
    on f.WOREASON = wo.CODE
LEFT JOIN (SELECT DISTINCT BRANCH_KEY, OFFICE_NUMBER, SYSTEM_CODE FROM HAH.DIM_BRANCH) b2
ON b2.OFFICE_NUMBER = f.OFFICENUMBER
    AND b2.SYSTEM_CODE = f.DFDB
LEFT JOIN HAH.DIM_CLIENT c2
ON TO_VARCHAR(c2.CLIENT_NUMBER) = TO_VARCHAR(f.CLIENTNUMBER)
    AND c2.SYSTEM_CODE = f.DFDB
LEFT JOIN HAH.DIM_CONTRACT n2
ON n2.CONTRACT_CODE = f.CONTRACTCODE
    AND n2.SYSTEM_CODE = f.DFDB
WHERE  AMOUNTTYPE LIKE '%WriteOff%'-- limit 100
AND CAST(f.ETL_LAST_UPDATED_DATE AS DATE) IN (SELECT MAX(CAST(ETL_LAST_UPDATED_DATE AS DATE))
FROM DISC_PROD.HAH_REPORTING.HIST_AGING_SUMMARY_AMOUNTDATA)
AND F.ETL_DELETED_FLAG = TRUE;