create or replace view DW_PROD.REPORT.VW_BUDGET(
	BRANCH_KEY,
	DETAILED_OFFICE_NAME,
	OFFICE_STATE_CODE,
	SERVICELINE,
	CALENDAR_DATE,
	MONTHDAYS,
	TOTALDAYSOFMONTHSOFAR,
	OFFICE_NUMBER,
	REGION_NAME,
	BUDGETEDCLIENTS,
	BUDGETEDREVENUE,
	BUDGETEDHOURS,
	BUDGETEDCLIENTSMONTH,
	BUDGETEDREVENUEMONTH,
	BUDGETEDHOURSMONTH
) as
WITH PAYROLLPERIODS
AS
(
SELECT OFFICE_STATE_CODE AS STATE,CAST(MAX(PERIOD_END_DATE) AS DATE) as PERIODEND
FROM HAH.FACT_BRANCH_PAYROLL_PERIODS o       
WHERE CHECK_DATE < Current_Date() -- This should be CheckDate NOT PeriodEnd, it takes a while for all the timesheets to be entered
group by OFFICE_STATE_CODE
),
DIMDATE
AS
(
  select CALENDAR_DATE,FIRST_DAY_OF_MONTH,
  DATEDIFF(day,FIRST_DAY_OF_MONTH,LAST_DAY_OF_MONTH) + 1 AS MONTHDAYS,
  CASE WHEN DATEDIFF(MONTH,CALENDAR_DATE,PERIODEND) = 0 THEN 
  DATEDIFF(day,FIRST_DAY_OF_MONTH,PERIODEND) + 1 ELSE 
  DATEDIFF(day,FIRST_DAY_OF_MONTH,LAST_DAY_OF_MONTH) + 1 END TOTALDAYSOFMONTHSOFAR ,STATE,PERIODEND
  FROM
  DW_PROD.hah.dim_date
  cross join 
  (select state,PERIODEND from PAYROLLPERIODS) PAYROLLPERIODS
  where CALENDAR_DATE > '2019-12-31' and CALENDAR_DATE <= PERIODEND
  --GROUP BY CALENDAR_DATE,FIRST_DAY_OF_MONTH,LAST_DAY_OF_MONTH
),
BUDGET
AS
(
  SELECT 
  BRANCH.BRANCH_KEY,BRANCH.DETAILED_OFFICE_NAME,BRANCH.OFFICE_STATE_CODE,SERVICELINE,
  CALENDAR_DATE,
  MONTHDAYS,TOTALDAYSOFMONTHSOFAR,
  BRANCH.OFFICE_NUMBER,
  BRANCH.REGION_NAME,
  ClientCount/MONTHDAYS AS BUDGETEDCLIENTS,
  Revenue/MONTHDAYS AS BUDGETEDREVENUE,
  Hours/MONTHDAYS AS BUDGETEDHOURS,
  ClientCount/TOTALDAYSOFMONTHSOFAR AS BUDGETEDCLIENTSMONTH,
  Revenue/TOTALDAYSOFMONTHSOFAR AS BUDGETEDREVENUEMONTH,
  Hours/TOTALDAYSOFMONTHSOFAR AS BUDGETEDHOURSMONTH
  FROM DIMDATE
  --DIMDATE
  LEFT OUTER JOIN
  (
    SELECT Officenumber,TRIM(serviceline) AS SERVICELINE,month,source,DBNAME,"'R'"as Revenue,
    "'H'" as Hours,"'C'" as ClientCount
    from
    (
        select * from "DISC_DEV"."BI_REPOSITORY"."KMOFFICEBUDGETS"
        pivot(sum(value) for METRIC in ('R','H','C')) as p
    ) B
  ) OFFICEBUDGET
  ON CAST(OFFICEBUDGET.MONTH AS DATE) = CAST(FIRST_DAY_OF_MONTH AS DATE)
  AND TRIM(OFFICEBUDGET.DBNAME) = DIMDATE.STATE 
  INNER JOIN
  "DW_DEV"."HAH"."DIM_SOURCE_SYSTEM" SOURCESYSTEM
  ON SOURCESYSTEM.BUDGET_SYSTEM_CODE = TRIM(OFFICEBUDGET.SOURCE)
  INNER JOIN
  (select DISTINCT SOURCE_SYSTEM_ID,BRANCH_KEY,DETAILED_OFFICE_NAME,OFFICE_STATE_CODE,
    CASE WHEN SYSTEM_CODE = '8485' THEN 'PA' ELSE SYSTEM_CODE END as SYSTEM_CODE,OFFICE_NUMBER ,
   REGION_NAME
    from HAH.DIM_BRANCH) BRANCH
  ON BRANCH.OFFICE_NUMBER = TRIM(OFFICEBUDGET.OFFICENUMBER)
  AND BRANCH.OFFICE_STATE_CODE = TRIM(OFFICEBUDGET.DBNAME)
  AND BRANCH.SOURCE_SYSTEM_ID = SOURCESYSTEM.SOURCE_SYSTEM_ID
 where BRANCH.OFFICE_STATE_CODE not in ('GA','SC')
  --where BUDGETEDCLIENTS != 0 OR  BUDGETEDREVENUE != 0 OR BUDGETEDHOURS != 0
)
SELECT * FROM BUDGET;