create or replace view DW_PROD.REPORT.VW_EXECUTIVE_OPERATIONS_EXCELLENCE_OVERTIME(
	CLIENT_KEY,
	SERVICE_MONTH,
	BRANCH_KEY,
	CONTRACT_KEY,
	EMPLOYEE_KEY,
	SUPERVISOR_KEY,
	PAYROLL_SERVICE_HOURS,
	OVERTIME_HOURS,
	OVERTIME_PAY_AMOUNT
) as 
SELECT
CLIENT_KEY ,
SERVICE_MONTH,
O.BRANCH_KEY,
O.CONTRACT_KEY,
EMPLOYEE_KEY, 
SUPERVISOR_KEY ,
PAYROLL_SERVICE_HOURS, 
OVERTIME_HOURS, 
OVERTIME_PAY_AMOUNT
FROM REPORT.OVERTIME_2 O
JOIN REPORT.VW_DASHBOARD_CONTRACTS DC ON O.CONTRACT_KEY=DC.CONTRACT_KEY
        AND DC.INCLUDE_FOR_EXEC_OPS_CLIENTS=1
WHERE SERVICE_MONTH BETWEEN DATE_TRUNC('YEAR',DATEADD('YEAR',-2,CURRENT_DATE())) AND CURRENT_DATE;