create or replace view DW_PROD.REPORT.VW_OPS_PERFORMANCE_DIM_DATE(
	PERIOD_BEGIN_DATE,
	PERIOD_END_DATE,
	PERIOD_NAME
) as
SELECT DISTINCT FIRST_DAY_OF_MONTH PERIOD_BEGIN_DATE, LAST_DAY_OF_MONTH PERIOD_END_DATE, CONCAT(MONTH_NAME, ' ', "YEAR") PERIOD_NAME
FROM DW_PROD.HAH.DIM_DATE
WHERE FIRST_DAY_OF_MONTH BETWEEN DATE_TRUNC(MONTH, DATEADD(MONTH, -14, CURRENT_DATE())) AND CURRENT_DATE();