create or replace view DW_PROD.STAGE.VW_CURRENT_ALAYACARE_DIM_BRANCH(
	CLIENT_KEY
) as
WITH ALAYACARE_DATA AS (
	SELECT MD5(NVL(TRIM(COMPANY.PROPERTIES_TBL_GT_ACCOUNT_DESCRIPTION), 'Unknown') || ' (' || COMPANY.BRANCH_ID || ')' || '-' || GROUPS.GROUP_ID || '-' || 'ALAYACARE') AS BRANCH_KEY,
		UPPER(TRIM(GROUPS.PROFILE_COMPANY)) AS BRANCH_NAME,
		UPPER(TRIM(COALESCE(STATE.STATE_ISO_CODE, COMPANY.PROFILE_STATE))) AS STATE,
		NVL(TRIM(COMPANY.PROPERTIES_TBL_GT_ACCOUNT_DESCRIPTION), 'Unknown') || ' (' || COMPANY.BRANCH_ID || ')' AS SYSTEM_CODE,
		9 AS SOURCE_SYSTEM_ID,
		GROUPS.GROUP_ID AS OFFICE_CODE,
		TRIM(REGEXP_SUBSTR(UPPER(GROUPS.PROFILE_REMARKS), '\\([^)]*HAH_OFFICE_CODE:\\s*(\\w+)', 1, 1, 'e', 1)) AS HAH_OFFICE_CODE,
		NVL(TRY_CAST(REGEXP_SUBSTR(UPPER(GROUPS.PROFILE_REMARKS), '\\([^)]*HAH_OFFICE_NUMBER:\\s*(\\w+)', 1, 1, 'e', 1) AS INT), -1) AS HAH_OFFICE_NUMBER
	FROM DISC_DEV.ALAYACARE.GROUPS AS GROUPS
	JOIN DISC_DEV.ALAYACARE.BRANCH AS COMPANY
		ON COMPANY.BRANCH_ID = GROUPS.BRANCH_ID 
	LEFT JOIN HAH.DIM_STATE AS STATE
		ON UPPER(TRIM(STATE.STATE_NAME)) = UPPER(TRIM(COMPANY.PROPERTIES_TBL_GT_ACCOUNT_DESCRIPTION))
), RISKCONNECT_HIERARCHY AS (
	SELECT * FROM DISC_DEV.STAGE.RISKCONNECT_HIERARCHY 
), HR_OFFICE_MAPPING AS (
	SELECT * FROM DISC_DEV.STAGE.HR_OFFICE_MAPPING 
), COASTAL_OFFICE_MAPPING AS (
	SELECT * FROM DISC_DEV.STAGE.COASTAL_OFFICE_MAPPING 
), HAH_OFFICES AS (
	SELECT UPPER(TRIM(OFFICES.STATE)) AS STATE,
		TRY_CAST(OFFICES.OFFICENUMBER AS INT) AS OFFICE_NUMBER,
		OFFICES.OFFICENAME AS OFFICE_NAME,
		CASE WHEN OFFICES.OFFICENAME LIKE '%DD%' THEN 'DD'
			WHEN OFFICES.OFFICENAME LIKE '%ADS%' THEN 'ADS'
		END AS BRANCH_SERVICE_LINE,
		OFFICES.ADDRESS AS OFFICE_ADDRESS1,
		OFFICES.ADDRESS2 AS OFFICE_ADDRESS2,
		OFFICES.CITY AS OFFICE_CITY,
		OFFICES.ZIP AS OFFICE_ZIP,
		OFFICES.PHONE AS OFFICE_PHONE,
		OFFICES.TOLLFREE AS OFFICE_TOLL_FREE_PHONE,
		OFFICES.FAX AS OFFICE_FAX,
		TRIM( OFFICES.Email) AS Primary_Branch_Email,
		CAST(NULL AS VARCHAR(10)) AS Secondary_Branch_Email,
		OFFICES.OFFICEMANAGER AS OFFICEMANAGER1,
		CAST(NULL AS VARCHAR(10)) AS OFFICEMANAGER2,
		OFFICES.DATECREATED AS DATE_CREATED,
		OFFICES.ETL_LAST_UPDATED_DATE
	FROM DISC_DEV.HAHUSERS.LOGIN_OFFICE AS OFFICES
	WHERE TRY_CAST(OFFICES.OFFICENUMBER AS INT) IS NOT NULL
)
	SELECT ALAYACARE_OFFICES.BRANCH_KEY
	FROM ALAYACARE_DATA AS ALAYACARE_OFFICES
	LEFT JOIN HAH_OFFICES AS HAH_OFFICES
		ON HAH_OFFICES.STATE = ALAYACARE_OFFICES.STATE AND ALAYACARE_OFFICES.HAH_OFFICE_NUMBER = HAH_OFFICES.OFFICE_NUMBER
	LEFT JOIN HAH.DIM_STATE AS STATES 
		ON STATES.STATE_ISO_CODE = ALAYACARE_OFFICES.STATE
	LEFT OUTER JOIN RISKCONNECT_HIERARCHY AS RISKCONNECT
		ON RISKCONNECT.STATE = ALAYACARE_OFFICES.STATE AND RISKCONNECT.PARENT_LEVEL = 2
			-- If SC, h.OFFICE_CODE is Numeric office number; else for GA, it is alphanumeric location code	
			AND TRIM(RISKCONNECT.OFFICE_CODE) = IFF(TRIM(ALAYACARE_OFFICES.STATE) <> 'SC', TRIM(ALAYACARE_OFFICES.HAH_OFFICE_CODE), ALAYACARE_OFFICES.HAH_OFFICE_NUMBER::STRING)
	LEFT OUTER JOIN HR_OFFICE_MAPPING AS HR
		ON TRIM(HR.OFFICE_CODE) = TRIM(ALAYACARE_OFFICES.HAH_OFFICE_CODE) AND TRIM(HR.STATE) = ALAYACARE_OFFICES.STATE
	LEFT JOIN DISC_DEV.HAH_REPORTING.KEYMETOFFICES AS REGION_OFFICES -- Only used for IL regions
		ON ALAYACARE_OFFICES.STATE = 'IL' AND TRIM(REGION_OFFICES.OFFICESTATE) = ALAYACARE_OFFICES.STATE AND TRY_CAST(REGION_OFFICES.OFFICENUMBER AS INT) = ALAYACARE_OFFICES.HAH_OFFICE_NUMBER
	LEFT JOIN DISC_DEV.BI_REPOSITORY.KMREGIONS AS REGIONS
		ON (REGION_OFFICES.REGIONNUMBER IS NULL AND 
			CASE WHEN UPPER(STATES.STATE_NAME) = 'GEORGIA' THEN 'GEORGIA/SOUTH CAROLINA'
				WHEN UPPER(STATES.STATE_NAME) = 'SOUTH CAROLINA' THEN 'GEORGIA/SOUTH CAROLINA'
				WHEN UPPER(STATES.STATE_NAME) = 'MICHIGAN' THEN 'DD/MICHIGAN'
				WHEN UPPER(STATES.STATE_NAME) = 'KANSAS' THEN 'MISSOURI' 
				WHEN UPPER(STATES.STATE_NAME) = 'IOWA' THEN 'ILLINOIS - NORTH' 
				WHEN UPPER(STATES.STATE_NAME) = 'MISSISSIPPI' THEN 'MISSISSIPPI/TENNESSEE'
				WHEN UPPER(STATES.STATE_NAME) = 'TENNESSEE' THEN 'MISSISSIPPI/TENNESSEE'
				ELSE UPPER(STATES.STATE_NAME) END = REGIONS.NAME) 
			OR (REGION_OFFICES.REGIONNUMBER = REGIONS.REGIONNUMBER)
	INNER JOIN DISC_DEV.ALAYACARE.CONFIGURATION  CONFIG
	ON CONFIG.OFFICE_STATE_CODE=COALESCE(HAH_OFFICES.STATE, ALAYACARE_OFFICES.STATE) 
	AND CONFIG.SYSTEM_CODE=ALAYACARE_OFFICES.SYSTEM_CODE
	WHERE CONFIGURATION_ACTIVE='TRUE';