create or replace view DW_PROD.REPORT.VW_HOURS_AND_CENCUS_BUDGETEDDATA(
	MONTH,
	OFFICE_STATE_CODE,
	OFFICE_NUMBER,
	BRANCH_KEY,
	SERVICELINE,
	BUDGETEDCLIENTS,
	BUDGETEDHOURS,
	BUDGETEDCAREGIVERS
) as
WITH BUDGETEDDATA AS (	
	SELECT CALENDAR_DATE AS MONTH, STATE_CODE AS OFFICE_STATE_CODE, OFFICE_NUMBER, BRANCH_KEY, SERVICE_LINE_CODE AS SERVICELINE,
		CLIENT_COUNT_BUDGETED_MONTHLY AS BUDGETEDCLIENTS,
		HOURS_BUDGETED_MONTHLY AS BUDGETEDHOURS,CAREGIVER_COUNT_BUDGETED_MONTHLY  AS BUDGETEDCAREGIVERS
	FROM INTEGRATION.FACT_BUDGET_MERGED 
	WHERE DAY(CALENDAR_DATE) = 1
)
	SELECT *
	FROM BUDGETEDDATA;