create or replace view DW_PROD.REPORT.VW_EXECUTIVE_OPERATIONS_EXCELLENCE_UTILIZATION_DIM_DATE_FOR_HOURS_AND_CLIENT_CENSUS_MONTHLY(
	FIRST_DAY_OF_MONTH,
	PERIOD_NAME
) as
	SELECT DISTINCT FIRST_DAY_OF_MONTH, CONCAT(MONTH_NAME, ' ', "YEAR") PERIOD_NAME
	FROM HAH.DIM_DATE 
	WHERE FIRST_DAY_OF_MONTH BETWEEN DATE_TRUNC(YEAR, DATEADD(YEAR, -4, CURRENT_DATE())) AND DATE_TRUNC(MONTH, DATEADD(MONTH, 2, CURRENT_DATE()));