create or replace view DW_PROD.REPORT.VW_OPS_PERFORMANCE_OVERTIME_BACKUP(
	EMPLOYEE_KEY,
	BRANCH_KEY,
	CLIENT_KEY,
	SUPERVISOR_KEY,
	CONTRACT_KEY,
	PAYROLL_SERVICE_HOURS,
	SERVICE_MONTH,
	OVERTIME_HOURS,
	ETL_LAST_UPDATED_DATE
) as 
SELECT 
O.EMPLOYEE_KEY,
O.BRANCH_KEY,
O.CLIENT_KEY,
O.SUPERVISOR_KEY,
O.CONTRACT_KEY,
O.PAYROLL_SERVICE_HOURS,
O.SERVICE_MONTH,
O.OVERTIME_HOURS,
O.ETL_LAST_UPDATED_DATE
FROM REPORT.OVERTIME_2 O
JOIN REPORT.VW_DASHBOARD_CONTRACTS DC ON O.CONTRACT_KEY=DC.CONTRACT_KEY 
    AND INCLUDE_FOR_OPS_PERF_CLIENTS=1
WHERE SERVICE_MONTH>='2020-01-01';