create or replace view DW_PROD.REPORT.VW_EXECUTIVE_OPERATIONS_EXCELLENCE_UTILIZATION_AUTHORIZATION_HOURS_DAILY(
	AUTH_DATE,
	CLIENT_KEY,
	BRANCH_KEY,
	SUPERVISOR_KEY,
	CLIENT_KEY_DATA,
	CONTRACT_KEY,
	AUTH_HOURS_DAILY_ALL,
	AUTH_HOURS_DAILY_WHERE_AUTH_EXISTS
) as
  SELECT DISTINCT D.CALENDAR_DATE AS AUTH_DATE,
  U.CLIENT_KEY,
  U.BRANCH_KEY,
  U.SUPERVISOR_KEY,
  U.CLIENT_KEY_DATA,
  U.CONTRACT_KEY,
  SUM(U.HOURS_AUTHORIZED_ALL)/date_part(day, D.LAST_DAY_OF_MONTH) AS AUTH_HOURS_DAILY_ALL,
  SUM(U.HOURS_AUTHORIZED_WHERE_AUTH_EXISTS)/date_part(day, D.LAST_DAY_OF_MONTH) AS AUTH_HOURS_DAILY_WHERE_AUTH_EXISTS
  FROM DW_PROD.HAH.DIM_DATE D
  INNER JOIN DW_PROD.REPORT.VW_EXECUTIVE_OPERATIONS_EXCELLENCE_UTILIZATION U
  ON date_part(month, U.PERIOD_BEGIN_DATE) = date_part(month, D.CALENDAR_DATE)
  AND date_part(year, U.PERIOD_BEGIN_DATE) = date_part(year, D.CALENDAR_DATE)
  AND CALENDAR_DATE >= '2020-01-01'
  GROUP BY D.CALENDAR_DATE,U.CLIENT_KEY,U.BRANCH_KEY,U.SUPERVISOR_KEY,U.CLIENT_KEY_DATA,U.CONTRACT_KEY,D.LAST_DAY_OF_MONTH
  ORDER BY D.CALENDAR_DATE ASC;