create or replace view DW_PROD.REPORT.CLIENT_DERIVED_MONTHLY_VISIT_METRICS_SEC_WITH_MASTER_CLIENT_KEY_BKCP_08_01_2022(
	SERVICE_MONTH,
	ORIGINAL_CLIENT_KEY,
	CLIENT_KEY,
	SOURCE_SYSTEM_ID,
	ORIGINAL_SOURCE_SYSTEM_ID,
	BRANCH_KEY,
	OFFICE_NAME,
	OFFICE_STATE_CODE,
	REFERRAL_DATE,
	CLIENT_STATE_CODE,
	LIFETIME_FIRST_SERVICE_MONTH,
	LIFETIME_LAST_SERVICE_MONTH,
	LIFETIME_TENURE_IN_MONTHS,
	LIFETIME_NUMBER_MONTHS_WITH_SERVICE,
	LIFETIME_NUMBER_MONTHS_WO_SERVICE,
	LIFETIME_NUMBER_OF_GAPS_IN_SERVICE,
	LIFETIME_SMALLEST_GAP_IN_SERVICE,
	LIFETIME_LARGEST_GAP_IN_SERVICE,
	NEW_CLIENT_FLAG,
	FIRST_MONTH_INACTIVE_FLAG,
	ACTIVE_FLAG,
	REACTIVATED_FLAG,
	CLIENT_ACQUIRED_FLAG,
	CLIENT_ACQUISITION_NAME,
	NUMBER_OF_SERVICE_LINES_PROVIDED,
	HC_SERVICE_LINE_PROVIDED,
	HH_SERVICE_LINE_PROVIDED,
	CLS_SERVICE_LINE_PROVIDED,
	NA_SERVICE_LINE_PROVIDED,
	IS_SERVICE_LINE_PROVIDED,
	NS_SERVICE_LINE_PROVIDED,
	OTHER_SERVICE_LINE_PROVIDED,
	NUMBER_OF_VISITS,
	PREVIOUS_MONTH_NUMBER_OF_VISITS,
	PREVIOUS_2_MONTH_NUMBER_OF_VISITS,
	NEXT_MONTH_NUMBER_OF_VISITS,
	NEXT_2_MONTH_NUMBER_OF_VISITS,
	SUM_OF_HOURS_RECEIVED,
	PREVIOUS_MONTH_SUM_OF_HOURS_RECEIVED,
	PREVIOUS_2_MONTH_SUM_OF_HOURS_RECEIVED,
	NEXT_MONTH_SUM_OF_HOURS_RECEIVED,
	NEXT_2_MONTH_SUM_OF_HOURS_RECEIVED,
	NUMBER_OF_HC_VISIT_DAYS,
	NUMBER_OF_HC_VISITS,
	SUM_OF_HC_HOURS_SERVED,
	NUMBER_OF_HH_VISIT_DAYS,
	NUMBER_OF_HH_VISITS,
	SUM_OF_HH_HOURS_SERVED,
	NUMBER_OF_CLS_VISITS,
	SUM_OF_CLS_HOURS_SERVED,
	NUMBER_OF_NA_VISITS,
	SUM_OF_NA_HOURS_SERVED,
	NUMBER_OF_IS_VISITS,
	SUM_OF_IS_HOURS_SERVED,
	NUMBER_OF_NS_VISITS,
	SUM_OF_NS_HOURS_SERVED,
	NUMBER_OF_OTHER_VISIT_DAYS,
	NUMBER_OF_OTHER_VISITS,
	SUM_OF_OTHER_HOURS_SERVED
) as
SELECT
    SERVICE_MONTH
	  ,ORIGINAL_CLIENT_KEY
	  ,CLIENT_KEY
	  ,SOURCE_SYSTEM_ID
	  ,ORIGINAL_SOURCE_SYSTEM_ID
	  ,BRANCH_KEY
	  ,OFFICE_NAME
	  ,OFFICE_STATE_CODE
	  ,REFERRAL_DATE
	  ,CLIENT_STATE_CODE
	  , LIFETIME_FIRST_SERVICE_MONTH
	  , LIFETIME_LAST_SERVICE_MONTH
	  , LIFETIME_TENURE_IN_MONTHS
	  , LIFETIME_NUMBER_MONTHS_WITH_SERVICE
	  , LIFETIME_NUMBER_MONTHS_WO_SERVICE
	  , LIFETIME_NUMBER_OF_GAPS_IN_SERVICE
	  , LIFETIME_SMALLEST_GAP_IN_SERVICE
	  , LIFETIME_LARGEST_GAP_IN_SERVICE
	  , NEW_CLIENT_FLAG, FIRST_MONTH_INACTIVE_FLAG
	  , ACTIVE_FLAG, REACTIVATED_FLAG
     ,CASE WHEN ACTIVE_FLAG = FALSE THEN LAG(ACQUiRED_FLAG) ignore nulls OVER (PARTITION BY CLIENT_KEY ORDER BY SERVICE_MONTH ASC) ELSE
      ACQUiRED_FLAG END AS CLIENT_ACQUiRED_FLAG,
      ACQUISITION_NAME AS CLIENT_ACQUISITION_NAME
	  , NUMBER_OF_SERVICE_LINES_PROVIDED
	  , HC_SERVICE_LINE_PROVIDED
	  , HH_SERVICE_LINE_PROVIDED
	  , CLS_SERVICE_LINE_PROVIDED
	  , NA_SERVICE_LINE_PROVIDED
	  , IS_SERVICE_LINE_PROVIDED
	  , NS_SERVICE_LINE_PROVIDED
	  , OTHER_SERVICE_LINE_PROVIDED
	  , NUMBER_OF_VISITS, PREVIOUS_MONTH_NUMBER_OF_VISITS
	  , PREVIOUS_2_MONTH_NUMBER_OF_VISITS
	  , NEXT_MONTH_NUMBER_OF_VISITS
	  , NEXT_2_MONTH_NUMBER_OF_VISITS
	  , SUM_OF_HOURS_RECEIVED
	  , PREVIOUS_MONTH_SUM_OF_HOURS_RECEIVED
	  , PREVIOUS_2_MONTH_SUM_OF_HOURS_RECEIVED
	  , NEXT_MONTH_SUM_OF_HOURS_RECEIVED, NEXT_2_MONTH_SUM_OF_HOURS_RECEIVED, NUMBER_OF_HC_VISIT_DAYS, NUMBER_OF_HC_VISITS, SUM_OF_HC_HOURS_SERVED, NUMBER_OF_HH_VISIT_DAYS, NUMBER_OF_HH_VISITS, SUM_OF_HH_HOURS_SERVED, NUMBER_OF_CLS_VISITS, SUM_OF_CLS_HOURS_SERVED, NUMBER_OF_NA_VISITS, SUM_OF_NA_HOURS_SERVED, NUMBER_OF_IS_VISITS, SUM_OF_IS_HOURS_SERVED, NUMBER_OF_NS_VISITS, SUM_OF_NS_HOURS_SERVED
	  , NUMBER_OF_OTHER_VISIT_DAYS, NUMBER_OF_OTHER_VISITS, SUM_OF_OTHER_HOURS_SERVED
FROM
(
SELECT 
	  CDM.SERVICE_MONTH
	  ,CDM.CLIENT_KEY AS ORIGINAL_CLIENT_KEY
	  ,CDM.CLIENT_KEY CLIENT_KEY
	  ,CDM.SOURCE_SYSTEM_ID AS SOURCE_SYSTEM_ID
	  ,ORIGINAL_SOURCE_SYSTEM_ID  AS ORIGINAL_SOURCE_SYSTEM_ID
	  ,CDM.BRANCH_KEY
	  ,OFFICE_NAME
	  ,OFFICE_STATE_CODE
	  ,REFERRAL_DATE
	  ,CLIENT_STATE_CODE
	  , LIFETIME_FIRST_SERVICE_MONTH
	  , LIFETIME_LAST_SERVICE_MONTH
	  , LIFETIME_TENURE_IN_MONTHS
	  , LIFETIME_NUMBER_MONTHS_WITH_SERVICE
	  , LIFETIME_NUMBER_MONTHS_WO_SERVICE
	  , LIFETIME_NUMBER_OF_GAPS_IN_SERVICE
	  , LIFETIME_SMALLEST_GAP_IN_SERVICE
	  , LIFETIME_LARGEST_GAP_IN_SERVICE
	  , NEW_CLIENT_FLAG, FIRST_MONTH_INACTIVE_FLAG
	  , ACTIVE_FLAG, REACTIVATED_FLAG,
  CCSI_BRANCH.BRANCH_KEY as ccsi_key
      ,CASE WHEN ACTIVE_FLAG =FALSE THEN NULL ELSE 
        IFF(COALESCE(CCSI_BRANCH.BRANCH_KEY,CCSI_ACQUIRED_CLIENT.CLIENT_KEY,MATRIXCARE_BRANCH.BRANCH_KEY,PRAETORIAN_ACQUIRED_CLIENT.CLIENT_KEY,PREFERRED_CLIENT.CLIENT_KEY) IS NULL, FALSE, TRUE)
        END AS ACQUIRED_FLAG,
      CASE WHEN COALESCE(CCSI_BRANCH.BRANCH_KEY,CCSI_ACQUIRED_CLIENT.CLIENT_KEY) IS NOT NULL THEN 'CCSI' 
      WHEN MATRIXCARE_BRANCH.BRANCH_KEY IS NOT NULL THEN 'ADAPTIVE' 
      WHEN PRAETORIAN_ACQUIRED_CLIENT.CLIENT_KEY IS NOT NULL THEN 'PRAETORIAN' 
      WHEN PREFERRED_CLIENT.CLIENT_KEY IS NOT NULL THEN 'PREFERRED'
	ELSE NULL END AS ACQUISITION_NAME
	  , NUMBER_OF_SERVICE_LINES_PROVIDED
	  , HC_SERVICE_LINE_PROVIDED
	  , HH_SERVICE_LINE_PROVIDED
	  , CLS_SERVICE_LINE_PROVIDED
	  , NA_SERVICE_LINE_PROVIDED
	  , IS_SERVICE_LINE_PROVIDED
	  , NS_SERVICE_LINE_PROVIDED
	  , OTHER_SERVICE_LINE_PROVIDED
	  , NUMBER_OF_VISITS, PREVIOUS_MONTH_NUMBER_OF_VISITS
	  , PREVIOUS_2_MONTH_NUMBER_OF_VISITS
	  , NEXT_MONTH_NUMBER_OF_VISITS
	  , NEXT_2_MONTH_NUMBER_OF_VISITS
	  , SUM_OF_HOURS_RECEIVED
	  , PREVIOUS_MONTH_SUM_OF_HOURS_RECEIVED
	  , PREVIOUS_2_MONTH_SUM_OF_HOURS_RECEIVED
	  , NEXT_MONTH_SUM_OF_HOURS_RECEIVED, NEXT_2_MONTH_SUM_OF_HOURS_RECEIVED, NUMBER_OF_HC_VISIT_DAYS, NUMBER_OF_HC_VISITS, SUM_OF_HC_HOURS_SERVED, NUMBER_OF_HH_VISIT_DAYS, NUMBER_OF_HH_VISITS, SUM_OF_HH_HOURS_SERVED, NUMBER_OF_CLS_VISITS, SUM_OF_CLS_HOURS_SERVED, NUMBER_OF_NA_VISITS, SUM_OF_NA_HOURS_SERVED, NUMBER_OF_IS_VISITS, SUM_OF_IS_HOURS_SERVED, NUMBER_OF_NS_VISITS, SUM_OF_NS_HOURS_SERVED
	  , NUMBER_OF_OTHER_VISIT_DAYS, NUMBER_OF_OTHER_VISITS, SUM_OF_OTHER_HOURS_SERVED
FROM REPORT.CLIENT_DERIVED_MONTHLY_VISIT_METRICS_SEC CDM
LEFT OUTER JOIN (SELECT BRANCH_KEY FROM HAH.DIM_BRANCH WHERE SOURCE_SYSTEM_ID = 8) CCSI_BRANCH
ON CCSI_BRANCH.BRANCH_KEY = CDM.ORIGINAL_BRANCH_KEY
LEFT OUTER JOIN (SELECT DISTINCT CLIENT_KEY FROM HAH.FACT_CLIENT_ACQUIRED_MERGED WHERE NOTES = 'CCSI Acquired') CCSI_ACQUIRED_CLIENT
ON CCSI_ACQUIRED_CLIENT.CLIENT_KEY = CDM.CLIENT_KEY AND CDM.SERVICE_MONTH >= '2021-07-01'
LEFT OUTER JOIN (SELECT DISTINCT CLIENT_KEY FROM HAH.FACT_CLIENT_ACQUIRED_MERGED WHERE NOTES = 'Praetorian') PRAETORIAN_ACQUIRED_CLIENT
ON PRAETORIAN_ACQUIRED_CLIENT.CLIENT_KEY = CDM.CLIENT_KEY AND CDM.SERVICE_MONTH >= '2022-01-01'
LEFT OUTER JOIN (SELECT BRANCH_KEY FROM HAH.DIM_BRANCH WHERE SOURCE_SYSTEM_ID = 7 AND BRANCH_NAME LIKE 'A_%') MATRIXCARE_BRANCH
ON MATRIXCARE_BRANCH.BRANCH_KEY = CDM.ORIGINAL_BRANCH_KEY
LEFT OUTER JOIN (SELECT DISTINCT CLIENT_KEY FROM HAH.FACT_CLIENT_ACQUIRED_MERGED WHERE NOTES = 'Preferred') PREFERRED_CLIENT
ON PREFERRED_CLIENT.CLIENT_KEY = CDM.CLIENT_KEY 
)MAIN;