resource "snowflake_view" "DW_REPORT_VW_EXECUTIVE_OPERATIONS_EXCELLENCE_HOURS_AND_CENSUS_BY_SERVICE_PAYROLL_PERIOD_WEEKLY" {
	database = "DW_${var.SF_ENVIRONMENT}"
	schema = "REPORT"
	name = "VW_EXECUTIVE_OPERATIONS_EXCELLENCE_HOURS_AND_CENSUS_BY_SERVICE_PAYROLL_PERIOD_WEEKLY"
	statement = <<-SQL
	 
WITH DATA AS (
    SELECT 
      DISTINCT B.BRANCH_PAYROLL_PERIODS_KEY,
        A.*,
        CM.DERIVED_FIRST_SERVICE_DATE DERIVED_FIRST_SERVICE_DATE,
        CM.DERIVED_LAST_SERVICE_DATE DERIVED_LAST_SERVICE_DATE      
    FROM REPORT.HOURS_AND_CENSUS_BY_PAYROLL_DATE_WEEKLY  A
    LEFT JOIN INTEGRATION.DIM_CLIENT_MERGED CM ON 
        A.CLIENT_KEY_DATA = CM.CLIENT_KEY
    LEFT JOIN REPORT.VW_DASHBOARD_CONTRACTS CT ON A.CONTRACT_KEY=CT.CONTRACT_KEY 
        AND (CT.INCLUDE_FOR_EXEC_OPS_HOURS=1 AND INCLUDE_FOR_EXEC_OPS_CLIENTS=1)
    LEFT JOIN INTEGRATION.FACT_BRANCH_PAYROLL_PERIODS_MERGED B ON A.BRANCH_KEY=B.ORIGINAL_BRANCH_KEY AND A.SERVICE_WEEK>=B.PERIOD_START_DATE 
      AND A.SERVICE_WEEK<=B.PERIOD_END_DATE
WHERE A.SERVICE_WEEK BETWEEN DATEADD('WEEK',-79,CURRENT_DATE) AND DATEADD( 'WEEK', 4, CURRENT_DATE)
)        
,DATE_DATA AS (
 SELECT DISTINCT A.CALENDAR_DATE AS CALENDAR_DATE,B.BRANCH_KEY AS BRANCH_KEY FROM HAH.DIM_DATE A
 LEFT JOIN INTEGRATION.FACT_BRANCH_PAYROLL_PERIODS_MERGED B ON A.CALENDAR_DATE BETWEEN B.PERIOD_START_DATE AND B.PERIOD_END_DATE
 WHERE A.CALENDAR_DATE BETWEEN DATEADD('WEEK',-79,CURRENT_DATE) AND DATEADD( 'WEEK', 4, CURRENT_DATE)
)
SELECT A.BRANCH_PAYROLL_PERIODS_KEY,
    A.PAYROLL_DATE,
    A.PAY_PERIOD_START_DATE,
    A.PAY_PERIOD_END_DATE,
    A.SERVICE_WEEK,
    A.SERVICE_END_OF_WEEK,
    A.BRANCH_KEY,
    A.SUPERVISOR_KEY,
    A.CLIENT_KEY_DATA,
    A.CONTRACT_KEY,
    A.ORIGINAL_SOURCE_SYSTEM_ID,
    A.SOURCE_SYSTEM_ID,
    A.CLIENT_KEY,
	A.HOURS_SCHEDULED,
	A.HOURS_SERVED_ALL,
	A.HOURS_CANCELLED,
	A.HOURS_IN_REVIEW,
	A.HOURS_MISSED,
	A.HOURS_RESCHEDULED,
	A.FUTURE_HOURS,
	A.FUTURE_CANCELLED_HOURS,
	A.FUTURE_HOLD_HOURS,
	A.VISITS_SCHEDULED,
	A.VISITS_COMPLETED,
	A.VISITS_CANCELLED,
	A.VISITS_IN_REVIEW,
	A.VISITS_MISSED,
	A.VISITS_RESCHEDULED,
	A.FUTURE_VISITS,
	A.FUTURE_CANCELLED_VISITS,
	A.FUTURE_HOLD_VISITS,
	A.VISITS_CLEAN_SHIFTS,
	A.VISITS_NEED_MAINTENANCE,
	A.CLIENT_ACQUIRED_FLAG,
	A.CLIENT_ACQUISITION_NAME,
	A.CLIENT_SERVED_FLAG,
    A.ETL_TASK_KEY,
    A.ETL_INSERTED_TASK_KEY,
    A.ETL_INSERTED_DATE,
    A.ETL_INSERTED_BY,
    A.ETL_LAST_UPDATED_DATE,
    A.ETL_LAST_UPDATED_BY,
    A.ETL_DELETED_FLAG,
    A.ETL_INFERRED_MEMBER_FLAG,
    A.DERIVED_FIRST_SERVICE_DATE DERIVED_FIRST_SERVICE_DATE,
    A.DERIVED_LAST_SERVICE_DATE DERIVED_LAST_SERVICE_DATE
FROM DATA A 
LEFT JOIN DATE_DATA B ON B.CALENDAR_DATE=DATEADD('DAY',-7,A.SERVICE_WEEK) AND A.BRANCH_KEY=B.BRANCH_KEY
WHERE B.CALENDAR_DATE IS NOT NULL;
SQL
	or_replace = true 
	is_secure = false 
}

