resource "snowflake_view" "DW_REPORT_VW_CLIENT_CENSUS" {
	database = "DW_${var.SF_ENVIRONMENT}"
	schema = "REPORT"
	name = "VW_CLIENT_CENSUS"
	statement = <<-SQL
	 
SELECT 
CLIENT_KEY ,
CASE WHEN CC.TERMINATED_FLAG=1 THEN CC.CLIENT_KEY ELSE NULL END AS TERMINATED_CLIENT_KEY,
CASE WHEN CC.REACTIVATED_FLAG=1 AND DATE_TRUNC('MONTH',CC.FIRST_SERVICE_DATE) <> CC.SERVICE_MONTH THEN CC.CLIENT_KEY ELSE NULL END AS REACTIVATED_CLIENT_KEY,
CASE WHEN CC.NEW_FLAG=1 THEN CC.CLIENT_KEY ELSE NULL END AS NEW_CLIENT_KEY,
CASE WHEN DATE_TRUNC('MONTH',CC.REFERRAL_DATE)=DATE_TRUNC('MONTH',CC.FIRST_SERVICE_DATE) THEN CC.CLIENT_KEY ELSE NULL END AS REFERRAL_CLIENT_KEY,
CC.SERVICE_MONTH,
CC.FIRST_SERVICE_DATE,
CC.REFERRAL_DATE,
CC.admission_date,
CC.BRANCH_KEY,
CC.SUPERVISOR_KEY,
CC.REVENUE_CATEGORY,
CC.REVENUE_SUBCATEGORY_CODE,
CC.SOURCE_SYSTEM_ID,
CC.ORIGINAL_SOURCE_SYSTEM_ID,
CC.SCHEDULE_TYPE 
FROM DW_${var.SF_ENVIRONMENT}.REPORT.CLIENT_CENSUS_WIP CC
WHERE  CC.SERVICE_MONTH BETWEEN DATE_TRUNC(YEAR,DATEADD(YEAR,-2,CURRENT_DATE)) AND CURRENT_DATE;
SQL
	or_replace = true 
	is_secure = false 
}

