resource "snowflake_view" "DW_REPORT_VW_OPS_PERFORMANCE_OVERTIME_BACKUP" {
	database = "DW_${var.SF_ENVIRONMENT}"
	schema = "REPORT"
	name = "VW_OPS_PERFORMANCE_OVERTIME_BACKUP"
	statement = <<-SQL
	 
SELECT 
O.EMPLOYEE_KEY,
O.BRANCH_KEY,
O.CLIENT_KEY,
O.SUPERVISOR_KEY,
O.CONTRACT_KEY,
O.PAYROLL_SERVICE_HOURS,
O.SERVICE_MONTH,
O.OVERTIME_HOURS,
O.ETL_LAST_UPDATED_DATE
FROM REPORT.OVERTIME_2 O
JOIN REPORT.VW_DASHBOARD_CONTRACTS DC ON O.CONTRACT_KEY=DC.CONTRACT_KEY 
    AND INCLUDE_FOR_OPS_PERF_CLIENTS=1
WHERE SERVICE_MONTH>='2020-01-01';
SQL
	or_replace = true 
	is_secure = false 
}

