resource "snowflake_view" "DW_REPORT_VW_INVOICES_METRICS" {
	database = "DW_${var.SF_ENVIRONMENT}"
	schema = "REPORT"
	name = "VW_INVOICES_METRICS"
	statement = <<-SQL
	 SELECT 
		INV.INVOICE_KEY,
		REV.REVENUE_KEY,	--ADDED ON 28/04/23
		INV.INVOICE_NUMBER,
	    INV.ALTERNATE_INVOICE_NUMBER,
		INV.INVOICE_TYPE,  -- ADDED ON 04/11
		REV.BILL_UNIT_TYPE,
		INV.FIRST_INVOICE_DATE,		--ADDED ON 04/04/23
		REV.REVENUE_DATE,
		REV.REPORT_DATE,
		BR.OFFICE_STATE_CODE,
        CON.CONTRACT_KEY, -- ADDED ON 12/16/2022
		CON.CONTRACT_CODE,
		CON.CONTRACT_NAME,
		CONCAT(CON.CONTRACT_CODE,' - ',CON.CONTRACT_NAME) AS CONTRACT_CODE_AND_NAME,
        BR.ORIGINAL_BRANCH_KEY, -- ADDED ON 12/16/2022
		BR.OFFICE_CODE,
		BR.OFFICE_NAME,
        CLI.ORIGINAL_CLIENT_KEY, -- ADDED ON 12/16/2022
		CLI.CLIENT_NAME,
		CLI.CLIENT_NUMBER,
		sum(REV.AMOUNT_BILLED) AS INVOICE_AMOUNT,
		sum(REV.INVOICE_HOURS) AS HOURS_BILLED,
		NULL AS AMOUNT_PAID,
		REV.PAYMENT_DATE,
		sum(REV.AMOUNT_COLLECTED) AS PAYMENT_RECEIVED,
		INV.PAYOR_CODE,
		NULL AS CREDITED_AMOUNT,
		sum(REV.AMOUNT_OUTSTANDING) AS AMOUNT_OUTSTANDING,
		CASE WHEN INV.AMOUNT_OUTSTANDING>0 THEN DATEDIFF(DAY, REV.REVENUE_DATE,GETDATE()) END AS OUTSTANDING_DAYS,
        CASE WHEN UPPER(INV.INVOICE_STATUS) NOT IN ('BILL PAID','PAID','BILLED') AND DATEDIFF('year',INV.FIRST_INVOICE_DATE,CURRENT_DATE) >2 THEN sum(inv.AMOUNT_OUTSTANDING) END AS UNCOLLECTABLE_REVENUE,
		NULL AS STATUS,
		INV.INVOICE_STATUS,
		CLI.FIRST_SERVICE_DATE AS START_OF_SERVICE,
		CLI.LAST_SERVICE_DATE AS END_OF_SERVICE,
		INV.PERIOD,
		NULL AS TOTAL_PAID_AMOUNT,
		CASE WHEN INV.WRITEOFF_FLAG = 'True' THEN SUM(INV.AMOUNT_BILLED) END AS TOTAL_WRITE_OFF_AMOUNT,
		REV.SOURCE_SYSTEM_ID,
		REV.ORIGINAL_SOURCE_SYSTEM_ID 
FROM DW_${var.SF_ENVIRONMENT}.HAH.DIM_INVOICE INV
LEFT JOIN DW_${var.SF_ENVIRONMENT}.INTEGRATION.FACT_REVENUE_MERGED  REV ON INV.INVOICE_KEY = REV.INVOICE_KEY
LEFT JOIN DW_${var.SF_ENVIRONMENT}.INTEGRATION.DIM_CLIENT_MERGED  CLI ON INV.CLIENT_KEY = CLI.ORIGINAL_CLIENT_KEY 
LEFT JOIN DW_${var.SF_ENVIRONMENT}.INTEGRATION.DIM_BRANCH_MERGED  BR ON INV.BRANCH_KEY = BR.ORIGINAL_BRANCH_KEY 
LEFT JOIN DW_${var.SF_ENVIRONMENT}.HAH.DIM_CONTRACT CON ON REV.CONTRACT_KEY = CON.CONTRACT_KEY
--LEFT JOIN DW_${var.SF_ENVIRONMENT}.HAH.DIM_SOURCE_SYSTEM SS ON SS.SOURCE_SYSTEM_ID=INV.SOURCE_SYSTEM_ID
WHERE --REV.REVENUE_DATE >= dateadd(month, -36,  cast(getdate() as date))
UPPER(Trim(INV.INVOICE_STATUS)) NOT IN ('CANCELLED','PENDING')
--AND NVL(REV.AMOUNT_OUTSTANDING,0)!=0	--CHNAGES MADE ON 24/03/23 FOR BI DASHBOARD
GROUP BY 
		INV.INVOICE_KEY,
		REV.REVENUE_KEY,
		INV.INVOICE_NUMBER,
		INV.INVOICE_TYPE,  -- ADDED ON 04/11
		REV.BILL_UNIT_TYPE,
		REV.REVENUE_DATE,
		REV.REPORT_DATE,
		BR.OFFICE_STATE_CODE,
        CON.CONTRACT_KEY, -- ADDED ON 12/16/2022
		CON.CONTRACT_CODE,
		CON.CONTRACT_NAME,
		CONTRACT_CODE_AND_NAME,
        BR.ORIGINAL_BRANCH_KEY, -- ADDED ON 12/16/2022
		BR.OFFICE_CODE,
		BR.OFFICE_NAME,
        CLI.ORIGINAL_CLIENT_KEY, -- ADDED ON 12/16/2022
		CLI.CLIENT_NAME,
		CLI.CLIENT_NUMBER,
		REV.PAYMENT_DATE,
		INV.PAYOR_CODE,
		OUTSTANDING_DAYS,
		STATUS,
		INV.INVOICE_STATUS,
        	INV.FIRST_INVOICE_DATE,
		START_OF_SERVICE,
		END_OF_SERVICE,
		INV.PERIOD,
		INV.WRITEOFF_FLAG,
		REV.SOURCE_SYSTEM_ID,
		REV.ORIGINAL_SOURCE_SYSTEM_ID,
		INV.ALTERNATE_INVOICE_NUMBER;
SQL
	or_replace = true 
	is_secure = false 
}

