resource "snowflake_view" "DW_REPORT_VW_HOURS_AND_CENSUS_BUDGETEDDATA_DAILY" {
	database = "DW_${var.SF_ENVIRONMENT}"
	schema = "REPORT"
	name = "VW_HOURS_AND_CENSUS_BUDGETEDDATA_DAILY"
	statement = <<-SQL
	 SELECT CALENDAR_DATE AS BUDGET_DATE, STATE_CODE AS OFFICE_STATE_CODE, OFFICE_NUMBER, BRANCH_KEY, SERVICE_LINE_CODE AS SERVICELINE,
	SUM(HOURS_BUDGETED_DAILY) AS HOURS_BUDGETED_DAILY
	FROM INTEGRATION.FACT_BUDGET_MERGED 
    WHERE CALENDAR_DATE >= '2020-01-01'
    GROUP BY 1,2,3,4,5;
SQL
	or_replace = true 
	is_secure = false 
}

