resource "snowflake_view" "DW_REPORT_VW_EXECUTIVE_OPERATIONS_EXCELLENCE_CLIENTS_REFERRED" {
	database = "DW_${var.SF_ENVIRONMENT}"
	schema = "REPORT"
	name = "VW_EXECUTIVE_OPERATIONS_EXCELLENCE_CLIENTS_REFERRED"
	statement = <<-SQL
	 SELECT DISTINCT
DATE_TRUNC('MONTH',R.REFERRED_DATE) AS REFERRED_DATE,
R.CLIENT_KEY,
R.CLIENT_NUMBER ,
R.CLIENT_NAME ,
R.DAYS_TO_SERVICE ,
R.BRANCH_KEY, 
R.FIRST_CONTRACT_KEY AS CONTRACT_KEY,
R.SOURCE_SYSTEM_ID 
,R.ORIGINAL_SOURCE_SYSTEM_ID 
FROM REPORT.CLIENTS_REFERRED R
JOIN REPORT.VW_DASHBOARD_CONTRACTS DC ON R.FIRST_CONTRACT_KEY=DC.CONTRACT_KEY 
    AND DC.INCLUDE_FOR_EXEC_OPS_CLIENTS=1
WHERE R.REFERRED_DATE BETWEEN DATE_TRUNC(YEAR,DATEADD(YEAR,-2,CURRENT_DATE)) AND CURRENT_DATE;
SQL
	or_replace = true 
	is_secure = false 
}

