resource "snowflake_view" "DW_REPORT_VW_OPS_PERFORMANCE_CLIENTS_TERMED" {
	database = "DW_${var.SF_ENVIRONMENT}"
	schema = "REPORT"
	name = "VW_OPS_PERFORMANCE_CLIENTS_TERMED"
	statement = <<-SQL
	 WITH TERMED_CLIENTS AS (
	SELECT DISTINCT CLIENTS.PERIOD_BEGIN_DATE,
		CLIENTS.CLIENT_KEY,
		CONTRACTS.REVENUE_CATEGORY,
		FIRST_VALUE(CLIENTS.CURRENT_BRANCH_KEY) OVER(PARTITION BY CLIENTS.PERIOD_BEGIN_DATE, CLIENTS.CLIENT_KEY, CONTRACTS.REVENUE_CATEGORY ORDER BY SUM(HOURS_SERVED_LAST_PERIOD) DESC) AS CURRENT_BRANCH_KEY,
		FIRST_VALUE(CLIENTS.CURRENT_SUPERVISOR_KEY) OVER(PARTITION BY CLIENTS.PERIOD_BEGIN_DATE, CLIENTS.CLIENT_KEY, CONTRACTS.REVENUE_CATEGORY ORDER BY SUM(HOURS_SERVED_LAST_PERIOD) DESC) AS CURRENT_SUPERVISOR_KEY
	FROM REPORT.CLIENTS_TERMED CLIENTS
	JOIN REPORT.VW_DASHBOARD_CONTRACTS CONTRACTS
		ON CONTRACTS.CONTRACT_KEY = CLIENTS.CONTRACT_KEY
		WHERE INCLUDE_FOR_OPS_PERF_CLIENTS=1
	GROUP BY CLIENTS.PERIOD_BEGIN_DATE, 
		CLIENTS.CLIENT_KEY, 
		CONTRACTS.REVENUE_CATEGORY,
		CLIENTS.CURRENT_BRANCH_KEY, 
		CLIENTS.CURRENT_SUPERVISOR_KEY
), VISITS AS (
	SELECT DISTINCT DATE_TRUNC(MONTH, VISIT.REPORT_DATE) AS PERIOD_BEGIN_DATE,
		VISIT.CLIENT_KEY,
		CONTRACTS.REVENUE_CATEGORY
	FROM HAH.FACT_VISIT VISIT
	JOIN REPORT.VW_DASHBOARD_CONTRACTS CONTRACTS
		ON CONTRACTS.CONTRACT_KEY = VISIT.CONTRACT_KEY
		AND VISIT.CONFIRMED_FLAG = 'YES' --VISIT.STATUS_CODE IN ('02','03','04','05')
		AND VISIT.HOURS_SERVED > 0
		WHERE INCLUDE_FOR_OPS_PERF_CLIENTS=1
), TERMED_CLIENTS_BY_CATEGORY AS (
	SELECT CLIENTS.PERIOD_BEGIN_DATE,
		CLIENTS.CLIENT_KEY,
		CLIENTS.REVENUE_CATEGORY,
		CLIENTS.CURRENT_BRANCH_KEY,
		CLIENTS.CURRENT_SUPERVISOR_KEY
	FROM TERMED_CLIENTS CLIENTS
	JOIN REPORT.VW_OPS_PERFORMANCE_DIM_DATE DATES
		ON DATES.PERIOD_BEGIN_DATE = CLIENTS.PERIOD_BEGIN_DATE 
	LEFT JOIN VISITS VISITS
		ON VISITS.PERIOD_BEGIN_DATE = CLIENTS.PERIOD_BEGIN_DATE
			AND VISITS.CLIENT_KEY = CLIENTS.CLIENT_KEY
			AND VISITS.REVENUE_CATEGORY = CLIENTS.REVENUE_CATEGORY
	WHERE VISITS.PERIOD_BEGIN_DATE IS NULL AND 
  DATES.PERIOD_BEGIN_DATE BETWEEN '2020-01-01' AND DATE_TRUNC(MONTH,CURRENT_DATE())
)
	SELECT PERIOD_BEGIN_DATE,
		CLIENT_KEY,
		REVENUE_CATEGORY,
		CURRENT_BRANCH_KEY,
		CURRENT_SUPERVISOR_KEY
	FROM TERMED_CLIENTS_BY_CATEGORY;
SQL
	or_replace = true 
	is_secure = false 
}

