resource "snowflake_view" "DW_REPORT_VW_EMPLOYEE_SUPERVISOR_BY_SERVICE_WEEK" {
	database = "DW_${var.SF_ENVIRONMENT}"
	schema = "REPORT"
	name = "VW_EMPLOYEE_SUPERVISOR_BY_SERVICE_WEEK"
	statement = <<-SQL
	 SELECT  
SERVICE_WEEK,
EMPLOYEE_KEY,
BRANCH_KEY	,
BRANCH_STATE,
BRANCH_NAME	,
EMPLOYEE_SYSTEM_CODE,
EMPLOYEE_ID	,
EMPLOYEE_LAST_NAME,
EMPLOYEE_CATEGORY,
SUPERVISOR_KEY	,
SUPERVISOR_SYSTEM_CODE	,
SUPERVISOR_CODE	,
SUPERVISOR_NAME ,
ETL_TASK_KEY	,
ETL_INSERTED_TASK_KEY	,
ETL_INSERTED_DATE	,
ETL_INSERTED_BY	,
ETL_LAST_UPDATED_DATE,
ETL_LAST_UPDATED_BY	,
ETL_DELETED_FLAG	
FROM REPORT.EMPLOYEE_SUPERVISOR_BY_SERVICE_WEEK
WHERE SERVICE_WEEK BETWEEN DATE_TRUNC('YEAR',DATEADD('YEAR',-2,CURRENT_DATE)) AND CURRENT_DATE;
SQL
	or_replace = true 
	is_secure = false 
}

