resource "snowflake_view" "DW_REPORT_ROLLING_ONHOLDCLIENTCOUNT_MONTHLY_MDA" {
	database = "DW_${var.SF_ENVIRONMENT}"
	schema = "REPORT"
	name = "ROLLING_ONHOLDCLIENTCOUNT_MONTHLY_MDA"
	statement = <<-SQL
	 SELECT dt.FIRST_DAY_OF_MONTH,MONTH,YEAR,STATE,BRANCH_NAME,BRANCH_KEY,
DISTINCTCLIENTCOUNT FROM "REPORT"."ROLLING_ONHOLDCLIENTCOUNT_MDA" ronclnt
INNER JOIN 
(SELECT DISTINCT LAST_DAY_OF_MONTH,FIRST_DAY_OF_MONTH,MONTH,YEAR FROM HAH.DIM_DATE dt
 WHERE dt.calendar_Date BETWEEN DATE_TRUNC(YEAR,DATEADD(YEAR,-2,CURRENT_DATE)) AND CURRENT_DATE)dt
on ronclnt.calendar_Date = dt.LAST_DAY_OF_MONTH
UNION ALL
SELECT dt.FIRST_DAY_OF_MONTH,MONTH,YEAR,STATE,BRANCH_NAME,BRANCH_KEY,
DISTINCTCLIENTCOUNT FROM "REPORT"."ROLLING_ONHOLDCLIENTCOUNT_MDA" ronclnt
INNER JOIN 
(SELECT DISTINCT calendar_Date,FIRST_DAY_OF_MONTH,MONTH,YEAR FROM HAH.DIM_DATE dt
 WHERE dt.IS_TODAY=TRUE)dt
on ronclnt.calendar_Date = dt.calendar_Date;
SQL
	or_replace = true 
	is_secure = false 
}

