resource "snowflake_view" "DISC_AXXESS_CLIENT_FOR_DEDUPE" {
	database = "DISC_${var.SF_ENVIRONMENT}"
	schema = "AXXESS"
	name = "CLIENT_FOR_DEDUPE"
	statement = <<-SQL
	 SELECT DISTINCT
	PI.PATIENT_ID AS PATIENT_ID,
	FIRST_NAME, 
	MIDDLE_INITIAL, 
	LAST_NAME,
	FIRST_NAME || ' ' || LAST_NAME AS NAME,
	SSN,
	TRY_TO_DATE(TRIM(pi.DATE_OF_BIRTH),'MM/DD/YYYY HH12:MI:SS AM +TZH:TZM') AS DATE_OF_BIRTH,
	pi.GENDER AS GENDER,
	pi.PHONE,
	pi.EMERGENCY_CONTACT_PHONE AS EMERGENCY_CONTACT_PHONE,
	ES.EMAIL_ADDRESS AS EMAIL_ADDRESS,
	NULLIF(UPPER(TRIM(ES.EMAIL_ADDRESS)),'') AS CLIENT_PERSONAL_EMAIL,
	ES.ADDRESSLINE_1 AS ADDRESSLINE_1,
	ES.ADDRESSLINE_2 AS ADDRESSLINE_2,
	pi.CITY AS CITY,
	pi.STATE AS STATE,
	ES.ZIPCODE AS ZIPCODE,
	ES.BRANCH AS BRANCH,
	ES.BRANCH_ID,
	pi.CASE_MANAGER_FIRST_NAME,
	pi.CASE_MANAGER_LAST_NAME,
	ES.CASE_MANAGER_NAME,
	MIN(ES.START_OF_CARE_DATE) AS START_OF_CARE_DATE,
	MIN(ES.REFERRAL_DATE) AS REFERRAL_DATE,
	MAX(ES.IS_DISCHARGED) AS IS_DISCHARGED,
	MAX(ES.PATIENT_STATUS) AS PATIENT_STATUS,
	MAX(ES.EPISODE_END_DATE) AS EPISODE_END_DATE
	FROM AXXESS.AXXESS_PATIENTINFO pi
LEFT JOIN AXXESS.AXXESS_EPISODESNAPSHOTS ES 
	ON TRIM(pi.PATIENT_ID) = ES.PATIENT_ID
GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22
ORDER BY 2,3,4,5,6,7,8,9,10;
SQL
	or_replace = true 
	is_secure = false 
}

