resource "snowflake_view" "DISC_AXXESS_VW_AXXESS_CLIENTS" {
	database = "DISC_${var.SF_ENVIRONMENT}"
	schema = "AXXESS"
	name = "VW_AXXESS_CLIENTS"
	statement = <<-SQL
	 
SELECT 
PATIENT_ID,
	MEDICAL_RECORD_NUMBER,
	LAST_NAME,
	FIRST_NAME,
	MIDDLE_INITIAL,
	SSN,
	DATE_OF_BIRTH,
	GENDER,
	ADDRESS,
	CITY,
	STATE,
	ZIP_CODE,
	REFERRAL_DATE,
	PHONE,
	EMERGENCY_CONTACT_PHONE,
	CASE_MANAGER_FIRST_NAME,
	CASE_MANAGER_LAST_NAME,
	ETL_TASK_KEY,
	ETL_INSERTED_TASK_KEY,
	ETL_INSERTED_DATE,
	ETL_INSERTED_BY,
	ETL_LAST_UPDATED_DATE,
	ETL_LAST_UPDATED_BY,
	ETL_DELETED_FLAG,
	REVENUE_CATEGORY
FROM (	
select ROW_NUMBER() OVER (PARTITION BY PATIENT_ID ORDER BY MEDICAL_RECORD_NUMBER  DESC) AS RANK,*  from (
SELECT 
PATIENT_ID
,MEDICAL_RECORD_NUMBER
,REPLACE(REPLACE(LAST_NAME,'"',''),$$\$$,'') LAST_NAME
,REPLACE(REPLACE(FIRST_NAME,'"',''),$$\$$,'') FIRST_NAME
,MIDDLE_INITIAL
,SSN
,DATE_OF_BIRTH
,GENDER
,ADDRESS
,CITY
,STATE
,ZIP_CODE
,REFERRAL_DATE
,PHONE
,EMERGENCY_CONTACT_PHONE
,CASE_MANAGER_FIRST_NAME
,CASE_MANAGER_LAST_NAME
,ETL_TASK_KEY
,ETL_INSERTED_TASK_KEY
,ETL_INSERTED_DATE
,ETL_INSERTED_BY
,ETL_LAST_UPDATED_DATE
,ETL_LAST_UPDATED_BY
,ETL_DELETED_FLAG
,'HH' AS REVENUE_CATEGORY
FROM AXXESS.AXXESS_PATIENTINFO 
WHERE PATIENT_ID IS NOT NULL
UNION ALL 
SELECT    DISTINCT        
CLIENT_ID AS PATIENT_ID 
,MRN AS MEDICAL_RECORD_NUMBER 
,CLIENT_LAST_NAME AS LAST_NAME      
,CLIENT_FIRST_NAME AS FIRST_NAME
,CLIENT_MIDDLE_INITIAL AS MIDDLE_INITIAL
,NULL AS SSN      
,CLIENT_DOB AS DATE_OF_BIRTH
,CLIENT_GENDER AS GENDER
,CLIENT_ADDRESS1 ADDRESS                           
,CLIENT_CITY AS CITY            
,CLIENT_STATE AS STATE
,CLIENT_ZIP AS ZIP_CODE
,REFERRAL_DATE
,NULL AS PHONE     
,NULL AS EMERGENCY_CONTACT_PHONE
,FIRST_VALUE(SUBSTRING(CAREPERIOD_CASEMANAGER_NAME , CHARINDEX(',', CAREPERIOD_CASEMANAGER_NAME)+1,LENGTH(CAREPERIOD_CASEMANAGER_NAME) ))
 OVER (PARTITION BY PATIENT_ID ORDER BY PATIENT_ID) AS  CASE_MANAGER_FIRST_NAME -- TO AVOID DUPLICATE ROWS DUE TO MULTIPLE SUPERVISORS FOR A PATIENT
,FIRST_VALUE(SUBSTRING(CAREPERIOD_CASEMANAGER_NAME , 1, CHARINDEX(',', CAREPERIOD_CASEMANAGER_NAME)-1) ) 
 OVER (PARTITION BY PATIENT_ID ORDER BY PATIENT_ID) AS  CASE_MANAGER_LAST_NAME -- TO AVOID DUPLICATE ROWS DUE TO MULTIPLE SUPERVISORS FOR A PATIENT
 --Modified by Pankti M. on 22-09-22
,ETL_TASK_KEY
,ETL_INSERTED_TASK_KEY
,ETL_INSERTED_DATE      
,ETL_INSERTED_BY   
,ETL_LAST_UPDATED_DATE  
,ETL_LAST_UPDATED_BY
,ETL_DELETED_FLAG
,'HC' AS REVENUE_CATEGORY
FROM AXXESS.AXXESS_CAREPERIODS
WHERE PATIENT_ID IS NOT NULL
  ) QUALIFY RANK = 1 
  )t;
SQL
	or_replace = true 
	is_secure = false 
}

