CREATE OR REPLACE PROCEDURE DISC_PROD.ALAYACARE.GET_FUNDER()
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
--*****************************************************************************************************************************
-- NAME:  GET_FUNDER 
--
-- PURPOSE: USING THIS SP FOR DISCOVERY TABLE LOAD
--
-- DEVELOPMENT LOG:
-- DATE        		AUTHOR                	NOTES:
-- ----------  		-------------------   	-----------------------------------------------------------------------------------------------
-- 2021-11-11		UNKNOWN					INITIAL DEVELOPMENT
-- 2023-09-05  		RAVI SUTHAR            	MIGRATED JavaScript to SQL
--*****************************************************************************************************************************
    return_result varchar(1000);
BEGIN
	
    INSERT OVERWRITE INTO ALAYACARE.FUNDER (
        FUNDER_ID, PROFILE_ID, GUID, BRANCH_ID, CODE, NAME, INVOICING_MODEL, DESCRIPTION, HOLIDAY_MULTIPLIER, TAX_CLASS_ID, CCAC_CODE, CCAC_NAME, MEDICAID_PAYER_CODE, MEDICAID_PAYER_NAME, MEDICAID_PROVIDER_CODE, MEDICAID_PROVIDER_NAME, MEDICAID_PROVIDER_TAX_ID, MEDICAID_PROVIDER_TAXONOMY_CODE, MEDICAID_PAYER_ELECTRONIC_TRANSMITTER_ID, MEDICAID_PROVIDER_ELECTRONIC_TRANSMITTER_ID, MEDICAID_USE_BANK, MEDICAID_CLAIM_TYPE, CCAC_CONTRACT_CODE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY, 
		PROFILE_ADDRESS, PROFILE_CITY, PROFILE_COUNTRY, PROFILE_PHONE_MAIN, PROFILE_STATE, PROFILE_ZIP, 
		PROPERTIES_OP, PROPERTIES_BILLING_ADJUSTMENT_PERIOD, PROPERTIES_CAN_USE_PAYPAL, PROPERTIES_CODE, PROPERTIES_CREATE_TIME, PROPERTIES_DESCRIPTION, PROPERTIES_GL_ASSET_ACC_ACCOUNT_ID, PROPERTIES_GL_BANK_ACC_ACCOUNT_ID, PROPERTIES_GUID, PROPERTIES_HOLIDAY_MULTIPLIER, PROPERTIES_ID, PROPERTIES_IDMASTERACCOUNT, PROPERTIES_IDPROFILE, PROPERTIES_INVOICING_MODEL, PROPERTIES_IS_DISABLED, PROPERTIES_NAME, PROPERTIES_UPDATE_TIME)
        SELECT FUNDER_ID AS FUNDER_ID, PROFILE_ID AS PROFILE_ID, GUID AS GUID, BRANCH_ID AS BRANCH_ID, CODE AS CODE, NAME AS NAME, INVOICING_MODEL AS INVOICING_MODEL, DESCRIPTION AS DESCRIPTION, HOLIDAY_MULTIPLIER AS HOLIDAY_MULTIPLIER, TAX_CLASS_ID AS TAX_CLASS_ID, CCAC_CODE AS CCAC_CODE, CCAC_NAME AS CCAC_NAME, MEDICAID_PAYER_CODE AS MEDICAID_PAYER_CODE, MEDICAID_PAYER_NAME AS MEDICAID_PAYER_NAME, MEDICAID_PROVIDER_CODE AS MEDICAID_PROVIDER_CODE, MEDICAID_PROVIDER_NAME AS MEDICAID_PROVIDER_NAME, MEDICAID_PROVIDER_TAX_ID AS MEDICAID_PROVIDER_TAX_ID, MEDICAID_PROVIDER_TAXONOMY_CODE AS MEDICAID_PROVIDER_TAXONOMY_CODE, MEDICAID_PAYER_ELECTRONIC_TRANSMITTER_ID AS MEDICAID_PAYER_ELECTRONIC_TRANSMITTER_ID, MEDICAID_PROVIDER_ELECTRONIC_TRANSMITTER_ID AS MEDICAID_PROVIDER_ELECTRONIC_TRANSMITTER_ID, MEDICAID_USE_BANK AS MEDICAID_USE_BANK, MEDICAID_CLAIM_TYPE AS MEDICAID_CLAIM_TYPE, CCAC_CONTRACT_CODE AS CCAC_CONTRACT_CODE, CREATED_AT AS CREATED_AT, CREATED_BY AS CREATED_BY, UPDATED_AT AS UPDATED_AT, UPDATED_BY AS UPDATED_BY, 
			PROFILE:address::STRING AS PROFILE_ADDRESS, PROFILE:city::STRING AS PROFILE_CITY, PROFILE:country::STRING AS PROFILE_COUNTRY, PROFILE:phone_main::STRING AS PROFILE_PHONE_MAIN, PROFILE:state::STRING AS PROFILE_STATE, PROFILE:zip::STRING AS PROFILE_ZIP, 
			PROPERTIES:Op::STRING AS PROPERTIES_OP, PROPERTIES:billing_adjustment_period::STRING AS PROPERTIES_BILLING_ADJUSTMENT_PERIOD, PROPERTIES:can_use_paypal::STRING AS PROPERTIES_CAN_USE_PAYPAL, PROPERTIES:code::STRING AS PROPERTIES_CODE, PROPERTIES:create_time::STRING AS PROPERTIES_CREATE_TIME, PROPERTIES:description::STRING AS PROPERTIES_DESCRIPTION, PROPERTIES:gl_asset_acc_account_id::STRING AS PROPERTIES_GL_ASSET_ACC_ACCOUNT_ID, PROPERTIES:gl_bank_acc_account_id::STRING AS PROPERTIES_GL_BANK_ACC_ACCOUNT_ID, PROPERTIES:guid::STRING AS PROPERTIES_GUID, PROPERTIES:holiday_multiplier::STRING AS PROPERTIES_HOLIDAY_MULTIPLIER, PROPERTIES:id::STRING AS PROPERTIES_ID, PROPERTIES:idmasteraccount::STRING AS PROPERTIES_IDMASTERACCOUNT, PROPERTIES:idprofile::STRING AS PROPERTIES_IDPROFILE, PROPERTIES:invoicing_model::STRING AS PROPERTIES_INVOICING_MODEL, PROPERTIES:is_disabled::STRING AS PROPERTIES_IS_DISABLED, PROPERTIES:name::STRING AS PROPERTIES_NAME, PROPERTIES:update_time::STRING AS PROPERTIES_UPDATE_TIME  
        FROM ALAYACARE_PRODUCTION."5C3EE5FE-45A5-4DA7-A35B-BD7CDAFE3548".SHARED_FUNDER;

	SELECT CONCAT(''Message : '',"number of rows inserted",'' Rows Inserted.'') into :return_result FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));
	return return_result;
END;
';