CREATE OR REPLACE PROCEDURE DISC_PROD.ALAYACARE.GET_FUNDING_BLOCK_TIER_4()
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
--*****************************************************************************************************************************
-- NAME:  GET_FUNDING_BLOCK_TIER_4 
--
-- PURPOSE: USING THIS SP FOR DISCOVERY TABLE LOAD
--
-- DEVELOPMENT LOG:
-- DATE        		AUTHOR                	NOTES:
-- ----------  		-------------------   	-----------------------------------------------------------------------------------------------
-- 2021-11-11		UNKNOWN					INITIAL DEVELOPMENT
-- 2023-09-05  		RAVI SUTHAR            	MIGRATED JavaScript to SQL
--*****************************************************************************************************************************
    return_result varchar(1000);
BEGIN
	
INSERT OVERWRITE INTO ALAYACARE.FUNDING_BLOCK_TIER_4
SELECT
    FUNDING_BLOCK_ID ,
    SERVICE_ID ,
    FUNDING_BLOCK_START_DATE ,
    FUNDING_BLOCK_END_DATE ,
    FUNDING_BLOCK_CREATE_DATE ,
    FUNDING_BLOCK_REVISION_DATE ,
    FUNDING_QUANTITY ,
    FUNDING_UNITS ,
    FUNDING_COMMENTS ,
    FUNDING_FREQUENCY ,
    FUNDING_BLOCK_EXPIRY ,
    MASTER ,
    PROPERTIES_FUNDING_BLOCK ,
    PROPERTIES_FUNDING_BLOCK[''comments'']::VARCHAR(16777216) AS PROPERTIES_FUNDING_BLOCK_COMMENTS,
PROPERTIES_FUNDING_BLOCK[''create_time'']::VARCHAR(100) AS PROPERTIES_FUNDING_BLOCK_CREATE_TIME,
PROPERTIES_FUNDING_BLOCK[''end_date'']::VARCHAR(100) AS PROPERTIES_FUNDING_BLOCK_END_DATE,
PROPERTIES_FUNDING_BLOCK[''frequency'']::VARCHAR(16777216) AS PROPERTIES_FUNDING_BLOCK_FREQUENCY,
PROPERTIES_FUNDING_BLOCK[''id'']::VARCHAR(100) AS PROPERTIES_FUNDING_BLOCK_ID,
PROPERTIES_FUNDING_BLOCK[''parent_id'']::VARCHAR(100) AS PROPERTIES_FUNDING_BLOCK_PPARENT_ID,
PROPERTIES_FUNDING_BLOCK[''quantity'']::VARCHAR(100) AS PROPERTIES_FUNDING_BLOCK_QUANTITY,
PROPERTIES_FUNDING_BLOCK[''service_id'']::VARCHAR(100) AS PROPERTIES_FUNDING_BLOCK_SERVICE_ID,
PROPERTIES_FUNDING_BLOCK[''start_date''] ::VARCHAR(100) AS PROPERTIES_FUNDING_BLOCK_START_DATE,
PROPERTIES_FUNDING_BLOCK[''units''] ::VARCHAR(100) AS PROPERTIES_FUNDING_BLOCK_UNITS,
PROPERTIES_FUNDING_BLOCK[''update_time'']::VARCHAR(100) AS PROPERTIES_FUNDING_BLOCK_UPDATE_TIME,
PROPERTIES_FUNDING_BLOCK_PARENT VARIANT,
PROPERTIES_FUNDING_BLOCK_PARENT[''comments'']::VARCHAR(16777216) AS PROPERTIES_FUNDING_BLOCK_PARENT_COMMENTS,
PROPERTIES_FUNDING_BLOCK_PARENT[''create_time'']::VARCHAR(100) AS PROPERTIES_FUNDING_BLOCK_PARENT_CREATE_TIME,
PROPERTIES_FUNDING_BLOCK_PARENT[''end_date'']::VARCHAR(100) AS PROPERTIES_FUNDING_BLOCK_PARENT_END_DATE,
PROPERTIES_FUNDING_BLOCK_PARENT[''frequency'']::VARCHAR(16777216) AS PROPERTIES_FUNDING_BLOCK_PARENT_FREQUENCY,
PROPERTIES_FUNDING_BLOCK_PARENT[''frequency_custom_days'']::VARCHAR(16777216) AS PROPERTIES_FUNDING_BLOCK_PARENT_FREQUENCY_CUSTOM_DAYS,
PROPERTIES_FUNDING_BLOCK_PARENT[''id'']::VARCHAR(100) AS PROPERTIES_FUNDING_BLOCK_PARENT_ID,
PROPERTIES_FUNDING_BLOCK_PARENT[''quantity'']::VARCHAR(100) AS PROPERTIES_FUNDING_BLOCK_PARENT_QUANTITY,
PROPERTIES_FUNDING_BLOCK_PARENT[''service_id'']::VARCHAR(100) AS PROPERTIES_FUNDING_BLOCK_PARENT_SERVICE_ID,
PROPERTIES_FUNDING_BLOCK_PARENT[''start_date''] ::VARCHAR(100) AS PROPERTIES_FUNDING_BLOCK_PARENT_START_DATE,
PROPERTIES_FUNDING_BLOCK_PARENT[''units''] ::VARCHAR(100) AS PROPERTIES_FUNDING_BLOCK_PARENT_UNITS,
PROPERTIES_FUNDING_BLOCK_PARENT[''update_time'']::VARCHAR(100) AS PROPERTIES_FUNDING_BLOCK_PARENT_UPDATE_TIME,
VISIT_COUNT
FROM
ALAYACARE_PRODUCTION."5C3EE5FE-45A5-4DA7-A35B-BD7CDAFE3548".SHARED_FUNDING_BLOCK_TIER_4;

	SELECT CONCAT(''Message : '',"number of rows inserted",'' Rows Inserted.'') into :return_result FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));
	return return_result;
END;
';