CREATE OR REPLACE PROCEDURE DISC_PROD.PARADOX.GET_FILLED_JOBS("TASKKEY" VARCHAR(16777216))
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
--*****************************************************************************************************************************
-- NAME:  GET_FILLED_JOBS 
--
-- PURPOSE: USING THIS SP FOR DISCOVERY TABLE LOAD
--
-- DEVELOPMENT LOG:
-- DATE				AUTHOR										NOTES:
-- ----------		-------------------							-----------------------------------------------------------------------------------------------
-- 2023-11-20		KOMAL DHOKAI/RAVI SUTHAR					INITIAL DEVELOPMENT
--*****************************************************************************************************************************

 
BEGIN 
    --TARGETSQL
    COPY INTO DISC_PROD.PARADOX.HIST_FILLED_JOBS FROM ( SELECT A.$1 REQ_ID, A.$2 STORE, A.$3 ORGANIZATIONAL_ALIGNMENT, A.$4 HIRING_MANAGER_NAME, A.$5 STATE, A.$6 CITY, A.$7 JOB_TITLE, A.$8 JOB_FAMILY, A.$9 JOB_CODE, A.$10 JOB_POSTING_DATE, A.$11 JOB_CLOSING_DATE, A.$12 DATE_AND_TIME_OFFER_ACCEPTED, A.$13 TIME_TO_SCHEDULE, A.$14 CANDIDATE_ID, A.$15 CANDIDATE_NAME, A.$16 CANDIDATE_ACCEPTED_OFFER, A.$17 CANDIDATE_REJECTED, A.$18 PHONE_NUMBER, A.$19 EMAIL, A.$20 SALARY, A.$21 START_DATE, A.$22 APPLICATION_SOURCE_TYPE, A.$23 TIME_FROM_APPLY_TO_INTERVIEW_HH_MM_SS, A.$24 TIME_FROM_INTERVIEW_TO_OFFER_HH_MM_SS, A.$25 TIME_FROM_OFFER_TO_HIRE_HH_MM_SS, A.$26 TIME_FROM_HIRED_TO_STARTDATE_HH_MM_SS, A.$27 TIME_FROM_APPLY_TO_HIRE_HH_MM_SS, A.$28 TIME_FROM_APPLY_TO_START_DATE_HH_MM_SS, A.$29 TIME_FROM_FULL_APPLICATION_COMPLETE_TO_HIRE_HH_MM_SS, A.$30 TIME_FROM_FULL_APPLICATION_COMPLETE_TO_START_DATE_HH_MM_SS, A.$31 TIME_FROM_ONBOARDING_SENT_TO_HIRED_HH_MM_SS, A.$32 TIME_FROM_ONBOARDING_SENT_TO_START_DATE_HH_MM_SS, A.$33 JOB_TITLE_CODE, A.$34 PROFILE_ID, A.$35 MULTIPLE_RECORDS, A.$36 PRIMARY_IDENTIFIER, A.$37 REAPPLY_IN_CAPTURE, A.$38 REAPPLY_IN_JOB_SEARCH, A.$39 REAPPLY_IN_CAMPAIGN, :TASKKEY AS ETL_TASK_KEY, :TASKKEY AS ETL_INSERTED_TASK_KEY, CURRENT_TIMESTAMP::TIMESTAMP_NTZ(9) AS ETL_INSERTED_DATE, CURRENT_USER() AS ETL_INSERTED_BY, CURRENT_TIMESTAMP::TIMESTAMP_NTZ(9) AS ETL_LAST_UPDATED_DATE, CURRENT_USER() AS ETL_LAST_UPDATED_BY, 0 AS ETL_DELETED_FLAG FROM @DISC_PROD.STAGE.AWSAZSTAGEPROD/PARADOX/UPLOAD_FILE/HIREFILLED (FILE_FORMAT => DISC_PROD.STAGE.CSV_FORMAT) A);

    --VIEWSQL
    CREATE OR REPLACE TABLE DISC_PROD.PARADOX.FILLED_JOBS AS SELECT REQ_ID REQ_ID,STORE STORE,ORGANIZATIONAL_ALIGNMENT ORGANIZATIONAL_ALIGNMENT,HIRING_MANAGER_NAME HIRING_MANAGER_NAME,STATE STATE,CITY CITY,JOB_TITLE JOB_TITLE,JOB_FAMILY JOB_FAMILY,JOB_CODE JOB_CODE,JOB_POSTING_DATE JOB_POSTING_DATE,JOB_CLOSING_DATE JOB_CLOSING_DATE,DATE_AND_TIME_OFFER_ACCEPTED DATE_AND_TIME_OFFER_ACCEPTED,TIME_TO_SCHEDULE TIME_TO_SCHEDULE,CANDIDATE_ID CANDIDATE_ID,CANDIDATE_NAME CANDIDATE_NAME,CANDIDATE_ACCEPTED_OFFER CANDIDATE_ACCEPTED_OFFER,CANDIDATE_REJECTED CANDIDATE_REJECTED,PHONE_NUMBER PHONE_NUMBER,EMAIL EMAIL,SALARY SALARY,START_DATE START_DATE,APPLICATION_SOURCE_TYPE APPLICATION_SOURCE_TYPE,TIME_FROM_APPLY_TO_INTERVIEW_HH_MM_SS TIME_FROM_APPLY_TO_INTERVIEW_HH_MM_SS,TIME_FROM_INTERVIEW_TO_OFFER_HH_MM_SS TIME_FROM_INTERVIEW_TO_OFFER_HH_MM_SS,TIME_FROM_OFFER_TO_HIRE_HH_MM_SS TIME_FROM_OFFER_TO_HIRE_HH_MM_SS,TIME_FROM_HIRED_TO_STARTDATE_HH_MM_SS TIME_FROM_HIRED_TO_STARTDATE_HH_MM_SS,TIME_FROM_APPLY_TO_HIRE_HH_MM_SS TIME_FROM_APPLY_TO_HIRE_HH_MM_SS,TIME_FROM_APPLY_TO_START_DATE_HH_MM_SS TIME_FROM_APPLY_TO_START_DATE_HH_MM_SS,TIME_FROM_FULL_APPLICATION_COMPLETE_TO_HIRE_HH_MM_SS TIME_FROM_FULL_APPLICATION_COMPLETE_TO_HIRE_HH_MM_SS,TIME_FROM_FULL_APPLICATION_COMPLETE_TO_START_DATE_HH_MM_SS TIME_FROM_FULL_APPLICATION_COMPLETE_TO_START_DATE_HH_MM_SS,TIME_FROM_ONBOARDING_SENT_TO_HIRED_HH_MM_SS TIME_FROM_ONBOARDING_SENT_TO_HIRED_HH_MM_SS,TIME_FROM_ONBOARDING_SENT_TO_START_DATE_HH_MM_SS TIME_FROM_ONBOARDING_SENT_TO_START_DATE_HH_MM_SS,JOB_TITLE_CODE JOB_TITLE_CODE,PROFILE_ID PROFILE_ID,MULTIPLE_RECORDS MULTIPLE_RECORDS,PRIMARY_IDENTIFIER PRIMARY_IDENTIFIER,REAPPLY_IN_CAPTURE REAPPLY_IN_CAPTURE,REAPPLY_IN_JOB_SEARCH REAPPLY_IN_JOB_SEARCH,REAPPLY_IN_CAMPAIGN REAPPLY_IN_CAMPAIGN,:TASKKEY AS ETL_TASK_KEY, :TASKKEY AS ETL_INSERTED_TASK_KEY, CURRENT_TIMESTAMP::TIMESTAMP_NTZ(9) AS ETL_INSERTED_DATE, CURRENT_USER() AS ETL_INSERTED_BY, CURRENT_TIMESTAMP::TIMESTAMP_NTZ(9) AS ETL_LAST_UPDATED_DATE, CURRENT_USER() AS ETL_LAST_UPDATED_BY, 0 AS ETL_DELETED_FLAG FROM DISC_PROD.PARADOX.HIST_FILLED_JOBS WHERE ETL_LAST_UPDATED_DATE = (SELECT MAX(ETL_LAST_UPDATED_DATE) FROM DISC_PROD.PARADOX.HIST_FILLED_JOBS);

    RETURN ''SUCCESS'';
END;

';