CREATE OR REPLACE PROCEDURE DISC_PROD.ALAYACARE.GET_SERVICE_CODE()
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
--*****************************************************************************************************************************
-- NAME:  GET_SERVICE_CODE 
--
-- PURPOSE: USING THIS SP FOR DISCOVERY TABLE LOAD
--
-- DEVELOPMENT LOG:
-- DATE        		AUTHOR                	NOTES:
-- ----------  		-------------------   	-----------------------------------------------------------------------------------------------
-- 2021-11-11		UNKNOWN					INITIAL DEVELOPMENT
-- 2023-09-05  		RAVI SUTHAR            	MIGRATED JavaScript to SQL
--*****************************************************************************************************************************
    return_result varchar(1000);
BEGIN
	
    INSERT OVERWRITE INTO ALAYACARE.SERVICE_CODE (
        SERVICE_CODE_ID, PROPERTIES_IDPAYCODEREGULAR, PROPERTIES_DURATION, PROPERTIES_DESCRIPTION, PROPERTIES_IDMASTERACCOUNT, PROPERTIES_NAME, PROPERTIES_IS_VISIT_CANCELLED, PROPERTIES_DISREGARD_SHIFT_COVERAGE, PROPERTIES_UPDATE_TIME, PROPERTIES_CREATE_TIME, PROPERTIES_MATCHING_SHIFT_LATE_START, PROPERTIES_IS_DISABLED, PROPERTIES_IDPAYCODEHOLIDAY, PROPERTIES_OP, PROPERTIES_DISREGARD_START_TIME, PROPERTIES_VISITS_CAN_OVERLAP, PROPERTIES_MATCHING_SHIFT_COVERAGE, PROPERTIES_CREATE_USER_ID, PROPERTIES_RATING_METHODOLOGY_TYPE, PROPERTIES_ALLOW_VIRTUAL_CARE, PROPERTIES_UPDATE_USER_ID, PROPERTIES_GUID, PROPERTIES_ID, PROPERTIES_DISREGARD_EMPLOYEE_CAPACITY, PROPERTIES_OT_EXEMPT, DEPARTMENT_ID, DEPARTMENT_NAME)
        SELECT SERVICE_CODE_ID AS SERVICE_CODE_ID, PROPERTIES:idpaycoderegular::STRING AS PROPERTIES_IDPAYCODEREGULAR, PROPERTIES:duration::STRING AS PROPERTIES_DURATION, PROPERTIES:description::STRING AS PROPERTIES_DESCRIPTION, PROPERTIES:idmasteraccount::STRING AS PROPERTIES_IDMASTERACCOUNT, PROPERTIES:name::STRING AS PROPERTIES_NAME, PROPERTIES:is_visit_cancelled::STRING AS PROPERTIES_IS_VISIT_CANCELLED, PROPERTIES:disregard_shift_coverage::STRING AS PROPERTIES_DISREGARD_SHIFT_COVERAGE, PROPERTIES:update_time::STRING AS PROPERTIES_UPDATE_TIME, PROPERTIES:create_time::STRING AS PROPERTIES_CREATE_TIME, PROPERTIES:matching_shift_late_start::STRING AS PROPERTIES_MATCHING_SHIFT_LATE_START, PROPERTIES:is_disabled::STRING AS PROPERTIES_IS_DISABLED, PROPERTIES:idpaycodeholiday::STRING AS PROPERTIES_IDPAYCODEHOLIDAY, PROPERTIES:Op::STRING AS PROPERTIES_OP, PROPERTIES:disregard_start_time::STRING AS PROPERTIES_DISREGARD_START_TIME, PROPERTIES:visits_can_overlap::STRING AS PROPERTIES_VISITS_CAN_OVERLAP, PROPERTIES:matching_shift_coverage::STRING AS PROPERTIES_MATCHING_SHIFT_COVERAGE, PROPERTIES:create_user_id::STRING AS PROPERTIES_CREATE_USER_ID, PROPERTIES:rating_methodology_type::STRING AS PROPERTIES_RATING_METHODOLOGY_TYPE, PROPERTIES:allow_virtual_care::STRING AS PROPERTIES_ALLOW_VIRTUAL_CARE, PROPERTIES:update_user_id::STRING AS PROPERTIES_UPDATE_USER_ID, PROPERTIES:guid::STRING AS PROPERTIES_GUID, PROPERTIES:id::STRING AS PROPERTIES_ID, PROPERTIES:disregard_employee_capacity::STRING AS PROPERTIES_DISREGARD_EMPLOYEE_CAPACITY, PROPERTIES:ot_exempt::STRING AS PROPERTIES_OT_EXEMPT, DEPARTMENT_ID AS DEPARTMENT_ID, DEPARTMENT_NAME AS DEPARTMENT_NAME
        FROM ALAYACARE_PRODUCTION."5C3EE5FE-45A5-4DA7-A35B-BD7CDAFE3548".SHARED_SERVICE_CODE;

	SELECT CONCAT(''Message : '',"number of rows inserted",'' Rows Inserted.'') into :return_result FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));
	return return_result;
END;
';