CREATE OR REPLACE PROCEDURE DISC_PROD.TRUSTPOINTDATA_HIST.EMPLOYEES_CV("STR_ETL_TASK_KEY" VARCHAR(16777216), "STR_CDC_START" VARCHAR(16777216), "STR_CDC_END" VARCHAR(16777216))
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
CREATE OR REPLACE TABLE DISC_PROD.TRUSTPOINTDATA.Employees AS
WITH curr_v AS (
  SELECT COMPANY, EMPLOYEE_NUMBER, MAX(ETL_LAST_UPDATED_DATE) AS MAX_LAST_UPDATED_DATE 
  FROM DISC_PROD.TRUSTPOINTDATA.HIST_EMPLOYEES GROUP BY COMPANY, EMPLOYEE_NUMBER ) 
  SELECT t.* FROM DISC_PROD.TRUSTPOINTDATA.HIST_EMPLOYEES t 
  INNER JOIN curr_v v 
  ON t.COMPANY = v.COMPANY 
  AND t.EMPLOYEE_NUMBER = v.EMPLOYEE_NUMBER 
  AND t.ETL_DELETED_FLAG = FALSE 
  AND t.ETL_LAST_UPDATED_DATE = v.MAX_LAST_UPDATED_DATE;
   ';