CREATE OR REPLACE PROCEDURE DISC_PROD.DATA_CLEANSING.MERGE_STAGE_DAT_CLEANSING_STD_EMPLOYEE_MITUL()
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
    return_result VARCHAR;
BEGIN
SELECT   * FROM DISC_PROD.DATA_CLEANSING.Employee_Src_Attributes AS addr limit 1;
return return_result;
END;
';