CREATE OR REPLACE PROCEDURE DISC_PROD.PAYOR_CONTRACT_UI.LOAD_REVENUE_CATEGORY("STR_ETL_TASK_KEY" VARCHAR(16777216))
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
    RETURN_RESULT VARCHAR;
BEGIN

MERGE INTO DISC_PROD.PAYOR_CONTRACT_UI.REVENUE_CATEGORY TGT 
USING APP_DB_PROD.PAYOR_CONTRACT_MAPPING.REVENUE_CATEGORY STAGE
ON STAGE.REVENUE_CATEGORY_CODE = TGT.REVENUE_CATEGORY_CODE
WHEN MATCHED THEN 
UPDATE SET TGT.REVENUE_CATEGORY_CODE = STAGE.REVENUE_CATEGORY_CODE
		  ,TGT.REVENUE_CATEGORY_NAME = STAGE.REVENUE_CATEGORY_NAME
		  ,TGT.ETL_TASK_KEY = :STR_ETL_TASK_KEY
        ,TGT.ETL_LAST_UPDATED_DATE = CONVERT_TIMEZONE(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ
        ,TGT.ETL_LAST_UPDATED_BY = CURRENT_USER
WHEN NOT MATCHED THEN 
INSERT 
	(REVENUE_CATEGORY_CODE
	,REVENUE_CATEGORY_NAME
	,ETL_TASK_KEY
	,ETL_INSERTED_TASK_KEY
	,ETL_INSERTED_DATE
	,ETL_INSERTED_BY
	,ETL_LAST_UPDATED_DATE
	,ETL_LAST_UPDATED_BY)
VALUES 
	(STAGE.REVENUE_CATEGORY_CODE
	,STAGE.REVENUE_CATEGORY_NAME
	,:STR_ETL_TASK_KEY  
	,:STR_ETL_TASK_KEY  
	,CONVERT_TIMEZONE(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ 
	,CURRENT_USER
	,CONVERT_TIMEZONE(''UTC'', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ 
	,CURRENT_USER)
;
SELECT CONCAT(''Message : '',"number of rows inserted", '' Rows Inserted & '' ,"number of rows updated",'' Rows Updated.'') into :return_result FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));
return return_result;
END;
';