CREATE OR REPLACE PROCEDURE DISC_PROD.ALAYACARE.GET_INTAKE()
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
--*****************************************************************************************************************************
-- NAME:  GET_INTAKE 
--
-- PURPOSE: USING THIS SP FOR DISCOVERY TABLE LOAD
--
-- DEVELOPMENT LOG:
-- DATE        		AUTHOR                	NOTES:
-- ----------  		-------------------   	-----------------------------------------------------------------------------------------------
-- 2021-11-11		UNKNOWN					INITIAL DEVELOPMENT
-- 2023-09-05  		RAVI SUTHAR            	MIGRATED JavaScript to SQL
--*****************************************************************************************************************************
    return_result varchar(1000);
BEGIN
	
    INSERT OVERWRITE INTO ALAYACARE.INTAKE (
        ID, TYPE, CREATE_DATE, STATUS, REFERRAL_SOURCE, REQUEST_TYPE, SERVICE_ID, OFFER_ID, RESPONSE, REFERRAL_TRANSMISSION_DATE, OFFER_TRANSMISSION_DATE, EXPIRY_DATE, PROCESS_DATE, UPDATE_USER_ID, REASON, REFUSAL_COMMENTS, COMMENT, INTAKE_SERVICE_TYPE_CODE, INTAKE_SERVICE_TYPE, INTAKE_RISK_CODE, REFERRAL_CASELOAD, BRANCH_ID, REFERRAL_POSTED, REFERRAL_PROCESSED, ACCEPTED, REFUSED, EXPIRED)
        SELECT ID AS ID, TYPE AS TYPE, CREATE_DATE AS CREATE_DATE, STATUS AS STATUS, REFERRAL_SOURCE AS REFERRAL_SOURCE, REQUEST_TYPE AS REQUEST_TYPE, SERVICE_ID AS SERVICE_ID, OFFER_ID AS OFFER_ID, RESPONSE AS RESPONSE, REFERRAL_TRANSMISSION_DATE AS REFERRAL_TRANSMISSION_DATE, OFFER_TRANSMISSION_DATE AS OFFER_TRANSMISSION_DATE, EXPIRY_DATE AS EXPIRY_DATE, PROCESS_DATE AS PROCESS_DATE, UPDATE_USER_ID AS UPDATE_USER_ID, REASON AS REASON, REFUSAL_COMMENTS AS REFUSAL_COMMENTS, COMMENT AS COMMENT, INTAKE_SERVICE_TYPE_CODE AS INTAKE_SERVICE_TYPE_CODE, INTAKE_SERVICE_TYPE AS INTAKE_SERVICE_TYPE, INTAKE_RISK_CODE AS INTAKE_RISK_CODE, REFERRAL_CASELOAD AS REFERRAL_CASELOAD, BRANCH_ID AS BRANCH_ID, REFERRAL_POSTED AS REFERRAL_POSTED, REFERRAL_PROCESSED AS REFERRAL_PROCESSED, ACCEPTED AS ACCEPTED, REFUSED AS REFUSED, EXPIRED AS EXPIRED 
        FROM ALAYACARE_PRODUCTION."5C3EE5FE-45A5-4DA7-A35B-BD7CDAFE3548".SHARED_INTAKE;

	SELECT CONCAT(''Message : '',"number of rows inserted",'' Rows Inserted.'') into :return_result FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));
	return return_result;
END;
';